### ISSUE TITLE
Doesn't work with ESBuild

### ISSUE THREAD

**Issue by nandorojo** [davidjbradshaw/iframe-resizer#1008]
**Describe the bug**

Hey, so I faced a bug where ESBuild can't properly import this library. I wrote an entire description of the issue at https://github.com/evanw/esbuild/issues/1708

Thanks to the ESBuild author's help, he found that the issue was this library. It seems like a small fix, and it's all a little over my head, so I'll link to his solution here: https://github.com/evanw/esbuild/issues/1708#issuecomment-951173629

For now, I'm going to try the hack he mentioned.

**To Reproduce**

See https://github.com/evanw/esbuild/issues/1708

**Expected behavior**

See https://github.com/evanw/esbuild/issues/1708

**Screenshots**

See https://github.com/evanw/esbuild/issues/1708
 

**Additional context**

Sorry for repetition, but it's best to see  https://github.com/evanw/esbuild/issues/1708

**Comment by davidjbradshaw** [comment]
I'm wondering if just getting rid of the `else` would fix this. Feel free to give that a go and raise a PR. I don't really have much time to dig into this right now

**Comment by davidjbradshaw** [comment]
Hopefully fixed by #1205
