### ISSUE TITLE
Resizing iframe as quickly as possible?

### ISSUE THREAD

**Issue by dmalan** [davidjbradshaw/iframe-resizer#1010]
Just wanted to ask what the best approach might be for minimizing the amount of time between page load and an iframe's initial resize?

We currently use iFrame Resizer in pages like https://cs50.harvard.edu/x/2021/weeks/0/, which have an iframed video player (e.g., https://video.cs50.io/YoXxevp1WRQ?screen=mu28ADhzRQE) atop an unordered list of links. The iframed video player is essentially a 16:9 YouTube video with a Bootstrap `nav` above it, the result of which is an aspect ratio of 16:x, where x > 9. Because the height of the `nav` is dependent on font size, we thus calculate the height of the `nav` dynamically in the child window (i.e., https://video.cs50.io/YoXxevp1WRQ?screen=mu28ADhzRQE) with:

```html
<script>
    window.iFrameResizer = {

        heightCalculationMethod: function() {

            // Player's width
            const width = $('#main').outerWidth();

            // Player's ideal height, assuming 16x9
            let height = width / 16 * 9;

            // Player's actual height with nav
            return Math.round(height + $('nav').outerHeight());
        }
    };
</script>
<script crossorigin="anonymous" integrity="sha256-62pj+jS8t+leByFOFwjiY0T92YlWwowYgHnFRklgv0M=" src="https://cdn.jsdelivr.net/npm/iframe-resizer@4.3.1/js/iframeResizer.contentWindow.min.js"></script>
 ```

A consistent symptom on the parent page (i.e., https://cs50.harvard.edu/x/2021/weeks/0/), though, is that it takes a second or so after page load for the child page's height to be resized. (E.g., screenshots below.) A side effect, then, is if a user loads the page and quickly moves their mouse to click on one of the links below the player, the player frequently pushes those links downward suddenly, resulting in misclicks. The user could, of course, just wait a second or so, but not an ideal UX, we're finding.

I assumed the delay might be the result of our own event listeners (e.g., waiting unnecessarily long to call `iFrameResize`), but even a minimalist example like https://codepen.io/malan/pen/PoKpXGJ seems to exhibit the same, whereby it takes a second or so for the iframe to resize. By contrast, the demo at https://davidjbradshaw.com/iframe-resizer/example/ seems quite instant.

Are we perhaps using iFrameResize suboptimally in our child window (i.e., https://video.cs50.io/YoXxevp1WRQ?screen=mu28ADhzRQE)? Might there be something we could do better on our end to reduce that delay? We could resort to `visibility: hidden` in the parent window until the iframes have resized to avoid the sudden downward shifting of content, though that too seems less than ideal UX-wise.

Many thanks for the library itself!

**On page load:**

![image](https://user-images.githubusercontent.com/788678/138802317-c8f1dc49-6800-49d8-b09c-ebec426ba67e.png)

**A second or so later:**

![image](https://user-images.githubusercontent.com/788678/138802338-5acc5226-98ff-4167-b4af-27764e09dd5d.png)

**Comment by davidjbradshaw** [comment]
The simplest solution to this problem is to set the initial height of the iframe to `100vh` minus the height of you navigation. Then as the page loads the iframe will size down to the content and the links will come into view as the iframe resizes.

Other things you might try are putting the call to `iFrameResize()` directly after the `iframe` tag and using the the `taggedElement` resize method. However, you can't beat the JS Event Loop, so you will always have some delay, which is why I think the `100vh` trick is the best approach to this.
