### ISSUE TITLE
Fractional parts are missed during the parsing message data

### ISSUE THREAD

**Issue by Blacknikomo** [davidjbradshaw/iframe-resizer#1017]
**Describe the bug**
In our environment, we use iframeResizer to embed snippets in the UI. Sometimes the height calculated with "taggedElement" is a fractional number, e.g. 89.5px.

Whenever the host instance receives the message, it parses the value using the parseInt, so the 89.5px transforms to 89px. In case the content has a border, the bottom part is hidden.

**Expected behavior**
Host uses parseFloat

**Screenshots**
![image](https://user-images.githubusercontent.com/4025552/143571133-ff67ecc2-625b-4912-89fe-92dab7c55ef0.png)

**Additional context**

**Comment by davidjbradshaw** [comment]
Happy to take a PR for this

**Comment by Blacknikomo** [comment]
Hi @davidjbradshaw. Thanks for the quick reply. 
I try to push a commit to a separate branch but receive rejection due to the lack of access rights. 
Would you prefer to have an IDEA-based patch?

**Comment by davidjbradshaw** [comment]
Just a normal PR should be fine and sorry for late reply, I have been somewhat unwell of late

**Comment by davidjbradshaw** [comment]
Fixed in v5.0..0 #1205
