### ISSUE TITLE
[iFrameSizer][Host page: iFrameResizer0] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.

### ISSUE THREAD

**Issue by neuropass** [davidjbradshaw/iframe-resizer#1018]
**Describe the bug**
I can't take this anymore. polluting my console. Why didn't you include a method to just disable the log? this beyond annoying! 
How do you disable this once for all? Nothing seems to work on all several google results related to this error!

`[iFrameSizer][Host page: iFrameResizer0] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.
`
please advice

**Comment by davidjbradshaw** [comment]
Did you try reading the last part of the message that explain how to do what your asking?

**Comment by neuropass** [comment]
hmmm obviously and guess what? it doesn't work. This why I'm posting here. Its been going on since day one and cant take anymore. Nothing works!

This doesn't work: 
warningTimeout: 0,


This doesn't work: 
warningTimeout: 10000,


I just want that log disabled once for all. Why doesn't have an option to disable? A production script should noy have any loggging enabled by default anyway. This is just poor design of the script.

**Comment by neuropass** [comment]
Why are you closing this? it does not work. It's a bug.

**Comment by kevin-daniel-hunt** [comment]
I also cannot seem to suppress this warning.  My page loads a bit slowly but it does work, so I would love a way to suppress this warning, but the `warningTimeout` option doesn't seem valid, and it is not listed in any documentation either.

**Comment by diyarbekirli1** [comment]
CloudFlare Rocket Loader can affect the loading order of some JavaScript files, causing files such as iframeresizer.contentwindow.min.js inside an iFrame to not load on time. In such cases, disabling Rocket Loader resolves the issue by ensuring that the scripts are loaded in the expected order.
