### ISSUE TITLE
NPM install not updating

### ISSUE THREAD

**Issue by djsaturn** [davidjbradshaw/iframe-resizer#1024]
I tried installing the latest version today but it's not updating. I checked the commits and for some reason the iframeResizer.min.js is still on the old version yet it says 4.3.2. I also removed and reinstalled it but same issue. Please let me know.

iFrame Resizer (iframeSizer.min.js ) - v4.3.2 - 2021-04-26

NPM shows:
4.3.2 • Public • Published 8 months ago

Thanks in advance

**Comment by davidjbradshaw** [comment]
I'm a bit confused, what version do you think it is on?

**Comment by djsaturn** [comment]
Hey David,

So the code did not update for whatever reason. If you look at NPM it says it was updated probably 9 months ago now. On github it's the same version but was updated Nov 30th 2021. Not sure how all this works but when I ran the update I still have the code from version v4.2.9 but says I'm on 4.3.2. Hope that makes sense.

Thanks!
