### ISSUE TITLE
FR: Add option for manual offset

### ISSUE THREAD

**Issue by JasonTheAdams** [davidjbradshaw/iframe-resizer#1030]
**Describe the bug**
We have an iframe with a box shadow. When the iframe resizes the box shadow is clipped as it's not calculated in the container height.

**To Reproduce**
1. Create an iframe with a box shadow
2. Resize the iframe to a new height
3. Look at the bottom of the iframe and notice the box shadow is clipped

**Expected behavior**
If there was an `offsetHeight` option, we could simply set a value which compensates for the box shadow. The offset would simply be applied to the final calculated height and would be a constant. It wouldn't be necessary for us, but allowing for a callback could also be helpful for someone to calculate the offset at each moment of resize.

**Screenshots**
![image](https://user-images.githubusercontent.com/2024145/149261342-d24bf147-1521-4457-bb7f-238d24d58630.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 1.34.80

**Comment by davidjbradshaw** [comment]
Happy to take a PR for this, can you please add width as well
