### ISSUE TITLE
iFrame has fixed width of 300px, without any styling defining 300px

### ISSUE THREAD

**Issue by crevulus** [davidjbradshaw/iframe-resizer#1032]
**Describe the bug**
Whatever content I place inside the iframe, the width is always 300px. Will not move; overflow is hidden if I add something >300px and still takes up 300px if my content is smaller than that.

**To Reproduce**
1. Set up new web page with desired content.
2. Set up second page; Import script; add iframe to index.html
3. Inspect element width.

**Expected behavior**
Width should change dynamically, like height does.

**Screenshots**
Three screenshots attached, showing the iframe width always at 300px regardless of content width.

<img width="1248" alt="Screenshot 2022-01-13 at 20 39 54" src="https://user-images.githubusercontent.com/50107046/149398331-114486a9-37fd-4652-857c-f0d2a8506644.png">

<img width="1183" alt="Screenshot 2022-01-13 at 20 42 30" src="https://user-images.githubusercontent.com/50107046/149398335-ddb8edd4-dd13-4ac4-b119-12bf18c57970.png">

<img width="1321" alt="Screenshot 2022-01-13 at 20 39 44" src="https://user-images.githubusercontent.com/50107046/149398308-668e651a-3256-4ecf-b55a-8b6fb415871c.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10
 - Browser: Chrome 97

**Additional context**
I also made two code sandboxes, and embedded one site in the other via an iframe. Unfortunately the iframe is hidden for some reason, but if you inspect and look for the iFrame with `id="inlineFrameExample"` (and not code sandbox's button iframe) you'll see it's 300px wide: https://exzts.csb.app/
The code for the parent site is here: https://codesandbox.io/s/eloquent-flower-exzts?file=/index.html
The code for the framed site is here: https://codesandbox.io/s/iframe-test-ss8fs

**Comment by davidjbradshaw** [comment]
You have a lot of CSS on your iFrame tag. Other than that not really sure. Think you will have more luck on StackOverflow.

**Comment by crevulus** [comment]
I'm not sre it is purely CSS-related, though. I removed all styles from the embedded site and the parent site except for `z-index`, and set `sizeWidth: true` in my `window.iFrameResize` options. Still always sizing my iframe to be 300px wide, but height resizing is working perfectly.

<img width="2048" alt="Screenshot 2022-01-15 at 21 01 18" src="https://user-images.githubusercontent.com/50107046/149636124-ec811dca-e55f-46bc-991f-abc840536662.png">

Not sure why the resizer isn't picking up on width change.

**Comment by nternetinspired** [comment]
This is the native behaviour of an iframe, actually any replaced element in html has a default height of 150px and default width of 300px. Solution? Define the elements size.
