### ISSUE TITLE
Is there something wrong with me writing like this in liquid? It doesn't work. . .

### ISSUE THREAD

**Issue by capewang** [davidjbradshaw/iframe-resizer#1033]
<style>iframe{width:100%}</style>

<iframe src="https://notepad-plus-plus.org/" scrolling="no"></iframe>

<script src="//cdn.shopify.com/s/files/1/0594/2876/5891/t/12/assets/iframeResizer.min.js?v=4363327085798756963" defer="defer"></script>

<script type="text/javascript">
	
    iFrameResize({
		    log: true,
		    heightCalculationMethod:taggedElement
		  
		});
</script>

do  not   work

**Comment by capewang** [comment]
<style>iframe{width:100%}</style>
<iframe src="https://notepad-plus-plus.org/" scrolling="no"></iframe>
<script src="//cdn.shopify.com/s/files/1/0594/2876/5891/t/12/assets/iframeResizer.min.js?v=4363327085798756963" defer="defer"></script>

<script type="text/javascript">
	
    iFrameResize({
		    log: true,
		    heightCalculationMethod:taggedElement
		  
		});
</script>


do  not  work

**Comment by capewang** [comment]
``<style>iframe{width:100%}</style>
<iframe src="https://notepad-plus-plus.org/" scrolling="no"></iframe>
<script src="//cdn.shopify.com/s/files/1/0594/2876/5891/t/12/assets/iframeResizer.min.js?v=4363327085798756963" defer="defer"></script>

<script type="text/javascript">
	
    iFrameResize({
		    log: true,
		    heightCalculationMethod:taggedElement
		  
		});
</script>

**Comment by markvantilburg** [comment]
`The most common cause of this is not placing the [iframeResizer.contentWindow.min.js](https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js) script inside the iFramed page.`

See: https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md

**Comment by 0hv1** [comment]
iframe {
    width: 1px;
    min-width: 100%;
  }
</style>
<iframe id="myIframe" src="http://google.com"></iframe>
<script>
  iFrameResize({ log: true }, '#myIframe')
</script

**Comment by 0hv1** [comment]
https://google.com
