### ISSUE TITLE
Height is changing when hover select inside the iframe

### ISSUE THREAD

**Issue by firestar300** [davidjbradshaw/iframe-resizer#1038]
**Describe the bug**
The height of the iframe is increasing when we hover the select inside the iframe

**To Reproduce**
1. Go to https://jsfiddle.net/firestar300/jfk69wbv/
2. Hover on "Ingrédients" select
3. The height of the iframe is increasing

**Expected behavior**
The iframe height should not increase.

**Comment by markvantilburg** [comment]
The hover styling is not done with css :hover class but the class is changed on hover using JavaScript. It might help by changing the hover to a css hover.

**Comment by firestar300** [comment]
Thank you for your answer.

Best.
