### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by richard-friend** [davidjbradshaw/iframe-resizer#1053]
**Describe the bug**
We are using the iframeresizer on Asda.com in the UK, everything has been working fine but as of a few weeks ago we have started to experience issues. On Asda the iframe doesn't load at all and just shows the loading circle (below the "More Product Information" bar).

The following error is in the console - bundle.wrapped-frame.7791c1c730d0b7ee260e.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://1d81e75c4337a6e2e3c2-4a69748413de5fcbd7a7a944817c2356.ssl.cf1.rackcdn.com') does not match the recipient window's origin ('https://groceries.asda.com').n.resizeIframe @ bundle.wrapped-frame.7791c1c730d0b7ee260e.js:1

**To Reproduce**

Steps to reproduce the behavior on Asda:
1. Go to 'https://groceries.asda.com/product/aa-batteries/duracell-optimum-aa-batteries-pack-of-8/1000300941083?&cmpid=ppc-_-ghs-_--_-google-_--_-dskwid-s92700059046120718_dm&s_kwcid=AL!11432!3!482369556466!!!g!1038711451830!&ds_rl=1254319&gclid=EAIaIQobChMI-MCV79ez9wIVDpntCh0V3w6AEAQYASABEgL4E_D_BwE&gclsrc=aw.ds'
3. Scroll down to 'below the "More Product Information" bar'
4. See error - You will see a loading spinner and nothing else

**Expected behavior**
When the page listed above loads, the user should have the conetnt from https://1d81e75c4337a6e2e3c2-4a69748413de5fcbd7a7a944817c2356.ssl.cf1.rackcdn.com/4381936_featureset_skuninja/index-1637837893.html displayed the More product info bar

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjbradshaw** [comment]
this looks like the iframe is being redirected, maybe by a CDN.Have you tried disabling the checkOrigin option?

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#checkorigin
