### ISSUE TITLE
iframe with float and other align css techniques

### ISSUE THREAD

**Issue by niknikopoulos** [davidjbradshaw/iframe-resizer#1059]
When i use the float or other techniques to align contents right or left **inline** to the iframe then it doesn't have the expected behaviour. For example I have a video inside the iframe and I need contents outside of the iframe to align to the right inline with the iframe. Whatever technique is used then either the contents will be below the iframe or the video will be shown in half

**Comment by sean1138** [comment]
try some flexbox?  example:
https://codepen.io/sean1138/pen/poaERbN

**Comment by niknikopoulos** [comment]
No I didn't mean that. It shows the button and the paragraph inside the the iframe and video. I mean outside. Side by side.

**Comment by sean1138** [comment]
updated the codepen
