### ISSUE TITLE
The size of an iframe keeps increasing when using vh units for elements inside the iframe

### ISSUE THREAD

**Issue by lelekaspb** [davidjbradshaw/iframe-resizer#1062]
**Describe the bug**
I have a page I need to embed with iframe. This page has a hero picture that takes up entire viewport (100vw and 100vh) plus the rest of the content that is dynamic and therefore changes it's height. The 100vw value behaves fine, however, 100vh break the page with embedded iframe. Namely, the height of the page endlessly while zooming in the picture. I saw that previous issues recommended removing unnecessary vh and % units, but in my case they are necessary. 

**To Reproduce**
Set height of a section on the child page to 100vh

**Expected behavior**
I would expect vh units work inside the iframe since this is now so popular and widely used.

**Desktop (please complete the following information):**
 I have seen the same behavior in Chrome and Firefox

**Comment by davidjbradshaw** [comment]
If you find a fix for this, I would welcome a PR

**Comment by Paulsky** [comment]
@davidjbradshaw I'm thinking about making a PR, but I'm not sure if you like this approach:

- Get browser window height in pixels
- Foreach element check if it has a style with 'vh' (could be elements with some kind of class?).
- If so, calculate the number of pixels by vh (`windowsHeight * (vhValue/100)`) and replace it
(example, the window has a height of 1080px, my element has a `'min-height: 50vh'`, the property gets replaced by `'min-height: 540px'`.

**Comment by davidjbradshaw** [comment]
What would happen is the user resizes the browser window?

**Comment by davidjbradshaw** [comment]
I'm happy to look at a PR, but I fear it will be tricky to make it work reliably. I'm also concerned about the performance impact. Currently I have a performance target of under 1ms to make all the size calculations.

**Comment by davidjbradshaw** [comment]
btw the upcoming V5 #1212 release will automatically remove `vh` units from the `<html>` and `<body>` tags. which will catch the main place where people use them. It's the most popular way to break things.

**Comment by davidjbradshaw** [comment]
Thinking a bit more the easiest solution might be to create an array of `vh` elements, set them all to `display: none` each time the page is resizing and then display them again once we're at the new page size.

I might add `beforeResize` and `afterResize` hooks if someone comes up with a good use for them.

**Comment by EvanBoyle** [comment]
I'm seeing issues with resizing when the user changes the zoom level on the browser. Could this be related?

**Comment by davidjbradshaw** [comment]
@EvanBoyle maybe, it really depends on the CSS in your iframe. Do you have issues with an unstyled page in the iframe? If so I think that is a new ticket.

**Comment by Paulsky** [comment]
Unfortunately, I currently don't have the time to create a PR. Maybe I'll be able to contribute in the near future.

**Comment by davidjbradshaw** [comment]
V5 docs are now online at https://iframe-resizer.com and an alpha release on NPM. Would welcome feedback

**Comment by davidjbradshaw** [comment]
Having looked into this, any possible fix would require inspecting the computed CSS for every element on the page and my test show that running that on this page would take around 20 seconds to process. So is just not practical to implement. 

Instead I will add a page the website on iframe content guidelines that explains why you don’t actually need `vh` units, as when the page resizes to meet your content, the content does not need to scale to meet the page size.
