### ISSUE TITLE
The library can not be used with ES6 import, do you have any way for es6 usage?

### ISSUE THREAD

**Issue by selcukmart** [davidjbradshaw/iframe-resizer#1070]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjbradshaw** [comment]
Hopefully this is now fixed

**Comment by selcukmart** [comment]
> 

Thank you for the update and work, maybe next time I can try.
