### ISSUE TITLE
onMessage handler not getting any data in IframeResizer in reactjs ?

### ISSUE THREAD

**Issue by avinashakula** [davidjbradshaw/iframe-resizer#1084]
import React, {useEffect, useRef, useState} from "react";
    import IframeResizer from 'iframe-resizer-react'

    export default()=>{
    const ref = useRef(null);
    const [message, setMessage] = useState("default");
    const onMessage = (msg)=>{ 
       // Not able to receive any data
       setMessage(msg)
    }

    return <>
        <IframeResizer
            forwardRef={ref}
            log
            src="link"
            onMessage={onMessage}
        />
        <p>{message}</p>
    </>
    }
onMessage handler is not triggering when something sends back to parent from src link but its working fine with window.addEventListner "message" in useEffect,     
The source link is simple webpage that return data if we click on button located in it. window.addEventLisnter ("message" is working fine in useEffect, but i want to use onMessage to get the message. Suggestions/solutions are highly appreciable.

**Comment by krishna-sharma-dev** [comment]
I am facing the same issue, any update/fix/workaround for this yet?

**Comment by davidjbradshaw** [comment]
Fixed in V5.0.0

Please see https://iframe-resizer.com/frameworks/react/#advanced-example
