### ISSUE TITLE
Request: Add to CDNjs

### ISSUE THREAD

**Issue by ethanpil** [davidjbradshaw/iframe-resizer#111]
Hi, I use CDNjs: https://cdnjs.com/

Can you add this project there? Its a simple pull/push via GitHub...
https://github.com/cdnjs/cdnjs

**Comment by vena** [comment]
Looks like they mandate auto-update now.

**Comment by davidjbradshaw** [comment]
https://github.com/cdnjs/cdnjs/commit/588fd627f084eba6f64521ef1f80f890935dcc02
