### ISSUE TITLE
[question] Resize iframe by microsoft

### ISSUE THREAD

**Issue by tkazik** [davidjbradshaw/iframe-resizer#1110]
What a beautiful tool!
I would like to embed an iframe from ms booking (example [here](https://outlook.office365.com/owa/calendar/SDRRetailConsulting@sdrretail.com/bookings/)) and have more control over the size of the iframe (e.g. cropping).
Two questions (as I am not the owner of outlook ;)):

- _The first (iframeResizer.min.js) is for the page hosting the iFrames._ This seems rather difficult in position, right? Any option to still use the iframe-resizer?
- How does CORS work with MS? [This](https://learn.microsoft.com/en-us/previous-versions/office/office-365-api/?redirectedfrom=MSDN) seems quite promising...

Thx a lot!

**Comment by davidjbradshaw** [comment]
Thank you.

You would need to raise a support ticket with MicroSoft and ask them to change their CORS setting or directly add support for iframe-resizer.
