### ISSUE TITLE
[question] Can properties of window.parentIframe be used in react dynamically?

### ISSUE THREAD

**Issue by msarauer** [davidjbradshaw/iframe-resizer#1111]
I'm trying to use `pageInfo.scrollTop` from `window.parentIFrame` to position a modal element in react. Is this possible? I am able to console log the info, but I can't set it to state for some reason.

Here is one of my attempts:

```
const [iFramePosition, setIFramePosition] = useState<IIFramePosition>({
    offsetTop: undefined,
    scrollTop: undefined,
  });

  if ('parentIFrame' in window) {
    window.parentIFrame.getPageInfo((pageInfo: any) => {
      setIFramePosition({
        offsetTop: pageInfo.offsetTop as number,
        scrollTop: pageInfo.offsetTop as number,
      });
    });
  }
```

I also tried in a useEffect hook and still didn't work.

**Comment by davidjbradshaw** [comment]
The problem is the callback is return async. Have a look at this SO, which I think should explain how to fix this problem. If it works, can you please post the final solution here. 

https://stackoverflow.com/questions/53898810/executing-async-code-on-update-of-state-with-react-hooks

**Comment by davidjbradshaw** [comment]
You got me thinking now and I think a custom effect would look something like this.

```js
const usePageInfo (setState) => useEffect(() => {
  window.parentIFrame.getPageInfo(setState)
  return () =>  window.parentIFrame.getPageInfo(false)
}, [])
```
