### ISSUE TITLE
Reizer didn't on the Native App.

### ISSUE THREAD

**Issue by masihurgmail** [davidjbradshaw/iframe-resizer#1117]
I have already used resizer library for our forum almost 4 years and it's working fine. Lots of client using our forum. Resizer is working fine on the website. Recently a client created a Native App and embed our forum into it. As you know the native app getting the data from the same page as web. 
He reported that the resizer works perfect on the web, but on the Native app something is wrong like some part of the footer is not visible, that means the resizer is not working. 
Debugged the code and noticed that on the native app the resizer is working when touch the screen after render the page. 

Please look into the issue, and provide me solution ASAP. 

-- 
Warm Regards,

Masihur Rahman
Team Lead
Website Toolbox
Email: masihur@websitetoolbox.com
http://www.websitetoolbox.com

**Comment by masihurgmail** [comment]
Hi,

Please reply on this.

**Comment by masihurgmail** [comment]
Hi,

Debugged it and noticed that be below code is not working on the "Native App"

![image](https://user-images.githubusercontent.com/66255086/213987970-2cc35774-13aa-43bd-97ab-cacb45eca1a9.png)

Please check it and fix the issue.

**Comment by davidjbradshaw** [comment]
Fix how? You have not supplied a minimum test case of the problem. 

I see also that you charge for your product, but expect me to drop everything and work on this for free. 

That is not how this works, please fix it yourself and then create a Pull Request with your changes, so that everyone can share your fix.
