### ISSUE TITLE
4.3.5 release breaks package import when used with @types/iframe-resizer package

### ISSUE THREAD

**Issue by AKlein920** [davidjbradshaw/iframe-resizer#1140]
**Describe the bug**
The 4.3.5 release changed the library's [exports](https://github.com/davidjbradshaw/iframe-resizer/compare/v4.3.4...v4.3.5#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R2).

This release requires a change to the import: `import {iframeResize} from 'iframe-resizer';`

Prior to this release, we imported the library like this: `import {iframeResizer} from 'iframe-resizer';`

We also use typescript, and the `@types/iframe-resizer` package, which [exports the `iframeResizer` function](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/iframe-resizer/index.d.ts#L317). 

The discrepancy in exports (`iframeResize` vs `iframeResizer`) makes it seem like this 4.3.5 release should have been labeled as major, rather than minor. 

Was this change intended? If so, we can adjust types separately.

**Comment by davidjbradshaw** [comment]
Bugger, not it wasn't.

**Comment by davidjbradshaw** [comment]
OK, not sure how that happened, but it now once again supports both. Technically `iframeResize()` is correct and what all the docs refer to, but I guess changing it in typings outside a major version is a bad idea. For now could you allow both?

**Comment by AKlein920** [comment]
Thank you very much for making this change!
