### ISSUE TITLE
Not Working in vue.js

### ISSUE THREAD

**Issue by proidit** [davidjbradshaw/iframe-resizer#1143]
page hosting the iFrames:
import * as Resize from 'iframe-resizer/js/iframeResizer.contentWindow';  
Vue.use(Resize);

Parent page:
	<script src="node_modules/iframe-resizer/js/iframeResizer.min.js"></script>  
	<script>  
		iFrameResize({ log: true }, '#player_iframe')  
	</script>  

No errors in javascript console

Parent warning:
iframeResizer.js:144 [iFrameSizer][Host page: player_iframe] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.

**Comment by davidjbradshaw** [comment]
What version? Can you try the one I released yesterday, I hope I fixed this already

**Comment by proidit** [comment]
sorry. already resolved with personal source code wuthout external library
