### ISSUE TITLE
Script version comment is one release behind

### ISSUE THREAD

**Issue by timf** [davidjbradshaw/iframe-resizer#1151]
**Describe the bug**

A small thing, but it was confusing at first. It appears the `4.3.6` release has an initial comment in the script that says it is `4.3.5`.

**To Reproduce**

Downloaded the release tarballs from GitHub,  `v4.3.5.tar.gz` and `v4.3.6.tar.gz`

A comparison reveals that `v4.3.6.tar.gz` contains `v4.3.6`, with the backwards compatibility fix. And the `package.json` is updated with the new version.

But, the initial comment in the JS files says `v4.3.5` for both:

```
diff -r iframe-resizer-4.3.5/js/iframeResizer.contentWindow.min.js iframe-resizer-4.3.6/js/iframeResizer.contentWindow.min.js
1c1
< /*! iFrame Resizer (iframeSizer.contentWindow.min.js) - v4.3.5 - 2023-03-01
---
> /*! iFrame Resizer (iframeSizer.contentWindow.min.js) - v4.3.5 - 2023-03-08
```

And:
```
diff -r iframe-resizer-4.3.5/js/iframeResizer.min.js iframe-resizer-4.3.6/js/iframeResizer.min.js
1c1
< /*! iFrame Resizer (iframeSizer.min.js ) - v4.3.5 - 2023-03-01
---
> /*! iFrame Resizer (iframeSizer.min.js ) - v4.3.5 - 2023-03-08
```

Thank you for maintaining this very helpful library.

**Comment by davidjbradshaw** [comment]
Fixed in v5.0.0-RC.1
