### ISSUE TITLE
Scrolling on iOS Devices

### ISSUE THREAD

**Issue by nuil** [davidjbradshaw/iframe-resizer#1156]
We're not having a fluent scrolling on iOS Devices when scrolling on the iframe

**To Reproduce**
Visit http://ewld.dev with your iOS device. Scroll starting from inside the iframe.
The production website has a stronger issue than my sample site. 

**Expected behavior**
Scrolling is smooth

**Screenshots**
https://user-images.githubusercontent.com/2334194/232099147-1081ad8c-5b80-4442-9862-2e8ba744e081.MP4

https://user-images.githubusercontent.com/2334194/232099158-757f8bcd-243e-4935-bc9d-165a96480ba9.MP4

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS 16.4.1
 - Browser Safari
 - Version 16.4.1

**Comment by DonfexCui** [comment]
me too, help!

**Comment by davidjbradshaw** [comment]
Seems to work fine on iOS 16.5

**Comment by Shepdesign** [comment]
This is still definitely happening and an issue.

**Comment by geoffreymina13** [comment]
Agreed - definitely still an issue.

**Comment by davidjbradshaw** [comment]
I'm not able to reproduce this. If it is still an issue, can someone please share a working page with the issue?
