### ISSUE TITLE
scrolling: integer ??

### ISSUE THREAD

**Issue by adaptifyDesigns** [davidjbradshaw/iframe-resizer#117]
Hi, I'm attempting to change the `scrolling` option depending on the `messageCallback` received from the child page. In the docs it says that scrolling is `false` by default, but describes the expected option value as an "integer". Sorry, I don't understand. If i'd like to configure the iframe to allow scrolling, what would I change that option to? I tried setting it to `true`, but this did not change the behavior. 

Thanks in advance for any help!

**Comment by psr1410** [comment]
Is this issue solved in the newer version. I'm still not able to set scrolling dynamically.
