### ISSUE TITLE
How can I use "autoResize" option dynamically. It's not working as expected.

### ISSUE THREAD

**Issue by masihurgmail** [davidjbradshaw/iframe-resizer#1170]
How can I use "autoResize" option dynamically.

On my website I am using Modal, I need to be stop autoResize in case of Modal open. When pass autoResize: false directly in the option then it will stop auto resize for other event as well. 
I need to be stop autoResize only if Modal is being open, Then set it again true after close the modal.

**Comment by masihurgmail** [comment]
Hi,

I am using below code in our forum JS file to prevent auto resizing, when open a model, and again enable it after close the modal. 

![image](https://github.com/davidjbradshaw/iframe-resizer/assets/66255086/0f521840-ed0c-4d41-8d8e-8686e10a2ec4)

But it's didn't set as false. 

I have prepared a screencast for the refrence.

URL: https://www.loom.com/share/987391376aa0405b81011e8498a6775a?sid=7bf7ddfe-0d0b-4bfd-9a4f-c4030b99227b

Also I tried to use latest library as well, but getting same error. 

Please check and provide a solution for it.

**Comment by masihurgmail** [comment]
Hi, 

I am still waiting but didn't get any response.

**Comment by davidjbradshaw** [comment]
There is an option in the Child Page API to turn this on and off.

https://iframe-resizer.com/api/child/#autoresizebool
