### ISSUE TITLE
How to use this in SvelteKit?

### ISSUE THREAD

**Issue by hi-brylle** [davidjbradshaw/iframe-resizer#1174]
That's it. My use case is for embedding Github gist for a tech blog. Width is pretty much set at 100%, it's the height that's tricky. Thank you.

**Comment by SamMousa** [comment]
@hi-brylle it's good form to post what you already tried and what exactly is not working.

**Comment by hi-brylle** [comment]
I elected to simply use a syntax highlighting library for my use case of showing code snippets . I no longer need Github gist embedding, but thank you for replying. Closing this now.
