### ISSUE TITLE
How to integrate with nuxt3?

### ISSUE THREAD

**Issue by Gildars** [davidjbradshaw/iframe-resizer#1184]
The solution in [this answer](https://github.com/davidjbradshaw/iframe-resizer/issues/831#issuecomment-665760332) is not suitable for nuxt3.

**Comment by davidjbradshaw** [comment]
If you find the right answer, can you please add it here. I have never used Nuxt

**Comment by vfcoding** [comment]
https://github.com/davidjbradshaw/iframe-resizer/issues/831#issuecomment-1857665812
