### ISSUE TITLE
Iframe resize not working in Mac Safari

### ISSUE THREAD

**Issue by SamuelEshetu** [davidjbradshaw/iframe-resizer#120]
Iframe resize not working in Mac Safari
![screen shot 2014-11-26 at 6 29 14 pm](https://cloud.githubusercontent.com/assets/4578566/5201597/62a29ace-759a-11e4-8f0c-db4d36869217.png)

**Comment by BarisW** [comment]
This might be related to [3rd party cookies not being accepted by Safari](http://stackoverflow.com/questions/9930671/safari-3rd-party-cookie-iframe-trick-no-longer-working). 

The trick that fixed the issue in my site is to first load a local URL in the iframe, that then redirects to the final (external) URL. Doing so fixes the 3rd party cookie problem.
