### ISSUE TITLE
Value for minHeight can not be greater than maxHeight

### ISSUE THREAD

**Issue by kapilpipaliya** [davidjbradshaw/iframe-resizer#1204]
**Describe the bug**
minHeight and maxHeight not setting properly. I am getting error: `Value for minHeight can not be greater than maxHeight` for following code:

**To Reproduce**
```
          el.addEventListener('load', () => iframeResizer({
                  checkOrigin: false,
                  minHeight: '99px',
                  maxHeight: '888px',
                  warningTimeout: 5000,
                  scrolling: true,
                }, el))
```
**Expected behavior**
It should properly parse integer before checking min and max height.

**Comment by davidjbradshaw** [comment]
It expects a number, not a string.
