### ISSUE TITLE
Callback from IframeResizer does not get the latest state object

### ISSUE THREAD

**Issue by avaya1** [davidjbradshaw/iframe-resizer#1230]
**Describe the bug**
I have a react component which house the IframeResizer and this component has state based on the event from IframeResizer.
The state supposed to manipulate the latest state with the event but when callback is called I am getting the initial state instead of the latest state which was updated part of last callback.

**To Reproduce**
1.  Download the sample project [associated with this ](https://codesandbox.io/p/sandbox/iframe-resizer-react-example-kuggj) Or refer Updated code [at](https://codesandbox.io/p/sandbox/iframe-resizer-react-example-forked-zt7y2q)
2. Modify app.jsx  
<code> const onMessage = data => {
    setMessageData({...messageData,...data})
    ref.current.sendMessage('Hello back from parent page')
  }</code>
3. Modify message-data.jsx change renderer
 <code>
return data ? (
    <span>
    <b>Frame ID:</b> {data.iframe.id} &nbsp;
    <b>Height:</b> {data.height} &nbsp;
    <b>Width:</b> {data.width} &nbsp;
    <b>Event type:</b> {data.type} &nbsp;
    <b>Message:</b> {data.message}
  </span>

  ) : null
</code>
4. Observe the message that is rendered on the bottom. You will have hight and width value.

> Frame ID: iFrameResizer0  Height: 546  Width: 751  Event type: init  Message:

6.  Now Click on Send message and observe the message that is rendered, empty Height and width

> Frame ID: iFrameResizer0  Height:  Width:  Event type:  Message: Hello from the iFrame

**Expected behavior**
As previous event had those attributes and already saved to the state we should have those values rendered as we are merging new event with the old state.

**updated Sample code**
Updated code [at](https://codesandbox.io/p/sandbox/iframe-resizer-react-example-forked-zt7y2q)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [all]
 - Version [all]

**Smartphone (please complete the following information):**
 - Not tested
**Additional context**

**Comment by davidjbradshaw** [comment]
Could you please try the test release of V5 of iframe resized and let me know if it still has the same issue?

https://davidjbradshaw.github.io/iframe-resizer-docs/

**Comment by davidjbradshaw** [comment]
Closed due to no response
