### ISSUE TITLE
iFrame with dynamic blog posts nested in toggles not resizing in mobile phones. 

### ISSUE THREAD

**Issue by jerrell-rebel** [davidjbradshaw/iframe-resizer#1231]
Firstly, great work on the resizer! Works well on desktop. Just one small issue, when I test it on my mobile, it does not resize the iFrame. Half of the content just sinks, it does not calculate the dynamic height too. Here's the page for reference - [thebreeze.com.au/who-we-work-with/](https://thebreeze.com.au/who-we-work-with/)

Nothing too special on how it is called. Just the regular CSS (iframe {width: 1px;min-width: 100%;}) script code (iFrameResize({ log: true }, '#myIframe');). I have also tried and experimented the different values from [heightCalculationMethod](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#heightcalculationmethod). 

resizer version is v4.3.9

Please let me know if you need more info! Thanks :)

**Comment by davidjbradshaw** [comment]
Check the console output, I'm seeing error 403 in the iframe when it tries to load the js file.

**Comment by jerrell-rebel** [comment]
There might have been a hiccup but I don't see the 403 error on my console on my end now. 

It's also worth mentioning I've set the warningTimeout to 20000.

**Comment by davidjbradshaw** [comment]
<img width="608" alt="Screenshot 2024-04-18 at 15 57 42" src="https://github.com/davidjbradshaw/iframe-resizer/assets/591634/32244271-b5a3-4772-b928-724f10bc883a">

**Comment by davidjbradshaw** [comment]
<img width="956" alt="Screenshot 2024-04-18 at 16 09 47" src="https://github.com/davidjbradshaw/iframe-resizer/assets/591634/fda599c4-6e41-41c4-947a-33f2eee5ce50">

**Comment by davidjbradshaw** [comment]
https://rebelagency.com.au/wp-admin/js/iframeResizer.contentWindow.min.js

**Comment by jerrell-rebel** [comment]
You're right! I didn't notice because my IP was whitelisted in my .htaccess file. For others experiencing the same error, here's how I managed to allow access without compromising the security/permissions of my other files.

1. You can try to adjust the file's permission first to 7/5/5 - ultimately allowing/ticking everything on the Execute row. 
![image](https://github.com/davidjbradshaw/iframe-resizer/assets/111322723/8b376654-222f-4ee8-920b-d58b2a936c4c)


2. If that still does not work, you might have an .htaccess file nested on your /wp-admin folder. Put on this code -
<Files "iframeResizer.contentWindow.min.js">
    Allow From All
</Files>
#iFrame Resizer allow execution/permission

Again, thank you David for this awesome library! 🤘

**Comment by davidjbradshaw** [comment]
Glad it works now. Could I ask a small favour, I'm currently updating the docs and I would love to add a small guide on how to use iframe-resizer with WordPress, but I've never used it. I was wondering, if you could detail how you set it up, so I could include it and help everyone else.

**Comment by davidjbradshaw** [comment]
I would have expected `644` to be ok for the permission, as it does not run on the server.

**Comment by jerrell-rebel** [comment]
> lo

Sure thing! In my case, we use a theme builder and a cpanel hosting with some custom security blocks to restrict .

**Comment by davidjbradshaw** [comment]
Thank you, I've just put a page together on the draft website for Version 5.
https://iframe-resizer.com/frameworks/wordpress/
