### ISSUE TITLE
Svelte

### ISSUE THREAD

**Issue by socketopp** [davidjbradshaw/iframe-resizer#1243]
I am coding in Svelte and I am implementing a Widget component that I will embed in a studio where you're suppose to be able to customize the widget. In this studio this component is going to located, pretty much in the center of the screen like you would expect. 

This widget is also available on a route `/widget/[id]` that is going to be embedded in an iframe in the lower right corner of the screen. 
Upon clicking the widget, a popup is appearing slightly top left of the widget icon. 

My current idea have been to have a fixed position on the iframe so I can place it in the lower right corner and have a absolute position on the <Widget/> component itself. However, no matter which ` heightCalculationMethod ` I use, iframe size does not expand to the size of the the popup content. 

The widget layout is something like this.

```js
<div class="absolute">

  <button class="absolute"> open popup</button>
  {#if showPopup}
    <div id="content" class="relative"/>
  {/if}
<div/>
```

I have this on my body

min-height: 100vh;
margin: 0;
background-attachment: fixed;

Could this cause any possible issues? 

**Update:** 
One issue I had was that it expanded but did not decrease in size. This was due to ` min-height: 100vh;` on body. 
Overall, it took me some time, had to have a div wrapping the content div that specified a height of the content that was going to be displayed.

**Comment by socketopp** [comment]
> Hey, I'd like to create an official version for Svelte and wondered if you had any code I could use as a starting point.
> 
> Vesrion 5 now has an [API](https://iframe-resizer.com/api/framework/) to support custom platform version.

Hi, sorry, I decided not to use iframe-resizer so I don't have any code for you to use as a starting point.

**Comment by davidjbradshaw** [comment]
OK no worries, thanks for getting back to me.
