### ISSUE TITLE
How to handle media queries?

### ISSUE THREAD

**Issue by socketopp** [davidjbradshaw/iframe-resizer#1244]
I got an iframe with media-queries, it needs the width of the iframe to be 100% otherwise the media queries won't work, but at the same time, I don't want the iframe to be bigger than necessary. I am very curious how to solve this since it feels like an obvious error many people should have encountered. 

I don't want the width of the iframe to be larger than the widget itself but at the same time, if I would set it to fixed 400px (roughly the size of the widget, the media queries doesn't respond when the parent viewport is changing)

![image](https://github.com/davidjbradshaw/iframe-resizer/assets/20456621/b5875ec1-16ef-4b50-96ce-0edb12d07339)

**Comment by davidjbradshaw** [comment]
Just set the width to 100% and maxWidth to 400px
