### ISSUE TITLE
License changed from MIT to GPL

### ISSUE THREAD

**Issue by Pixelshaped** [davidjbradshaw/iframe-resizer#1265]
Hi there!

There are some implications to the GPL license that make it a breaking change: the GPL license is transitive (any project embedding your code has to be shared under the GPL license too). This means a lot of closed source apps that were relying on your code will have to eventually drop it.

This might not be news for you, and you're absolutely entitled to the change, but maybe you were unaware of this, hence this message.

Thanks!

**Comment by davidjbradshaw** [comment]
Hi,

Yeah this project is now dual licensed, if you don't want to use the GPL, then you have the option to use the new commercial license for a low cost one time fee.

https://iframe-resizer.com/pricing/

Cheers,
Dave.
