### ISSUE TITLE
Incorrect license in 4.4.x package.json

### ISSUE THREAD

**Issue by janrg** [davidjbradshaw/iframe-resizer#1268]
The 4.4.x versions on npm ship with an MIT license text but state GPL-3 in the package.json. I'm assuming this is not intended as presumably the license change was supposed to come into effect with version 5. As it is right now, npm might update the version automatically and people will end up with a GPL-3 package in their projects without realizing.

**Comment by davidjbradshaw** [comment]
Good spot, will update when I get a moment

**Comment by HSH73** [comment]
@davidjbradshaw Thanks also from my side for cleaning this up- just for clarity, If we still see the GPL reference in package.json of older versions (like 4.4.X), may I assume we can simply ignore this reference, given the relicensing to a dual licensing model applies only starting with Version 5?

**Comment by davidjbradshaw** [comment]
Fixed 4.4.5

**Comment by davidjbradshaw** [comment]
NPM won’t let me change old versions. The only difference in 4.4.5 is the license
