### ISSUE TITLE
Some times page show as blank on IOS device (iPhone Safari Browser) if forum is embedded and scroll up and down and then stop. 

### ISSUE THREAD

**Issue by masihurgmail** [davidjbradshaw/iframe-resizer#1269]
Issue: Some times page show as blank on IOS device (iPhone Safari Browser) if forum is embedded and scroll up and down and then stop. 

One of our client reported an issue that once user scroll the page up and down speedly, after that stop it then the page sow as blank. 
While if sroll again then the page show properly. 

Without embed like on normal forum working fine. So it looks like the issue is related to the resizer library. 

Please check it.

**Comment by davidjbradshaw** [comment]
Please can you provide a minimal reproducible example of the issue, so that I can take a look.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by davidjbradshaw** [comment]
Closed due to no response
