### ISSUE TITLE
5.1.2 bug - index.umd.js:20 Uncaught TypeError: Invalid value used in weak set

### ISSUE THREAD

**Issue by relima** [davidjbradshaw/iframe-resizer#1275]
**Describe the bug**
index.umd.js:20 Uncaught TypeError: Invalid value used in weak set
    at WeakSet.add (<anonymous>)
    at index.umd.js:20:11034
    at index.umd.js:20:62
    at index.umd.js:20:66

**To Reproduce**
<script src="/node_modules/@iframe-resizer/child/index.umd.js"></script>

**Expected behavior**
no error.

**Comment by davidjbradshaw** [comment]
Can you please send me a simpe example for how to reproduce this.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by relima** [comment]
I've reverted to using Parent page: 5.1.2 with Child page: 5.1.0, and the issue no longer occurs, so this solution works for me at the moment.

**Comment by davidjbradshaw** [comment]
I'm unable to reproduce the issue without more information. I have looked at the code and spotted one possible issue, that I have release a fix in v5.1.3. Can you let me know if that fixes it for you.

**Comment by relima** [comment]
the error persist. I have decided to leave it up so that you may see it in prod https://stonex.digital/eventos

**Comment by davidjbradshaw** [comment]
OK thank you, I see the issue now is that `document.body` is returning 'null' during startup and all my tests load the script file using `defer` so I never have that issue.

Anyway should hopefully be fixed in v5.1.4

**Comment by relima** [comment]
The issue has been resolved on 5.1.4. Thank you.
