### ISSUE TITLE
[Question] Does this lib support prevent cross site tracking feature in safari iframe?

### ISSUE THREAD

**Issue by catmans1** [davidjbradshaw/iframe-resizer#1283]
Regarding, This is just a question
Does this lib support prevent cross site tracking feature in safari iframe?

**Comment by davidjbradshaw** [comment]
This lib should have no effect on cross site tracking prevention in Safari.

**Comment by catmans1** [comment]
@davidjbradshaw 
Super response!
Thank you!
I closed this thread.
