### ISSUE TITLE
Back button not working with inPageLinks with workaround

### ISSUE THREAD

**Issue by kevinkaske** [davidjbradshaw/iframe-resizer#1286]
When enabling inPageLinks during initialization, the anchor links work but the back button takes you to the previous page (the page in your history before the page that contains the iframe)

Expected behavior:
Take you to the previous spot on the parent page where the link was clicked.

Workaround:
I added the following to the child page to add the hash to the parent page history. I also added the class "samepagelink" to make assigning the javascript easier. This adds the same hash from the child page link to the parent page history.

```
    document.addEventListener("DOMContentLoaded", function() {    	
        var elements = document.getElementsByClassName("samepagelink");
        
        Array.from(elements).forEach(function (anchor) {
            anchor.addEventListener("click", function (event) {
                window.parent.location.hash = anchor.hash;
            });
        });
    });
```

**Comment by davidjbradshaw** [comment]
Interesting idea. Will give it some though on how to integrate it to the main code base.

**Comment by davidjbradshaw** [comment]
This was a one line fix that should have been there from the start. Thanks for the idea. It will be included in the next release.
