### ISSUE TITLE
window is not defined (ssr)

### ISSUE THREAD

**Issue by dackmin** [davidjbradshaw/iframe-resizer#1291]
**Describe the bug**
v5 is using `window` inside `@iframe-resizer/child` which breaks server-side rendering.

**To Reproduce**
Load a child from something like Next (that has server side rendering)

**Expected behavior**
v4 doesn't and works perfectly.

**Screenshots**
<img width="515" alt="Capture d’écran 2024-07-11 à 08 48 45" src="https://github.com/davidjbradshaw/iframe-resizer/assets/1873323/7862e2fc-7011-422f-b8bb-0181443fa5a5">

**Desktop**
 - OS: MacOS Sonoma v14.5.0
 - Browser: Chrome v126.0.6478.127 (arm64)
 - Node: v20.13.1
 - Next: v14.2.4
 - @iframe-resizer/child: latest (5.1.5 right now)

**Comment by davidjbradshaw** [comment]
Thanks for this, the child code checks for `window` and halts if it is not there. However, their where a couple of variables getting setup before that point that had references to `window` in them, that I now also guard. This was not an issue in v4 due to the build process being different and allowing me to check for `window` and exit before defining anything. But sadly that is not possible with Rollup.  

I will hopefully get a beta out with a number of things in it later today.

**Comment by davidjbradshaw** [comment]
Could you please try version `5.2.0-beta.3` and let me know if that fixes this for you?

**Comment by dackmin** [comment]
<img width="520" alt="Capture d’écran 2024-07-11 à 13 38 31" src="https://github.com/davidjbradshaw/iframe-resizer/assets/1873323/92e5b8ee-f022-4530-9406-dc241684221d">

almost there 😄

**Comment by dackmin** [comment]
here's a codesandbox to see the bug in action: https://codesandbox.io/p/devbox/iframe-resizer-ssr-issue-dr8r95

**Comment by davidjbradshaw** [comment]
OK different and more robust approach. I've wrap the whole thing in a function, that only gets called if window is available.

`5.2.0-beta.4`

Hopefully it works for you this time.

**Comment by davidjbradshaw** [comment]
Make that `5.2.0-beta.5`.

I need to come up with an SSR test, as everything is currently configures for Client Side and auto mocks `window` and `document`.

**Comment by dackmin** [comment]
Works perfectly inside codesandbox, I can't work on the original project right now but that's the exact same configuration so it should work too.
Well done!

**Comment by davidjbradshaw** [comment]
Thanks for letting me know. Just putting the finishing touches to rewriting the performance observer code and then will push out the final release of 5.2.

**Comment by davidjbradshaw** [comment]
Released in v5.2
