### ISSUE TITLE
Changes to the license are not mentioned in breaking changes for v5

### ISSUE THREAD

**Issue by darkowic** [davidjbradshaw/iframe-resizer#1299]
The change of a license is an important breaking change that should be clearly highlighted in upgrade notes! I understand why you do this and what the consequences are but I really disapprove such a dirty play. The new minor release has a spamming warning about the upgrade available (which is not possible to remove and we can not upgrade immediately due to license change), the readme for tag 4.4.x is incorrect and redirects to the v5 API.

We will validate options to upgrade to v5 and eventually buy the license but the lack of appropriate communication could lead to illegal usage of your library which we don't want.

**Comment by davidjbradshaw** [comment]
That’s a fair point,I will update the V5 Release notes
