### ISSUE TITLE
version 5 typings - use in Angular 18

### ISSUE THREAD

**Issue by triplew-creative** [davidjbradshaw/iframe-resizer#1302]
I am unable to use the new version, 5.2.3 (e.g. [@iframe-resizer/parent](https://www.npmjs.com/package/@iframe-resizer/parent)), in Angular because there is no typings package. Previously, for version 4 you can use [@types/iframe-resizer](https://www.npmjs.com/package/@types/iframe-resizer), however can't be used as references the v4 files (iframeResizer.contentWindow.js).

**Describe the solution you'd like**
Create a new @types/iframe-resizer for version 5. Is this in the cards?

**Describe alternatives you've considered**
I see in another issue #478, There are mentions of creating an Angular version in the latest comments from Jan this year (i.e. an angular wrapper @iframe-resizer/angular). However, a typings would be sufficient.

**Comment by davidjbradshaw** [comment]
There is now a typings file in the package.

https://www.npmjs.com/package/@iframe-resizer/parent?activeTab=code
