### ISSUE TITLE
Child API Documentation - Typo in parentIframe Detection Example

### ISSUE THREAD

**Issue by Smoles** [davidjbradshaw/iframe-resizer#1306]
In the [Child API documentation](https://iframe-resizer.com/api/child/) under the Methods section there's a slight typo in the `if` check example. There's an extra `d` at the end of "parentIframe" string.

![image](https://github.com/user-attachments/assets/d828074a-66b5-498c-aa7c-c85c2177d807)

**Comment by davidjbradshaw** [comment]
Good spot, fixed.
