### ISSUE TITLE
TypeError: Cannot create property 'id' on number '0'

### ISSUE THREAD

**Issue by hkdave95** [davidjbradshaw/iframe-resizer#1316]
Dear David

This javascript error has crept in. I just got the latest three js-dist files.

The resizer works so I am only just addressing this. The first three grabs from GitHub since I upgraded to your new source have been causing this error.

I am licensed on david@dar-jader.com ...

Steps to reproduce:

1. dial up https://www.studentrms.org/referral-staging
2. Check javascript console when fully rendered.
3. Note full error

My implementation:

.cshtml:

    window.iframeResizer = {
        targetOrigin: '@lsTLD'
    }

your script:

<script type="text/javascript" src="/js/iframe-resizer.child.js" defer></script>

js

     oIFrame.iframeResize({ license: 'obsfucated', waitForLoad: true, direction: 'vertical', inPageLinks: true, checkOrigin: [sDomain] });

your script:

            jQuery.getScript(_sStagingOrLive + "/js/kendo/jszip.min.js"),
            jQuery.getScript(_sStagingOrLive + "/js/kendo/kendo.all.min.js"),
            jQuery.getScript("https://www.bugherd.com/sidebarv2.js?apikey=obsfucatd"),
            jQuery.getScript(_sStagingOrLive + "/js/iframe-resizer.jquery.js"),
            jQuery.getScript(_sStagingOrLive + "/js/h28.js"),

Note the jQuery method to load scripts is a Wordpress "hack" to utilise Custom HTML.

Please could you tell me what I am missing, as this seems pretty simple.

I work on staging a lot so I hope when you refresh it is between compiles ... 

KR

David

**Comment by davidjbradshaw** [comment]
Just published `v5.2.5` which should fix this.

**Comment by davidjbradshaw** [comment]
btw I don't see iframe-resizer running on the above link

**Comment by davidjbradshaw** [comment]
Sorry my bad, the issue does not appear in Safari, just Chrome for some reason. It is happening on the parent page. It looks like the element that you jQuery is passing to iframe-resizer, is not an iframe. But in that case you should be getting a better error message.

Can you please create a simple parent page that just has the iframe and the JS to start iframe resizer and I will look a bit deeper at this.

**Comment by davidjbradshaw** [comment]
No to worry I found the issue, you must be the first person to try the new jQuery plugin.

The issue is jQuery's `.each()` method puts the `index` before `array[index]` for some daft reason and I didn't catch it as all the tests use the non JS version.

I will sort the tests and then release a fix early next week, as I don't like pushing updates on a Friday.

**Comment by davidjbradshaw** [comment]
Fixed: `v5.2.6`
