### ISSUE TITLE
Feature Request: listen to url / history change from outside the iframe

### ISSUE THREAD

**Issue by fabiangigler** [davidjbradshaw/iframe-resizer#1349]
**Is your feature request related to a problem? Please describe.**
I'm always annoyed when my iFrame is now perfectly sized, but I still have to implement additional functionality to redirect the parent page, when i.e. a form is submitted in the embedded iFrame.

**Describe the solution you'd like**
Ideally I could subscribe to history change events from the parent frame, without having to write additional code in the child page.

**Describe alternatives you've considered**
It seems I can implement this myself by using the `sendMessage` method and `onMessage` event, but even though it's not directly related to resizing iframes, I find needing this functionaliaty at least 50% of the times in addition to resizing.

**Additional context**
I did get a professional license (kudos to figuring out a way to support your work, while still keeping pricing affordable), but even though I'm not sure how the licensing works exactly, this would be a great additional feature to opt for a higher pricing tier.

**Comment by davidjbradshaw** [comment]
Just to be clear, you want to be able to redirect the parent page after a form submission, and maybe other events in the iframe?

How would this be different to just doing the following in the iFrame?
```js
top.location.href = ‘https://mysite.com/next_page.html’
```

**Comment by fabiangigler** [comment]
In the context of a react or Next.js application that would embed an iFrame from a pre-existing site or external form hosting service, I would like to listen to a history change event in the child iframe, to do a range of different things on the parent page actually, ideally without having to add additional code to the child iframe.

This desire comes mostly from the use case of embedding parts of legacy websites on new developments.

**Some more specific use cases include:**

- Showing a success message on the parent page (and hiding the entire iFrame) once a redirect in the child frame to externaldomain.com/success is detected. 

- Closing/Hiding the iframe on the parent page once a "Cancel" or "Back" link is clicked within the iframe.

- Redirection to a Thank you page on the parent site, once a checkout/payment form on the iframe triggers a redirect to /thank you within the iframe

**Comment by davidjbradshaw** [comment]
I don’t really see how that could be achieved without having you write code in the child page. As the library would not be able to tell which events to report and which to ignore.

**Comment by fabiangigler** [comment]
I understand, it's not always easy, depending on the child iframe application, but the most basic implementation would be to send a postMessage with the current URL from the child script as early in the script execution as possible.

That would allow me to listen to the load event from the parent page, with the significant advantage over the default iFrame load event, that I would receive another load event once the URL inside the iFrame changes (as long as it's to another page, that has the iframeResizer script added)

If you want to go a bit further, sending a postMessage on the beforeUnload event would allow you to track interactions that navigate away from a page using links or forms, or whatever. 

Hope that makes sense!

**Comment by davidjbradshaw** [comment]
The `onload` event on the iframe already fires each time the page in the iframe changes. It’s what _iframe-resizer_ uses internally to detect the page has changed.

Access to the URL of the iframe is blocked by the browser for security reasons and I don’t want to circumvent browser security. So I’m afraid, whilst it would be simple to add URL tracking, it is not something I am going to do.

**Comment by davidjbradshaw** [comment]
Closed due to no response
