### ISSUE TITLE
iFrame loading in the wrong location

### ISSUE THREAD

**Issue by markjamesm** [davidjbradshaw/iframe-resizer#1350]
**Describe the bug**
Sometimes when a page with the iFrame Resizer loads, the form appears below the footer of the website instead of where it should be (to the right of "Curious about how Maya HTT can help you?" in the screenshot below.

**To Reproduce**
1. Go to [https://www.mayahtt.com/products/simcenter-3d-for-additive-manufacturing/](https://www.mayahtt.com/products/simcenter-3d-for-additive-manufacturing/).
3. Scroll down to the contact us section.
4. Sometimes the form will appear below the site footer like in the screenshot below.

**Expected behavior**
The form loads in the correct place.

**Screenshots**

![contact-form](https://github.com/user-attachments/assets/e59dd83b-befd-41d3-acc7-3c058cb6f00e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge 
 - Version: 29.0.2792.89 (Official build) (64-bit)

**Additional context**
This is the embed I'm using on my site:

```html
<style>
    #pardotForm {
        width: 100%;
        height: 100vh;
        border: 0px;
    }
</style>

<noscript>
    <iframe src="https://www2.mayahtt.com/l/504061/2018-02-06/67n2mt" id="pardotForm" type="text/html"
        allowTransparency="true"></iframe>
</noscript>

<iframe id="pardotForm" src="https://www2.mayahtt.com/l/504061/2018-02-06/67n2mt"></iframe>

<script src="https://cdn.jsdelivr.net/npm/@iframe-resizer/parent"></script>

<script>
    iframeResize({
        license: 'xxxx',
        waitForLoad: true,
        log: false,
    }, '#pardotForm');
</script>
```

**Comment by davidjbradshaw** [comment]
Looking at your code embed, if you don't have JS you will end up loading the iframe twice. You don't need that `<noscript/>` block and given it uses the same ID on both iframes, I'm not sure what effect that will have on iframe-resizer. Beyond that your code looks good to me.

**Comment by davidjbradshaw** [comment]
Closed due to no response
