### ISSUE TITLE
Minimum working archive

### ISSUE THREAD

**Issue by tipodanet** [davidjbradshaw/iframe-resizer#1357]
Could you add a Minimum Work Archive? 
No decoration, with minimal comments. For dummies. 
I do according to the simpler version 4.4.5 - - does not work.
Version 5.3.2 seems more difficult to me. 
In an archive of 5 files (2.html + 3.js), perhaps I would understand.

**Comment by tipodanet** [comment]
<script src="../../../js/iframe-resizer.child.js"></script> --- NOW
may be  ?
  <script src="../../../js-dist/iframe-resizer.child.js"></script>

**Comment by davidjbradshaw** [comment]
That’s a good spot. `js` is my build folder that doesn’t get checked in and I use the examples for manual testing. But yes I need to think about that a bit more and make it work as an example.

I would be interested on you feedback on the https://iframe-resizer.com website and what you find difficult, as I would like to make the instructions as easy to follow as possible.

**Comment by tipodanet** [comment]
david , TNX !  
gradually I realized that all resize works! I've almost figured it out. 
No more simple designs for dummies are needed. 
I have reduced everything to 4 files. 
Not because there's a lot to spare, but that's the only way I can adapt IFRAME-RESIZER to my training site. Thanks again.
