### ISSUE TITLE
Doesn't work in dev (Next.js)?

### ISSUE THREAD

**Issue by bdrtsky** [davidjbradshaw/iframe-resizer#1360]
I set my app following docs, it didn't worked in dev, but after the build it does work. Is there any way to make it work in dev with Next.js? Since it's impossible to use this way.

Would be glad to use it in commercial product, but not sure how to start, if it does not work

**Comment by davidjbradshaw** [comment]
You have not given me any details on what you are trying to do, if you are trying to run next.js in the iframe, then add the import for the child JS package in app.js
