### ISSUE TITLE
license 

### ISSUE THREAD

**Issue by HSH73** [davidjbradshaw/iframe-resizer#1366]
I saw this is dual licensed now -  a move you are absolutely entitled to of course. 
However, the wording „_This JavaScript library is Copyright © 2013-2024 David J. Bradshaw and i**s distributed under the GPL V3 for non-commercial use__**” seems to be somewhat misleading and requires explanation and potentially correction. 
The wording, as it currently stands, could be understood as if the package is not at all available for use under the GPL in any _commercial_ environment, like use for a website with a commercial background or the like, and the one and only option is to use it for such purposes is under the commercial license. 
I think this is neither possible under the GPL nor intended by you, if I am not mistaken. 
The GPL proposes that any type of use is allowed, may it be for commercial or non-commercial purposes, provided that the user is prepared to accept the consequences, e.g. like having to provide the project source code if the code is being conveyed to downstream recipients. But to add deviating _conditions_ to the use of GPL’ed code is not allowed (“_You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License. For example, you may not impose a license fee, royalty, or other charge for exercise of rights granted under this License,…_). 
Of course, you are free offer to waive the downsides of the GPL under a commercial license through a dual-licensing mechanism, where the user (including commercial purposes) can choose to either use under the GPL accepting all somewhat burdensome consequences/obligations under the GPL), or to simply opt for the commercial license. But, at least to my understanding, one cannot restrict the use under the GPL to only non commercial projects. 
If my assumptions are correct, I propose to change the language to a more “customary” language for dual licensed projects, for instance: “_This JavaScript library is Copyright © 2013-2024 David J. Bradshaw . It is  dual licensed and can be used, at your option, either under the GPL V3 or under a commercial license which can be obtained here: https://iframe-resizer.com/pricing/_ . 
At least please clarify the intention of the language. Thanks.

**Comment by davidjbradshaw** [comment]
Yeah, but I don't have a lot of space to explain the GPL to someone who is new to it,

**Comment by boris-moduscreate** [comment]
Hey David, I get your perspective but have to agree with the previous poster. There is no mechanism within GPL to restrict usage to non-commercial use cases only. You are either GPL or you are not. It's absolutely your right to charge for the app, and typically the solution to this is to make a portion of the code that provides meaningful business value not covered by GPL. Your current approach isn't legally sound and I would encourage you contact an attorney to make sure you're protected in the way you expect.  As is, users can legally take the code and use it in a commercial setting without any risk to themselves which seems like it will undermine your goals of making your work sustainable. Best of luck with the tool and I appreciate all your hard work on it over the years.

**Comment by HSH73** [comment]
Again, I believe the issue would be sorted by simply replacing the misleading text :"„_This JavaScript library is Copyright © 2013-2024 David J. Bradshaw and i**s distributed under the GPL V3 for non-commercial use_*_*" by “This JavaScript library is Copyright © 2013-2024 David J. Bradshaw . It is dual licensed and can be used, at your option, either under the GPL V3 or under a commercial license which can be obtained here: https://iframe-resizer.com/pricing/_

**Comment by dominikzogg** [comment]
@HSH73 GPL V3 allows commercial use, but to everyone you distribute the application is entitled to ask for the source. Thats why i complain. This is a GPLv3 violation.

GPLv3 or commercial for non GPLv3 compliant  projects would be correct.

**Comment by hosiet** [comment]
Hi @davidjbradshaw , this is a @Debian Developer that encounters your project when working on other projects that embed your work in their software.

I have no doubt that you have the absolute right to determine the license of your published project. Yet from what I read above and from the current license file in v5.x releases, my interpretation is that you essentially forbid any commercial use unless the user obtains a separate license. This is a violation to GPLv3, and makes your software proprietary and non-free in terms of [Free/Libre software definition (OSI)](https://opensource.org/). This is not a problem, but I have to work with other projects to strip your work from their software because they want to keep their software free/libre.

Please correct me if my understanding is wrong. Many thanks!

**Comment by davidjbradshaw** [comment]
Hi @hosiet, I think you’re misunderstanding my aims. The commercial license is aimed at for profit sites/organisations that don’t want to publish 100% of their site code, as required by the GPL. 

The aim is provide an additional route to license the code for sites that are not fully compliant with the GPL. This is similar to what TideLift does, when you sign up with them you grant their subscribers the right to use your code outside of the GPL.

I hope that clears things up, however, I’m happy to continue the conversation if you have more questions.

Dave.

**Comment by hosiet** [comment]
Hi @davidjbradshaw , thanks for the response. Can you update the LICENSE file to rephrase it so that we have no doubt on the actual license terms? For example:

> This JavaScript library is Copyright © 2013-2025 David J. Bradshaw and is dual-licensed, either under GPL V3, or a commercial license that is available for purchase upon request. For more information on commercial licensing, please see ...

In that way, we can make it clear that it is allowed to redistribute your work under a pure GPLv3 license. Of course, the redistribution will retrain the verbatim copy of your `LICENSE` file as a whole so that the dual-licensing condition is retrained.

**Comment by davidjbradshaw** [comment]
@hosiet Sorry for the slow reply, I have been unwell. I've updated the file with your suggestion.

**Comment by hosiet** [comment]
Many thanks @davidjbradshaw ! The current version is unambiguous and looks great.
