### ISSUE TITLE
Site auto-scrolling to contact form

### ISSUE THREAD

**Issue by markjamesm** [davidjbradshaw/iframe-resizer#1367]
**Describe the bug**

When I load my website with the iFrame-Resizer, sometimes it auto-scrolls to the contact form at the bottom of the page. An example can be found here, and you can see when various pages load, they auto-scroll to the iFrame near the footer: https://www.youtube.com/watch?v=dObm9gq5tUc

This has been confirmed to happen to over ten users so far.

**To Reproduce**

- Go to https://mayahtt.com/ or any other page on the site.
- The page should auto-scroll to the contact form, but the issue happens intermittently making it difficult to debug.

**Expected behavior**

The page loads normally and only scrolls to the bottom when the URL contains the anchor link ([https://mayahtt.com#contact](https://mayahtt.com/#contact))

**Desktop (please complete the following information):**

Browser: Chrome
129.0.6668.71 (Official Build) (64-bit)

**Additional context**
This seems to happen on any page containing a contact form but intermittently.

**Comment by davidjbradshaw** [comment]
I still do not believe this to be an issue with _iframe-resizer_. Please can you stop raising the same issue again and again. I note that you did not even acknowledge my response to the last time you raised this in issue #1350. In that ticket I pointed out issues with your code that could be causing undefined results.

For me to look at this further I would need you to create a [Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) and clear instruction on how to replicate the issue. A YouTube video of a page scrolling gives me absolutely nothing to go on.

**Comment by davidjbradshaw** [comment]
Sorry that was a bit too rude, I’ve had a bad day. If you create the simple example, I will be happy to look at the isssue.
