### ISSUE TITLE
FireFox parentIFrame undefined

### ISSUE THREAD

**Issue by mglazer-cengage** [davidjbradshaw/iframe-resizer#141]
So this works in Chrome but not firefox.
I have enablePublicMethods to true and I'm doing this:
            var doc         = that.contentDocument;
            var frameWin    = that.contentWindow;

            var fun = function(){
            console.log(frameWin, frameWin.parentIFrame) // undefined in firefox works in chrome
              if ('parentIFrame' in frameWin) {
                   setTimeout(function(){ // Fix FireFox timing issue
                       frameWin.parentIFrame.size();
                   },0);
               }
           };

            $(doc).hover(fun);

One thing to note my iframe is not a url it is created like so: 
doc.open()
doc.write(html)
doc.close()

Any ideas?

**Comment by davidjbradshaw** [comment]
Not really, I'd look around stack exchange for help on get a ref to the iframe when it's created like that. If you do find an answer can you please let me know as I think I might have that issue soon on another project.

**Comment by mglazer-cengage** [comment]
I have the ref to the iframe that's the 'frameWin' that's defined it's this property that is undefined: frameWin.parentIFrame.

var that= iframeNodeObject;
var doc = that.contentDocument;
var frameWin = that.contentWindow;

I can see when i turn on the logging that the execution get's halter not sure if that's due to postMessage/something failing..

"[iFrameSizer][Host page] IFrame scrolling disabled for cas-cxp-frame" iframeResizer.min.js:24

"[iFrameSizer][Host page][init] Sending msg to iframe (cas-cxp-frame:8:true:true:32:true:true:null:max:null:null:0)" iframeResizer.min.js:24

"[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (cas-cxp-frame:8:true:true:32:true:true:null:max:null:null:0)" iframeResizer.min.js:24

**Comment by mglazer-cengage** [comment]
I don't think I was clear - the frameWin is defined, it is the parentIFrame within frameWin that isn't defined and only in FireFox.

**Comment by davidjbradshaw** [comment]
Do you have a test case I can take a quick look at?


On Tue, Jan 13, 2015 at 6:38 PM, mglazer-cengage <notifications@github.com>
wrote:

> I don't think I was clear - the frameWin is defined, it is the
> parentIFrame within frameWin that isn't defined and only in FireFox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/141#issuecomment-69795005>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by mglazer-cengage** [comment]
I resolved it.
The issue had to do with how the contentWindow.js was being loaded.

I was initially loading it in the doc (frameWin via createElement and head.append before doc.open
That loaded it virtually but not into the actual rendered dom which FireFox seemed to have an issue with.

The fix was to simple prepend the script tag to the html used within doc.write - it then is added to the head tag.

**Comment by davidjbradshaw** [comment]
Thanks for the update.
