### ISSUE TITLE
Send message from parent frame to iframe

### ISSUE THREAD

**Issue by viatoste** [davidjbradshaw/iframe-resizer#142]
Is it possible to send a message from the parent frame to the iframe with your script? window.parentIFrame.sendMessage works fine for sending a message to the parent frame, but i'm looking for the other way

**Comment by davidjbradshaw** [comment]
That's not supported currently, you will need to you the native postMessage method for this.

The child to parent version was added mainly to help with automated testing and it was only a couple of lines to add it. Doing it the other way is more complex to add as you would have to have a way of saying which iFrame and then add something to support callbacks in the iFrame. Where as the child only had ne parent and the call back handling code is already in place.

**Comment by richardhovdsveen** [comment]
I + this. 
By the console it seems like you push through an object to the iframe while init it. Could you explain how this is done or give an example of how its possible to receive the message in an Iframe?

**Comment by davidjbradshaw** [comment]
The info can be found on MDN:

https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage
