### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '#/lobby/' is not a valid selector

### ISSUE THREAD

**Issue by ezzatron** [davidjbradshaw/iframe-resizer#145]
Just encountered this bug when mixing an AngularJS single-page app with iframe-resizer. This is happening in `findTarget()`, which is being called from `checkLocationHash()`.

The resizer code is assuming that any URI fragment represents an anchor/element within the page, which is not always true. Perhaps you could simply surround in a try/catch, or check the fragment against a regex before looking for a target element?

**Comment by davidjbradshaw** [comment]
Ah good point, I think rather than try catch, just testing for '/' in the string should catch the issue.

**Comment by davidjbradshaw** [comment]
Thank you for the PR on this.

Released as v2.8.2
