### ISSUE TITLE
autoResize: false - stopped working

### ISSUE THREAD

**Issue by paulbors** [davidjbradshaw/iframe-resizer#148]
Conform the API:
```
autoResize

default: true
type:    boolean
When enabled changes to the Window size or the DOM will cause the iFrame to resize to the new content size. Disable if using size method with custom dimensions.
```

However, when I turned this option off by setting it to false and to my surprise the iFrame still resized :(

See http://jsfiddle.net/paulbors/n3abtczy/5/
Click on the button below "Home" half hidden on the screen.

**Comment by davidjbradshaw** [comment]
That option disables all the events that check to see if the page resizes after the initial sizing of the iFrame. It's meant for iFrames that just need sizing once.

**Comment by paulbors** [comment]
Aha, I guess I got confused in the documentation of it.

Then this is not an issue since that's exactly how it behaves.

**Comment by davidjbradshaw** [comment]
Does the documentation need to be clearer?

**Comment by paulbors** [comment]
Yes, I would advise updating the documentation with a better choice of words as it can be confusing.
