### ISSUE TITLE
window.parentIFrame.size(250), but msg shows 900

### ISSUE THREAD

**Issue by jezmck** [davidjbradshaw/iframe-resizer#149]
Hi,
apologies if this isn't the right place for this, but ...

With the following, I cannot get the iframe to resize on request.

The iframe starts with external uneditable source, but later requests new source from the same domain.

The parent frame includes the following

    <iframe src="{external domain}" width="100%" height="900" id="sagepay"
            marginheight="0" frameborder="0" scrolling="no"></iframe>
    <script type="text/javascript" src="/js/iframeResizer.min.js"></script>
    <script type="text/javascript">
        iFrameResize( { autoResize: false, minHeight: 200, enablePublicMethods: true, checkOrigin: false, log: true }, '#sagepay' );
    </script>

the iframe includes the following

    <script type="text/javascript" src="/themes/shorefield/js/iframeResizer.contentWindow.min.js"></script>
    <script type="text/javascript">
      window.top.hidetotals();
      if ('parentIFrame' in window) {
          window.parentIFrame.size(250);
      }
    </script>

The log:

```
"[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (sagepay:8:false:true:32:true:false:null:offset:null:null:0)" iframeResizer.min.js:8:533
"[iFrameSizer][Host page] Received: [iFrameSizer]sagepay:900:970:init" iframeResizer.min.js:8:533
"[iFrameSizer][Host page] Checking height is in range 200-Infinity" iframeResizer.min.js:8:533
"[iFrameSizer][Host page] Checking width is in range 0-Infinity" iframeResizer.min.js:8:533
"[iFrameSizer][Host page] Requesting animation frame" iframeResizer.min.js:8:533
"[iFrameSizer][Host page] IFrame (sagepay) height set to 900px" iframeResizer.min.js:8:533
"[iFrameSizer][sagepay] HTML & body height set to "auto"" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] Enable public methods" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] Auto Resize disabled" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] Setting up location.hash handlers" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] Trigger event lock on" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] Sending message to host page (sagepay:900:970:init)" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] Trigger event lock off" iframeResizer.contentWindow.min.js:9:234
"[iFrameSizer][sagepay] --" iframeResizer.contentWindow.min.js:9:234
```

I've tried all sorts of combinations of options, but the message always says 900!

Any help will be hugely appreciated!

**Comment by davidjbradshaw** [comment]
Your making the call to `size()` before the code has initialised. Try something like this.

 	$(document).ready(function(){
		$(window).one('resize',function(){
			if ('parentIFrame' in window) {
				window.parentIFrame.size(250);
			}
		});
	});

**Comment by jezmck** [comment]
Hi, afraid that didn't help, and I've discovered that `parentIFrame` isn't `in` `window`. Any idea?

**Comment by davidjbradshaw** [comment]
It won't be until the init script has finished running, as that is what adds it. This is another option.

	var timer = setTimeout(function(){
			if ('parentIFrame' in window) {
				parentIFrame.size(250);
				clearTimeout(timer);
			}
	},16);

**Comment by jezmck** [comment]
Okay, that's working, not sure why it needs such a big delay, but there are a number of odd things on my page.

Many thanks for your help!
