### ISSUE TITLE
Race condition with setHeightCalculationMethod()

### ISSUE THREAD

**Issue by ezzatron** [davidjbradshaw/iframe-resizer#150]
I'm using `setHeightCalculationMethod()` from within the content window to set the height calculation method, as `lowestElement` is the only method that correctly calculates the height for me. This is working only intermittently, and I believe I've figured out why.

When it works (about 20% of the time), the order of events is:

1. Parent window loads
2. Child window loads
3. Child window sets height calculation method
4. Iframe-resizer calculates height correctly

When it fails, the order of events is:

1. Parent window loads
2. Child window loads
3. Iframe-resizer calculates height based upon the default height calculation method
4. Child window sets the desired height calculation method
5. Iframe-resizer does not reset the iframe height
6. No further window events fire to cause another iframe resize

I've tried hacking the iframe-resizer code to make `setHeightCalculationMethod()` cause an iframe resize, and I've also tried manually calling the undocumented public method `reset()` after setting the height calculation method.

Neither of these approaches work, because of the `triggerLocked` system that is in place in `iframeResizer.contentWindow.js`. If I'm interpreting the code correctly, it's designed to prevent the resize happening in rapid succession.

There are two things I think would fix this, and potential future race condition issues:

1. Scrap the `triggerLocked` system in favour of a proper [debounce](https://lodash.com/docs#debounce) implementation. Rather than just ignoring subsequent events, this will allow you to perform a resize on the leading and/or trailing edge of a set of events.
2. Setting the height calculation method should automatically trigger a `reset()`. Either that, or document `reset()`, and mention that it needs to be called manually after setting the method.

If I get a chance, I'll have a go at a PR, but this one might be a bit complex for me to tackle.

**Comment by ezzatron** [comment]
Okay, I *may* have jumped the gun there. There is a race condition, but it's not the one described above. I was using this logic in my app (forgive the CoffeeScript and Angular-ness):

```coffee
if $window.parentIFrame?
    $window.parentIFrame.setHeightCalculationMethod "lowestElement"
``` 

The problem was actually that, most of the time, `window.parentIFrame` did not exist yet, as the parent window had not finished executing its initialization code in time. So now I'm stuck with the lovely solution of using `setInterval()` to account for this delay:

```coffee
iFrameResizeAttempts = 0
iFrameResizeInterval = null
initIframeResize = ->
    if ++iFrameResizeAttempts > 30
        $window.clearInterval iFrameResizeInterval
    else if $window.parentIFrame?
        $window.clearInterval iFrameResizeInterval
        $window.parentIFrame.setHeightCalculationMethod "lowestElement"
iFrameResizeInterval = setInterval initIframeResize, 100
```

Do you have any better ideas on how to solve this?

**Comment by davidjbradshaw** [comment]
Your the second person this week to raise this, maybe the lib needs to fire a custom event event on ready. Easy with jQuery, need to think about native.

**Comment by davidjbradshaw** [comment]
That said why are you not setting the height calc mode in the parent?

**Comment by ezzatron** [comment]
The parent is controlled by a different software company to the one I work for. Setting the calc method from the child allows me to change it without instigating a laborious political process ;)

**Comment by davidjbradshaw** [comment]
Ah.

https://c1.staticflickr.com/1/36/96987427_d3a0582fdc.jpg


-- 
Sent from my iPhone.
