### ISSUE TITLE
Message conflict parse error

### ISSUE THREAD

**Issue by aleross** [davidjbradshaw/iframe-resizer#154]
I need to send messages down the `postMessage()` pipeline. The messages our application sends are JSON-encoded. It seems the iFrame Resizer content script is throwing errors on each one of these JSON messages. Any tips?

`Uncaught SyntaxError: Unexpected token i`

**Comment by davidjbradshaw** [comment]
It should cope with that. Can you send me a simple test case and I will take a look.

**Comment by aleross** [comment]
It was my mistake actually, iframe-resizer does cope nicely. I forgot to valid JSON on one of my ends. Thanks for the quick response!
