### ISSUE TITLE
[Question] Alternative for height: 100%

### ISSUE THREAD

**Issue by MikeGameDev** [davidjbradshaw/iframe-resizer#156]
I am having issues getting my frame to scale down, scaling up works perfectly. After looking around, I've found that a common cause for this is setting attributes to height: 100%. I have that all over the place in my code and I was wondering what I should do instead.

My initial thought was to use the resizedCallback in the parent document to change the height of elements to whatever the new size of the iframe is, but I cannot figure out how to get the callback to trigger.

Here is a link to the page I'm working on: http://mikegamedev.weebly.com/blog.html

 I'm trying to embed a blogspot blog into a weebly site. Any help would be appreciated.

Thanks,
Mike

**Comment by davidjbradshaw** [comment]
Changing the height calculation method to `max` might help, beyond that it's more of a question for stackoverflow.
