### ISSUE TITLE
IE9 support?

### ISSUE THREAD

**Issue by numediaweb** [davidjbradshaw/iframe-resizer#161]
I got this error while running the script (v2.8.4) on IE9 virtual machine:
`[iFrameSizer][iFrameResizer0] MutationObserver not supported in this browser!`

The iframe doesn't get resized.

However I see the script supports IE8+.. Am I missing something?

Thanks

**Comment by davidjbradshaw** [comment]
It's just a warning message, in IE10 and below it has to fall back to using setInteval.

**Comment by numediaweb** [comment]
Thanks @davidjbradshaw but the iframe doesn't do the resize on IE9, at least in my case.. Is there any special requirements for IE9?

**Comment by davidjbradshaw** [comment]
Is the example working for you?

**Comment by numediaweb** [comment]
The example is working, so I tried to find what was wrong with my code that it doesn't resize on IE9.. I found when setting `heightCalculationMethod: 'documentElementOffset'` the iframe doesn't resize on IE9.

I leave it to default and the iframe resizes.

Any hints :) ?

**Comment by davidjbradshaw** [comment]
Use 'max' or 'grow'.

**Comment by numediaweb** [comment]
@davidjbradshaw Thanks for the quick support :)
