### ISSUE TITLE
Not able to intitialize

### ISSUE THREAD

**Issue by j-christopher** [davidjbradshaw/iframe-resizer#164]
Hi, I've been searching around and this seems like a great solution to my iFrame woes! 

However, I have followed your install instructions and have logging turned on but nothing is working on page or logging to the console. I have pasting my code snippets below (1st parent, 2nd child). Any help is greatly appreciated!

PARENT PAGE / Container: 

&lt;head&gt;
&lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js&quot;&gt;&lt;/script&gt;
&lt;script type=&quot;text/javascript&quot; src=&quot;scripts/iframeResizer/js/iframeResizer.min.js&quot;&gt;&lt;/script&gt;
&lt;/head&gt;

&lt;body&gt;
&lt;iframe style=&quot;overflow:hidden;&quot; src=&quot;http://www.externalsite.com/stores/events_service.php?source=index&quot; width=&quot;100%&quot; scrolling=&quot;no&quot;/&gt;&lt;/div&gt;
&lt;/body&gt;

&lt;script type=&quot;text/javascript&quot;&gt;
// Options for iFrameResize plugin  

			iFrameResize({
				log                     : true,                  // Enable console logging
				enablePublicMethods     : true,                  // Enable methods within iframe hosted page
				resizedCallback         : function(messageData){ // Callback fn when resize is received
					$('p#callback').html(
						'&lt;b&gt;Frame ID:&lt;/b&gt; '    + messageData.iframe.id +
						' &lt;b&gt;Height:&lt;/b&gt; '     + messageData.height +
						' &lt;b&gt;Width:&lt;/b&gt; '      + messageData.width + 
						' &lt;b&gt;Event type:&lt;/b&gt; ' + messageData.type
					);
				},
				messageCallback         : function(messageData){ // Callback fn when message is received
					$('p#callback').html(
						'&lt;b&gt;Frame ID:&lt;/b&gt; '    + messageData.iframe.id +
						' &lt;b&gt;Message:&lt;/b&gt; '    + messageData.message
					);
					alert(messageData.message);
				},
				closedCallback         : function(id){ // Callback fn when iFrame is closed
					$('p#callback').html(
						'&lt;b&gt;IFrame (&lt;/b&gt;'    + id +
						'&lt;b&gt;) removed from page.&lt;/b&gt;'
					);
				}
			});

		&lt;/script&gt;
----------------

CHILD PAGE / Content:

&lt;html&gt;
&lt;head&gt;
&lt;script language=&quot;javascript&quot; type=&quot;text/javascript&quot; src=&quot;/stores/scripts/jquery-1.3.2.min.js&quot;&gt;&lt;/script&gt;
&lt;/head&gt;

&lt;body&gt;
..... content goes here .... 
..... more content here ..... 
..... content goes here .... 
..... more content here ..... 
&lt;/body&gt;

&lt;script type=&quot;text/javascript&quot; language=&quot;javascript&quot; src=&quot;/stores/scripts/iframeResizer/js/iframeResizer.contentWindow.min.js&quot;&gt;&lt;/script&gt;
&lt;/html&gt;

**Comment by davidjbradshaw** [comment]
Try just doing `iframeResize();` If that doesn't fix things, then you should ask a question on StackOverflow.

**Comment by j-christopher** [comment]
Thanks. When I tried that in the console I get: Uncaught ReferenceError: iFrameResize is not defined

**Comment by RJSekar** [comment]
Try calling in the iframe onload event.
This works fine for me :
&lt;iframe src="https://www.demourl.com/" onload="iFrameResize({log:true})" scrolling="no" frameborder="0"&gt;&lt;/iframe&gt;

**Comment by davidjbradshaw** [comment]
You should call it after the iframe tag, not via onload.
