### ISSUE TITLE
Problems with version v2.8.4 and IE8

### ISSUE THREAD

**Issue by pacionet** [davidjbradshaw/iframe-resizer#165]
Hi,
we are using iframe-resizer version 2.8.4 to resize an iframe.
The plugin works perfectly with all browser except IE8
In the console we see the following messages:

[iFrameSizer][itol_acquisti_iframe] MutationObserver not supported in this browser!
[iFrameSizer][itol_acquisti_iframe] Unexpected message ([iFrameSizer]itol_acquisti_iframe:4879:931:init)

The code is here:

$("#IFRAME_ID").height(0);
$("#IFRAME_ID").iFrameResize({
		log: true,
		autoResize: true
	});

The first statement seems necessary otherwise IE cannot calculate well page resize.
Is this a bug?

**Comment by davidjbradshaw** [comment]
The first one means the code is falling back to setInterval, as IE10 and below don't support mutationObsever.

The second one is unexpected, do you see this in the examples in IE8?

**Comment by davidjbradshaw** [comment]
Does it still work in IE8, looking at this a bit more, when the iFrame first loads the init message can sometimes get fired twice, in which case the second one will be ignored and this message logged.

**Comment by pacionet** [comment]
No,
in the example page IE8 works but I noticed that is is a different version.
The script
http://davidjbradshaw.com/iframe-resizer/iframeResizer.contentWindow.min.js
seems to be 2.8.3:
iFrame Resizer (iframeSizer.contentWindow.min.js) - v2.8.3 - 2015-01-29

**Comment by davidjbradshaw** [comment]
Strange can you post the full 2.8.4 log here.

**Comment by davidjbradshaw** [comment]
Also is this just an issue with the warning message, or does IE8 currently fail to work for you?

**Comment by pacionet** [comment]
HTML1300: Navigation occurred.
File: acquisti
[iFrameSizer][Host page] IFrame scrolling disabled for itol_acquisti_iframe
[iFrameSizer][Host page][init] Sending msg to iframe (itol_acquisti_iframe:8:false:true:32:false:true:null:offset:null:null:0:false)
[iFrameSizer][itol_acquisti_iframe] HTML & body height set to "auto"
[iFrameSizer][itol_acquisti_iframe] Added event listener: Animation Start
[iFrameSizer][itol_acquisti_iframe] Added event listener: Animation Iteration
[iFrameSizer][itol_acquisti_iframe] Added event listener: Animation End
[iFrameSizer][itol_acquisti_iframe] Added event listener: Device Orientation Change
[iFrameSizer][itol_acquisti_iframe] Added event listener: Transition End
[iFrameSizer][itol_acquisti_iframe] Added event listener: Window Clicked
[iFrameSizer][itol_acquisti_iframe] Added event listener: Window Resized
[iFrameSizer][itol_acquisti_iframe] MutationObserver not supported in this browser!
[iFrameSizer][itol_acquisti_iframe] setInterval: 32ms
[iFrameSizer][itol_acquisti_iframe] In page linking not enabled
[iFrameSizer][itol_acquisti_iframe] Trigger event lock on
[iFrameSizer][itol_acquisti_iframe] Sending message to host page (itol_acquisti_iframe:4879:931:init)
[iFrameSizer][itol_acquisti_iframe] Unexpected message ([iFrameSizer]itol_acquisti_iframe:4879:931:init)
[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (itol_acquisti_iframe:8:false:true:32:false:true:null:offset:null:null:0:false)
[iFrameSizer][itol_acquisti_iframe] Trigger event lock off
[iFrameSizer][itol_acquisti_iframe] --

**Comment by davidjbradshaw** [comment]
Weird. The iframe is receiving the message from the iframe, instead of it going to the host page.

Can you try this with 2.8.3?

**Comment by pacionet** [comment]
Same problem with 2.8.3
The code used to resize the iframe is the following (in the iframe)

function parentFrameResize(){
		if (parent.frameResizeTrackingOrder) {
	    	                 parent.frameResizeTrackingOrder();                           
	 	}
}
and in the host page:

function frameResizeTrackingOrder() {	
	$("#<IFRAME>").height(0);
	$("#<IFRAME>").iFrameResize({
		log: false,
		autoResize: true
	});
}
It could be a problem?

**Comment by davidjbradshaw** [comment]
Try,

    function frameResizeTrackingOrder() {
        $("#IFRAME").height(1);
        $("#IFRAME").iFrameResize({
            log: false,
            autoResize: true
        });
    }

**Comment by davidjbradshaw** [comment]
Infact you don't need all that code. Just do this in the parent page and the rest will be automagic.

    $("#IFRAME").iFrameResize({
        log: false,
        autoResize: true
    });

**Comment by pacionet** [comment]
Same problem and now i see only 1 pixel row ...
Same log:

HTML1300: Navigation occurred.
File: acquisti
[iFrameSizer][itol_acquisti_iframe] MutationObserver not supported in this browser!
[iFrameSizer][itol_acquisti_iframe] In page linking not fully supported in this browser! (See README.md for IE8 workaround)
[iFrameSizer][itol_acquisti_iframe] Unexpected message ([iFrameSizer]itol_acquisti_iframe:4879:931:init)

**Comment by davidjbradshaw** [comment]
I think the issue is your wrap code, just call the basic function.

**Comment by pacionet** [comment]
It works! Thanks a lot.
to be thorough the following is the working code:

<iframe onLoad="frameResizeTrackingOrder();" ... >

**Comment by pacionet** [comment]
It works but: in IE8 when I have to resize the iframe after an event on the iframe page, how can I trigger the resize without calling the parent?

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#size-customheight-customwidth
