### ISSUE TITLE
`settings` not scoped to each iframe

### ISSUE THREAD

**Issue by ReedD** [davidjbradshaw/iframe-resizer#169]
I have multiple (not nested) iframes in a window and each new iframe added overwrites the previous iframe's `settings`. i.e. Instantiating a second iframe will overwrite the `settings.messageCallback` for the first iframe.

**Comment by davidjbradshaw** [comment]
Yep agree that is a bug. If you want go through and scope `settings` to `settings[iframeId` throughout the host page js file, I'll be happy to take a pull request.

**Comment by ReedD** [comment]
Okay will do.

**Comment by ReedD** [comment]
So I just took another look at this and `iframeID` is not available for every instance in which `settings` is referenced. To get this fixed it may take a little bit of refactoring (unless I've overlooked a more obvious solution). I can take a shot at it if you want though.

**Comment by davidjbradshaw** [comment]
It should be available on the setup functions. I think you just need to
create it in the receive function and then set it from messageData.iframe.id
in processMsg().

On Tuesday, March 17, 2015, Reed Dadoune <notifications@github.com> wrote:

> So I just took another look at this and iframeID is not available for
> every instance in which settings is referenced. To get this fixed it may
> take a little bit of refactoring (unless I've overlooked a more obvious
> solution). I can take a shot at it if you want though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/169#issuecomment-82159727>
> .
>


-- 
Sent from my iPhone.

**Comment by ReedD** [comment]
How about for the `log` function?

**Comment by ReedD** [comment]
Perhaps the easiest solution is to make `log` setting global... However it is nice being able to isolate the log messages for a given iframe.

**Comment by davidjbradshaw** [comment]
I think we could make iframeId global and set each time we call in.

On Tuesday, March 17, 2015, Reed Dadoune <notifications@github.com> wrote:

> Perhaps the easiest solution is to make log setting global... However it
> is nice being able to isolate the log messages for a given iframe.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/169#issuecomment-82498286>
> .
>


-- 
Sent from my iPhone.

**Comment by ReedD** [comment]
Alright that seems to work pretty good, I created a new [pull request](https://github.com/davidjbradshaw/iframe-resizer/pull/173).

**Comment by davidjbradshaw** [comment]
Released as v2.8.5.

Thanks once again for a couple of good fixes.
