### ISSUE TITLE
Can't close an iframe whose height and width are 0

### ISSUE THREAD

**Issue by ReedD** [davidjbradshaw/iframe-resizer#170]
If you attempt to close an iframe whose height and width is zero `no change` is detected and the iframe remains in the DOM of the parent window. My current work around is to call `window.parentIFrame.size(1, 1)` and then subsequently call `window.parentIFrame.close()` so that a change is registered.

**Comment by davidjbradshaw** [comment]
This is a browser bug.

If you add the following to line 120, does it fix it for you?

    var style = messageData.iframe.style;
    style['height']  = style['width'] = '1px';

**Comment by ReedD** [comment]
Nope, the event never makes it out of `iframeSizer.contentWindow.js`.

**Comment by davidjbradshaw** [comment]
Strange. Do you have a simple test case? Can you paste the log from it.

**Comment by ReedD** [comment]
I created a [pull request](https://github.com/davidjbradshaw/iframe-resizer/pull/171) for this and referenced the line of code I believe is causing the issue.

**Comment by davidjbradshaw** [comment]
Fixed #171.

Thanks Merged. Will do a release at the weekend, when I have a chance to look at a couple of other things.
