### ISSUE TITLE
Javascript Error SCRIPT5007 on IE8

### ISSUE THREAD

**Issue by robertux** [davidjbradshaw/iframe-resizer#172]
When calling the iFrameResize function in IE8, it shows the following error in console:

**SCRIPT5007: Unable to get value of the property 'call': object is null or undefined**
iframeResizer.min.js, Línea 8 Carácter 5761

I replicated this error using the following initialization parameters with Internet Explorer 9 in IE8 compatibility mode:

```
iFrameResize({"log": false, 
	"heightCalculationMethod": "grow", 
	"resizedCallback": function() {
		//...
		}}, 
	"#form-iframe");
```
This is the iframe HTML code:
```
<iframe id="form-iframe" src="http://..." 
style="margin:0; width:100%; height:100%px; border:none; overflow:hidden;" scrolling="no"></iframe>
```
Using version 2.8.4 - 2015-02-20

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#browser-compatibility

**Comment by robertux** [comment]
Sorry, didn't read the browser compatibility section.

**Comment by davidjbradshaw** [comment]
That's ok you just neeed to either use it with jQuery or loaded the polyfil.

On Tue, Mar 17, 2015 at 4:09 PM, robertux <notifications@github.com> wrote:

> Sorry, didn't read the browser compatibility section.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/172#issuecomment-82437020>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net
