### ISSUE TITLE
Not Downsizing to new iframe height

### ISSUE THREAD

**Issue by jd159** [davidjbradshaw/iframe-resizer#174]
Hi, I am using a bootstrap template, and when you resize the page so that it has a very small width, when returning to the full width, the iframe does not resize. 

In the log it states that no iframe resize detected, but there was in fact a change in the size. 

Only when I refresh the page does the height of the iframe resize to encompass the content.

**Comment by davidjbradshaw** [comment]
See #70 for some suggestions on working around this bug.
