### ISSUE TITLE
Anchor link inside iframe resizer doesn't work

### ISSUE THREAD

**Issue by snoopy15** [davidjbradshaw/iframe-resizer#175]
I'm using iframe-resizer in my application and it works fine but I have problem with anchor links inside iframe, they doesn't work.

For example I have link a href="#page1" and I tried to put full url  a href="http://mydomain.com/page1" also tried to use target attribute. I also find something like this a target="_parent" href="http://parenturl.com/#my-id", I sow this solution but it doesn't work.

Any suggestions?

Thank you

**Comment by davidjbradshaw** [comment]
Did you set this?

https://github.com/davidjbradshaw/iframe-resizer#enableinpagelinks

**Comment by snoopy15** [comment]
I have found this but I had 2.8.3. version and it doesn't work, and it should work, so I download newest version and it works now. Thank you!
