### ISSUE TITLE
Initial config data or perhaps the ability to send messages to content window

### ISSUE THREAD

**Issue by ReedD** [davidjbradshaw/iframe-resizer#176]
In the project I am working on I need the ability to give my iFrame some initial configuration parameters. The simplest way I can think of to achieve this is by simply adding a new config key to the `iFrameResize` function called `data`. `data` would then get sent along during the init phase and made accessible through `window.parentIFrame.data`. A second and more complicated way might be to make the [`trigger`](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.js#L413-L416) function public so that data could be sent at any time to the content window. `window.parentIFrame` would then of course need a way to register/deregister listeners to receive parent messages. 

What are your thoughts on this?

**Comment by ReedD** [comment]
Another easy option is to add my config variables as GET params to my iFrame src but that is not ideal. I also thought maybe attributes prefixed with `data-` on the iFrame element could get passed along in a similar way to the first method that I mentioned above.

**Comment by davidjbradshaw** [comment]
Interesting idea to support sending data, but would it not be easier, to pass URL Parameters, that way they are available during page load, rather than having to wait until after the iFrame has done it's first resize.

**Comment by davidjbradshaw** [comment]
Adding the sending of a data object would be very simple, the down side is you then have to poll for it becoming available in the iFrame.

I think if your at the point where you want to send messages it's simpler just to use the native postMessage methods.

**Comment by ReedD** [comment]
Yeah I hadn't considered the initial load/resize delay, that's a good point. Seems a bit inelegant but perhaps URL params is the way I need to go after all.

**Comment by davidjbradshaw** [comment]
Can you add a parsed UrlEncoded JSON object to the URL?
