### ISSUE TITLE
Cross Domain Issue

### ISSUE THREAD

**Issue by adiwithadidas** [davidjbradshaw/iframe-resizer#177]
This is more like an question for you.  As from the documentation it seems that it is compatible with cross domain iframes. My question is what if i want to use a third party domain. I mean to say a domain of which i do not have any control like let say i want to include the gtihub.com in the iframe. Will it be able to re-size the height of the iframe to be the exact same of height of github.com  so that i do not have a vertical scroll bar. If yes then can you please let me know how to do this.

Thanks
Adi

**Comment by davidjbradshaw** [comment]
Nope require JS at both ends.
