### ISSUE TITLE
scrollToOffset() not being exposed

### ISSUE THREAD

**Issue by davebeesley** [davidjbradshaw/iframe-resizer#178]
Hi.
I'm using v2.8.5.
I have exposed the parent iframe using enablePublicMethods
I can see all the other methods except for scrollToOffset.

Here is a console log of the parentIFrame object in the child page.
![iframeresizer](https://cloud.githubusercontent.com/assets/1854049/6822159/7dc65398-d2d5-11e4-9883-2e5497f4a778.PNG)

This is Chrome 41. But it's the same in Firefox 36 too

**Comment by davidjbradshaw** [comment]
That's strange, I've just checked this on the example and I can still see that method.

![screen shot 2015-03-25 at 10 36 12](https://cloud.githubusercontent.com/assets/591634/6822866/cc758f72-d2da-11e4-920b-854034aff854.png)

Are you looking on the example, or you own code?

**Comment by davebeesley** [comment]
Found my problem.
Whilst the parent page js had been updated. The iframew content was still on an old version of .contentWindow.js
