### ISSUE TITLE
Add horizontal and vertical scroll options independently

### ISSUE THREAD

**Issue by CAYdenberg** [davidjbradshaw/iframe-resizer#181]
Would be nice to be able to add the horizontal scroll bar by itself.

**Comment by davidjbradshaw** [comment]
Happy to take a pull request to allow and x,y object to be passed the
scrolling option.

On Thu, Mar 26, 2015 at 8:56 PM, Casey Ydenberg <notifications@github.com>
wrote:

> Would be nice to be able to add the horizontal scroll bar by itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/181>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek
