### ISSUE TITLE
Example demo link doesn't work

### ISSUE THREAD

**Issue by PabloValor** [davidjbradshaw/iframe-resizer#182]

**Comment by davidjbradshaw** [comment]
Just tested and works fine for me.

**Comment by tinystride** [comment]
I'm getting a 404 on the demo link (http://davidjbradshaw.com/iframe-resizer/example/)

![screen shot 2015-04-23 at 1 22 07 pm](https://cloud.githubusercontent.com/assets/1767309/7304247/cf7ce2ae-e9bb-11e4-9978-29a98d538918.png)

**Comment by davidjbradshaw** [comment]
Strange, can you try again as it just worked for me.

On Thursday, 23 April 2015, Neil Renicker <notifications@github.com> wrote:

> I'm getting a 404 on the demo link (
> http://davidjbradshaw.com/iframe-resizer/example/)
>
> [image: screen shot 2015-04-23 at 1 22 07 pm]
> <https://cloud.githubusercontent.com/assets/1767309/7304247/cf7ce2ae-e9bb-11e4-9978-29a98d538918.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/182#issuecomment-95676976>
> .
>


-- 
Sent from my iPhone.

**Comment by PabloValor** [comment]
Hi David, I have the same issue.
![untitled](https://cloud.githubusercontent.com/assets/6534833/7311664/9decbe30-ea15-11e4-86f5-b508dd8f7a2a.png)

**Comment by davidjbradshaw** [comment]
Can you post the trace route to the server.

**Comment by davidjbradshaw** [comment]
Also the results of this command. 

    dig davidjbradshaw.com

**Comment by davidjbradshaw** [comment]
I've looked at this a bit more and the issue is your DNS is pointing to the wrong server. I would like to understand why, but need the output from the `dig` command to do so.

**Comment by markvantilburg** [comment]
Are you sure both nameservers are configured correctly?

I see a different ordering when using 8.8.8.8 and the one of my isp;

davidjbradshaw.com      nameserver = ns2.afraid.org
davidjbradshaw.com      nameserver = ns1.davidjbradshaw.com

davidjbradshaw.com      nameserver = ns1.davidjbradshaw.com
davidjbradshaw.com      nameserver = ns2.afraid.org

**Comment by davidjbradshaw** [comment]
I need to see the IP address each option returns.

**Comment by davidjbradshaw** [comment]
Secondly DNS updated. Let me know if it works now.
