### ISSUE TITLE
TypeError: undefined is not a function (evaluating '$('p#callback')')

### ISSUE THREAD

**Issue by LeaseBizznis** [davidjbradshaw/iframe-resizer#185]
TypeError: undefined is not a function (evaluating '$('p#callback')')

Js:

<div class="speciaalcalc"><code>
<script type="text/javascript">// <![CDATA[
if (!Array.prototype.forEach){ Array.prototype.forEach = function(fun /*, thisArg */){ "use strict"; if (this === void 0 || this === null || typeof fun !== "function") throw new TypeError(); var t = Object(this), len = t.length >>> 0,
thisArg = arguments.length >= 2 ? arguments[1] : void 0;
for (var i = 0; i < len; i++) if (i in t) fun.call(thisArg, t[i], i, t); }; }
// ]]></script>
<iframe style="border: none;" src="http://aaserver15s.autodisk.nl/OnlineOfferteAanvraag2014/zoek.aspx?Client=leasebizznis" width="100%" height="150" scrolling="no"></iframe>
<script src="http://leasebizznis.nl/wp-content/themes/schema/js/iframeResizer.min.js?974591" type="text/javascript"></script><script type="text/javascript">// <![CDATA[
iFrameResize({
log : false, // Enable console logging
enablePublicMethods : true, // Enable methods within iframe hosted page
resizedCallback : function(messageData){ // Callback fn when resize is received
$('p#callback').html(
'<b>Frame ID:</b> ' + messageData.iframe.id +
' <b>Height:</b> ' + messageData.height +
' <b>Width:</b> ' + messageData.width +
' <b>Event type:</b> ' + messageData.type
);
},
messageCallback : function(messageData){ // Callback fn when message is received
$('p#callback').html(
'<b>Frame ID:</b> ' + messageData.iframe.id +
' <b>Message:</b> ' + messageData.message
);
alert(messageData.message);
},
closedCallback : function(id){ // Callback fn when iFrame is closed
$('p#callback').html(
'<b>IFrame (</b>' + id +
'<b>) removed from page.</b>'
);
}
});
// ]]></script></code></div>

Can you see what's the problem??

**Comment by davidjbradshaw** [comment]
Your calling jQuery without loading it.

Please ask support questions on StackOverflow this forum is for reporting bugs.
