### ISSUE TITLE
iPhone (Safari / Chrome)

### ISSUE THREAD

**Issue by jetbeck** [davidjbradshaw/iframe-resizer#187]
Hi,

I'm having some issues getting this to work on the iphone, I don't know if something is conflicting or not but everytime I load the page with this on it through the iphone 5, 6+, etc. it barely loads and ends up crashing the browser. 

Everything works quite well in other browsers and platforms. 

Site its hosted on is here: http://developer.webgears.ca/2z7newmark/new-inventory/

**Comment by davidjbradshaw** [comment]
Not seeing an issues on my iPad, can you make a simple test case.

**Comment by davidjbradshaw** [comment]
Also please update to version 2.8.6, as that has some fixes that might help you. Please let me know if that version fixes things for you.

**Comment by jetbeck** [comment]
Will do, I have to wait on the parent page provider to update their version.

Regards,

**Comment by davidjbradshaw** [comment]
Closing, but happy to reopen when you provide a test case.
