### ISSUE TITLE
phpbb iframe in joomla

### ISSUE THREAD

**Issue by ducklin5** [davidjbradshaw/iframe-resizer#189]
I'm trying to set this up and I've managed to include both the host (Joomla!) and client (phpBB) scripts in the site. phpBB is in an iframe with class "wrapper" and I called the function with: 
~~~~~~~~~~~
  $('iframe').iFrameResize( [{log:true}] );
  iFrameResize( [{log:true}], [wrapper] || [iframe] );
~~~~~~~~~~~
Only the homepage on phpBB has "iframeResizer.contentWindow.min.js" include, but it should still work, instead I get a small iframe that cuts out almost everything. The iframe is set to:
~~~~~~~~~~~~~~~
 overflow: hidden
 height: auto
 scroll: no
~~~~
feel free to look at the site yourself golem.fnhost.org/j3/index.php/forum

FIXED
-I hadn't copied the other .map files
-wasn't calling the function right (removing the css selector fixed this)

**Comment by ducklin5** [comment]
I still have an issue though, whenever the iframe resizes to a larger page, then if i go back to the smaller page, the iframe remains larger, is there a way to undo this

**Comment by davidjbradshaw** [comment]
Please provide a simple test case.

https://css-tricks.com/reduced-test-cases/
