### ISSUE TITLE
Down Sizing is not working on mobile.

### ISSUE THREAD

**Issue by masihur** [davidjbradshaw/iframe-resizer#191]
Hi,

I have integrated iframe-resizer on our forum with WordPress plugin. I have open our forum into wordpress site into an i-frame. At first when we open forum page then i-frame rsizer working fine now if we open a page which height is greater than previous page then iframe resizer working fine but if we open a page which height is less then previous page then page not resized.
My code as below.

iFrameResize({
	log:true,
	tolerance: 2,
	heightCalculationMethod: heightResizeMethod,
	enablePublicMethods: true,
	resizedCallback: function(messageData){
			alert(messageData.height);
			iframeResizerLoaded = true;
	}
});

It creates proble only on mobile, on desktop it's working fine.

I have also used iframeresizer_size() to fixed this issue but it return previous page height.
Also I have used jQuery Mobile for the UI of the mobile version on our forum.

**Comment by davidjbradshaw** [comment]
Please provide a simple test case.

https://css-tricks.com/reduced-test-cases/

**Comment by masihur** [comment]
Hi Downsizing is not working on mobile. If we open a page which height is less then previous page height then it can not calculate current page height, while on the desktop it calculate the hieight, could not depend on previous page height.

**Comment by davidjbradshaw** [comment]
Closing due to lack of a clear test case. Read the link I posted above if you want this reopened.
