### ISSUE TITLE
Changing the iframe src 

### ISSUE THREAD

**Issue by yuval-netanel** [davidjbradshaw/iframe-resizer#192]
Hi,

I'm using iframe-resizer and it's working pretty well.
The problem is when I change the iframe src, the iframe-resizer stops working.
It's worth mentioning that I'm using [react-router](https://github.com/rackt/react-router), so when I change the url  it uses push-state.

Any suggestions?

**Comment by davidjbradshaw** [comment]
Please provide a simple test case.

https://css-tricks.com/reduced-test-cases/

That said have you checked for an error message in the console log?

**Comment by yuval-netanel** [comment]
There is no error message, the log communication just stops. 

But I've found a workaround:
Adding onLoad attribute to the iframe, which calls iFrameResize with id selector.
Meaning we init the content window every time we change the source.

 I will try to investigate the problem a little bit more and send a pull request if I will find a solution.

Thanks!

**Comment by davidjbradshaw** [comment]
Strange, you shouldn't need to do that.

Can you add the log to this ticket.

On Tuesday, April 14, 2015, Yuval Netanel <notifications@github.com> wrote:

> There is no error message, the log communication just stops.
>
> But I've found a workaround:
> Adding onLoad attribute to the iframe, which calls iFrameResize with id
> selector.
> Meaning we init the content window every time we change the source.
>
> I will try to investigate the problem a little bit more and send a pull
> request if I will find a solution.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/192#issuecomment-93004312>
> .
>


-- 
Sent from my iPhone.

**Comment by davidjbradshaw** [comment]
Closed due to no response.

**Comment by SeanZicari** [comment]
Why wouldn't it be necessary to re-initialize the iframe resizer when the src is changed? Does it automatically set up the parentIFrame object when the public API is requested?

**Comment by davidjbradshaw** [comment]
It watch the iFrame tag's load event and refires init when a new page loads in the iFrame.

**Comment by SeanZicari** [comment]
Thanks for the info. Would having my own load events cause an issue? I know it shouldn't, but I'm finding the iframe resizer stops working when switching src at certain times. Messages just stop and then none of the callbacks fire. Basically the same as the OP. Here is a log that will hopefully help. Note that there are some Facebook messages mixed in, and the "Pinging iframe" messages are from my code in an attempt to "kickstart" the resizer back into working (naive attempt, I know).

```
Failed to load resource: the server responded with a status of 404 (NOT FOUND)
Initializing the iframe resizer with settings Object
[iFrameSizer][Host page] IFrame scrolling disabled for overridden_template_source
[iFrameSizer][Host page] Set maxWidth = 840px
[iFrameSizer][Host page][init] Sending msg to iframe (overridden_template_source:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent)
Invalid App Id: Must be a number or numeric string representing the application id.
FB.getLoginStatus() called before calling FB.init().
Pinging iframe
[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (overridden_template_source:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent)
[iFrameSizer][overridden_template_source] Height calculation method set to "lowestElement"
[iFrameSizer][overridden_template_source] HTML & body height set to "auto"
[iFrameSizer][overridden_template_source] Enable public methods
[iFrameSizer][overridden_template_source] Added event listener: Animation Start
[iFrameSizer][overridden_template_source] Added event listener: Animation Iteration
[iFrameSizer][overridden_template_source] Added event listener: Animation End
[iFrameSizer][overridden_template_source] Added event listener: Device Orientation Change
[iFrameSizer][overridden_template_source] Added event listener: Transition End
[iFrameSizer][overridden_template_source] Added event listener: Window Clicked
[iFrameSizer][overridden_template_source] Enable MutationObserver
[iFrameSizer][overridden_template_source] In page linking not enabled
[iFrameSizer][overridden_template_source] Parsed 121 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 0ms
[iFrameSizer][overridden_template_source] Trigger event lock on
[iFrameSizer][overridden_template_source] Sending message to host page (overridden_template_source:424:940:init)
[iFrameSizer][Host page] Received: [iFrameSizer]overridden_template_source:424:940:init
[iFrameSizer][Host page] Checking connection is from: http://dev.friendbuy.com:5060
[iFrameSizer][Host page] Checking height is in range 0-Infinity
[iFrameSizer][Host page] Checking width is in range 0-840
[iFrameSizer][Host page] Set width to max value
[iFrameSizer][Host page] Requesting animation frame
(Re-)Initialized iframe Arguments[1]
[iFrameSizer][overridden_template_source] Parsed 121 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 1ms
[iFrameSizer][overridden_template_source] Trigger event: Device Orientation Change
[iFrameSizer][overridden_template_source] No change in size detected
[iFrameSizer][Host page] IFrame (overridden_template_source) height set to 424px
[iFrameSizer][overridden_template_source] Trigger event lock off
[iFrameSizer][overridden_template_source] --
[iFrameSizer][Host page][Window resize] Sending msg to iframe (resize)
[iFrameSizer][overridden_template_source] Parsed 121 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 0ms
[iFrameSizer][overridden_template_source] Trigger event: Parent window resized
[iFrameSizer][overridden_template_source] No change in size detected
Pinging iframe
[iFrameSizer][overridden_template_source] Trigger event lock on
[iFrameSizer][overridden_template_source] Parsed 121 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 0ms
[iFrameSizer][overridden_template_source] Trigger event: parentIFrame.size()
[iFrameSizer][overridden_template_source] No change in size detected
[iFrameSizer][overridden_template_source] Trigger event lock off
[iFrameSizer][overridden_template_source] --
[iFrameSizer][Host page][Window resize] Sending msg to iframe (resize)
[iFrameSizer][overridden_template_source] Parsed 121 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 1ms
[iFrameSizer][overridden_template_source] Trigger event: Parent window resized
[iFrameSizer][overridden_template_source] Trigger event lock on
[iFrameSizer][overridden_template_source] Sending message to host page (overridden_template_source:420:940:resizeParent)
[iFrameSizer][Host page] Received: [iFrameSizer]overridden_template_source:420:940:resizeParent
[iFrameSizer][Host page] Checking connection is from: http://dev.friendbuy.com:5060
[iFrameSizer][Host page] Checking height is in range 0-Infinity
[iFrameSizer][Host page] Checking width is in range 0-840
[iFrameSizer][Host page] Set width to max value
[iFrameSizer][Host page] Requesting animation frame
[iFrameSizer][Host page] IFrame (overridden_template_source) height set to 420px
[iFrameSizer][overridden_template_source] Trigger event lock off
[iFrameSizer][overridden_template_source] --
Pinging iframe
[iFrameSizer][overridden_template_source] Trigger event lock on
[iFrameSizer][overridden_template_source] Parsed 121 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 0ms
[iFrameSizer][overridden_template_source] Trigger event: parentIFrame.size()
[iFrameSizer][overridden_template_source] Sending message to host page (overridden_template_source:424:940:size)
[iFrameSizer][Host page] Received: [iFrameSizer]overridden_template_source:424:940:size
[iFrameSizer][Host page] Checking connection is from: http://dev.friendbuy.com:5060
[iFrameSizer][Host page] Checking height is in range 0-Infinity
[iFrameSizer][Host page] Checking width is in range 0-840
[iFrameSizer][Host page] Set width to max value
[iFrameSizer][Host page] Requesting animation frame
[iFrameSizer][Host page] IFrame (overridden_template_source) height set to 424px
[iFrameSizer][overridden_template_source] Trigger event lock off
[iFrameSizer][overridden_template_source] --
[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (overridden_template_source:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent)
[iFrameSizer][overridden_template_source] Height calculation method set to "lowestElement"
[iFrameSizer][overridden_template_source] HTML & body height set to "auto"
[iFrameSizer][overridden_template_source] Enable public methods
[iFrameSizer][overridden_template_source] Added event listener: Animation Start
[iFrameSizer][overridden_template_source] Added event listener: Animation Iteration
[iFrameSizer][overridden_template_source] Added event listener: Animation End
[iFrameSizer][overridden_template_source] Added event listener: Device Orientation Change
[iFrameSizer][overridden_template_source] Added event listener: Transition End
[iFrameSizer][overridden_template_source] Added event listener: Window Clicked
[iFrameSizer][overridden_template_source] Enable MutationObserver
[iFrameSizer][overridden_template_source] In page linking not enabled
[iFrameSizer][overridden_template_source] Parsed 36 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 1ms
[iFrameSizer][overridden_template_source] Trigger event lock on
[iFrameSizer][overridden_template_source] Sending message to host page (overridden_template_source:776:712:init)
[iFrameSizer][Host page] Received: [iFrameSizer]overridden_template_source:776:712:init
[iFrameSizer][Host page] Checking connection is from: http://dev.friendbuy.com:5060
[iFrameSizer][Host page] Checking height is in range 0-Infinity
[iFrameSizer][Host page] Checking width is in range 0-840
[iFrameSizer][Host page] Requesting animation frame
(Re-)Initialized iframe [iframe#overridden_template_source]
[iFrameSizer][Host page] IFrame (overridden_template_source) height set to 776px
[iFrameSizer][overridden_template_source] Parsed 36 HTML elements
[iFrameSizer][overridden_template_source] LowestElement bottom position calculated in 0ms
[iFrameSizer][overridden_template_source] Trigger event: Device Orientation Change
[iFrameSizer][overridden_template_source] No change in size detected
[iFrameSizer][overridden_template_source] Trigger event lock off
[iFrameSizer][overridden_template_source] --
[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (overridden_template_source:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent)
Invalid App Id: Must be a number or numeric string representing the application id.
FB.getLoginStatus() called before calling FB.init().
1 tags failed to render in 30000 ms
```

**Comment by SeanZicari** [comment]
I don't know if these details are relevant, but we've got an iframe on a page with a button that dynamically changes its width between "full width" and "mobile width". The iframe resizer appears to stop working just switching the src, though.

**Comment by davidjbradshaw** [comment]
That looks like the iframe switch to a page that doesn't contain the `iframeResizer.contentWindow.js` file.

**Comment by SeanZicari** [comment]
The page I'm using the iframe resizer on has buttons that change the iframe source. I click from the initially-loaded src, which resizes correctly, to another src which also resizes correctly, then back to the original src. At that point, the resizer appears to stop working (the iframe is not hidden but is pushed out of view until it finishes loading, at which point it is brought back into view). The contentWindow file should be there, as it was there on first load for the affected src.

**Comment by davidjbradshaw** [comment]
Not sure, if you create a simple test case online somewhere, I'll try and
take a look at it next week.

On Fri, Jun 12, 2015 at 6:08 PM, Sean Zicari <notifications@github.com>
wrote:

> The page I'm using the iframe resizer on has buttons that change the
> iframe source. I click from the initially-loaded src, which resizes
> correctly, to another src which also resizes correctly, then back to the
> original src. At that point, the resizer appears to stop working (the
> iframe is not hidden but is pushed out of view until it finishes loading,
> at which point it is brought back into view). The contentWindow file should
> be there, as it was there on first load for the affected src.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/192#issuecomment-111559693>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by davidjbradshaw** [comment]
Also when you say 'should' be there, I would suggest checking that it 'is'
there.

On Fri, Jun 12, 2015 at 6:33 PM, Dave Bradshaw <david.j.bradshaw@gmail.com>
wrote:

> Not sure, if you create a simple test case online somewhere, I'll try and
> take a look at it next week.
>
> On Fri, Jun 12, 2015 at 6:08 PM, Sean Zicari <notifications@github.com>
> wrote:
>
>> The page I'm using the iframe resizer on has buttons that change the
>> iframe source. I click from the initially-loaded src, which resizes
>> correctly, to another src which also resizes correctly, then back to the
>> original src. At that point, the resizer appears to stop working (the
>> iframe is not hidden but is pushed out of view until it finishes loading,
>> at which point it is brought back into view). The contentWindow file should
>> be there, as it was there on first load for the affected src.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/davidjbradshaw/iframe-resizer/issues/192#issuecomment-111559693>
>> .
>>
>
>
>
> --
> David J. Bradshaw )'( dave@bradshaw.net
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by SeanZicari** [comment]
I can do that. It turns out it only seems to happen in my local environment, so I'm wondering if it has anything to do with that.

**Comment by SeanZicari** [comment]
I'm going to say this is only an issue with my particular environment. I'm only experiencing it in Safari when I run my site locally. Further, it's not happening with my local site in Chrome, Firefox or IE.

**Comment by davidjbradshaw** [comment]
Ok some browsers have odd issues when you run locally.

**Comment by SeanZicari** [comment]
@davidjbradshaw Greetings again. The issues persist locally. We have frequent cases where the resized callback does not fire and so our callbacks aren't called. Can you give me an idea of what can tend to break if this lib is used with a local URL?

**Comment by davidjbradshaw** [comment]
Try turning the checkOrigin option to false. Beyond that I need a test case to have a look at.

**Comment by SeanZicari** [comment]
I tried ``checkOrigin``, to no avail. Honestly, it works perfectly in Firefox in all environments. It doesn't work consistently in Chrome or Safari. I get this error from the iframe resizer contentWindow on the third or fourth iframe src change:

```
[iFrameSizer][] Received message of type (resize) before initialization.
```

**Comment by davidjbradshaw** [comment]
In that case set the resizeFrom option to child.

**Comment by davidjbradshaw** [comment]
I have been trying to repro this in Chrome this morning and can not recreate the issue.

Can I suggest you try upgrading to v3.0.0 beta version. It can be found here.

https://github.com/davidjbradshaw/iframe-resizer/tree/dev

**Comment by SeanZicari** [comment]
Thank you for putting some time into this issue. I've been thinking through a way I can provide an example that doesn't expose sensitive company data or code. Unfortunately, I've got your library integrated into an app library, so it will take some work to untangle it.
