### ISSUE TITLE
Downsizing issue in mobile

### ISSUE THREAD

**Issue by masihur** [davidjbradshaw/iframe-resizer#193]
Hi,

I have integrated iframe-resizer on our forum with WordPress plugin. Open out forum inside iframe on WordPress site. At first when we open forum page then i-frame resizer working fine.
If we open a new page which height is greater then previous page then resizer working fine, but if we open a page which height is less then previous page then page not resized. Down sizing is not working on mobile.
I have also used iframeresizer_size() to fixed this issue but it return previous page height.

Also I have used jQuery Mobile for the UI of the mobile version on our forum.

**Comment by davidjbradshaw** [comment]
Please provide a simple test case.

https://css-tricks.com/reduced-test-cases/

**Comment by davidjbradshaw** [comment]
Please do not open multiple tickets for one issue!
