### ISSUE TITLE
Multiple iframes Issue

### ISSUE THREAD

**Issue by mattcom26** [davidjbradshaw/iframe-resizer#197]
Hello,

First, great program. Allow me to apologize in advance that I'm mostly out of my depth when it comes to trouble-shooting the problem I'm about to describe. I saw some closed tickets that might be dealing with a similar scenario, but I couldn't glean a solution for mine.

I have a page which is loading up to six iframes, with a dynamic content area that loads the frames based on a selection in the left-page menu. The problem is that most of the time only the first iframe that loads is actually resized. Looking at the Console readout, I can see that the others are being set to zero, so I assume it could be a timing issue having to do with the fact that the iframes haven't been selected when the script runs. 

Here is my test page for reference:
http://activatebiz.com/dev/WLGO-frames/resize-test.html

Any suggestions you could offer would be appreciated. Again, sorry in advance if I'm not seeing something obvious here.

**Comment by davidjbradshaw** [comment]
This is really a question for StackOverflow. However, if you look at the browser log you will see lots of errors.

    Font from origin 'https://www.worldslargestgolfouting.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://activatebiz.com' is therefore not allowed access.

    billboard.cfm:164 Uncaught ReferenceError: iFrameResize is not defined

    billboard.cfm:164 Uncaught ReferenceError: iFrameResize is not defined

    homepageleaderboard.cfm:86 Uncaught ReferenceError: iFrameResize is not defined

    resize-test.html:1 Font from origin 'https://www.worldslargestgolfouting.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://activatebiz.com' is therefore not allowed access.

    billboard.cfm?cid=10759:110 Uncaught TypeError: Cannot read property 'onSeek' of undefined

    billboard.cfm?cid=2274:110 Uncaught TypeError: Cannot read property 'onSeek' of undefined

    homepageleaderboard.cfm:86 Uncaught ReferenceError: iFrameResize is not defined

    Uncaught ReferenceError: iFrameResize is not defined

    Failed to load resource: the server responded with a status of 404 (Not Found)

    resize-test.html:1 XMLHttpRequest cannot load http://www.activatebiz.com/_track?e=i&p=00000145-183d-d81d-aded-d83dfac3000…a96-a1f7-ddbff75a0000,00000145-b05c-d4ca-abc5-b27cb4b10000&_=1430816871952. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://activatebiz.com' is therefore not allowed access. The response had HTTP status code 404.

    Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.etsemoney.com') does not match the recipient window's origin ('https://wlgo.charitygolftech.com').
