### ISSUE TITLE
Not Working on AOSP Browser.

### ISSUE THREAD

**Issue by psycmos** [davidjbradshaw/iframe-resizer#198]
I tested it in many android browsers and in AOSP browser are not working.
This web browser is very important bause many people use it because comes native in android system.

There are any possibility to get it working?

my website http://g*r*e*e*n*s*e*p*t*e*m*b*e*r.pt

Please remove *

Best regards. Nuno

**Comment by davidjbradshaw** [comment]
Look at the console.

	Refused to execute script from 'https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
	greenseptember.pt/:80 Uncaught ReferenceError: iFrameResize is not defined
	greenseptember.pt/:201 Uncaught ReferenceError: iFrameResize is not defined
	intro.html:1 Refused to execute script from 'https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
	index.html:1 Refused to execute script from 'https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
	http://greenseptember.pt/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

You need to host JS files locally, not load them from GitHub.

**Comment by psycmos** [comment]
Thanks a lot for your support and for this great work!
Now are Working Perfect!!! :D
