### ISSUE TITLE
Issue w/ IE 9 and IE 8

### ISSUE THREAD

**Issue by mickotia** [davidjbradshaw/iframe-resizer#2]
David,

Thanks for your detailed explanation and examples of how this works.  I have been working on dynamically applying height and width to a cross-domain iframe for about a week unsuccessfully until I read your article.  I have everything up and running correctly on my staging site and host site ( using Firefox, Chrome, and IE 10 ), however I notice that this is not working for me on IE 9 and IE 8.  The content loads in a smaller frame at the top of the page and does not expand or adjust dynamically.

How you experienced this issue before, or perhaps am I applying something incorrectly.

Thanks,
Mike K.

**Comment by ManojReddyN** [comment]
Hi, I am facing the same issue. In IE the Iframe is not loading completely. Please provide a solution.

**Comment by davidjbradshaw** [comment]
I'm available to hirer if you want me to work on your code base.

If you have a new bug, then you need to follow these guidelines to report it. https://github.com/davidjbradshaw/iframe-resizer/blob/master/CONTRIBUTING.md
