### ISSUE TITLE
iFrame doesn't resize if the source page is on HTTPS

### ISSUE THREAD

**Issue by pedromaximiano** [davidjbradshaw/iframe-resizer#204]
Hello,

I'm loading an iFrame from an HTTPS server and the iFrame resizer is not working.

I'm activating it like this:

    $(document).ready(function () {
        $("#externalIFrame").iFrameResize({ log: true, checkOrigin: false });
    });

and the iFrame is defined like this:

<iframe id="externalIFrame" seamless="seamless" src="https://bemmaisseguro.com/partner/tacerto/cotacao" border="0" width=100% height=265px style="border: 0"></iframe>

On the console, I found this two messages, that I think are relevant:

[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (externalIFrame:8:false:true:32:false:true:null:offset:null:null:0:false:parent)

Uncaught SecurityError: Blocked a frame with origin "https://bemmaisseguro.com" from accessing a frame with origin "https://www.tacerto.com". Protocols, domains, and ports must match.

Any thoughts?

Thanks!

**Comment by davidjbradshaw** [comment]
If you send me a link, I'll have a quick look at it.

**Comment by pedromaximiano** [comment]
Hello David,

Thanks for your reply.

Here's a link for the site: http://dev.tacerto.com/celular

The frame is located in https://qa.bemmaisseguro.com/partner/tacerto/cotacao
.

We have another page that's working perfectly:
http://dev.tacerto.com/telecom.

Thanks a lot for your help.

Regards,
Pedro Maximiano

On Tue, May 19, 2015 at 6:37 PM, David J. Bradshaw <notifications@github.com

**Comment by davidjbradshaw** [comment]
Had a quick look, that error is with your code before iframe-resizer even runs. (app.min.js).

I don't think this is a bug, in iFrame-resizer. Check you have the second JS page loaded into you search results page. If you do then something else is crashing JS on your page and stopping out scripts running.

If you think it is still a bug, then you'll need to make a simple test case, that doesn't have any other JS in it.

**Comment by pedromaximiano** [comment]
Thanks for your reply, David.

I'll try to talk to the other party.

Regards,
Pedro

**Comment by pedromaximiano** [comment]
Sorry for my pushing this again, but if you look at the console, you'll
clearly see that the iFrameResizer on the iFrame is running and that
there's a security error.

http://puu.sh/hU1eD/cd46163c3f.png

Can you please advise on the log messages, so I can ma sense of it?

Thanks!

On Wed, May 20, 2015 at 11:32 AM, Pedro Maximiano <pedro.maximiano@gmail.com
> wrote:

> Thanks for your reply, David.
>
> I'll try to talk to the other party.
>
> Regards,
> Pedro
>
> On Wed, May 20, 2015 at 11:06 AM, David J. Bradshaw <

**Comment by davidjbradshaw** [comment]
The error is in app.min.js, I only see iframe-resizer running in the parent
page, not the iframe. You have to include the second JS file into every
page that you load into the iframe, not just the first one.

On Wed, May 20, 2015 at 11:36 AM, Pedro Maximiano <notifications@github.com>
wrote:

> Sorry for my pushing this again, but if you look at the console, you'll
> clearly see that the iFrameResizer on the iFrame is running and that
> there's a security error.
>
> http://puu.sh/hU1eD/cd46163c3f.png
>
> Can you please advise on the log messages, so I can ma sense of it?
>
> Thanks!
>
> On Wed, May 20, 2015 at 11:32 AM, Pedro Maximiano <
> pedro.maximiano@gmail.com
> > wrote:
>
> > Thanks for your reply, David.
> >
> > I'll try to talk to the other party.
> >
> > Regards,
> > Pedro
> >
> > On Wed, May 20, 2015 at 11:06 AM, David J. Bradshaw <
> > notifications@github.com> wrote:
> >
> >> Had a quick look, that error is with your code before iframe-resizer
> even
> >> runs. (app.min.js).
> >>
> >> I don't think this is a bug, in iFrame-resizer. Check you have the
> second
> >> JS page loaded into you search results page. If you do then something
> else
> >> is crashing JS on your page and stopping out scripts running.
> >>
> >> If you think it is still a bug, then you'll need to make a simple test
> >> case, that doesn't have any other JS in it.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/davidjbradshaw/iframe-resizer/issues/204#issuecomment-103833533
> >
>
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/204#issuecomment-103838921>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by pedromaximiano** [comment]
OK, I'll try talk to the other team.

Thanks again.
