### ISSUE TITLE
ReferenceError: iFrameResize is not defined

### ISSUE THREAD

**Issue by masihur** [davidjbradshaw/iframe-resizer#207]
Hi,
I have applied iframe resizer on a site, In the site alos applied some other js library. 
Due to some javascripct confiction iframe resizer could not work properly.

**Comment by davidjbradshaw** [comment]
As mentioned before, please read the [Contributing Guidelines](https://github.com/davidjbradshaw/iframe-resizer/blob/master/CONTRIBUTING.md) before submitting tickets. Closing as you have not supplied any details on what this issue is.

**Comment by RJSekar** [comment]
I know this is a closed Issue, In case if u haven't found any solution yet. 
Try calling in the iframe onload event.
This works fine for me :
&lt;iframe src="https://www.demourl.com/" onload="iFrameResize({log:true})" scrolling="no" frameborder="0"&gt;&lt;/iframe&gt;

**Comment by davidjbradshaw** [comment]
You should call it after the iframe tag, not via onload.
