### ISSUE TITLE
Append #forumid=123 into parent URL.

### ISSUE THREAD

**Issue by masihur** [davidjbradshaw/iframe-resizer#208]
Hi,
I have applied our foum into wordpress site using iframe resizer. Now we need a feature that if a user clciks on any link then link parameter append into the parent window URL also change the iframe URL so that if any user reload the page then same page open instead of index page.
I have used 
iFrameResize({
			log: true,
			enablePublicMethods: true,
			tolerance: 10,
			heightCalculationMethod: heightResizeMethod,
			resizedCallback: function(messageData){
				iframeResizerLoaded = true;
			}
		});
to resize the iframe.

I have used parent.postMessage() for it but it could not cahnge URL.

**Comment by davidjbradshaw** [comment]
This is beyond the scope of this project. Try posting a question on StackOverflow.
