### ISSUE TITLE
Domain name davidjbradshaw.com mapped to micro.asylum.org.za?

### ISSUE THREAD

**Issue by pscdodd** [davidjbradshaw/iframe-resizer#210]
Clicking "example" (http://davidjbradshaw.com/iframe-resizer/example/) in the README.md produced 403 "Forbidden" (mapped to 127.0.0.1 at our proxy server). The domain name davidjbradshaw.com is mapped to 62.210.238.10 which is micro.asylum.org.za.

**Comment by davidjbradshaw** [comment]
It would appear to be an issue with your proxy server being incorrectly configured. It should be mapping davidjbradshaw.com to 62.210.238.10, not 127.0.0.1.

I have checked my site from a couple of endpoints and it appears to be working ok.
