### ISSUE TITLE
Does not work in accordion in IE11/Edge

### ISSUE THREAD

**Issue by Bolandish** [davidjbradshaw/iframe-resizer#211]
Hi!

My iframe with a formular is not getting its height.

[On this site](http://www.tradium.dk/uddannelser/erhvervsuddannelser/teknologi,+byggeri+-c12-+transport/automatik-+og+procesuddannelsen) check the last accordion with the text "Vil du vide mere". 

If you resize, it will be shown , but not if i write the init method in console.

Do you have a fix ?

**Comment by davidjbradshaw** [comment]
If you can make a simple test case, I'll look in to it.

**Comment by davidjbradshaw** [comment]
Closing due to no response.
