### ISSUE TITLE
Touch screen devices (mobile tablet) flicker on scroll

### ISSUE THREAD

**Issue by fizex** [davidjbradshaw/iframe-resizer#212]
Currently when using the default setting on a mobile or tablet a flickering effect happens when scrolling. IOS (mobile and tablet), Andorid etc.

**Comment by davidjbradshaw** [comment]
Just tried the example page on my iPad without issue. Can you send a link to your test case.

**Comment by fizex** [comment]
Interesting, I can't share it at the moment as it's an internal project. I'll try the example page and look for differences in our set up. We are using a dynamic form in the iframe which does a lot of crazy JS stuff so I suspect it'll be that. Sorry for the inconvenience and thanks so much for the plugin! Feel free to close this, I'll let you know what the resolution is.

**Comment by davidjbradshaw** [comment]
Ok, interested to know what the outcome is. Also check you are on the very latest version.
