### ISSUE TITLE
Quite simply does not work

### ISSUE THREAD

**Issue by fir3pho3nixx** [davidjbradshaw/iframe-resizer#216]
Seriously fella, you need to go back to the drawing board. Tested on IE 11 ... Fail.

**Comment by CodingSamurai** [comment]
What an incredibly rude and arrogant comment.  There are plenty of people who are using this library just fine, even on IE 11.  So perhaps you should double check to see if you installed and configured it correctly.

Then perhaps you should learn some basic manners and not be a jerk to someone who's providing a FREE library for you to use.  The only #fail I've seen here is your attitude.

**Comment by fir3pho3nixx** [comment]
Now now calm down. If you write shit code and dont want to know about get off github.

**Comment by fir3pho3nixx** [comment]
Clearly you are not interested. Sorry for offending you.

**Comment by davidjbradshaw** [comment]
@CodingSamurai Thank you.

@fir3pho3nixx you seem to be stupid as well as rude. That last comment wasn't from the project owner. I have raised an abuse report with GitHub for your account. You are also now blocked from this project.
