### ISSUE TITLE
Not working with ANGULAR JS on content window

### ISSUE THREAD

**Issue by aarele** [davidjbradshaw/iframe-resizer#217]
Hi,

I am having troubles when using this in AngularJS environment.
Seems as Augular uses directives (templating/HtmlAtRuntime), iFrameResizer is not able to detect change in height...

I always get '[iFramereSizer][frame] No change in size detected' in logs.

Let me know if it's a known issue and what needs to be done to resolve it.

Thanks,
Abhiraj

**Comment by davidjbradshaw** [comment]
New one on me. I have seen people get the two working together without
problem in the past. The most likely problem is CSS related, see the
troubleshooting section. If that doesn't help then please make a simple
test case for me to look at.

On Friday, 5 June 2015, aarele <notifications@github.com> wrote:

> Hi,
>
> I am having troubles when using this in AngularJS environment.
> Seems as Augular uses directives (templating/HtmlAtRuntime), iFrameResizer
> is not able to detect change in height...
>
> I always get '[iFramereSizer][frame] No change in size detected' in logs.
>
> Let me know if it's a known issue and what needs to be done to resolve it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/217>.
>


-- 
Sent from my iPhone.

**Comment by aarele** [comment]
Hi David,

It was a CSS issue (body was given a height), I fixed it and now it works like a charm.
Thanks for your feedback man, helped a lot.

Thanks,
Abhiraj

**Comment by davidjbradshaw** [comment]
Thanks for letting me know and glad you got it sorted.

On Fri, Jun 5, 2015 at 8:04 PM, Abhiraj Arele <notifications@github.com>
wrote:

> Closed #217 <https://github.com/davidjbradshaw/iframe-resizer/issues/217>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/217#event-323883530>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net
