### ISSUE TITLE
Infinity height increase

### ISSUE THREAD

**Issue by lifeart** [davidjbradshaw/iframe-resizer#218]
if iframe `body>div` has `margin-top:1vh` it runs Infinity height increase

ex:
iframe:

`body>div {
  width: 98vw;
  margin-left: 1vw;
  margin-top: 0;
  margin-bottom: 1vh;
}`

**Comment by davidjbradshaw** [comment]
Have you tried playing with the tolerence option?

I expect you have somehow created a page that is sized via CSS to always be
101% the size of the page and hence the loop.

If you can create a simple test case I'll have a bit more of a look at this.

On Fri, Jun 5, 2015 at 5:14 PM, Alex Kanunnikov <notifications@github.com>
wrote:

> if iframe body>div has margin-top:1vh it runs Infinity height increase
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/218>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek

**Comment by davidjbradshaw** [comment]
Closed due to no response.
