### ISSUE TITLE
*Sometimes* Iframe doesn't resize

### ISSUE THREAD

**Issue by itailulu** [davidjbradshaw/iframe-resizer#219]
Hello,
Thanks David for the great plugin.
The plugin works perfectly *most* of the time however sometimes it doesn't.
I'm guessing there is something basic (and stupid) about how I implemented it, and hoping you guys could help me fixing it...

My setup is this:
iframeSizer.contentWindow.min.js (v2.7.1) is embeded in the <iframe>, close to the </body> tag.

Another <script> is located right after the </iframe> tag. this script is called embed.js, which loads the iframeResizer.min.js script right to the <head> part: http://pastebin.com/pmar1Hxg

the embed script loads the iframeResizer.min.js script like that: <script type="text/javascript" src="//some-domain.com/assets/iframe-resizer/js/iframeResizer.min.js"></script>

Again - most of the time it's working, but sometimes the iframe stays "short".
I couldn't isolate the problem, but I know it is there.

Thanks in advance - I would appreciate any help!

**Comment by davidjbradshaw** [comment]
I expect you have some sort of race condition in your script loader. What your doing will cause them to load async and the can create problems. My suggestion would to use LAB.js instead as it allows pauses between loading different scripts.

**Comment by itailulu** [comment]
Thanks david for the reply.
I'm not sure I fully understand.
How can I use LAB.js for loading the scripts, it one script is loaded from INSIDE the iframe, and one from the parent window?

**Comment by davidjbradshaw** [comment]
My suggestion was to use it to replace you pastebin code. The problem is your JS files sometimes load out of order with what your currently doing.
