### ISSUE TITLE
External Domain Clarification

### ISSUE THREAD

**Issue by dazzlingbull** [davidjbradshaw/iframe-resizer#22]
Hi, sorry if my terminology is wrong, I am trying to iframe a website that is hosted on another server into a page on my server, and your code was given as a link that could do this?

Q. Does your code do this, or do I need access to both sites / files etc?

I cannot access the other websites files, it is a shutterfly website, so my code to call the page is this:

<iframe src="https://bethelmen.shutterfly.com" width="1000px" scrolling="no"></iframe>

...and it needs to be embedded on our website in the appropriate area? Is this possible with your code? This has left me blank so far .

If it is possible to post a working example that would be great, as I have tried all examples and only get a height of approx 100px?

Many thanks in advance.

**Comment by xSeekTruthx** [comment]
We have the same issue, however, we have access to the page, and can add script information to the HTML of the page. We do not have file access on the OtherDomain. Can this be done? Already tried  copying entire "iframeSizer.contentWindow.min.js" into the page between <script> tags but still receive error in java console asking...

[iFrameSizer][Host page: myIframe1] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ingored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.

How can we make it load correctly by embedding it into the HTML?

Thank you

**Comment by davidjbradshaw** [comment]
Just add a script link to the iframe that loads the contentWindow script from your domain
