### ISSUE TITLE
wordpress

### ISSUE THREAD

**Issue by hasskk** [davidjbradshaw/iframe-resizer#221]
Hi David,
  I've 2 blogs a.com and b.com . I want to show the content of a.com on b.com in iframe, and I want your plugin to calculate the height of the content of a.com for b.com.
To test your plugin, I uploaded the 'js' and 'example' folder to a.com .
http://a.com/example/index.html works very good.WoW
Then, I uploaded the index.html to b.com/test/index.html,
The code of index.html for b.com was,
<pre><code>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;iFrame message passing test&lt;/title&gt;
&lt;meta name="description" content="iFrame message passing test"&gt;
&lt;meta name="viewport" content="width=device-width"&gt;
&lt;meta http-equiv="X-UA-Compatible" content="IE=edge"&gt;
&lt;script type="text/javascript"&gt;
//MDN PolyFil for IE8 (This is not needed if you use the jQuery version)
if (!Array.prototype.forEach){
Array.prototype.forEach = function(fun /*, thisArg */){
"use strict";
if (this === void 0 || this === null || typeof fun !== "function") throw new TypeError();

var
t = Object(this),
len = t.length &gt;&gt;&gt; 0,
thisArg = arguments.length &gt;= 2 ? arguments[1] : void 0;

for (var i = 0; i &lt; len; i++)
if (i in t)
fun.call(thisArg, t[i], i, t);
};
}
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h2&gt;Automagically resizing iFrame&lt;/h2&gt;
&lt;p&gt;Resize window or click one of the links in the iFrame to watch it resize.&lt;a name="anchorParentTest"&gt;&lt;/a&gt;&lt;/p&gt;
&lt;div style="margin:20px;"&gt;
&lt;iframe src="http://a.com/example/frame.content.html" width="100%" scrolling="no"&gt;&lt;/iframe&gt;
&lt;/div&gt;
&lt;p id="callback"&gt;
&lt;/p&gt;
&lt;div style="margin: 8px 0;font-size:13px;"&gt;
For details on how this works, see
&lt;a href="http://davidjbradshaw.github.io/iframe-resizer/"&gt;http://davidjbradshaw.github.io/iframe-resizer/&lt;/a&gt;.
&lt;/div&gt;

&lt;script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="http://a.com/js/iframeResizer.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript"&gt;

/*
* If you do not understand what the code below does, then please just use the
* following call in your own code.
*
* iFrameResize({log:true});
*
* Once you have it working, set the log option to false.
*/

iFrameResize({
log : true, // Enable console logging
enablePublicMethods : true, // Enable methods within iframe hosted page
enableInPageLinks : true,
resizedCallback : function(messageData){ // Callback fn when resize is received
$('p#callback').html(
'&lt;b&gt;Frame ID:&lt;/b&gt; ' + messageData.iframe.id +
' &lt;b&gt;Height:&lt;/b&gt; ' + messageData.height +
' &lt;b&gt;Width:&lt;/b&gt; ' + messageData.width +
' &lt;b&gt;Event type:&lt;/b&gt; ' + messageData.type
);
},
messageCallback : function(messageData){ // Callback fn when message is received
$('p#callback').html(
'&lt;b&gt;Frame ID:&lt;/b&gt; ' + messageData.iframe.id +
' &lt;b&gt;Message:&lt;/b&gt; ' + messageData.message
);
alert(messageData.message);
},
closedCallback : function(id){ // Callback fn when iFrame is closed
$('p#callback').html(
'&lt;b&gt;IFrame (&lt;/b&gt;' + id +
'&lt;b&gt;) removed from page.&lt;/b&gt;'
);
}
});

&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;
</code></pre>
When I opened b.com/test/index.html , the content of a.com/example/frame.content.html was not shown completely.
Please help me, I want to use it on wordpress.
I'm waiting for your reply.
Sorry, I'm not good in speaking English.

**Comment by capynet** [comment]
This wolud help http://stackoverflow.com/questions/8822907/html5-cross-browser-iframe-postmessage-child-to-parent

**Comment by davidjbradshaw** [comment]
If you add a link I will have a quick look.

**Comment by capynet** [comment]
There is the link in my previous comment :S

**Comment by hasskk** [comment]
I don't know how but I made a little mistake that I excluded log:true line from the code.
********************************************
Friend of my friend is using your plugin
<b>He has</b>
<pre><code>&lt;!-- 
eval(unescape('%66%75%6e%63%74%69%6f%6e%20%6b%62%63%31%39%65%28%73%29%20%7b%0a%09%76%61%72%20%72%20%3d%20%22%22%3b%0a%09%76%61%72%20%74%6d%70%20%3d%20%73%2e%73%70%6c%69%74%28%22%31%34%39%31%38%39%39%37%22%29%3b%0a%09%73%20%3d%20%75%6e%65%73%63%61%70%65%28%74%6d%70%5b%30%5d%29%3b%0a%09%6b%20%3d%20%75%6e%65%73%63%61%70%65%28%74%6d%70%5b%31%5d%20%2b%20%22%36%35%33%33%39%31%22%29%3b%0a%09%66%6f%72%28%20%76%61%72%20%69%20%3d%20%30%3b%20%69%20%3c%20%73%2e%6c%65%6e%67%74%68%3b%20%69%2b%2b%29%20%7b%0a%09%09%72%20%2b%3d%20%53%74%72%69%6e%67%2e%66%72%6f%6d%43%68%61%72%43%6f%64%65%28%28%70%61%72%73%65%49%6e%74%28%6b%2e%63%68%61%72%41%74%28%69%25%6b%2e%6c%65%6e%67%74%68%29%29%5e%73%2e%63%68%61%72%43%6f%64%65%41%74%28%69%29%29%2b%2d%39%29%3b%0a%09%7d%0a%09%72%65%74%75%72%6e%20%72%3b%0a%7d%0a'));
eval(unescape('%64%6f%63%75%6d%65%6e%74%2e%77%72%69%74%65%28%6b%62%63%31%39%65%28%27') + '%42%78%64%7d%7a%71%7c%2f%79%78%6f%4f%2a%30%33%30%74%67%73%6b%70%6b%3b%70%73%7f%69%7f%8a%31%7b%74%2a%41%40%3b%7f%65%7a%75%7d%75%41%1e%1b%13%14%40%7f%7e%8b%74%69%43%1e%15%1a%1a%13%6c%2c%87%2a%66%74%7f%6e%75%45%73%7a%71%77%78%47%2a%8f%17%14%16%1a%43%30%74%7c%84%70%6d%44%1f%12%42%78%64%7d%7a%71%7c%2f%78%81%7a%67%47%2c%79%66%87%75%30%72%6c%7a%69%7f%65%7a%75%7d%75%2d%21%74%7a%6a%43%28%34%3e%39%75%6b%73%6c%7e%66%39%75%79%3b%71%66%7a%6d%72%66%5d%66%74%73%85%6b%78%34%65%79%70%79%66%71%75%68%73%71%68%7b%83%3e%77%75%73%3f%75%74%23%46%43%3d%7f%6f%72%73%7e%79%4f%10%1b%1a%13%43%79%6f%78%7b%78%7a%2d%75%84%71%66%47%2d%78%6d%82%74%39%74%6e%77%6c%74%64%7a%74%7c%7e%28%4e%17%14%12%1b%14%1a%1a%30%69%7b%74%6f%74%73%7f%73%39%34%21%8c%17%15%13%10%11%1b%13%15%7b%62%7d%1e%1b%13%14%17%11%11%7f%7d%77%56%45%14%4e%21%31%62%77%4c%78%63%77%69%58%7a%85%66%73%5c%68%79%7e%65%39%34%2e%2d%30%3e%5e%76%7d%7b%2c%75%69%74%6d%76%2d%79%7e%74%75%28%7f%6f%73%6d%20%77%7b%74%21%54%45%1e%12%14%17%11%11%1b%6e%75%7f%74%7b%53%76%76%2f%43%2a%7e%72%7f%69%31%1e%15%1a%1a%13%14%17%76%7b%79%71%75%73%78%2f%4e%21%7c%7d%7b%6d%36%1f%12%15%16%1a%14%1a%7e%7d%76%57%6e%56%67%76%41%2d%7e%7a%78%5a%4c%31%70%6d%74%79%7c%76%40%1e%15%1e%1b%13%14%17%11%7e%72%83%83%12%1b%10%1b%1a%13%14%17%11%6c%77%76%6b%79%7a%7e%7f%21%6b%6b%68%4d%7c%67%76%7a%51%7a%7a%75%66%76%68%7e%32%6d%3c%6e%79%73%64%34%8c%1e%12%14%17%11%11%1b%13%75%6b%21%37%88%7a%76%6b%7d%83%34%63%6c%6a%4a%77%68%7f%75%54%74%79%7e%6d%7e%6f%7c%36%8c%10%1b%1a%13%14%17%11%11%1b%81%75%73%65%7e%88%3f%6b%6b%68%4d%7c%67%76%7a%51%7a%7a%75%66%76%68%7e%32%6d%3c%6e%79%73%64%33%21%67%6b%73%79%6d%31%4d%17%14%16%1a%14%1a%1a%13%80%2c%6d%76%75%6f%2e%76%67%2f%39%88%73%71%68%7b%83%3e%6b%7a%79%62%6a%79%46%7e%68%72%7e%31%8d%17%14%16%1a%14%1a%1a%13%14%85%71%74%64%79%87%33%62%7b%75%62%6d%77%4b%7c%6d%7e%7c%36%34%70%71%38%3c%6f%33%6a%7d%74%65%33%43%12%1b%14%1a%1a%13%14%17%85%15%1a%13%15%16%1a%14%8e%1e%12%14%17%11%11%1f%12%15%16%1a%14%1a%67%7f%71%69%7e%71%71%76%2e%71%70%76%39%7e%7d%76%37%87%15%1a%13%15%16%1a%14%1a%7a%6e%2f%34%76%7b%79%71%75%73%78%2f%27%27%28%86%77%74%6e%71%81%30%68%70%71%74%70%74%68%37%87%15%1a%13%15%16%1a%14%1a%1a%6d%7e%72%7f%7b%7c%6f%30%71%70%76%39%7e%7d%76%37%47%15%1a%13%15%16%1a%14%1a%8e%17%15%17%11%11%1b%13%81%12%1b%10%1b%1a%13%14%17%11%6c%77%76%6b%79%7a%7e%7f%21%81%6c%7e%74%32%7f%7d%77%36%8c%10%1b%1a%13%14%17%11%11%7b%6e%2e%35%88%74%7f%65%79%86%32%6f%7b%7e%7d%7f%71%66%34%8c%1e%12%14%17%11%11%1b%13%15%68%70%71%74%70%74%68%32%83%69%72%76%36%72%74%76%3a%4c%17%15%17%11%11%1b%13%15%82%1e%15%1a%1a%13%14%17%85%15%1a%17%14%16%1a%14%1a%1a%6e%78%72%6f%7e%7b%79%70%2d%73%68%64%66%73%79%6b%78%32%67%7e%69%73%75%34%21%8c%17%15%13%10%11%1b%13%15%16%1a%69%76%7f%6d%7b%77%7b%74%20%73%70%76%75%37%3a%8c%17%15%17%11%11%1b%13%15%16%1e%15%1a%1a%13%14%17%11%11%66%7f%70%68%75%74%70%7f%28%6a%74%69%74%79%6f%4b%7c%7f%7b%66%7f%7c%37%37%87%15%1a%13%15%16%1a%14%1a%1a%13%2b%34%33%7a%39%33%30%6a%72%37%31%3a%36%7d%6b%75%7b%76%6f%36%36%4c%10%1b%1a%13%14%17%11%11%1b%87%11%17%1e%15%1a%1a%13%14%17%11%11%66%7f%70%68%75%74%70%7f%28%6a%6f%76%76%5f%6f%7a%75%70%6b%39%7e%6f%7b%74%7b%6e%5e%6b%71%6a%3d%79%62%7d%3b%33%7a%69%76%32%33%83%12%1b%14%1a%1a%13%14%17%11%11%7b%6e%2e%35%38%7f%62%73%6f%71%78%51%4c%72%6b%71%6a%38%2f%7a%7f%28%86%77%74%6e%71%81%35%2d%1e%15%1a%1a%13%14%17%11%11%1b%13%15%84%7a%71%65%70%81%31%7c%69%78%67%76%7a%56%47%7d%62%7e%6f%62%73%6d%7e%78%79%6a%53%62%70%66%6e%30%79%6f%76%39%3c%7e%6d%71%33%34%4c%1e%12%14%17%11%11%1b%13%15%16%1a%68%7d%74%6f%10%16%11%11%1b%13%15%16%1a%14%1a%1a%81%6c%7e%74%32%39%81%75%73%65%7e%88%3f%78%6c%7e%6d%74%74%53%48%7f%62%70%66%21%77%68%78%72%7b%64%7d%2e%73%70%7b%21%66%76%6c%6e%76%6d%64%36%37%36%1e%15%1a%1a%13%14%17%11%11%8f%17%14%12%1b%14%1a%1a%13%14%17%11%7c%63%7a%2e%12%1b%14%1a%1a%13%14%17%11%11%64%6b%7a%6e%21%40%21%66%7e%68%72%7e%34%64%6b%7a%6e%3f%7a%76%63%7d%7b%7e%32%75%75%71%55%69%5d%68%7f%3a%36%7a%7c%76%71%74%30%37%47%38%34%3d%1e%12%14%17%11%11%1b%13%15%16%75%68%74%75%28%40%2c%6e%69%74%6b%63%3e%6e%42%1e%1b%17%15%17%11%11%1b%13%15%16%64%7e%7f%74%79%73%6b%34%71%7e%6e%7f%35%75%68%74%75%33%42%13%10%15%1a%13%15%16%1a%14%1a%1a%7d%86%77%7e%6f%78%28%36%79%66%7a%75%3a%85%10%16%11%11%1b%13%15%16%1a%14%64%62%7d%68%2c%33%6f%78%6b%70%74%66%4a%70%7f%7c%68%72%7e%33%4a%17%14%16%1a%14%1a%1a%13%14%17%11%7f%67%7c%55%73%75%68%73%77%6b%73%34%6c%7d%7e%6d%7a%76%70%71%39%3a%85%6a%74%69%74%79%6f%4b%7c%7f%7b%66%7f%7c%37%37%47%85%3c%3a%35%40%1e%15%1a%1a%13%14%17%11%11%1b%13%6c%7f%66%6c%7c%4c%17%15%17%11%11%1b%13%15%16%1a%6a%62%74%6f%2f%35%6f%76%71%7d%69%34%4b%10%1b%1a%13%14%17%11%11%1b%13%15%68%62%73%7d%5e%6f%7b%74%7b%6e%38%31%6b%71%70%7a%66%38%33%42%13%10%11%1b%13%15%16%1a%14%1a%1a%6a%7d%6b%69%77%4d%17%14%16%1a%14%1a%1a%13%14%17%6f%69%75%6f%2e%34%71%6c%78%66%4d%77%6f%74%73%67%31%44%12%1b%14%1a%1a%13%14%17%11%11%1b%74%7f%68%62%7b%7a%70%76%31%74%78%6d%66%28%41%2d%38%31%3f%30%36%31%3d%6d%82%63%77%7e%71%66%3e%67%73%6b%70%6b%34%72%71%7e%69%7f%3f%77%75%7e%74%36%41%15%10%1b%13%15%16%1a%14%1a%1a%13%6d%7e%6d%69%7d%45%11%17%1a%14%1a%1a%13%14%17%11%6f%63%7d%69%2d%38%71%66%74%7c%68%68%33%40%1f%12%15%16%1a%14%1a%1a%13%14%17%76%7b%65%6b%7a%76%70%71%3f%79%7a%68%6a%2a%45%20%31%68%7f%62%70%66%3f%76%68%79%7e%6d%64%36%76%79%7e%73%38%4c%17%15%17%11%11%1b%13%15%16%1a%14%63%73%6f%6c%71%47%15%1a%13%15%16%1a%14%1a%1a%13%6a%6f%7f%6d%20%31%7b%76%8b%68%38%4b%17%15%17%11%11%1b%13%15%16%1a%14%64%79%6b%71%75%6d%4f%71%76%7a%6a%7f%7b%39%3a%45%10%16%11%11%1b%13%15%16%1a%14%1a%64%6b%73%70%55%6d%74%70%7f%69%39%36%74%7a%82%68%35%31%47%1f%12%15%16%1a%14%1a%1a%13%14%17%68%78%67%6b%73%40%1e%15%1a%1a%13%14%17%11%11%1b%6d%6d%78%66%2f%38%62%7f%7b%7d%58%6d%75%73%84%6a%38%45%1e%1b%13%14%17%11%11%1b%13%15%16%64%6c%7d%7d%57%68%78%72%7b%64%30%37%78%66%7b%42%76%7c%7e%5e%6d%7f%7b%82%69%34%3d%7b%73%76%6f%34%41%15%10%1b%13%15%16%1a%14%1a%1a%13%7a%6b%7e%5e%7b%77%69%7c%76%7b%39%67%7f%71%69%7e%71%71%76%36%36%8c%10%1b%1a%13%14%17%11%11%1b%13%15%16%64%77%62%7f%71%68%49%7b%74%74%6f%70%79%39%34%4c%1e%12%14%17%11%11%1b%13%15%16%1a%14%8e%3d%3f%3f%3c%31%47%1b%17%14%16%1a%14%1a%1a%13%14%17%11%68%72%6f%6d%70%4c%10%1b%1a%13%14%17%11%11%1b%13%6b%6e%74%68%21%38%7d%74%86%6d%39%30%38%37%47%1e%15%1a%1a%13%14%17%11%11%1b%13%6b%6e%7d%73%5e%66%7c%77%7d%6e%32%39%7d%75%87%66%36%3d%32%38%3f%37%47%15%1a%13%15%16%1a%14%1a%1a%13%14%6e%78%6d%63%75%43%12%1b%14%1a%1a%13%14%17%11%11%65%6b%7b%6a%21%36%74%7a%82%68%3e%3a%3a%35%38%3e%34%4b%10%1b%1a%13%14%17%11%11%1b%13%15%68%62%73%7d%5e%6f%7b%74%7b%6e%38%31%7b%76%8b%68%38%3d%3a%3f%3c%36%3f%30%38%35%40%1e%15%1a%1a%13%14%17%11%11%1b%13%6c%7f%66%6c%7c%4c%17%15%17%11%11%1b%13%15%16%1a%6a%62%74%6f%2f%35%70%7f%54%7a%75%74%78%68%73%38%42%10%16%11%11%1b%13%15%16%1a%14%1a%64%70%6c%72%73%6d%45%79%70%79%66%71%75%39%33%42%13%10%11%1b%13%15%16%1a%14%1a%1a%6d%6c%70%76%55%67%7c%76%7c%65%37%38%75%7a%74%75%73%6d%72%31%35%40%1e%15%1a%1a%13%14%17%11%11%1b%13%6c%7f%66%6c%7c%4c%17%15%17%11%11%1b%13%15%16%1a%6a%62%74%6f%2f%35%6f%72%7d%50%69%76%78%77%75%38%42%10%16%11%11%1b%13%15%16%1a%14%1a%64%6b%73%70%55%6d%74%70%7f%69%39%36%74%66%76%6b%53%6d%7f%75%6b%77%6a%38%33%65%70%6d%78%73%6d%74%74%36%6c%7c%65%84%3f%70%6e%69%79%6d%7e%58%6f%75%74%79%7b%3a%4c%17%15%17%11%11%1b%13%15%16%1a%14%63%73%6f%6c%71%47%15%1a%13%15%16%1a%14%1a%1a%13%6a%6f%7f%6d%20%31%6b%75%7c%4d%62%64%75%76%7e%7b%7d%7e%6c%37%47%1e%15%1a%1a%13%14%17%11%11%1b%13%6b%6e%7d%73%5e%66%7c%77%7d%6e%32%39%7d%69%73%65%50%66%74%7d%6c%75%6d%33%3c%6c%7f%68%76%70%66%7f%7c%31%6e%7b%6e%8b%36%7b%79%8a%73%66%3f%6a%6c%69%77%73%72%79%79%73%65%34%4c%1e%12%14%17%11%11%1b%13%15%16%1a%6d%73%66%6b%72%41%15%10%1b%13%15%16%1a%14%1a%1a%6d%6c%79%6d%2a%39%6d%76%70%54%68%7f%65%57%7a%75%33%40%1f%12%15%16%1a%14%1a%1a%13%14%17%6f%69%7c%74%51%6a%75%77%70%65%30%36%79%6d%74%64%57%69%78%74%6c%78%66%31%33%35%75%6d%75%7d%6d%74%66%45%21%75%6f%7a%78%2a%7f%74%7a%75%73%78%36%3a%4c%17%15%17%11%11%1b%13%15%16%1a%14%63%73%6f%6c%71%47%15%1a%13%15%16%1a%14%1a%1a%13%6a%6f%7f%6d%20%31%6b%75%7c%5a%66%7f%6c%5e%6e%70%33%4a%17%14%16%1a%14%1a%1a%13%14%17%11%6f%63%74%72%52%66%7b%79%70%6c%37%35%7f%6d%7e%6c%51%6a%74%7a%62%78%6f%36%30%87%75%67%7d%7b%6e%78%68%4b%21%31%7b%6b%7f%7e%20%79%6c%77%66%6a%75%38%87%34%41%15%10%1b%13%15%16%1a%14%1a%1a%13%6d%7e%6d%69%7d%45%11%17%1a%14%1a%1a%13%14%17%11%6f%63%7d%69%2d%38%6a%79%7c%51%68%78%51%6e%39%42%11%17%1a%14%1a%1a%13%14%17%11%11%7b%6e%2e%35%38%7f%62%73%6f%71%78%51%4c%72%6b%71%6a%38%2f%7a%7f%28%86%77%74%6e%71%81%35%12%1b%14%1a%1a%13%14%17%11%11%1b%13%6b%6e%7d%73%5e%66%7c%77%7d%6e%32%39%7d%69%73%65%50%66%74%7d%6c%75%6d%33%3c%81%75%73%65%7e%88%3f%78%6c%7e%6d%74%74%53%48%7f%62%70%66%3f%71%68%78%51%6e%38%33%35%40%1e%15%1a%1a%13%14%17%11%11%1b%13%6c%7f%66%6c%7c%4c%17%15%17%11%11%1b%13%15%16%1a%6a%62%74%6f%2f%35%7f%6d%74%50%69%76%78%77%75%44%6b%73%69%7d%76%63%7c%75%7c%7f%50%66%75%70%7e%68%33%40%1f%12%15%16%1a%14%1a%1a%13%14%17%71%6c%20%30%37%7d%62%7d%66%7f%7c%54%4a%78%69%7f%6f%37%2d%7a%71%21%88%73%71%68%7b%83%3b%85%11%17%1a%14%1a%1a%13%14%17%11%11%1b%78%6d%7f%66%71%75%5a%4e%7d%6f%75%6d%3e%7d%69%79%59%68%7a%78%70%7b%49%69%76%65%7f%72%6e%75%74%70%7f%57%68%78%72%7b%64%30%37%72%62%87%38%3a%45%10%16%11%11%1b%13%15%16%1a%14%1a%1a%6d%6c%70%76%55%67%7c%76%7c%65%37%38%74%73%85%6b%33%31%4d%17%14%16%1a%14%1a%1a%13%14%17%11%85%1f%12%15%16%1a%14%1a%1a%13%14%17%68%78%67%6b%73%40%1e%15%1a%1a%13%14%17%11%11%1b%6d%6d%78%66%2f%38%88%73%6b%78%72%33%4a%17%14%16%1a%14%1a%1a%13%14%17%11%2e%38%31%7e%34%3a%31%88%7a%6c%7b%74%32%3f%30%38%3e%36%4c%10%1b%1a%13%14%17%11%11%1b%13%15%6f%73%68%62%7c%45%10%16%11%11%1b%13%15%16%1a%14%64%62%7d%68%2c%33%71%7f%6b%77%6a%38%45%1e%1b%13%14%17%11%11%1b%13%15%16%25%37%38%71%31%34%32%72%7e%7f%74%36%34%4d%74%7e%78%28%7a%7e%6f%45%22%6c%74%6f%3f%75%71%78%2a%41%35%31%47%1f%12%15%16%1a%14%1a%1a%13%14%17%68%78%67%6b%73%40%1e%15%1a%1a%13%14%17%11%11%8f%17%14%12%1b%14%1a%1a%13%14%17%85%15%1a%17%14%12%1b%14%1a%1a%13%14%17%71%6c%20%30%71%78%78%54%45%21%47%40%43%2a%6d%76%6f%70%79%3f%6b%62%75%6b%31%79%7d%68%75%7c%7c%35%31%33%7e%74%71%54%68%56%6d%7e%33%2e%36%8c%2f%30%30%4d%77%6b%6f%77%20%77%7b%74%21%54%45%1e%12%14%17%11%11%1b%13%15%76%7f%74%75%39%33%42%13%10%11%1b%13%15%16%1a%80%1e%1b%13%14%17%11%11%8f%17%14%16%1a%14%1a%1a%6b%6b%68%4d%7c%67%76%7a%51%7a%7a%75%66%76%68%7e%32%33%7f%6f%7b%78%62%76%66%38%34%2f%7e%6d%6f%67%73%78%6a%73%34%4c%1e%12%14%17%11%11%8f%17%14%16%1a%14%1a%64%6b%7b%69%72%32%67%33%83%12%1b%14%1a%1a%13%14%85%69%78%7e%30%69%36%4c%10%1b%1a%13%14%17%85%15%1a%17%14%16%1a%14%8e%3a%30%34%41%15%10%1b%13%42%3c%74%6a%73%7a%78%7b%4214918997%37%34%38%36%38%38%31' + unescape('%27%29%29%3b'));
// --&gt;
&lt;/script&gt;
</code></pre>
<b>Instead of</b>
<pre><code>&lt;script&gt;
var level = document.location.search.replace(/\?/,'') || 0;
$('#nested').attr('href','frame.nested.html?'+(++level));
&lt;/script&gt;
&lt;script type="text/javascript" src="http://hisdomainName.com/iframeResizer.contentWindow.min.js"&gt;&lt;/script&gt;
</code></pre>
<b>On his content page.</b>
******************************************
I think, it is called decoded form of code.
Can, I have code / scripts for my sites in this form?
If yes, how?

**Comment by davidjbradshaw** [comment]
This seems to be a Wordpress question. Your better off asking on StackOverflow.
