### ISSUE TITLE
Parent scrolling to anchor?

### ISSUE THREAD

**Issue by kahuna900** [davidjbradshaw/iframe-resizer#225]
Is there a way to scroll the parent page to an anchor in the iframe?  When I'm going back and forth between long and short iframe content, the scroll seems to get lost.

**Comment by davidjbradshaw** [comment]
Try the dev branch version.

On Wednesday, July 15, 2015, kahuna900 <notifications@github.com> wrote:

> Is there a way to scroll the parent page to an anchor in the iframe? When
> I'm going back and forth between long and short iframe content, the scroll
> seems to get lost.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/225>.
>


-- 
Sent from my iPhone.

**Comment by kahuna900** [comment]
The dev branch version works great on PC browsers, but now anchor linking no longer works in the mobile android browser.  :(

**Comment by davidjbradshaw** [comment]
Do you get an error in the browsers console on Android?

Is the error in the examples?

**Comment by davidjbradshaw** [comment]
CLosed due to lack of response.
