### ISSUE TITLE
Chrome Problem: Dynamic height

### ISSUE THREAD

**Issue by Geddo** [davidjbradshaw/iframe-resizer#227]
Hi,

first of all: Awesome script. Thank you very much. But I'm having some troubles with the height resize in the latest chrome version. I also have to say that I'm loading a big asp-table from another domain into my site. It works perfectly for the first call, but when I'm clicking on one of the links within the frame, the height doesnt resize. it keeps the height of the first view. I also tried the negative interval, but it doesnt help. Any ideas? It's just chrome. IE and Firefox are working great.

**Comment by davidjbradshaw** [comment]
Send me a link and I'll have a quick look.

Have you tried different hightCalculationMethods?

D.

On Thursday, July 16, 2015, Geddo <notifications@github.com> wrote:

> Hi,
>
> first of all: Awesome script. Thank you very much. But I'm having some
> troubles with the height resize in the latest chrome version. I also have
> to say that I'm loading a big asp-table from another domain into my site.
> It works perfectly for the first all, but when I'm clicking on one of the
> links within the frame, the height doesnt resize. it keeps the height of
> the first view. I also tried the negative interval, but it doesnt help. Any
> ideas? It's just chrome. IE and Firefox are working great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/227>.
>


-- 
Sent from my iPhone.

**Comment by Geddo** [comment]
heightCalculationMethod : "max" works a little better, but not as good in your examples. Cant provide link at current state, sorry

**Comment by davidjbradshaw** [comment]
Without a link all I can suggest is to read the troubleshooting guide. Most likely a CSS issue.
