### ISSUE TITLE
Width downsizing not working

### ISSUE THREAD

**Issue by LuizPanariello** [davidjbradshaw/iframe-resizer#228]
Hi, I'm trying to downsize a div inside the iframe and change the iframe size, but it don't seem to work on any browser. I tried to use all heightCalc methods and updated to dev branch, but still not working.

My configuration is not simple to replicate on a JSBin or any online javascript tool, I'm using this great lib with a AngularJS within the iframe, so I won't post it. 

Anyway, on my tests I tried to get window 'innerWidth' (and many other width getters / bodyscroll etc) of the iframe element from inside of it and all return my older width.

Great lib, thx!!

**Comment by davidjbradshaw** [comment]
Csn you please try the dev branch, which has the Beta for v3 in it. This
provides much better width sizing support.

On Mon, Jul 20, 2015 at 10:58 PM, Luiz Panariello <notifications@github.com>
wrote:

> Hi, I'm trying to downsize a div inside the iframe and change the iframe
> size, but it don't seem to work on any browser. I tried to use all
> heightCalc methods and updated to dev branch, but still not working.
>
> My configuration is not simple to replicate on a JSBin or any online
> javascript tool, I'm using this great lib with a AngularJS within the
> iframe, so I won't post it.
>
> Anyway, on my tests I tried to get window 'innerWidth' (and many other
> width getters / bodyscroll etc) of the iframe element from inside of it and
> all return my older width.
>
> Great lib, thx!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/228>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek
