### ISSUE TITLE
Host method for closing an iFrame

### ISSUE THREAD

**Issue by alexanderkraus** [davidjbradshaw/iframe-resizer#229]
I know there is an iFrame method for closing an iFrame (communication iFrame -> host). Would it be possible to provide an equivalent method for the opposite direction, i.e. removing the settings for a specific iFrame from the host window?
Currently, if an iFrame is "tracked" by iFrameResizer and this iFrame is removed later by other code, iFrameResizer is still listening for events (e.g. resize of host window). When iFrameResizer recognizes that an iFrame is not present anymore, the settings for this iFrame are deleted (which I think is a good behavior) and a warning is printed to the console.
It would be great if one could tell iFrameResizer to not track a specific iFrame anymore to forestall the warning.

**Comment by davidjbradshaw** [comment]
This feature is the beta of v3.0.0  which can be found on the dev branch.

On Thursday, July 23, 2015, alexanderkraus <notifications@github.com> wrote:

> I know there is an iFrame method for closing an iFrame (communication
> iFrame -> host). Would it be possible to provide an equivalent method for
> the opposite direction, i.e. removing the settings for a specific iFrame
> from the host window?
> Currently, if an iFrame is "tracked" by iFrameResizer and this iFrame is
> removed later by other code, iFrameResizer is still listening for events
> (e.g. resize of host window). When iFrameResizer recognizes that an iFrame
> is not present anymore, the settings for this iFrame are deleted (which I
> think is a good behavior) and a warning is printed to the console.
> It would be great if one could tell iFrameResizer to not track a specific
> iFrame anymore to forestall the warning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/229>.
>


-- 
Sent from my iPhone.
