### ISSUE TITLE
Iframe starts with height:0

### ISSUE THREAD

**Issue by gthvidsten** [davidjbradshaw/iframe-resizer#230]
When I first load the page the iframe gets `style="height: 0px"`, which causes the iframe to be invisible.
If I, in Chrome Developer Tools, mark the iframe and uncheck the height value, the iframe-resizer observes that something is going on and immediately changes the height value to a correct size.
This is only observed if the client includes the `iframeResizer.contentWindow.min.js` script. When that file is not included the iframe starts off with the correct height at once.

On a related note: I was under the impression that in order for the iframe to resize when the client content changes this file must be included. Whether or not the file is included the iframe never changes its size when the client content changes (not even after changing the height value to force iframe-resizer to do some work).

This has been tested on both the master and dev branch using Chrome for Windows.

**Comment by davidjbradshaw** [comment]
This sounds like a CSS issue in your iframed page. Please see the troubleshooting section and try different heightCalculationMethods.
