### ISSUE TITLE
Iframe doesn'r resize after subsequent load

### ISSUE THREAD

**Issue by gthvidsten** [davidjbradshaw/iframe-resizer#231]
The Iframe gets resized when the page is first loaded, and grows when the content changes.
If the iframe is hidden in the browser (it is used in a modal popup) then made visible again the iframe doesn't resize. It has the same size as when it was initially loaded.
Also, the iframe never shrinks if the content gets smaller.
This has been tried out with all the heightCalculationMethod options.

**Comment by davidjbradshaw** [comment]
The first issue is interesting, I expect we need to detect window.onfocus
somewhere. If you can make a simple test case I'll take a look when back
from holiday in August. Or your welcome to submit a pull request. It's very
simple to add extra event handlers to iframe.

For the second issue try the dev branch version, it has a new height calc
method 'taggedElement' that might help you.

On Friday, July 24, 2015, Glenn Thomas Hvidsten <notifications@github.com>
wrote:

> The Iframe gets resized when the page is first loaded, and grows when the
> content changes.
> If the iframe is hidden in the browser (it is used in a modal popup) then
> made visible again the iframe doesn't resize. It has the same size as when
> it was initially loaded.
> Also, the iframe never shrinks if the content gets smaller.
> This has been tried out with all the heightCalculationMethod options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/231>.
>


-- 
Sent from my iPhone.

**Comment by davidjbradshaw** [comment]
Also which browser is this an issue in?

**Comment by davidjbradshaw** [comment]
Just had another read of this. The solution is to use the beta of v3 in the dev branch, as it has an option to tell the iframe to resize itself that you can call after unhidding it.

**Comment by anderspetersson** [comment]
Hey, thanks for a nice library!

I stumbled into the same issue (on Firefox) upgraded to the just released 3.0 but I can't figure out how to access the iFrameResizer object :(

Could you please document an example?

**Comment by davidjbradshaw** [comment]
document.getElementById('#myIFrame').iframeResizer
