### ISSUE TITLE
Mouse scroll not working on firefox

### ISSUE THREAD

**Issue by harilal** [davidjbradshaw/iframe-resizer#232]
I have been using this iframe resizer with malihu scorller. I am adding the iframe  dynamically here is my code

$("#elemId_container").find(".slider-content-wrap").html("<div class='iframe-container'> <iframe id='elemId_iframe' src='"+iframeSrc+"' width='100%' height='1000' scrolling='no' frameborder='0'></iframe></div> ");                                                 

$("#elemId_container .iframe-container").mCustomScrollbar({
    autoHideScrollbar: true,
    axis:"yx",
});
$("#elemId_iframe").iFrameResize()

It's working in chrome but mouse scroll not working on firefox 39

**Comment by davidjbradshaw** [comment]
I'll have a quick look, but need a link to a simple test case.

**Comment by harilal** [comment]
first is there cross domain issue with this framework. It worked when i hosted in the public server. But not on localhost, though it worked on chrome.

**Comment by davidjbradshaw** [comment]
It works cross domain. Try the examples.

**Comment by davidjbradshaw** [comment]
Closing due to no response.
