### ISSUE TITLE
Infinate resizing on iOS

### ISSUE THREAD

**Issue by scroniser** [davidjbradshaw/iframe-resizer#233]
I'm sure that there is something odd and/or a conflict going on, but we're using your resizer in order to display courses pulled from another website. The page displays fine on the desktop version, but it oddly resizes all of the rows on mobile. Any ideas what could be causing this?

Here's the example: http://www.math.northwestern.edu/undergraduate/courses/current-year-courses/fall.html

**Comment by davidjbradshaw** [comment]
Have you set the viewport size?

**Comment by davidjbradshaw** [comment]
Just tested on iOS 8 and your link works ok.

**Comment by scroniser** [comment]
I am still seeing the problem.

**Comment by davidjbradshaw** [comment]
Can you please add the log. Also what version of iOS?

On Sun, Aug 2, 2015 at 3:50 PM, scroniser <notifications@github.com> wrote:

> I am still seeing the problem.
>
> Sent from my iPhone
>
> > On Aug 2, 2015, at 9:02 AM, David J. Bradshaw <notifications@github.com>
> wrote:
> >
> > Just tested on iOS 8 and your link works ok.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/233#issuecomment-127032114>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by scroniser** [comment]
FYI, looked at log and found that the iframeResizer.contentWindow.map file wasn't added to the host server of the iframed page. Requested the add and the problem was resolved. Thanks for your help & fast response (I work in a University, so the response usually comes at a snail's pace).
