### ISSUE TITLE
Host send init, but content resizer not responding if using Kendo UI Editor

### ISSUE THREAD

**Issue by mykone** [davidjbradshaw/iframe-resizer#234]
Hello, this looks like a great library, but I have been unlucky to get it to work in my current setup. Rather than using <iframe src="source.html"/>. The content is being set by Kendo Editor. Does iframe-resizer only works with src being set by an html file?

**Comment by davidjbradshaw** [comment]
Does the page in the iFrame have the second JS file in it?

**Comment by mykone** [comment]
Yeah. I do console logs as well to test that it's loaded.

**Comment by davidjbradshaw** [comment]
If you can make a simple test case I will take a quick look.

Have you tried the dev branch version?

**Comment by davidjbradshaw** [comment]
Thinking about this a bit more, is the script in the iframe being loaded before the on load event fires?

**Comment by davidjbradshaw** [comment]
Just had another thought on this. Can you download the latest dev branch version and the in the iframe after the script has loaded, add this line of JS.

```js
window.parent.postMessage('[iFrameResizerChild]Ready','*');
```

This should kick start things for you.
