### ISSUE TITLE
Warning logs when resizing window - from content window

### ISSUE THREAD

**Issue by aleross** [davidjbradshaw/iframe-resizer#235]
Hi,

First thanks for making iframe-resizer. I'm using version 2.8.10 with Chrome 44 on Mac and am getting a stream of warning logs when I resize the window. The logs are coming from the content window script, in response to a message presumably sent by the parent window.

I only have one iFrame on the page, and while I have my own iFrame communications going on - I disabled them and still get this log statement.

I attached a screenshot of the message object. Do you have any recommendations? Thank you.

![screen shot 2015-07-28 at 9 44 25 pm](https://cloud.githubusercontent.com/assets/1857007/8950210/40a4ca8e-3573-11e5-827d-9bd19d513ebd.png)

**Comment by davidjbradshaw** [comment]
That's very strange. Can you please make a simple test case and I will take
a look at it next week whenI'm back from my holiday.

On Wed, Jul 29, 2015 at 6:55 AM, Alex Ross <notifications@github.com> wrote:

> Hi,
>
> First thanks for making iframe-resizer. I'm using version 2.8.10 and am
> getting a stream of warning logs when I resize the window. The logs are
> coming from the content window script, in response to a message presumably
> sent by the parent window.
>
> I only have one iFrame on the page, and while I have my own iFrame
> communications going on - I disabled them and still get this log statement.
>
> I attached a screenshot of the message object. Do you have any
> recommendations? Thank you.
>
> [image: screen shot 2015-07-28 at 9 44 25 pm]
> <https://cloud.githubusercontent.com/assets/1857007/8950210/40a4ca8e-3573-11e5-827d-9bd19d513ebd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/235>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek

**Comment by davidjbradshaw** [comment]
Please make sue you have the v2.8.10 or higher in the iframe as well.
