### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by braguzz** [davidjbradshaw/iframe-resizer#236]
I got this error

Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'.

I use your amazing script in

http://www.provincia.livorno.it/altri/amministrazione-trasparente/organizzazione/organi-di-indirizzo-politico-amministrativo-dal-13-ottobre-2014/

**Comment by davidjbradshaw** [comment]
That's strange, can you put the uncompressed version on the script, so I can take a look.

Are you setting targetOrigin?

**Comment by braguzz** [comment]
done.

no targetorigin setted

2015-08-06 17:12 GMT+02:00 David J. Bradshaw <notifications@github.com>:

**Comment by davidjbradshaw** [comment]
You page is creating an iframe with src="" in it. This has a different ID each time I load the page. Try the dev branch version which should now cope with that.

**Comment by braguzz** [comment]
no errors with dev version.
thanks

but probably now I misanderstood know how the script works.

look at my page.
when the page for example is resized to 1024x768 , the target fram is too wide, and I'd like to see scrolling panel for the widht.

I want too much?

thanks again,
PB

**Comment by davidjbradshaw** [comment]
Set the min width and scrolling options.

**Comment by braguzz** [comment]
I have setted in this way but it doesnt work


iFrameResize({
log                     : false,                  // Enable console logging
enablePublicMethods     : true,                  // Enable methods within
iframe hosted page
inPageLinks : true,
scrolling : true,
minWidth :600,
//heightCalculationMethod : lowestElement,
//widthCalculationMethod : leftMostElement,
resizedCallback         : function(messageData){ // Callback fn when resize
is received
$('p#callback').html(
'<b>Frame ID:</b> '    + messageData.iframe.id +
' <b>Height:</b> '     + messageData.height +
' <b>Width:</b> '      + messageData.width +
' <b>Event type:</b> ' + messageData.type
);
},
messageCallback         : function(messageData){ // Callback fn when
message is received
$('p#callback').html(
'<b>Frame ID:</b> '    + messageData.iframe.id +
' <b>Message:</b> '    + messageData.message
);
alert(messageData.message);
},
closedCallback         : function(id){ // Callback fn when iFrame is closed
$('p#callback').html(
'<b>IFrame (</b>'    + id +
'<b>) removed from page.</b>'
);
}
});


2015-08-07 11:33 GMT+02:00 David J. Bradshaw <notifications@github.com>:

**Comment by davidjbradshaw** [comment]
You don't need most of that code. This issue tracker is for bugs. If you want me to develop code for you, then I'm available for hire.

**Comment by braguzz** [comment]
if I put
heightCalculationMethod:  : 'lowestElement',

I have a js error:

Uncaught SyntaxError: Unexpected token :

2015-08-07 12:06 GMT+02:00 David J. Bradshaw <notifications@github.com>:

**Comment by braguzz** [comment]
Sorry, I dont know if my specific behaviour is a misconfiguration or a error or simply this script cant handle.

I'd like that the iframe shows only the orizontal scroll, but it shows both.

thanks again,
PB

**Comment by davidjbradshaw** [comment]
The scroll option is currently all or none.

**Comment by braguzz** [comment]
ok

2015-08-07 12:37 GMT+02:00 David J. Bradshaw <notifications@github.com>:
