### ISSUE TITLE
Resize dynamically generated iframe with injected contentWindow

### ISSUE THREAD

**Issue by steffenmllr** [davidjbradshaw/iframe-resizer#241]
I'm trying to resize an iFrame that is dynamically generated via `contentWindow.document.write` and get's the contentWindow script via injection.

It locks the iframe but does not resize the window. Could it be that the `addEventListener(window, 'message', receiver);` within the script doesn't get executed?

Here is a testcase:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>iFrame message passing test</title>
        <meta name="description" content="iFrame message passing test">
        <meta name="viewport" content="width=device-width">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    </head>
    <body>
        <button onclick='createIframe()'>Clickme</button>
        <script type="text/javascript" src="http://davidjbradshaw.com/iframe-resizer/js/iframeResizer.min.js"></script>
        <script type="text/javascript">
            var iframeContent = '<!DOCTYPE html> <html> <head> <meta charset="utf-8"> <title>Inner Frame</title> <meta name="description" content="iFrame message passing test"> <meta name="viewport" content="width=device-width"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> </head> <body> <div style="height:1000px;background:black;">foobar</div> </body> </html>';

            function createIframe () {
                var iframe = document.createElement('iframe');
                document.body.appendChild(iframe);
                iframe.contentWindow.document.open();
                iframe.contentWindow.document.write(iframeContent);
                var script = iframe.contentWindow.document.createElement('script');
                script.type = 'text/javascript';
                script.src = 'http://davidjbradshaw.com/iframe-resizer/js/iframeResizer.contentWindow.min.js';
                iframe.contentWindow.document.body.appendChild(script);

                iFrameResize({
                    log: true,
                    checkOrigin: false
                }, iframe);

            }
        </script>

    </body>
</html>
```

**Comment by steffenmllr** [comment]
Nevermind. `setTimeout` before `iFrameResize ` did the trick

**Comment by davidjbradshaw** [comment]
Good old race conditions. Version 3.1 which is currently on the dev branch has the option to kick start things from the iframe, which will save you having to use setTimeout.

in 3.1 you would run this line of code in the iframe once your ready to start resizing.

```js
window.parent.postMessage('[iFrameResizerChild]Ready','*');
```

**Comment by steffenmllr** [comment]
Thanks, that might be the better option. I'm creating and destroying a lot of iframes within a react application. Might be a better setup to have one `iFrameResize` object instead of multiple.

Didn't have the time to look at the `iFrameResize` code to see how the beste way to handle this is.

**Comment by davidjbradshaw** [comment]
OK so I just noticed I managed to merge out the code that I just pointed you at. It will be back shortly!

The code maintains a object array in it's closure for every iFrame that you setup. If you want to remove an iFrame from the page you should really do it by calling `[iframeDomObject].iframeResizer.close()` as this will delete everything internally.
