### ISSUE TITLE
Iframe won't downsize

### ISSUE THREAD

**Issue by tkreykes** [davidjbradshaw/iframe-resizer#250]
I am working on an application that is the content of the iframe, I have the file included and the iframe gets larger as necessary but it doesn't downsize when the size of the content is smaller. 
What am I missing? Do I need to call a function in order to for it to downsize?

**Comment by davidjbradshaw** [comment]
Have a read of the troubleshooting section, it has lots of suggestions. Most likely thing is some element having CSS height set to 100%.

**Comment by tkreykes** [comment]
Great thanks, it was a CSS height issue!
