### ISSUE TITLE
Issue with resizedCallback in IE8

### ISSUE THREAD

**Issue by archanasharma14061986** [davidjbradshaw/iframe-resizer#251]
When i am trying to call this iFrameResize in document.ready and uses resizedCallback property to get the messageData height and based on that i need to set the height of some element.Then its getting called in loop in IE8. Please help me to resolve it.

**Comment by archanasharma14061986** [comment]
Also to add, i have 2 iframes in the page. In the first (parent) iframe i have some controls like radio button and on click of that the second (child) iframe appears. Is it conflicting anywhere??

**Comment by archanasharma14061986** [comment]
Also I am trying to call this iFrameResize function on Animation completed function.in document.ready

**Comment by davidjbradshaw** [comment]
Hi,

If you make a simple test case, I will take a look in a weeks time, when I'm back from holiday. Likely offline for most of the next seven days.

**Comment by archanasharma14061986** [comment]
Oh no :(

**Comment by archanasharma14061986** [comment]
$(this).animate({
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: screen.height + addmargin
}, 'slow', 'swing', function () {
    //resizing of iframes
    iFrameResize({
        heightCalculationMethod: isOldIE ? 'max' : 'lowestElement',
        log: false,                  // Enable console logging
        inPageLinks: true,
        resizedCallback: function (messageData) {
            if (messageData.height < screen.height) {
                $(plugin.settings.tilesexpanded).height(screen.height + innermargin);
                $(plugin.settings.parentframe).height(screen.height + outerrmargin);
            }
            else {
                $(plugin.settings.tilesexpanded).height(messageData.height - (-innermargin));
                $(plugin.settings.parentframe).height(messageData.height - (-outerrmargin));
            }
        },
    });

});

**Comment by davidjbradshaw** [comment]
Does this help?
http://stackoverflow.com/questions/32116603/how-to-make-iframe-resizer-to-dynamically-apply-minheight-value

**Comment by davidjbradshaw** [comment]
I think you should not use the 'max' height calc method in this case.

**Comment by archanasharma14061986** [comment]
Finally my issue got resolved when i used heightCalculationMethod : "grow". Cheers :)
