### ISSUE TITLE
Error  'log' of undefined

### ISSUE THREAD

**Issue by Nicola1976** [davidjbradshaw/iframe-resizer#252]
Hi David,

First I must compliment. 
Your script is great and it works perfectly .

I have only one problem in last days.
In console I can not understand why I have always an error Uncaught TypeError : Can not read property ' log ' of undefined on iframeResizer.js

This happens even though I turned off the log in option log : false .
There is another way to force the disabling of the logs ?

thank you very much and congratulations again
Nicola

**Comment by davidjbradshaw** [comment]
Can you add a link please.

**Comment by Nicola1976** [comment]
Hi David! 

Thank you very much for your reply and sorry for the delay but I have prepared two sample pages to better explain my problem.

Here they are :

1) http://www.topasiahair.com/test-fif/indexFIF.html?testpassbackdisplay

2) http://www.topasiahair.com/test-fif/indexFIF-2iframe.html?testpassbackdisplay

In both the resizer it works properly . 

I do not know if it's related to the problem but noticed that in the first one , with only one iframe , I have no errors . In the second with 2 iframes I have an error log .

Thanks a lot for any suggestions you can give me .

See you soon
Nicola

**Comment by davidjbradshaw** [comment]
GET http://oas.rcsadv.it/RealMedia/ads/adstream_mjx.ads/iodonna.it/hp/125257228….html%3Ftestpassbackdisplay&XE&oas_pv=no_analytics&if_nt_CookieAccept=Y&XE net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ mjx.js:61
    Uncaught ReferenceError: OAS_RICH is not definedOAS_AD @ mjx.js:63(anonymous function) @ indexFIF-2iframe.html?testpassbackdisplay:9
    Uncaught ReferenceError: OAS_RICH is not definedOAS_AD @ mjx.js:63(anonymous function) @ indexFIF-2iframe.html?testpassbackdisplay:16

Is all I see.

**Comment by Nicola1976** [comment]
Hi David,
try with this url:

http://www.gazzetta.it/?testpassbackdisplay

thankz a lot
Nicola

**Comment by davidjbradshaw** [comment]
I don't see the error on that page.

**Comment by Nicola1976** [comment]
Sorry Davide, I was working on it
Try this.
http://www.gazzetta.it/index-noasync.shtml?testadxpassbackdisplay

here a screenshot

![image](https://cloud.githubusercontent.com/assets/14162566/9999657/dcd3a17e-6097-11e5-9598-239a11536db6.png)


Thankz
Nicola

**Comment by davidjbradshaw** [comment]
![screen shot 2015-09-21 at 19 38 22](https://cloud.githubusercontent.com/assets/591634/10001173/60896364-6098-11e5-9271-c697a6063dc1.png)

Page doesn't even load the script!

**Comment by davidjbradshaw** [comment]
Are you using version 3.2.0?

**Comment by Nicola1976** [comment]
Hi David, 
actually I'm using older version  v2.8.5 - 2015-03-25.

About the page to load script you have to look at the url I sent you: http://www.gazzetta.it/test-f2-adx/index-gazzaF2sync.shtml?testadxpassbackdisplay (and not on the url I see on your sceenshot: http://www.gazzetta.it/?refresh_ce).

Let me know!

Thanks a lot!
Nicola

**Comment by davidjbradshaw** [comment]
I'm out of ideas try the latest version.
