### ISSUE TITLE
Issue when used with MooTools

### ISSUE THREAD

**Issue by mrweix** [davidjbradshaw/iframe-resizer#253]
when using the latest version 3.2.0 of your plugin I get the following error in the console of safari and Chrome.

Uncaught TypeError: Cannot read property 'tagName' of undefined

a	@	iframeResizer.js:855
(anonymous function)	@	mootools-core.js:88
(anonymous function)	@	iframeResizer.js:876

Before I used version 2.8.6 so I reverted to that version for now, because there I don't get any mistakes....

**Comment by davidjbradshaw** [comment]
Can you please add a link and I'll have a look.

**Comment by mrweix** [comment]
Since I have to use the site that works (so I use iframeresizer 2.8.6) I unfortunately don't have a link to the site. The thing is I also get other Error messages on that site and on another environment 3.2.0 works. So its probably some sort of problem where 2 plugins interfere....

**Comment by davidjbradshaw** [comment]
Could you add your call to the script here. Just wondering what settings your using.

**Comment by mrweix** [comment]
iFrameResize({log : true,enablePublicMethods : true,enableInPageLinks : true});

**Comment by davidjbradshaw** [comment]
Are you using an old version of mootools? To me it looks like the bug is with that. I expect you can work around it by passing the iframe directly, rather than searching for it.

     var myIFrame = document.getElementById('myIFrame');
     iFrameResize({log : true,inPageLinks : true},myIFrame);

Note the options in v3 have changed a little.
