### ISSUE TITLE
Failed to execute 'postMessage' error

### ISSUE THREAD

**Issue by jasonhill** [davidjbradshaw/iframe-resizer#254]
The error message indicates an issue with the targetOrigin but we have not set that option so the default should allow all origins right? Is there a specific setting we need to use to enable cross origin posting?

I would prefer to send a link to the page privately - is that possible?

**Comment by davidjbradshaw** [comment]
Yep email address is dave@bradshaw.net

**Comment by davidjbradshaw** [comment]
Can you add the error message here.

**Comment by jasonhill** [comment]
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided
('XXX') does not match the recipient window's origin ('YYY').

**Comment by davidjbradshaw** [comment]
Are you manually setting the target?

**Comment by jasonhill** [comment]
No. We tried that too but it still failed with the same error.

**Comment by davidjbradshaw** [comment]
Just had a look at your page. The issue is that the URL in the iFrame tag does not have a protocol on it and without that it can not workout the domain to send the message to. You can get around this problem by adding the `checkOrigin:false` option. The default is to restrict it the domain listed in the iFrame.

Interesting issue will have to think of a way to deal with this automatically in the next release.

**Comment by davidjbradshaw** [comment]
The targetOrigin issue seems, to be an issue with Google Chrome, upgrading to this weeks version fixed it for me.

**Comment by davidjbradshaw** [comment]
You seem to be getting this problem on your page now.

http://requirejs.org/docs/errors.html#mismatch

**Comment by jasonhill** [comment]
We added the protocol to the iframe but are still seeing this error. You
mentioned later that this could be a Chrome issue though so should we
specify the targetOrigin or the checkOrigin:false option? Are there
security concerns with the latter? We are not seeing the error in Firefox
but the iframe isn't resizing.

**Comment by davidjbradshaw** [comment]
It's not resizing in Firefox due to an unrelated issue. How are you calling iframeresizer?

**Comment by jasonhill** [comment]
var element = document.getElementById('widget-placeholder);
var iframe = document.createElement('iframe');
iframe.id = 'widget123';
iframe.width = '100%';
iframe.src = 'xxx';
iframe.scrolling = 'no';
iframe.frameBorder = 0;
iframe.style.overflow = 'hidden';
element.parentNode.insertBefore(iframe, element);

if (window.jQuery) {
    jQuery(iframe).iFrameResize(
    {
        enablePublicMethods: true
    });
} else {
    iFrameResize({
        enablePublicMethods: true
    }, iframe);
}

**Comment by delroh** [comment]
I'm getting the same error message, but the resize seems to be working fine though (using Google Chrome).

**Comment by mehanoid** [comment]
The error may occur in Chrome if iframe is not loaded yet. A solution is to call iframeresizer on iframe load event.

**Comment by shobhitsharma** [comment]
Even after trying out `targetOrigin`, I am still having CORS issue as I'm trying it on social media embeds. Probably to have an option to skip this function execution?

**Comment by davidjbradshaw** [comment]
If you have the error message, but things still work it is due to a bug in Chrome. The error happens when you call iFrameResize before the iFrame has loaded. Their is no way to stop the error in the console, but as soon as the loaded event fires on the iFrame then iFrameResizer resents the message to kick off the resize. 

So if things work just ignore the error message.

**Comment by dylanwoo** [comment]
I got around it with this:

$("#targetframe").on("load", function () {
   
   $('#targetframe').iFrameResize( [{
		checkOrigin:false,
		log:true,
		minHeight:15000,
		heightCalculationMethod:'lowestElement'
		}] );
   
   
});

**Comment by shobhitsharma** [comment]
I figured outs its web security issue. Unless we do a patch with nginx for self hosted URIs. My case was to access contents inside facebook/social embed iframes. I solved that by putting this into a container which resizes through iframe size change.
