### ISSUE TITLE
Cross domain iframe resizing not working?

### ISSUE THREAD

**Issue by chrismfrench** [davidjbradshaw/iframe-resizer#255]
Hi there, I tried to using the following source http://davidjbradshaw.com/iframe-resizer/example/ to test cross domain resizing. I only replaced two things:

```<iframe src="frame.content.html" width="100%" scrolling="no" id="iFrameResizer0" style="overflow: hidden;"></iframe>```
**to**
```<iframe src="http://facebook.com" width="100%" scrolling="no" id="iFrameResizer0" style="overflow: hidden;"></iframe>````

**and**

```<script type="text/javascript" src="../js/iframeResizer.min.js"></script>```
**to**
```<script type="text/javascript" src="http://davidjbradshaw.com/iframe-resizer/js/iframeResizer.min.js"></script>````

I can get facebook to populate in the iframe but reszing still doesn't work?

**Comment by adamlindqvist** [comment]
The page in the iframe need to have the file iframeResizer.contentWindow.min.js referenced.

As written in the docs:

> The second file (iframeResizer.contentWindow.min.js) is a native JavaScript file that needs placing in the page contained within your iFrame. This file is designed to be a guest on someone else's system, so has no dependencies and won't do anything until it's activated by a message from the containing page.

**Comment by chrismfrench** [comment]
Thanks, this makes total sense and closes the issue for me.

**Comment by nachitox** [comment]
You need access to the other domain? It's very misleading

**Comment by Fairyshi** [comment]
Solved!  it will work by add the second step of the "Getting started" in the offical doc. That is add the "iframeResizer.contentWindow.min.js" doc into the iframe content page.
