### ISSUE TITLE
Cross domain iframe not resizing in Chrome, Firefox works fine.

### ISSUE THREAD

**Issue by chrismfrench** [davidjbradshaw/iframe-resizer#256]
So I took the source code from David Bradshaw's example page http://davidjbradshaw.com/iframe-resizer/example/ and simply replaced the iframe content with page I own and put the proper JS files in place. However, it's not working in Chrome.

Look at the following URL http://159.100.180.57/iframe-test/ in both Chrome and Firefox. Confirm what I see in the screenshot below. Thanks in advance for the help, truly great script if I can get it to work.

![iframe](https://cloud.githubusercontent.com/assets/3171732/9949080/55ee9646-5d5e-11e5-8e1f-1039a2e0b0b1.png)

**Comment by sean1138** [comment]
Microsoft's browsers seem to be affected as well.

http://i.imgur.com/pqo7zNx.jpg - ie10 and 11
http://i.imgur.com/pqo7zNx.jpg - edge

**Comment by chrismfrench** [comment]
Thanks for sharing Sean. Looking for any ideas on this. Thanks!

**Comment by davidjbradshaw** [comment]
Refused to execute script from 'https://raw.githubusercontent.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

You need to host the JS, not link to it on GitHub.

**Comment by chrismfrench** [comment]
Thank you David, hosting the JS fixed the issue. Much appreciated and thank you for this fantastic script!
