### ISSUE TITLE
v3.3.0 includes test code causing errors

### ISSUE THREAD

**Issue by MikeRyan52** [davidjbradshaw/iframe-resizer#257]
Looks like some test code was mistakenly published in 3.3.0: https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L1038

Bundling iframeResizer from the version published on NPM throws this error: `define is not defined`

**Comment by davidjbradshaw** [comment]
Are you using the version in src or js?

**Comment by MikeRyan52** [comment]
Working in a CommonJS environment, so hitting index.js which does seem to be pulling in from src.

**Comment by davidjbradshaw** [comment]
Arh, give me a moment to move it to js.

**Comment by davidjbradshaw** [comment]
Can you try the dev branch build and let me know if that works for you.

**Comment by MikeRyan52** [comment]
Yeah, the dev branch works well.

**Comment by davidjbradshaw** [comment]
Thanks, released as v3.3.1.

**Comment by MikeRyan52** [comment]
Thanks for the quick response and fix!

**Comment by mbrevda** [comment]
Is it possible that said code is still [in the source](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L1078)? I'm getting `define is not defined` error in iframeResizer.contentWindow

**Comment by davidjbradshaw** [comment]
Use the version in the JS, not the SRC folder.

**Comment by mbrevda** [comment]
Brilliant, thanks m8! :beers:
