### ISSUE TITLE
IE8 - querySelectorAll - no polyfill?

### ISSUE THREAD

**Issue by neiljthomson** [davidjbradshaw/iframe-resizer#258]
While the readme clearly states that document.querySelectorAll needs to be added for IE 8 to work in native mode, I don't see that in the ie8.polyfils.js file. And in testing, the Object doesn't support method error faithfully shows up in iframeResizer.contentWindow.js.

While can attempt to grab and include a solution for this on my own, I'm not clear on why one isn't included. 

For my particular example, the page is running with Browser Mode: IE8 Compat View and Document Mode: IE8 Standards

**Comment by davidjbradshaw** [comment]
You need to force IE8 into standards mode to get it. Add the following line to you `<head>` section.

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by neiljthomson** [comment]
The page says it's running:
       Browser Mode: IE8 Compat View and Document Mode: IE8 Standards
What is interesting is that inserting code to see if document.querySelectorAll exists, for example:
      typeof document.querySelectorAll !== 'undefined'
on the host side (e.g. iframeResizer.js) and on the iframe side (iframeResizer.contentWindow.js) to log to the console gets 'true' for host side and 'false' for the iframe side.

Knowing the app we're inserting into the iframe, which runs in IE5 Quirks mode if you run it directly in a browser window strongly suggests that despite the page believing it's running in IE 8 standards, the iframe is running in less than IE8 standards mode, or at least it is in IE8. This problem doesn't happen in IE9+ even if we run the page in IE8 mode via XUA Compatible.

**Comment by davidjbradshaw** [comment]
You only need it on the parent page.

**Comment by neiljthomson** [comment]
iframeResizer.contentWindow.js uses it in getAllElements() when using the "lowestElement" calculation option. That's where we hit the issue.

**Comment by davidjbradshaw** [comment]
I wouldn't use that in IE8, the browser is far too slow.
