### ISSUE TITLE
Bug in versions >= 3.2.1

### ISSUE THREAD

**Issue by ddtxra** [davidjbradshaw/iframe-resizer#259]
Hello,
Thanks for your amazing plugin, however it looks like there is a bug on versions >= to 3.2.1.
I have tried to see what was going on and it seems to me that some global variables are erased. 
I am using your plugin in an angular project and I had some issue with injection of modules (they were not defined if I am using this library) ... 
I have seen there is some code related to the window variable that was changed in 3.2.1 so I assume there is some problem there.
Could you look into that?

**Comment by davidjbradshaw** [comment]
Could you please give me a bit more info to go on? A simple test case would be great and which line of code are you saying changed?

**Comment by ddtxra** [comment]
I have created a quick repo here with 2 commits (1st commit is working):
https://github.com/calipho-sib/test-iframe

You should get some errors net::ERR_NAME_NOT_RESOLVED (that's because I am working with internal servers)

Second commit is not working (last one):
Uncaught Error: [$injector:modulerr] Failed to instantiate module np due to:
Error: [$injector:modulerr] Failed to instantiate module ngCookies due to:
Error: [$injector:nomod] Module 'ngCookies' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

The diff between the 2 is the iframe upgrade.
I hope this helps, I can give you more details next week.
Thanks for looking into this.

**Comment by davidjbradshaw** [comment]
That doesn't look related to this project to me.

**Comment by ddtxra** [comment]
hum strange because things work when I do 

> bower install iframe-resizer#3.2.0 --save

but stop working when I do:

> bower install iframe-resizer#3.2.1 --save

I am not a JavaScript ninja but I will investigate and I will keep you posted.
Cheers and thanks for your time

**Comment by davidjbradshaw** [comment]
Ok closing for now, but let me know if you find anything more.

**Comment by ddtxra** [comment]
Ok found out the problem.

The bower.json decribes 2 main files:  iframeResizer.contentWindow.js and iframeResizer.js.

On the bower documentation they say to use only one per filetype (http://bower.io/docs/creating-packages/)

Brunch was taking the 2 files and therefore there was a problem with the iframeResizer.contentWindow.js file (this file shouldn't be included)...

In any case this problem was not occurring before 3.2.0, so I investigated the cause. The problem seems related to this commit: https://github.com/davidjbradshaw/iframe-resizer/commit/19a04aa4b75b739c934318ef05f57d56b7640da1#diff-002d9f87a896b32fd1a9beb67dc6cbdc

at the end of  iframeResizer.contentWindow.js 

```
	// TEST CODE START //
	//Create test hooks
	function mockMsgListener(msgObject){
		receiver(msgObject);
		return win;
	}
	win={};
	removeEventListener(window, 'message', receiver);
	define([], function() {return mockMsgListener;});
	// TEST CODE END //
```

Looks like there is some test code executed and the function "define(....)" is not defined... Is this supposed to be like this?

Let me know if you plan to change the bower.json to describe only one main file (otherwise I will put a special case for my vendor.js) 
I don't know if there is a solution for this, but maybe the solution is to have 2 bower projects.

**Comment by davidjbradshaw** [comment]
Sorry, missed this post whilst on holiday.
