### ISSUE TITLE
Error:Cannot call method 'extend' of undefined 

### ISSUE THREAD

**Issue by SFPink** [davidjbradshaw/iframe-resizer#26]
Hello,

I've been searching for something like this for a while. 

Have just implemented it and am throw this error in the console:

Cannot call method 'extend' of undefined 

Using asp.net, jQuery 1.9.1..

I think my iFrame cant be found, I'll update this shortly

**Comment by carol-braileanu** [comment]
Hello,

I have an asp.net page inside the iframe, and as you said, it breaks all events on postback. So after postback resizing doesn't work. How can I rebind all events after postback?

Thank you.
