### ISSUE TITLE
taggedElement - method proposition

### ISSUE THREAD

**Issue by LuizPanariello** [davidjbradshaw/iframe-resizer#261]
Hi, first of all awesome lib. I'm having problems trying to shrink the iFrame *horizontally* using iframeResizer. I tried all the methods for width and none worked, so I think i came up with a simple solution, but since no one tried it yet I don't know if you want to go that way.
I think that the taggedElement width should be the 'max' in your calculations, different from height, bodyOffset and  bodyScroll never shrinks, the width is converted to a margin in the body. So, we could easily get the width of biggest element or the one marked with a tag. Using left to fetch its position dons't seen right since the left point is the closest to 0, we should use the **width** of that element. 
Sorry if I cause any confusion.

**Comment by davidjbradshaw** [comment]
Your right it should be 'right' rather than 'left'. I will change that just as soon as I get a spare moment.

**Comment by davidjbradshaw** [comment]
#263
