### ISSUE TITLE
$('iframe').iFrameResize() throws error with no options argument

### ISSUE THREAD

**Issue by mslatt** [davidjbradshaw/iframe-resizer#265]
if no arguments, set options = {}

**Comment by davidjbradshaw** [comment]
What version are you using, that was fixed awhile back.

**Comment by sportsracer** [comment]
I'm also experiencing this with 3.2.0 and 3.3.3. The error I get is

> Uncaught TypeError: Cannot read property 'id' of undefined

Code snippet to reproduce:

    <script type="text/javascript" src="https://api.trustyou.com/static/3rdparty/iframe-resizer/js/iframeResizer.min.js"></script>
    <iframe src="https://api.trustyou.com/hotels/dc9dacd7-f476-4cd4-9f82-4ccc83ed7f86/tops_flops.html?key=698b8681-bb2d-4ad2-817e-64e6641e4f3d&iframe_resizer=true" allowtransparency="true" frameborder="0" width="100%" ></iframe>
    <script type="text/javascript">iFrameResize();</script>

**Comment by davidjbradshaw** [comment]
Thanks I'll take a look.
