### ISSUE TITLE
Dynamicaly Added/Removed iFrames

### ISSUE THREAD

**Issue by ace007** [davidjbradshaw/iframe-resizer#266]
Hi,

I am dynamically creating my iframes on the page, when a user clicks on something.
Currently I am just calling the iFrameResize method each time I add a new one.
Also when I use the iFrameResizer.close method on an iframe the array returned by iFrameResize still contains a reference to the (now removed) iframe. I now manually set the slot in the array to 'undefined'.

1) Is this a problem calling iFrameResize multiple times on a page ?
2) Would it be possible/desirable for the library to use the MutationObserver function to spot the iframe add/remove and adjust accordingly ?
3) Could the library adjust the returned array, when an iframe is added/removed ?

**Comment by davidjbradshaw** [comment]
Their is no issue with calling it more than once, it will ignore iFrames that are already setup. The returned array of iFrames only contains ones that where looked at during that call. If it's return more than you want then you need to uses the second param to limit the scope of the call. If your creating iFrames in JS, then you can just pass the iFrame directly into iFrameResize.
