### ISSUE TITLE
Unable to link to anchor within iFrame

### ISSUE THREAD

**Issue by serres2** [davidjbradshaw/iframe-resizer#268]
I've been working with your iFrame-resizer and the thing is quite powerful.

All of the documentation I have read includes the ability to link to an anchor within the iFrame itself from an outside domain.

My goal is to link from anywhere to the parent domain and call an anchor within the iFrame. 

An example, I would send a user a link like www.parentdomain.com/index.html#test to access the anchor named "test" residing at www.childdomain.com/#test that has been iFramed into www.parentdomain.com.

Could you provide an example of how this would work or some insight as to how I can use your tool to accomplish this?

**Comment by davidjbradshaw** [comment]
Currently you can only call an anchor from the parent to the child via JS and it doesn't work with nested iFrames.

If your wanting to do it on page load, then you have a couple of options. Although please note I've not tested any of this code.

The first one should send the hash to every iFrame on the page.

	iFrameResize({
		initCallback:function(iframe){
			iframe.iFrameResizer.moveToAnchor(location.hash);
		}
	});

The second one just works with the first iFrame on the page.

	var iframe = iFrameResize()[0];
	iframe.iFrameResizer.moveToAnchor(location.hash);

This version could then be extend to work on links on the page with something like this.

	$('[a[href^=#]').on('click',function(){
		iframe.iFrameResizer.moveToAnchor(this.href);
	});

Let me know if it works and I'll think about adding something to the docs.

**Comment by serres2** [comment]
I have tried all three with no luck -- would this code go into the parent or child page and in the head, body, or bottom?

An example can be found at http://www.baxterauto.com/spec.htm where I have iFramed in http://performanceautoblog.com/specials/baxterauto/.

The goal is to have a user access an anchor (http://performanceautoblog.com/specials/baxterauto/#test) through http://www.baxterauto.com.

**Comment by davidjbradshaw** [comment]
Bottom of the parent page.
