### ISSUE TITLE
Multiple iframe resizers on parent page

### ISSUE THREAD

**Issue by SeanZicari** [davidjbradshaw/iframe-resizer#269]
Greetings,

I work for a company that provides social media widgets. Our content loads inside an iframe on our client websites, and we use iframe resizer to help manage the iframe during its lifetime on the page. The problem we just ran into is that some clients are also using iframe resizer, and it's a tossup whether their version or ours will load first and handle messages from the iframe.

Is this something you've run into before, and is there anything low-maintenance we can do to address this? Anything like namespacing our iframe resizer and having the contentwindow in our iframe target that instead of just any listening iframe resizer? I didn't see any parameters in the configuration options for doing such a thing, and that was just the first idea that came to mind.

I wanted to ensure there wasn't a better handle to handle this situation before diving in too deeply myself.

Thanks!
Sean

**Comment by davidjbradshaw** [comment]
In theory, both versions should receive the message, but only the one that has the iFrame registered with it should process it. The other one should just ignore it. If you or your client is running a version prior to v2.8.6 then you'll likely run into some issues, as this deconflicting is relatively new feature.

**Comment by davidjbradshaw** [comment]
My suggestion would be to get your client to upgrade to either 2.8.10 or 3.4.0 and try again. I'd be interested to know the outcome either way, as this is not something I've really looked into much.

**Comment by SeanZicari** [comment]
We'll upgrade our instance first and see how things work out. Though I'm curious how the contentwindow code registers with an iframe resizer instance in the first place. Does it prefer the same version, or is there some other logic?

**Comment by davidjbradshaw** [comment]
The message format is the same all the way back to version one. In cases where it doesn't get a value for a newer option, it just inserts the default value.

**Comment by davidjbradshaw** [comment]
The other option in your case is to change the value for `msgId` in both JS files. This will completely deconflict things for you, but at the expense of creating your own fork of the project.

**Comment by SeanZicari** [comment]
That sounds promising - we're giving that a try now. 

Sounds also like it would be a handy feature. Is that something you've considered doing? Exposing the message ID as a configuration option for the iframe resizer, and maybe looking for a certain property on the window object for the contentwindow? I'd be happy to put together a pull request for that if you think there's value outside of our use case.

**Comment by SeanZicari** [comment]
So we changed `msgId` in both iframe resizer and contentwindow, but we're still getting an error:

![](https://s3.amazonaws.com/uploads.hipchat.com/194774/1383619/YOiv6yoIGMxIECR/upload.png)

**Comment by davidjbradshaw** [comment]
That's not because you have two copies on the page. Looks like you've redefined `document` somewhere. This is the code that error relates to, it's in the first function that runs when you make the call, and just looks for iFrames on the page.

```js
Array.prototype.forEach.call(
	document.querySelectorAll( target || 'iframe' ),
	init.bind(undefined, options)
);
```

**Comment by SeanZicari** [comment]
The client is using a service called murm that also has the iframe resizer embedded. Their JS file can be found here:

https://www.murm.io/sdk/murm.js

If you look on line 513, you'll see the same function you linked to, except it looks like this:

```js
        return function iFrameResizeF(options,selecter){
            processOptions(options);
            Array.prototype.forEach.call( document.querySelectorAll( selecter || 'iframe' ), init );
        };
```

So there's a selecter [sic] argument that is being passed in as the iframe HTMLElement itself, as opposed to a string CSS selector. It seems like your original advice to have the client update their iframe resizer instance is the best option, but I was surprised to see that the function that's breaking is within the iframe resizer. Can you help me understand what's going on with this? What is selecter originally intended to be, and how could it receive an iframe HTMLElement directly instead of a CSS selector string?

**Comment by davidjbradshaw** [comment]
Looks like they have a very old version. The full function in the latest release is.

```js
return function iFrameResizeF(options,target){
	iFrames = []; //Only return iFrames past in on this call

	switch (typeof(target)){
	case 'undefined':
	case 'string':
		Array.prototype.forEach.call(
			document.querySelectorAll( target || 'iframe' ),
			init.bind(undefined, options)
		);
		break;
	case 'object':
		init(options,target);
		break;
	default:
		throw new TypeError('Unexpected data type ('+typeof(target)+')');
	}

	return iFrames;
};
```

This allows you to pass either a dom element, or a css selector to choose which iFrames to apply this code to. The older version, only supported CSS selectors. Looks like they are using an old version, but reading the latest documentation!

**Comment by davidjbradshaw** [comment]
Looks like they have v2.6.0.

**Comment by SeanZicari** [comment]
Your advice is right on. We created a local copy of the client's web page and updated the third party's code to the latest iframe resizer, and the problem went away without any further modifications. So, we're reaching out to the third party and also our client to get this issue fixed the right way (without workarounds).

Thanks again for a great library!
