### ISSUE TITLE
Issue with height calculation

### ISSUE THREAD

**Issue by archanasharma14061986** [davidjbradshaw/iframe-resizer#270]
hello,
When i try to use resizedCallback method to get  the height of messageData, the height is a bit more than the desired height (when compare to the most child iframe height). Need to know whether it is having some height margins, or ideally it should take the exact same height as of the body of the child iframe. I have tried with all the possible heightcalculationmethod but its not happening. 

Also to add, the most child iframe only appears on the click of the content present in the parent iframe.
Please suggest some way out.
![height_issue](https://cloud.githubusercontent.com/assets/14237491/10341327/2a3002f2-6d0c-11e5-957c-9df63c57e923.png)
to get the exact height.

Thanks.

**Comment by davidjbradshaw** [comment]
The problem is going to be with your CSS in the iFrame, does the outer most element have a bottom margin on it?
