### ISSUE TITLE
Not re-sizing with a dropdown

### ISSUE THREAD

**Issue by steelers4582** [davidjbradshaw/iframe-resizer#272]
We have a page which creates a Bootstrap ul/li dropdown list.  When the page loads I see the dropdown but when it it keyed, I see the dropdown content which is larger that the iframe to disapear at the bottom since the iframe does not resize.  What can we do for it to resize?  Thanks

**Comment by davidjbradshaw** [comment]
Try using different hightCalculationMethods, I expect the list goes outside the body tag, which the default method uses to calculate the size.

**Comment by steelers4582** [comment]
Thanks, I got it to work now using lowestElement when needed
