### ISSUE TITLE
Issue with iframe width not scaling on iPhone

### ISSUE THREAD

**Issue by nikokauranen** [davidjbradshaw/iframe-resizer#273]
Hi there,

Ran into an issue where the iframe width won't scale on the iPhone (height works though), there's a test case here: http://bit.ly/1GJNHuM 

The first iframe is the one not working, the second iframe includes a page from the same domain as where the iframe resides, the scaling there works as expected across the board.

What could be causing this problem?

**Comment by davidjbradshaw** [comment]
Could you please put some simple content in those iFrames.

**Comment by nikokauranen** [comment]
Just checking, you mean something simpler than the content they now contain or are they empty for you?

**Comment by davidjbradshaw** [comment]
Yes just enough hamlet to recreate the issue.

**Comment by nikokauranen** [comment]
Sorry for the late reply, turns out the site that was in the iFrame had a point where the horizontal scrollbar became visible, this also became the exact width of the iFrame on Safari/iPhone. Now that the "iFramed" site is corrected and responsive everything works as expected. Thanks for a great library!

**Comment by davidjbradshaw** [comment]
Thanks for the update.
