### ISSUE TITLE
can't access the parentIframe

### ISSUE THREAD

**Issue by petrKoukal** [davidjbradshaw/iframe-resizer#274]
I updated to the newest version, and since then I have troubles accessing the `parentIframe`

I tried all of these: 
```
parentIframe
window.parentIframe
iFrameResizer
window.iframeResizer
iframe.iFrameResizer
```

both from the iFrame itselft and the page hosting the iframe, but with no success. I always get `undefined`. I was able to do so with the previous 2.4.? version. Is it a bug or am I just terribly missing something?

(what I try to achieve is to manually trigger iframe resize)

**Comment by davidjbradshaw** [comment]
parentIFrame

**Comment by petrKoukal** [comment]
sorry, it's what I meant, `parentIFrame`, just mistyped it. I don't want to bother, the resizer is really cool and works great, it would just be really nice to be able to leverage all it's strength.

sounds I miss something really obvious then
