### ISSUE TITLE
"float: right" causes invisibility after initialisation (in chrome and opera)

### ISSUE THREAD

**Issue by sweiguny** [davidjbradshaw/iframe-resizer#276]
Hi,

you've created a very helpful tool :)

but, i have an iframe floated to the right and after initialisation the iframe is invisible, but not due to a css directive or the like. with css inspectio i can see, that the resizing worked, but the iframe is simply invisible. if i omit the "float: right" directive, then the the iframe is properly displayed.

(well, a handy workaround is to use a wrapper over the iframe and give it "text-align: right")

i tested and noticed this bad behavior in chrome and opera.
firefox does not have this problem.

bye

**Comment by davidjbradshaw** [comment]
Can you please add a link to a simple test case.
