### ISSUE TITLE
Listen on parent scroll event

### ISSUE THREAD

**Issue by 4ants** [davidjbradshaw/iframe-resizer#278]
Is it possible to listen on parent scroll event in iframe page?

This is what I use now, but seems hacky and waste of resources:

```javascript
if ('parentIFrame' in window) {
	parentWindow = window.parentIFrame;
	scrollTopLast = 0;
	setInterval(function () {
			parentWindow.getPageInfo(function (parentData) {
					scrollTop = parentData.scrollTop;
					if (scrollTop !== scrollTopLast) {
							animate();
					}
			});
	}, animateSpeed);
}
```

Thank you.

**Comment by davidjbradshaw** [comment]
Not currently, but it's an interesting point.

**Comment by davidjbradshaw** [comment]
Have a try of the dev branch. The callback now gets recalled when the parent is scrolled or resized.

To disable pass `false` to `getPageInfo()`

**Comment by davidjbradshaw** [comment]
Let me know if this works for you.

**Comment by 4ants** [comment]
It works.
Tnx. :)

**Comment by shreeramk** [comment]
Hello,
I'm inserting an iframe into another page and adding the getPageInfo callback in iframe page. Is that the correct procedure? FYI it didn't worked even after that.
Do you mind sharing the a sample code for getPageInfo usage?
