### ISSUE TITLE
Need correct height of iframe on load

### ISSUE THREAD

**Issue by archanasharma14061986** [davidjbradshaw/iframe-resizer#279]
Height of messagedata is being calculated only on resizedCallback function. Is there any way to get the proper height on the very first of iframe load as well.Please suggest some way out.
Thanks,

**Comment by davidjbradshaw** [comment]
ResizedCallback also gets called the first time the iframe is sized.

**Comment by archanasharma14061986** [comment]
For the very first time of iframe load, the messageData.height is not accurate. I am using default "HeightCalculationMethod". Once i click anywhere on iframe or resize it, it picks up the correct height. Could you let me know the reason.

**Comment by davidjbradshaw** [comment]
That’s a new one on me. Can you share a link to a simple test case please.

**Comment by archanasharma14061986** [comment]
I am attaching the screenshots from your example itself. may be it will help you to understand better.
![correct_height](https://cloud.githubusercontent.com/assets/14237491/10732295/50f12e40-7bf1-11e5-967a-0e9e9514df2a.png)
![incorrect_height](https://cloud.githubusercontent.com/assets/14237491/10732296/5101e122-7bf1-11e5-828f-75ec1c893ef9.png)

**Comment by archanasharma14061986** [comment]
I tried using resizeFrom : 'child' and its somehow working..Not sure its 100% solution for all scenarios.

**Comment by davidjbradshaw** [comment]
That's very strange, it gets the size right when I run that page. Can you post the log output here please.

**Comment by davidjbradshaw** [comment]
Can you please try the latest dev branch build.

**Comment by davidjbradshaw** [comment]
Did this fix it for you?

**Comment by davidjbradshaw** [comment]
I guess it did then.
