### ISSUE TITLE
Iframe "increases" to minimum height

### ISSUE THREAD

**Issue by Baldoius** [davidjbradshaw/iframe-resizer#280]
First, thank you very much for your nice script! It's working very nice, but sometimes with a problem:

Normally,
1. I click on a link in the iframe
2. Iframe get resized

But sometimes (~ every 10th click)the frame resizes to the min-height and resizes only to the "right" height when you click in the frame..

**Comment by davidjbradshaw** [comment]
If you provide a link to a simple test case I'll take a look.

**Comment by Baldoius** [comment]
I've sent you the link :)

**Comment by davidjbradshaw** [comment]
Can you please try the latest dev branch build.

**Comment by Baldoius** [comment]
I'll try it later today and give a feedback

Am 28.10.2015 um 23:26 schrieb David J. Bradshaw:

**Comment by Baldoius** [comment]
Thanks! The fix is working!

**Comment by davidjbradshaw** [comment]
So did it fix it?

**Comment by Baldoius** [comment]
I have to correct my answer. The problem is still appearing

![Still appearing](http://i.snag.gy/hKJlN.jpg)

**Comment by davidjbradshaw** [comment]
Your loading both iframeResizer.contentWindow.js and iframeResizer.contentWindow.min.js into your iframe and that is causing some weirdness. You only need one of them!!!

**Comment by Baldoius** [comment]
It's working now. I'll check back tomorrow and close if it's working 
stable ;)
Thanks!

Am 30.10.2015 um 18:23 schrieb David J. Bradshaw:

**Comment by davidjbradshaw** [comment]
Guessing it worked then.
