### ISSUE TITLE
Getting "target origin does not match window's origin" error in Chrome only

### ISSUE THREAD

**Issue by beakid** [davidjbradshaw/iframe-resizer#282]
Not sure if something changed recently, but suddenly my solution doesn't work in Chrome. Works in Firefox and IE though.

http://www.beakid.se/Iframe.html

Try for yourselves and see the errors in the console. Doesn't matter if I specify checkOrigin or targetOrigin.

(Using Chrome Version 46.0.2490.80 m on Windows 8.1 if it matters)

**Comment by davidjbradshaw** [comment]
This is a bug in the latest version of Chrome. The error is thrown when you send a postMessage to a frame before it is loaded. It is the frame that throws the error so their is nothing I can do to trap it.

However, it has no impact on the script running, as postMessage is sent again when the `onload` event fires on the iframe. It works this way as you can not test a cross domain iFrame to see if it has loaded.

In your link the content of the iFrame is 404ed.

**Comment by beakid** [comment]
It does have impact though, look now (updated iframe.html with correct url, sigh).

Compare with how the videos look for example: http://www.enklaelbolaget.se/boymachine-tv4 (the url inside the iframe)

**Comment by davidjbradshaw** [comment]
```
Uncaught SecurityError: Failed to read the 'frame' property from 'Window': Blocked a frame with origin "http://www.enklaelbolaget.se" from accessing a frame with origin "http://www.beakid.se". Protocols, domains, and ports must match.
```

Is thrown by line 1957 by video.js. Not iframe-resizer.

**Comment by beakid** [comment]
You're right.

For anyone coming here with the same problem, here's how I fixed video.js to make it work inside an iframe. I changed the function hasAutomationEqualityBug into this:

```
var hasAutomationEqualityBug = (function () {
    /* global window */
    var _window = window;
    if (window.parent) {
        _window = window.parent;
    }
	if (typeof _window === 'undefined') { return false; }
	for (var k in _window) {
		if (!blacklistedKeys['$' + k] && has.call(_window, k) && _window[k] !== null && typeof _window[k] === 'object') {
			try {
			    equalsConstructorPrototype(_window[k]);
			} catch (e) {
				return true;
			}
		}
	}
	return false;
}());
```
