### ISSUE TITLE
iFrame loads with too much height, then readjusts with mouse click or hover

### ISSUE THREAD

**Issue by bmounteer** [davidjbradshaw/iframe-resizer#283]
When my iframe loads it looks like this: 
![iframebefore](https://cloud.githubusercontent.com/assets/814538/10799678/01d74592-7d7c-11e5-94b8-bc870030be18.png)

With this log code: 
![screenshot 2015-10-28 13 56 59](https://cloud.githubusercontent.com/assets/814538/10799713/3d41d570-7d7c-11e5-8ac0-c02e1d2d4b19.png)

After you hover your mouse over the iframe or click in the area of the iframe, then it sizes it correctly:
![iframeafter](https://cloud.githubusercontent.com/assets/814538/10799732/59246cf8-7d7c-11e5-90d7-c9dc1ffc979d.png)

With this log code:
![screenshot 2015-10-28 13 57 19](https://cloud.githubusercontent.com/assets/814538/10799741/6542d646-7d7c-11e5-8e33-03abbd36fc6a.png)

How do you get it to detect the correct iframe size when the page loads?

**Comment by davidjbradshaw** [comment]
Can you please try the latest dev branch build.

**Comment by davidjbradshaw** [comment]
Did this fix it for you?

**Comment by bmounteer** [comment]
Thanks for the feedback David. No, the issue is still occurring. We were able to hack it by calling this function when the modal is opened:

```_forceIframeResize: function () {
        var iframe = this._element.find('.iframe-resizer').get(0);

        // brute force
        var prevHeight = $(iframe).height();
        var interval = setInterval(function () {
          // if height has changed, call it good
          var nextHeight = $(iframe).height();
          if (nextHeight !== prevHeight) {
            clearInterval(interval);
            return;
          }

          iframe.iFrameResizer.resize();
        }, 10);

        // give up after a second
        setTimeout(function () {
          clearInterval(interval);
        }, 1000);
      }```

**Comment by davidjbradshaw** [comment]
Would you be able to make a simple test case for me to look at. 

Also what browsers/platforms is this an issue in?

**Comment by bmounteer** [comment]
You can see it happening on this page: https://www.lendio.com/bp/signup

All tests were done on OS X El Capitan. Chrome and safari has the height issue we are talking about. Firefox occasionally will not even show the iframe. If you go that page and it looks normal, just refresh it a few times and you'll see it.

**Comment by davidjbradshaw** [comment]
Any idea how many times that function of yours gets called?

Also I'd suggest changing the setTimeout from 10 to 16 as their is no point checking more than once every screen refresh.

**Comment by davidjbradshaw** [comment]
Your link looks very different to you screen shot.

**Comment by davidjbradshaw** [comment]
Just looking at your page and it has v3.0.0 on it, current is v3.5.0. Can you please download the version on the dev branch and try that.

https://github.com/davidjbradshaw/iframe-resizer/blob/dev/js/iframeResizer.contentWindow.js

**Comment by bmounteer** [comment]
It appears that my function is only being called once to resize the iframe. 

I have updated the script to the current version. The bug is still occurring without my timeout in place. It's strange because I use the iframe resizer for this widget in a few other locations on the site and I don't have this issue. I think that its must be a timing issue with the javascript being loaded in certain instances. Once we deploy this live with our timeout hack in place, I can create an example page for you using the same page I took a screenshot of without the hack if you'd like to look at it. That should happen today.

**Comment by davidjbradshaw** [comment]
I’d like to know if the unreleased version in the dev branch fixes this for
you. I added a timeout into the main code to push the init size check to
the bottom of the JS event loop, to prevent any race condition with the
browser render.  Which I think is the most likely cause of your issue.

On Mon, Nov 2, 2015 at 2:31 PM, Bill Mounteer <notifications@github.com>
wrote:

> It appears that my function is only being called once to resize the
> iframe.
>
> I have updated the script to the current version. The bug is still
> occurring without my timeout in place. It's strange because I use the
> iframe resizer for this widget in a few other locations on the site and I
> don't have this issue. I think that its must be a timing issue with the
> javascript being loaded in certain instances. Once we deploy this live with
> our timeout hack in place, I can create an example page for you using the
> same page I took a screenshot of without the hack if you'd like to look at
> it. That should happen today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/283#issuecomment-153031897>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by bmounteer** [comment]
I put the unreleased version in our site and added a comment to distinguish its loading the new code. In these two screenshots you can see it didn't fix the issue. 

![screenshot 2015-11-02 08 55 22](https://cloud.githubusercontent.com/assets/814538/10884900/1c4502ee-8140-11e5-9277-327396642d7d.png)
![screenshot 2015-11-02 08 58 13](https://cloud.githubusercontent.com/assets/814538/10884901/1c472e48-8140-11e5-9aab-20d377246468.png)

**Comment by davidjbradshaw** [comment]
I'm at a bit of a loss. If you can build a simple test case then I'd like to take a look.

**Comment by jehoshua02** [comment]
FWIW: On http://lendio.com/bp/signup, I use an interval like this:

```
    $(function () {
      var $element = $('#widget-iframe');

      $element.iFrameResize({
        log: true
      });

      var interval = setInterval(function () {
        console.log('FORCE RESIZE');
        $element.get(0).iFrameResizer.resize();
      }, 100);

      setTimeout(function () {
        clearInterval(interval);
      }, 1000);
    });
```

It works for us (obviously in a less than optimal way). But I noticed something interesting and possibly relevant:

<img width="1367" alt="screen shot 2015-11-03 at 10 44 28 am" src="https://cloud.githubusercontent.com/assets/625814/10916313/205d99ee-8218-11e5-9f47-8ea6a83606b0.png">

You'll notice that at one point it sets the iframe height to `509`. Then it sets it again to `124`.

And when I don't use the interval, you can see that the iframe height is being set to `509` but that's it. It never sets the height again until there is some event in the iframe page (hover, focus, mouse, etc):

<img width="1357" alt="screen shot 2015-11-03 at 10 47 56 am" src="https://cloud.githubusercontent.com/assets/625814/10916374/7660758c-8218-11e5-8a0b-b719f946d2bd.png">

__My Hunch__: There is something in our iframe that is loading late, after iframe-resizer does it's thing, like some styles or scripts, that affect the total height of the document in some way but without triggering an event that iframe-resizer is listening or can listen to.

I think the next step, for me at least, is to prove or disprove my hunch by tinkering with a simplified example.

**Comment by davidjbradshaw** [comment]
You hunch sounds worth investigating. Although their are very few things that can cause CSS to change with out triggering mutationObserver.  Do you late load a CSS file?

**Comment by davidjbradshaw** [comment]
Just had an idea. I think adding readystatechange to the list of watched events should fix this. 

https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange

**Comment by davidjbradshaw** [comment]
Can you please give the dev branch another go. I'm hopefully this will fix it.
