### ISSUE TITLE
Console log inside window.content

### ISSUE THREAD

**Issue by LuizPanariello** [davidjbradshaw/iframe-resizer#284]
![screen shot 2015-10-29 at 4 11 13 pm](https://cloud.githubusercontent.com/assets/5797527/10827831/17bd9488-7e58-11e5-94cd-7cbf11907aa5.png)

When iframeresizer don't find a tagged element it prints a console log warn as seem as the image above. I think this should be turned off when iFrameResizer is set as "({log:false});". Not a big problem but I just wanted to point it up as an minor update.

**Comment by davidjbradshaw** [comment]
In this case it stops the iFrame resizing, so think it needs to be shown. 

That said maybe it should fall back to bodyOffset in this case.
