### ISSUE TITLE
Is tolerance parameter being used?

### ISSUE THREAD

**Issue by ranierimazili** [davidjbradshaw/iframe-resizer#285]
Hello,
I'm using your library and I'm having the flicker behavior because I'm using bodyScroll calculation method (I really need to use it).

When any field on the iframe page is selected, there's an visual effect that causes the flicker behavior... the variation of height size is low (about 30px) and I would like to ignore the resize using tolence as parameter, but it's not working.

I decided to check your code (iframeResize.js) and could see (or couldn't find) that you're not using tolerance to decide if you will resize the iframe or not.

Is it a bug or am I wrong?

**Comment by davidjbradshaw** [comment]
It's in the iframe.contentWindow.js file.

```js
		function isSizeChangeDetected(){
			function checkTolarance(a,b){
				var retVal = Math.abs(a-b) <= tolerance;
				return !retVal;
			}

			currentHeight = (undefined !== customHeight)  ? customHeight : getHeight[heightCalcMode]();
			currentWidth  = (undefined !== customWidth )  ? customWidth  : getWidth[widthCalcMode]();

			return	checkTolarance(height,currentHeight) || (calculateWidth && checkTolarance(width,currentWidth));
		}
```
