### ISSUE TITLE
[Suggestion] Add to jsDelivr (CDN)

### ISSUE THREAD

**Issue by Rycochet** [davidjbradshaw/iframe-resizer#287]
As in the title - instructions are here: https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

It auto-updates on GitHub changes, and would make it easier to include in projects :-)

**Comment by davidjbradshaw** [comment]
A cdn version can be found at: https://cdnjs.com/libraries/iframe-resizer

Feel free to add this project on JSdeliver, if you would prefer it there. You don't need access to this repro to do it.

**Comment by Rycochet** [comment]
Looks like someone has added it since I posted this (was just about to add it myself) - awesome to whomever did it :-)

**Comment by davidjbradshaw** [comment]
Cool. Thanks for the update.
