### ISSUE TITLE
Preventing "flicker" behavior with tolerance parameter

### ISSUE THREAD

**Issue by ranierimazili** [davidjbradshaw/iframe-resizer#288]
Hi,

some days ago I opened an issue here, where I explained my problem with flicker behavior when using bodyScroll calculation method (https://github.com/davidjbradshaw/iframe-resizer/issues/285).

I have found a solution, but I had to change your code and I don't know if this code can be applied to all situations.

In the iframeResizer.contentWindow.js file, you are forcing the resetIFrame if using bodyScroll when any height or width has changed... but you're not considering the tolerance value for this situation...
So, to "fix" this behavior to my case I have changed your checkDownSizing method on this way.

**From** 
```javascript
function checkDownSizing(){
	if (isForceResizableEvent() && isForceResizableCalcMode()){
		resetIFrame(triggerEventDesc);
	} else if (!(triggerEvent in {'interval':1})){
		logIgnored();
	}
}
```
**To**
```javascript
//Added isSizeChangeDetected() inside if clause
function checkDownSizing(){
	if (isForceResizableEvent() && isForceResizableCalcMode() && isSizeChangeDetected()){
		resetIFrame(triggerEventDesc);
	} else if (!(triggerEvent in {'interval':1})){
		logIgnored();
	}
}
```

Take a look if this can be added to your official code.
Thanks

**Comment by davidjbradshaw** [comment]
The reason it doesn't check the size here, is because it can only detect upward sizing. We do the reset to force it to workout if it has downsized. It doesn't matter if the resize is within the tolerance setting or not.

I expect with your use case you would be better of using 'grow'
