### ISSUE TITLE
iFrame resizer: Uncaught Error: Multiple anonymous defines

### ISSUE THREAD

**Issue by laeeqwtb** [davidjbradshaw/iframe-resizer#289]
Hi,

When my page load, the iFrame load with scroll. Below is loaded iFrame with error log :

![image](https://cloud.githubusercontent.com/assets/2102705/10939137/4e31c7f6-8325-11e5-910d-fbfb2b75703c.png)

It's not re-sizing iFrame to remove scroll as it return JavaScript error "iFrameResize is not defined"  and "Uncaught Error: Multiple anonymous defines" that you can see in error log code in above screen.

I have tried to debug JavaScript error and find the error return due to "iframeResizer.min.js" conflict with a JavaScript "duel.js" used in HEAD tag in this page. As this page created with Godaddy website builder, so the "duel.js" used in each page and return no JavaScript error. But when "iframeResizer.min.js"  used on this page to load iFrame re-size. It started returning JavaScript error.

I have created a sample page and removed "duel.js" from page HEAD, its started working fine by re-size iFrame without any JavaScript error.

So it seems the issue is with "duel.js" that return JavaScript error "Uncaught Error: Multiple anonymous defines" when we use plugin file "iframeResizer.min.js". 

Please look into this issue to fix JavaScript error and load iFrame without scroll.  

Link using duel.js: http://beta3.websitetoolbox.com/iframetest.html
Link without using duel.js: http://beta3.websitetoolbox.com/iframetest1.html

**Comment by davidjbradshaw** [comment]
I agree this is an issue with Dual.js, as it seems to stop other scripts loading. You will need to at fixing that. This does not seem to be an issue with iFrame-Resizer.
