### ISSUE TITLE
selective listeners

### ISSUE THREAD

**Issue by yumyo** [davidjbradshaw/iframe-resizer#290]
Hello, 
I'm not sure if I'm missing some way to achieve that but it will be very userful to have the ability to selectively enable/disable the various resize listener, especially click and dom changes in the iframe content.

**Comment by davidjbradshaw** [comment]
Yep something on the list for the future.

In the meantime setting interval to a negative number disables the DOM observer. Pick a large negative value to stop the interval check running as well.

**Comment by yumyo** [comment]
Thank you David. In the meanwhile, to achive it manually, it is just a matter of "selectively" commenting the `manageTriggerEvent` lines of the `manageEventListeners` function inside iframeResizer.contentWindow.js ?

**Comment by davidjbradshaw** [comment]
Yep you can do that.

**Comment by yumyo** [comment]
Great, thanks.

**Comment by davidjbradshaw** [comment]
These will be removed in V5
