### ISSUE TITLE
IFrame Resizer does not work when iframe ids contain double colons

### ISSUE THREAD

**Issue by ChristianAlbrecht** [davidjbradshaw/iframe-resizer#291]
When iframes are present, where an id contains a double colon, Iframe Resizer does not work anymore, because the check in function isInitMsg() (line 1012 in iframeResizer.contentWindows.js) will fail.

**Comment by davidjbradshaw** [comment]
I expect it will break in a few other places as well. The only fix I can think of is to replace the colons with spaces before sending the message and then converting spaces to colons when the parent page receives a message back from the iFrame. 

If you want to do that, then your welcome to submit a PR.

Can not begin to workout why you would put a colon in an ID attribute.
