### ISSUE TITLE
two-finger-scrolling not working in OSX Safari 9 when iframe is in scrollable container

### ISSUE THREAD

**Issue by sch4lly** [davidjbradshaw/iframe-resizer#293]
I have a resized iframe in a fixed-height div with overflow:auto. Scrolling works great in Chrome (mousewheel and two-finger gesture) but not in Safari (only mousewheel works). I have created a little demo to showcase this:

http://sch4lly.github.io/iframeresize/index.html

Any idea how i can fix this?

**Comment by davidjbradshaw** [comment]
Sorry no idea. If you find a fix please can you up date this ticket.

**Comment by davidjbradshaw** [comment]
Thinking about this why not just set the iFrame to be the height of the DIV container?

**Comment by Rycochet** [comment]
It's an iOS issue - (hopefully) you only need to add ```-webkit-overflow-scrolling: touch;``` on the css next to the overflow :-)

**Comment by sch4lly** [comment]
Unfortunately, this does not work. As i said, this happens under OSX, not iOS

**Comment by davidjbradshaw** [comment]
This looks like a Safari bug beyond the scope of this project.

**Comment by steezeburger** [comment]
@sch4lly hey I think I'm having the same issue, curious if you ever found a fix? For me, scrolling up works, but not scrolling down. Unless you scroll up a bit first then try to quickly scroll down, haha. Super wonky, Safari only. Chrome/FF work great.
