### ISSUE TITLE
when I use jquery UI effects the height behavior was very strange

### ISSUE THREAD

**Issue by psr1410** [davidjbradshaw/iframe-resizer#296]
I had an iframe in side a PopUp which is having minimize icon. When it was minimized there is a maximize icon to display that PopUp. By default It was maximized and displayed until user clicks on minimize icon everything working to be fine. When user clicks on minimize icon I need to hide the PopUp and need to show a maximize icon, here I'm using jquery UI effect to hide slowly with an duration of 1 sec. While Hiding the PopUp the height returning was very weird. 

Is any thing I'm missing while initializing the iframeResizer. I'm using the basic settings which were shown in the example.

OR 

Is there a way to stop and start the resizing observer when user clicks on minimize / maximize?

**Comment by psr1410** [comment]
Is anybody there to respond this issue?

**Comment by danballance** [comment]
You say you are using the basic settings. Could you share your actual
settings? That might make it easier to offer some advice.

**Comment by psr1410** [comment]
$('#iframe-container').iFrameResize({
                log                     : false,                  // Enable console logging
                inPageLinks             : true,
                interval                : 300,
                resizedCallback         : function(messageData){
                      contentHeight = parseInt(messageData.height);
                      //My height related modifications
               }
});

$(document).on("click",".minimize-icon", function(){
     $(".content-holder").hide(1000);
});

$(document).on("click",".maximize-icon", function(){
     $(".content-holder").show(500,'swing');
});

**Comment by davidjbradshaw** [comment]
You can force the iFrame to resize by doing this:

    document.getElementById('myIFrame').iframeResizer.resize();
