### ISSUE TITLE
IE8 - document.body is null

### ISSUE THREAD

**Issue by LuizPanariello** [davidjbradshaw/iframe-resizer#297]
if a "script" with iframeResize.contentWindow is being loaded inside the document "head" and not in the "body" the document.body is null. Maybe it should wait for window.onload to try to do the first resize.

**Comment by davidjbradshaw** [comment]
Was this only an issue in IE8? The code shouldn't get fired until document ready normally.

**Comment by davidjbradshaw** [comment]
Patch will be in v3.5.4
