### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by pixelpaulaus** [davidjbradshaw/iframe-resizer#299]
i have copied the examples and tried everything but i keep getting this error in the console and the iframe will not resize, any ideas?

Uncaught ReferenceError: define is not defined(anonymous function) 
@ sizer.js:1078(anonymous function) 
@ sizer.js:1082

size.js  is the iframeResizer.contentWindow.min.js file

**Comment by Pasha-fpa** [comment]
You should remove test code from the bottom of "iframeResizer.contentWindow.min.js"

**Comment by davidjbradshaw** [comment]
Use the version in the JS folder not SRC folder.
