### ISSUE TITLE
Conflict with babel browser script

### ISSUE THREAD

**Issue by PaulGrimshaw** [davidjbradshaw/iframe-resizer#300]
The plugin does not seem to work correctly when the content window has the babel browser script referenced:

<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>

When this script is referenced, iframe resizer throws up the following error:

Uncaught SecurityError: Failed to read the 'frame' property from 'Window': Blocked a frame with origin "http://xxx.com" from accessing a frame with origin "http://yyy.com". Protocols, domains, and ports must match.

**Comment by davidjbradshaw** [comment]
Can you make a simple test case?

**Comment by PaulGrimshaw** [comment]
Made a simple test case.

Source code is here: http://iframewindow.quick-tracks.com/babel-conflict-test.zip (some reason github won't let me upload).

http://iframewindow.quick-tracks.com can be used as a content window, and has the babel script referenced.

**Comment by PaulGrimshaw** [comment]
![image](https://cloud.githubusercontent.com/assets/4194874/11866653/556ada62-a4a4-11e5-84a1-3fb03339cdcc.png)

Problem seems to be on the above line in browser.js

**Comment by davidjbradshaw** [comment]
This looks like a bug in the es5-shim project.
