### ISSUE TITLE
The iframe does not resizes at all.

### ISSUE THREAD

**Issue by pavneet9** [davidjbradshaw/iframe-resizer#301]
I am not sure if this is an issue but the iframe is not resizing at all. I checked the parent file and it includes iframeResizer.contentWindow.js. Also on the page that display the iframe i have included the iframeResizer.js.

Here are the links to the pages that i am using

1. Page to be included in an iframe- http://testbackend.cloudapp.net/map.php?m_id=240
2. Sample page with iframe included- http://testbackend.cloudapp.net/testingiframe.html

I think the problem maybe that the content is generated through ajax and maybe that's why it is not working properly.

here is the iframe function i am using

iFrameResize({heightCalculationMethod: "lowestElement"}, "#kmaps-test-embed");</script>

Is the problem due to ajax content or some other issue.

**Comment by davidjbradshaw** [comment]
Try turning the log option on and have a look at the console.

**Comment by pavneet9** [comment]
I changed the code to this. But when i resize the windows nothing shows up in the console. Does this point in some way to a mistake i might be committing.

iFrameResize({log:"true",heightCalculationMethod: "lowestElement"}, "#kmaps-test-embed");

**Comment by davidjbradshaw** [comment]
Paste the log here.

On Wednesday, 16 December 2015, pavneet9 <notifications@github.com> wrote:

> I changed the code to this. But when i resize the windows nothing shows up
> in the console. Does this point in some way to a mistake i might be
> committing.
>
> iFrameResize({log:"true",heightCalculationMethod: "lowestElement"},
> "#kmaps-test-embed");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/301#issuecomment-165257824>
> .
>


-- 
Sent from my iPhone.

**Comment by pavneet9** [comment]
I checked the log again, it is empty. There are no messages being added to the console

**Comment by davidjbradshaw** [comment]
The iFrameResize is not being called.

**Comment by pavneet9** [comment]
can you give me some pointer on what i may be doing wrong .

Here is the code i am using


<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://testbackend.cloudapp.net/js/iframeResizer.min.js"></script>
<script type="text/javascript">
iFrameResize({log:"true",heightCalculationMethod: "lowestElement"}, "#kmaps-test-embed");

</script>
</head>
<body>
<iframe id="kmaps-test-embed"
src="http://testbackend.cloudapp.net/map.php?m_id=240" scrolling="no" frameborder="0"  width="80%"></iframe>
</body>
</html>

**Comment by davidjbradshaw** [comment]
The script needs to be after the iFrame.

**Comment by mannverma** [comment]
@davidjbradshaw [iFrameSizer][Host page: inside_content] [iFrame.onload] Sending msg to iframe[inside_content] (inside_content:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent:scroll) targetOrigin: *

Please find my logs above. as i am too get the iframe content via ajax.
please help.
