### ISSUE TITLE
Chrome: deviceorientation event is deprecated on insecure origins

### ISSUE THREAD

**Issue by datafunk** [davidjbradshaw/iframe-resizer#302]
Hi

Google Chrome is introducing new policy: *"Deprecating Powerful Features on Insecure Origins"* rendering the script ineffective on non HTTPS.

**See details in**
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**The actual console alert reads:**
The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by davidjbradshaw** [comment]
It's just a warning message and doesn't stop anything working.
