### ISSUE TITLE
IE8 throwing error "Object doesn't support this property or method"

### ISSUE THREAD

**Issue by regauser** [davidjbradshaw/iframe-resizer#303]
Hi

I am trying to update my implementation of iFrameResizer from v2.8.6 to v3.5.1.

I want to support IE8, and have noted that with v3 I need to include the IE8 polyfils file.

I am using jquery version 1.11.3, which is the latest version that supports IE8.

However, IE8 is throwing an error "Object doesn't support this property or method".

This is coming from something in iFrameResizer causing jQuery to call... document.removeEventListener( "DOMContentLoaded", completed, false )

I believe that IE8 doesn't have the document.removeEventListener method, and I can't see anything in the IE8 polyfils file that adds that method.

Is there something missing from the polyfils file? Or, can you see anything else that I have done wrong?

Here is an basic example, using v3.5.1, where you can see the error...

http://www.wavyd.com/tests/iframeresizerie8/3.5.1/

Note, the demo uses the source code version of jquery 1.11.3, so it's easier for you guys to see what is going on.

Thanks very much

David

**Comment by davidjbradshaw** [comment]
Oh just delete that, it’s never used.

On Fri, Dec 18, 2015 at 3:16 PM, regauser <notifications@github.com> wrote:

> Hi
>
> I am trying to update my implementation of iFrameResizer from v286 to v351
>
> I want to support IE8, and have noted that with v3 I need to include the
> IE8 polyfils file
>
> I am using jquery version 1113, which is the latest version that supports
> IE8
>
> However, IE8 is throwing an error "Object doesn't support this property or
> method"
>
> This is coming from something in iFrameResizer causing jQuery to call
> documentremoveEventListener( "DOMContentLoaded", completed, false )
>
> I believe that IE8 doesn't have the documentremoveEventListener method,
> and I can't see anything in the IE8 polyfils file that adds that method
>
> Is there something missing from the polyfils file? Or, can you see
> anything else that I have done wrong?
>
> Here is an basic example, using v351, where you can see the error
>
> http://wwwwavydcom/tests/iframeresizerie8/351/
>
> Note, the demo uses the source code version of jquery 1113, so it's easier
> for you guys to see what is going on
>
> Thanks very much
>
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/303>.
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek

**Comment by regauser** [comment]
Hi David

Thanks for your prompt reply.

Can you explain which bit I need to delete?

The line of code I detailed above is in jQuery, and I don't want to delete anything from there.

In which case were you telling me delete the ie8 polyfils file?

Or, more likely, were you telling me to delete some code from within the iFrameResizer script files? 

In which case could you indicate which parts and from which files? I can see several references to "removeEventListener " in both the host page and content page .js files, and unfortunately I'm not confident about what is safe to delete / comment out.

Do you know if this error message is something that is likely to be rectified in a future version of iFrameResizer?

Thanks again

David

**Comment by davidjbradshaw** [comment]
delete documentremoveEventListener from the polyfil

On Mon, Dec 21, 2015 at 10:01 AM, regauser <notifications@github.com> wrote:

> Hi David
>
> Thanks for your prompt reply.
>
> Can you explain which bit I need to delete?
>
> The line of code I detailed above is in jQuery, and I don't want to delete
> anything from there.
>
> In which case were you telling me delete the ie8 polyfils file?
>
> Or, more likely, were you telling me to delete some code from within the
> iFrameResizer script files?
>
> In which case could you indicate which parts and from which files? I can
> see several references to "removeEventListener " in both the host page and
> content page .js files, and unfortunately I'm not confident about what is
> safe to delete / comment out.
>
> Do you know if this error message is something that is likely to be
> rectified in a future version of iFrameResizer?
>
> Thanks again
>
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/303#issuecomment-166256680>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by regauser** [comment]
Hi David

Sorry, I'm confused... 

I can't find any removeEventListener anywhere in the ie8.polyfils.js file.

Thanks

David

**Comment by pravinweb** [comment]
Hi David,

I am facing same issue as well I am using 

iFrame Resizer (iframeSizer.min.js ) - v3.5.1 - 2015-11-04
ie8.polyfils.js
and jquery-1.11.2.js

Could you please help with this

Thanks,
Pravin

**Comment by davidjbradshaw** [comment]
Fixed in v3.5.2
