### ISSUE TITLE
iFrameResize

### ISSUE THREAD

**Issue by shaneonabike** [davidjbradshaw/iframe-resizer#305]
We are using this for a iFrame that resizes and after submitted shrinks again. When it shrinks it seems to not position itself below the actual top menu header. Is there some extra calls or parameters that I should set to add some padding.

```iFrameResize({checkOrigin: false, enablePublicMethods: true})```

I tried adding a margin-top to the iFrame but that didn't seem to work properly and it still had the same issue...

**Comment by davidjbradshaw** [comment]
I suggest posting an example on stackoverflow.

**Comment by shaneonabike** [comment]
Fair point... you can't be doing all the support for folks... thanks and happy holidays
