### ISSUE TITLE
Asynchronous iframeResizer.min.js

### ISSUE THREAD

**Issue by javiertury** [davidjbradshaw/iframe-resizer#306]
I've been thinking about how to load iframeResizer.min.js asynchronously in the parent window. Bear in mind that this code HASN'T been tested and probably contains mistakes, it is just an idea.

```
<script async src="//domain.com/include/js/iframeResizer.min.js"></script>
<script>
jQuery.fn.iFrameResize = jQuery.fn.iFrameResize || function(options) {
	var iFrameQer = { object: this, args: options };
	(window.iFrameResizeQ = window.iFrameResizeQ || []).push(iFrameQer);
};
</script>
...
<div id='iframe1'><iframe width="100%" src="//anotherdomain.com/iframe1.html" scrolling="no"></iframe></div>
<script>jQuery('#iframe1 iframe').iFrameResize( [{log:true}] )</script>
...
<div id='iframe2'><iframe width="100%" src="//anotherdomain.com/iframe2.html" scrolling="no"></iframe></div>
<script>jQuery('#iframe2 iframe').iFrameResize({log:true})</script>
```
So this is the first part, it would require to create inline the function "jQuery.fn.iFrameResize" if it hasn't already been loaded so it queues the commands(well, the iframe object and the command arguments) in the global variable "window.iFrameResizeQ".

Later on, after the iframeResizer.min.js file has been loaded and it has overwritten the function "jQuery.fn.iFrameResize" with the original/working one, the queue is executed in FIFO order as follows:
```
if (window.iFrameResizeQ) {
	var iFrameQer {};
	for ( var i=0; i < window.iFrameResizeQ.length; i++ ) {
		iFrameQer = window.iFrameResizeQ.shift();
		iFrameQer["object"].iFrameResize(iFrameQer["args"]);
	}
}
```
The code would be located at the end of iframeResizer.min.js

So far the main issue is having this feature working with both jQuery and native javascript seamlessly.  Also, what is the reason behind [this line](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.js#L991)?

**Comment by davidjbradshaw** [comment]
Why not just use requireJS or WebPack to achieve async loading?

That last line guards against loading the JS file twice.

**Comment by javiertury** [comment]
If here you use dedicated script handlers then it makes native support for asynchronous loading redundant for you.

Still that last line would have to be changed to make the file compatible with native javascript queuing. I've worked an example that doesn't need to include the queue cleaner in the iframeResizer.min.js file but I can't implement an enqueuer for native javascript method without changing that last line.

For those not using requireJS or WebPack and using the jquery method the following(now tested) example can be quite useful
```
<script>jQuery.fn.iFrameResize = jQuery.fn.iFrameResize || function(options) {
    var iFrameQer = { object: this, args: options };
    (window.iFrameResizeQ = window.iFrameResizeQ || []).push(iFrameQer);
    return this;
};
cleaniFrameQ = function() {
    var iFrameQer = {};
    while ( window.iFrameResizeQ.length > 0) {
        iFrameQer = window.iFrameResizeQ.shift();
        iFrameQer['object'].iFrameResize(iFrameQer['args']);
    }
};
</script><script async src="https://domain.com/include/js/iframeResizer.min.js" onload="cleaniFrameQ()"></script>
...
<div id='iframe1'><iframe width="100%" src="//anotherdomain.com/iframe1.html" scrolling="no"></iframe></div>
<script>jQuery('#iframe1 iframe').iFrameResize({log:true})</script>
...
<div id='iframe2'><iframe width="100%" src="//anotherdomain.com/iframe2.html" scrolling="no"></iframe></div>
<script>jQuery('#iframe2 iframe').iFrameResize( [{log:true}] )</script>
```

This last example can be added to the documentation/readme. If you want I will create an enqueuer for native javascript methods and expand the cleaniFrameQ function to cover that case, otherwise you can close this issue.
