### ISSUE TITLE
Extra space underneath iframe at bottom

### ISSUE THREAD

**Issue by pjb493** [davidjbradshaw/iframe-resizer#308]
Hi,

I have found an issue with the margin at the bottom of the iframe. I think this may be connected to issue 281 which was allegedly solved for ver.3.5.1 but as shown in this demo, there is a gap at bottom still. I've tested this with multiple iframe contents and the result is the same. This is not a css error as have thoroughly checked all styling linked to both the parent and iframe pages. Demos are given below:
[Content of iframe](http://concert-band.co.uk/new/Forms/committee-update.php)
[Parent page containing iframe (simplified example)](http://concert-band.co.uk/new/Forms/demo.html)
[Parent page containing iframe (real example)](http://concert-band.co.uk/new/Forms/index.html)

Thanks

**Comment by tzewangdorje** [comment]
Hi,

Those links aren't working for me I'm afraid. The dots seem to have been
stripped out and when I add them back in I get a 401 auth error?

The issue I reported is fixed and working for me now in production, but
perhaps you have hit upon a variation that didn't get handled properly? The
issue I was hitting was possibly the opposite of yours in that I couldn't
get any margin or padding under the iframe, the calculation was causing it
to get cropped short.

If you can provide some more details I'll gladly take a look and see if I
can shed any light on the issue you're having.

Dan

**Comment by pjb493** [comment]
Apologies, i've removed the htaccess files now so it should be visible.

**Comment by danballance** [comment]
I'm still getting an .htaccess auth request I'm afraid :(

**Comment by pjb493** [comment]
Okay, it should be okay now. I think the server was recreating the access file every time I deleted it.

**Comment by pjb493** [comment]
So far, I've found that the iframe seems to have a 4px gap at the bottom on the simplified example, and a 6px gap at the bottom of the real example. It's not attributable to any margin or padding of any element. Other than that I can't really be of any more help.

**Comment by pjb493** [comment]
Hi, has there been any progress made with this issue yet (sorry to be pushy) :)

**Comment by danballance** [comment]
I did make a space a couple of times to look at the issue you have raised,
but both times I couldn't see the code you had referenced. I'm not directly
related to this project, but seeing as we use this library I thought I'd
try to lend a hand. I'm currently on leave and not near a development
machine. I will try and take a quick look later in the week if you've not
found a resolution by then.

**Comment by tzewangdorje** [comment]
One thing I notice from a quick look is that you're not passing any
parameter options apart from log: true. There's a very useful setting
heightCalculationMethod:

https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod

I'd try experimenting with those values - in particular lowestElement and
taggedElement I have found to be very useful.

Let us know how you get on with some of those options,

Dan

**Comment by pjb493** [comment]
Thanks I'll give that a try, really appreciate the help, both of you :)

**Comment by pjb493** [comment]
Hi Dan,

I did try some different height calculation methods but these did not help since the extra space seems to be outside the iframe itself.

**Comment by pjb493** [comment]
Hey,

Fixed the issue, turns out this is a known issue with iframes in general that if they are display:inline, there are often problems with whitespace. Changing to display:block solved this problem.

**Comment by tzewangdorje** [comment]
Great stuff, glad you managed to get it sorted :)

**Comment by davidjbradshaw** [comment]
Hanks for the update that is one for the troubleshooting section.
