### ISSUE TITLE
<option> tag should never be consider as a displayed element

### ISSUE THREAD

**Issue by korvent** [davidjbradshaw/iframe-resizer#312]
With Firefox, if you have a &lt;select> tag with a large number of &lt;option> elements, the last &lt;option> element can be _under the last displayed element_.

The example beneath shows a HTLM page with a label and a select element on the same line. Hidden &lt;option> tags are revealed by inspecting sources with debugging tools.

![select](https://cloud.githubusercontent.com/assets/14818306/12615058/bc4018a4-c503-11e5-9b99-78e74cc32c52.png)

With option "heightCalculationMethod : 'lowestElement'", _iFrameResize()_ method consider the last &lt;option> tag as the lowest element. So the calculated frame size is wrong.
It happens every time the last &lt;option> tag is _under the last displayed element_.

Calculation method should ignore tags that are not displayed (&lt;option>, &lt;optgroup>, and more ?).

FYI : with MS Internet Explorer, calculation is good.

**Comment by markvantilburg** [comment]
It also effects the rendering of the page, i would think this is a firefox bug and not one of iframe resizer.

**Comment by korvent** [comment]
No web browser is perfect, web standards are not perfect, and web browsers does not respect standard fully.
Whether it is a Firefox bug or not iFrameResizer loses all interest with such an issue.

In my opinion, it is a good thing that libraries like iFrameResizer provide an abstraction layer that permit to use them in the same way whatever is the web browser rendering implementation.

I can help solving this. I noticed that calculation is correct with css "option {display: none;}". I did not forked yet because I presume it would be a modification that involve the core and could be quite tricky.

**Comment by davidjbradshaw** [comment]
I'd welcome a PR if you want to take a look at it. I'm super busy on other things for the next few weeks. 

Agree it is yet another thing we should work around. 

Normally best to avoid playing with CSS in the iFrames as don't want to mess up the page. 

Perhaps the function that tests for the elements position needs to check for a list of tags to ignore as well. 

It would be also good to raise a bug on FireFox.

**Comment by edvaldoperreira** [comment]
Thank you very much for that! I had the same issue on my project. I am using angular material and to solve it, I have changed this code to something like this:

`return document.querySelectorAll('body :not(.mdc-list-item__primary-text):not(.mat-ripple):not(.mat-mdc-option):not(option):not(optgroup)');`

**Comment by davidjbradshaw** [comment]
@edvaldoperreira sad to see this is still an issue, and nice fix.  I will add `:not(option):not(optgroup)` to the code base and think about away for users to add library classes that cause an issue.

**Comment by davidjbradshaw** [comment]
Thinking a bit more, I'm going to check an element is visible, before working out it's position.

**Comment by davidjbradshaw** [comment]
Fixed in v5.0.0
