### ISSUE TITLE
Unable to set scrolling property for iframes to 'auto'

### ISSUE THREAD

**Issue by FrancisRussell** [davidjbradshaw/iframe-resizer#315]
When scrollbars are requested, setScrolling() sets the scrolling property to 'yes'. It would be nice to have the scrollbars added only when necessary. On browsers like Chrome, Safari and IE, 'yes' is treated the same as 'auto', so they're only added when necessary. Also, 'auto' is typically the default. In Opera though, they'll always be added. Ideally it would be possible to either tell iframe-resizer to set this to 'auto', have 'auto' as the default for scrolling rather than 'yes' or disable iframe-resizer's setting of the scrolling properties entirely.

**Comment by davidjbradshaw** [comment]
Would you like to make a PR to add auto as an option?

**Comment by FrancisRussell** [comment]
Hi, and sorry for not responding to the first comment - I've been a little overloaded. Given that most browsers treat "yes" the same as "auto" for the scrolling property, I'm inclined just to create a pull request for that change as you originally suggested, unless you think a more sophisticated option would be more useful.

**Comment by davidjbradshaw** [comment]
Well I expect it's only a couple of lines of code to allow the option flag to be true, false, or 'auto'. 

Also stupidity busy right now so don't worry about slow replies.
