### ISSUE TITLE
library throwing error on IE8 on windows xp, includes solution.

### ISSUE THREAD

**Issue by geogiam-net** [davidjbradshaw/iframe-resizer#320]
Hello,

My company's website stopped to work correctly within IE8 on windows xp.
I discovered the bug came from your library and fixed it.

 I share you how ; >

I applied a polyfill on Function.prototype.bind and Array.prototype.forEach immediately when the page starts. You invoke them in your library and they are not defined in IE8.

I send you the txt if you want to confirm it.
I did the test with a vm from
https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/, 'ie8 on XP'

Best regards

George Baxter

[PolyFil.txt](https://github.com/davidjbradshaw/iframe-resizer/files/126577/PolyFil.txt)

**Comment by markvantilburg** [comment]
Did you check: https://github.com/davidjbradshaw/iframe-resizer#upgrading-to-version-3 ?
