### ISSUE TITLE
Doesn't works for multiple iframes on same page

### ISSUE THREAD

**Issue by rajushrestha** [davidjbradshaw/iframe-resizer#321]
Firstly, this plugin is awesome and thanks for it.

It is working well as expected for single iframe but doesn't works for multiple iframes loading in same page.

Here is an example : http://quiz.leadquizzes.net/wordpress/sample-page/

For Now I have put fixed height on iframe.

**Comment by pscdodd** [comment]
Hi Raju Shrestha

All iframes have the same ID:
id="lquizIframe"
- thus it will not work.
Try using different IDs i.e. lquizIframe1, lquizIframe2 ... lquizIframeN

You don't need to load "iframeResizer.min.js<https://quiz.leadquizzes.com/js/iframeResizer/iframeResizer.min.js>" in your iframes, only "iframeResizer.contentWindow.min.js<https://quiz.leadquizzes.com/js/iframeResizer/iframeResizer.contentWindow.min.js>".

Regards
Paul Dodd

________________________________
Von: Raju Shrestha [notifications@github.com]
Gesendet: Donnerstag, 18. Februar 2016 17:12
An: davidjbradshaw/iframe-resizer
Betreff: [iframe-resizer] Doesn't works for multiple iframes on same page (#321)


Firstly, this plugin is awesome and thanks for it.

It is working well as expected for single iframe but doesn't works for multiple iframes loading in same page.

Here is an example : http://quiz.leadquizzes.net/wordpress/sample-page/<redir.aspx?REF=aMLo7lV3vuTalwp7ugfMo-f5YLQyvK6ibApEltf6NJZgSuiYhzjTCAFodHRwOi8vcXVpei5sZWFkcXVpenplcy5uZXQvd29yZHByZXNzL3NhbXBsZS1wYWdlLw..>

For Now I have put fixed height on iframe.

**Comment by schroding3rscat** [comment]
@pscdodd, it doesn't work even with different ids. As a workaround, I explicitly called iframeResize on every new iframe on the page.

**Comment by davidjbradshaw** [comment]
It does work, the issue is going to be with your code. Try removing all the IDs from your iFrame tags. If that doesn't work post a question on StackOverflow.
