### ISSUE TITLE
IE11 Crashed with the code in host page - Bug

### ISSUE THREAD

**Issue by jasonliaocn** [davidjbradshaw/iframe-resizer#322]
Hi, I have a MVC application hosted inside a SharePoint portal. It's using the iframe.
After I add the iFrameResize into my SharePoint Master page, it's cause the IE crashed.
The code I added into the master page is as below:

    <script type="text/javascript" src="../SiteAssets/iframeResizer.js"></script>
    <script type="text/javascript">
         iFrameResize({
				//log                     : true,                  // Enable console logging
				sizeWidth				: true,
				checkOrigin				: false,
				resizedCallback         : function(messageData){ 
				}			
			});
    </script>

the Error log from windows application event says below:
Faulting application name: IEXPLORE.EXE, version: 11.0.10586.20, time stamp: 0x56541caa
Faulting module name: MSHTML.dll, version: 11.0.10586.103, time stamp: 0x56a85017
Exception code: 0xc0000005
Fault offset: 0x0061c314
Faulting process id: 0x7020
Faulting application start time: 0x01d16a82102db66b
Faulting application path: C:\Program Files (x86)\Internet Explorer\IEXPLORE.EXE
Faulting module path: C:\WINDOWS\SYSTEM32\MSHTML.dll
Report Id: 4b2facd5-b3a8-4d39-bed2-0ddc145d3e12
Faulting package full name: 
Faulting package-relative application ID:

if I remove the inline java script code, it works fine.

please help check.

**Comment by davidjbradshaw** [comment]
That is not a bug in this library, I'd suggest talking to MicroSoft.

**Comment by jasonliaocn** [comment]
how can I talk to Microsoft, even this is a Microsoft Bug, this library should provide the feature to support auto re-size, right? Have you tested it in IE 11?

**Comment by davidjbradshaw** [comment]
Yes it's tested in IE11 and yes it works. This looks like a sharepoint issue to me. You can raise a bug with MircoSoft via an MSDN subscription.

If you can repro this as a simple test case without using SharePoint, then I'll take a look.

**Comment by jasonliaocn** [comment]
OK, seems it is a SharePoint issue. Apologize for that.
I have use an alternate solution to make it work. Thanks.
