### ISSUE TITLE
iFrame not shrinking after long page in IE and Chrome

### ISSUE THREAD

**Issue by lxiam** [davidjbradshaw/iframe-resizer#324]
In Firefox your tool works fine, but in IE and Chrome (and possibly other browsers too) the iframes will grow, but not shrink again. So if you are on a long page and navigate to a much shorter page the iframe remains the height of the previous (long) page. I have created a sample page to test this for yourself. You can find it here:
https://dl.dropboxusercontent.com/u/3335845/iframeResizer-checker-tangram.htm
The content is in Dutch but the UI is English so you should be able to work through it. Hint: just select the top most vacancy and press the button "Apply for this job". In the screen with the four options ("Upload your CV" etc.) you can see that the iframe is much too high for the content. At least in IE and Chrome...

**Comment by davidjbradshaw** [comment]
that depends on what options you set. Please see the project README file.
