### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by wimlibby** [davidjbradshaw/iframe-resizer#325]
I am having trouble getting to work when using both https.  Works fine when primary site is http and iframe src is https.

I was told by one engineer at web host company this will not work cross-domain. To quote him, "This is due to browsers enforcing a Cross-Origin Resource Sharing security policy. Page A can’t perform manipulations on page B unless both pages are being served from the same web site. "

Does this make sense?  I didn't want to trouble shoot or disagree without confirming first.

If it is possible and should work, does anyone have an example page I can point them to show as a reference that it will work?   I think if they saw a working example, they would try a little harder to fix it.

Thanks!

**Comment by davidjbradshaw** [comment]
Normally you can not talk to an iFrame in a different domain, however, we get around that restriction by using the postMessage API for this.

Have you tried setting the checkOrigin flag to false? Also turn logging on and look at the browser console for info on what is happening.
