### ISSUE TITLE
Script is not working for me for cross domain site

### ISSUE THREAD

**Issue by goudmahendra** [davidjbradshaw/iframe-resizer#330]
Hello,
            I have applied your code for cross domain iframe but is not working for me please have a look image url http://awesomescreenshot.com/0a25ofev9c for what output i am getting.
my code is below

<div class="contentpane">

<iframe src="http:joomla.org" width="100%" scrolling="no">
	no irame
</iframe>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script type="text/javascript" src="http://jdevcorp.com/components/com_wrapper/views/wrapper/tmpl/iframeResizer.min.js"></script>
		<script type="text/javascript">

			/*
			 * If you do not understand what the code below does, then please just use the
			 * following call in your own code.
			 *
			 *   iFrameResize({log:true});
			 *
			 * Once you have it working, set the log option to false.
			 */

			iFrameResize({
				log                     : true,                  // Enable console logging
				inPageLinks             : true,
				resizedCallback         : function(messageData){ // Callback fn when resize is received
					$('p#callback').html(
						'<b>Frame ID:</b> '    + messageData.iframe.id +
						' <b>Height:</b> '     + messageData.height +
						' <b>Width:</b> '      + messageData.width +
						' <b>Event type:</b> ' + messageData.type
					);
				},
				messageCallback         : function(messageData){ // Callback fn when message is received
					$('p#callback').html(
						'<b>Frame ID:</b> '    + messageData.iframe.id +
						' <b>Message:</b> '    + messageData.message
					);
					alert(messageData.message);
					document.getElementsByTagName('iframe')[0].iFrameResizer.sendMessage('Hello back from parent page');
				},
				closedCallback         : function(id){ // Callback fn when iFrame is closed
					$('p#callback').html(
						'<b>IFrame (</b>'    + id +
						'<b>) removed from page.</b>'
					);
				}
			});

		</script>

</div>

Please let me know what wrong I am doing.

**Comment by davidjbradshaw** [comment]
Impossible to tell from a screenshot.
