### ISSUE TITLE
Add the ability of the parent to check if the child has the required javascript for resize

### ISSUE THREAD

**Issue by cjbose** [davidjbradshaw/iframe-resizer#331]
Hey,

I'm working on a project where I'm in control of the parent page, but I'm not in control of the child pages. The owners of the child pages have agreed to change, however that will not be any time soon. Is there currently a way for me, as the parent application, to check if the child has the iframe-resize code before executing?

What I'm running into is that some child applications have the iframe-resize code while others do not. For the ones that have it, everything works fine. For the ones without it, the scrollbar is being removed from the iframe causing you to not be able to see all of the content. If I set the scrolling flag to true, the ones without the code display the scroll bar as expected; However the ones with it now have a flickering scroll bar any time the iframe content is resized.

Thanks,
Cody

**Comment by davidjbradshaw** [comment]
Interesting question.

I’d suggest turn the scrolling on, then use the initCallback to turn it of
in the ones that work.

```js
iframeReszie({
   initCallback:function(iframe){
      iframe.scrolling = ‘no'
   }
});
```

Or something like that.
