### ISSUE TITLE
window.parentIframe does not get set in an angular context

### ISSUE THREAD

**Issue by andrehagemeier** [davidjbradshaw/iframe-resizer#332]
First of all, I don't know if this is related to angular at all. Actually, I doubt it but I figured it might be an interesting piece of information.
If have an angular app, that I want to include in an iframe with the resizer. The resizing works perfectly, only sending messages from the iframe to the parent does not work at all. The reason is, that the parentIframe will not be added to the window object of the iframe. Neither to window nor to the $window services that is exposed via angular. I added a couple of tests to my app to see if it is due to delay, but it just never appears:
```js
      var test = function() {
        if ('parentIFrame' in window) {
          console.log('found it in window');
        }
        else {
          console.log('not in window');
        }

        $timeout(test, 1000);
      };
      test();

      var test2 = function() {
        console.log('test2 triggered');
        window.iFrameResizer = {
          readyCallback: function(){
            console.log('test2 callbacl');
              var myId = window.parentIFrame.getId();
              window.xyz = window.parentIFrame;
              console.log('The ID of the iFrame in the parent page is: '+myId);
          }
        }
      }
      test2();
```

The callback never gets executed. The resizing itself works properly. I looked a bit into the code and saw the setupPublicMethods() method which seems to add the parentIFrame object to the window. The log statements inside this method never get executed. No hint in the log about init messages that are sent from the parent to the client. Since the resizing doesn't seem to make use of these public functions, that seems to be the reason why resizing works.
Any idea at what point I could start digging deeper to find out why this is happening?

**Comment by davidjbradshaw** [comment]
Don't really do Angular, however, I'd suggest looking at where the iframeResizer object gets bound to the `window`. Not sure how Angular would block that from happening, or what `$window` is. Could you test for the later their and bind to both if it exists?

If you make a simple test case, I'd be interested to take a look at some point, but hyper busy right now.

**Comment by LuizPanariello** [comment]
I use iframeResizer + AngularJS 1.2 and 1.3 on production, and I don't have this kind of problem. Aren't you forgetting to add the contentWindow script inside the angular page or calling it before the frame is ready?

**Comment by jcossio** [comment]
Trying to do the same with Angular 2. Maybe Luiz has had a change to make it work with it?
