### ISSUE TITLE
iFrameResizer not working in iOS.

### ISSUE THREAD

**Issue by premedios** [davidjbradshaw/iframe-resizer#334]
I tried to view my company's site at http://www.itup.pt but what I get is the following:

![ios_safari](https://cloud.githubusercontent.com/assets/265363/13743573/7c92ff22-e9da-11e5-91c8-90ad0ae6f6e7.jpg)

The server hosting this already has the most recent version (3.5.1) installed. Here is the javascript we have:

`

			iFrameResize({
				log                     : true,                  // Enable console logging
				enablePublicMethods     : true,                  // Enable methods within iframe hosted page
				resizedCallback         : function(messageData){ // Callback fn when resize is received

				},
				messageCallback         : function(messageData){ // Callback fn when message is received

				},
				closedCallback         : function(id){ // Callback fn when iFrame is closed

				},
				heightCalculationMethod : 'max'
			});

		`
The site displays fine in mobile size in Chrome Windows. If I missed any options I should be using/trying, I would appreciate anyone pointing that out. Any other clues appreciated.

Thanks

Pedro Remedios

**Comment by timpwbaker** [comment]
I have the same problem. Did you find any solutions?

**Comment by premedios** [comment]
I found out what was wrong. Apparently I had to tell iFrameResizer who big the screen was as it seems it's not doing very well. These are the options that I used for that:

maxWidth: screen.width,
minWidth: screen.width,
sizeWidth: 'true'

Hope this helps.

**Comment by abdulrahim-luminescent** [comment]
@premedios 
Thanks, Your solution is working for me.

` var screenWidth = screen.width;
    if (browser.iPad) { screenWidth = screenWidth - 300;}
    if (browser.iPhone) { screenWidth = screenWidth - 50;  }
---------------------------------------------------------------------
 S = {
            ------
            maxHeight: 1 / 0,
            maxWidth: screenWidth,
            minHeight: 0,
            minWidth: 0,
            resizeFrom: "parent",
            scrolling: !1,
            sizeHeight: !0,
            sizeWidth: true,
            ------------------
        };`

**Comment by nishantprajapti** [comment]
Thank you so much for the help.
It really worked for me.

**Comment by sharplogicians** [comment]
I was having a problem on mobile browsers (both android/iOS) that when the iframe loaded, the height kept on increasing and increasing and increasing. So When I used this, it resolved the issue.
`iFrameResize({ log:true, 
interval:1, 
tolerance: 1, 
resizeFrom : 'parent', 
heightCalculationMethod: heightResizeMethod, 
resizedCallback: function(messageData){
 iframeResizerLoaded = true; 
}
});
`
