### ISSUE TITLE
failed to execute postMessage

### ISSUE THREAD

**Issue by edencorbin** [davidjbradshaw/iframe-resizer#336]
Everything is working perfect, but I get a failed to esecute postMessage in my console. I'm pulling a static page no two way information needed, can I resolve?

**Comment by davidjbradshaw** [comment]
You can ignore this message, it's a false error message from the browser. Basically the parent page is trying to talk to the iFrame before the iFrame has started loading.

**Comment by EveryNameTaken** [comment]
I have multiple iframes, and my console is full of these messages. Is it possible to remove these messages?

**Comment by davidjbradshaw** [comment]
It's a bug in the Chrome browser. You need to raise a bug with Google.
