### ISSUE TITLE
IE 11 script error 

### ISSUE THREAD

**Issue by ieuser** [davidjbradshaw/iframe-resizer#337]
Hi,

I got an error on only in IE (my test was on IE 11), it working well for Chrome and FreFox.

Error message :
`[iFrameSizer][Host page: iFrameResizer0] [iFrame.onload] IFrame(iFrameResizer0) not found
SCRIPT5007: Unable to get property 'firstRun' of undefined or null reference
File: iframeResizer.min.js, Line: 8, Column: 7626`

the error is located exactly here:
`var b=P[w].firstRun`

If you can have a look I will appreciate it.

PS: Thanks for your lib it's a very good tool !

**Comment by davidjbradshaw** [comment]
Can you try that on the non min version.

**Comment by ieuser** [comment]
Hey David,

with the non min version the error is there:

`function checkReset(){
			// Reduce scope of firstRun to function, because IE8's JS execution
			// context stack is borked and this value gets externally
			// changed midway through running this function!!!
			var
				firstRun           = settings[iframeId].firstRun,`

the value for iframeId is for example "iFrameResizer4"
but in settings there is only the  iFrameResizer5.
so IE throws 'Unable to get property 'firstRun' of undefined or null reference'

Thanks

**Comment by davidjbradshaw** [comment]
Strange do you have a link I could look at

**Comment by Egor-Sapronov** [comment]
I have the same issue but on IE 10
