### ISSUE TITLE
Destroy iFrameResize

### ISSUE THREAD

**Issue by csysmans** [davidjbradshaw/iframe-resizer#338]
Is it required to destroy the iFrameResize when working in an SPA environemnt (Ember) and dynamically adding and removing iframes?
If so, how can you tear down the iFrameResize?

**Comment by davidjbradshaw** [comment]
Call the close method in either the iFrame or the parent page. See docs for details.

**Comment by httpete** [comment]
Does this disconnect all listeners / watchers?  My use case is I am instantiating an angular route that contains a resizeable iframe. On enter I need to connect, and on exit I need to destroy so things aren't watching when it's gone.

**Comment by davidjbradshaw** [comment]
It should clear up everything.

**Comment by spiderpug** [comment]
Sorry to hijack this issue, but I can't seem to make it work. I use vue.js in my project and my setup is basically:

```
{
  mounted () {
    this.iframe = $(this.$el).find('iframe').get(0);
    iframeResizer(opts, this.iframe);
  },

  beforeDestroy () {
    this.iframe.iFrameResizer.close();
  }
}
```

but after my component is destroyed properly, I still see warnings in console:

`[iFrameSizer][Host page: iFrameResizer0] No response from iFrame. Check iFrameResizer.contentWindow.js has been loaded in iFrame`

after a few seconds. What am I missing?

**Comment by davidjbradshaw** [comment]
Try updating to v3.5.14
