### ISSUE TITLE
Firefox calculated height is bigger than Safari's and Chrome's

### ISSUE THREAD

**Issue by juliomac** [davidjbradshaw/iframe-resizer#340]
I have used the same code and testes across these three browsers. However, on Firefox, iFrame is loaded with a slightly bigger height than on other browsers, getting on top of content of the parent page.

I get calculated height=68px on Safari and Chrome:
```js
<iframe id="libertas" src="https://myiframesource.com" scrolling="no" style="overflow: hidden; height: 68px;"></iframe>
```

But I get height=111.6px on FireFox:
```js
<iframe id="libertas" src="https://myiframesource.com" scrolling="no" style="overflow: hidden; height: 111.6px;"></iframe>
```

Is there a way to prevent it? What could be causing it on my code?

**Comment by davidjbradshaw** [comment]
I've no idea without see code. Create a simple test case.

https://github.com/davidjbradshaw/iframe-resizer/blob/master/CONTRIBUTING.md
