### ISSUE TITLE
Manually trigger the resize from the parent page ?

### ISSUE THREAD

**Issue by stephane-tessier** [davidjbradshaw/iframe-resizer#341]
I cannot set autoResize to true because on mobile it trigger issues when scrolling. (URL bar come and goes, triggering resizes and flickering).
So I want to mimic the autoResize behaviour, except that if the width doesn't change, I won't post the resize message. How can I do that ?

**Comment by davidjbradshaw** [comment]
`document.getElementById('myiframe').iframeResizer.resize();`
