### ISSUE TITLE
undefined document.getElementsByTagName('iframe')[0].iframeResizer in example published

### ISSUE THREAD

**Issue by tangrammer** [davidjbradshaw/iframe-resizer#343]
Hi guys!
I'll try to call document.getElementsByTagName('iframe')[0].iframeResizer.resize() from on-line example http://davidjbradshaw.com/iframe-resizer/example/ but always got  `VM1319:2 Uncaught TypeError: Cannot read property 'resize' of undefined(…)`

But as you can check in the image below, the iframe exists and is resizer works properly

![screen shot 2016-04-19 at 13 15 35](https://cloud.githubusercontent.com/assets/731829/14637319/d81f72f4-0630-11e6-925e-a51813297d19.png)

It's very related to #341 

thanks in advance for your help
Juan

**Comment by davidjbradshaw** [comment]
Do you have more then one iFrame on the page? Use getElementById rather thantagName.

**Comment by tangrammer** [comment]
Hi @davidjbradshaw and thanks for your response
I don't think this is the problem in your published example [http://davidjbradshaw.com/iframe-resizer/example/](http://davidjbradshaw.com/iframe-resizer/example/)
```js
document.getElementsByTagName('iframe').length
=> 1
```
could you reopen the issue again so anyone could take a look on that?

Thanks again!
Juan
