### ISSUE TITLE
Force update of iframe height after click.

### ISSUE THREAD

**Issue by JamesMyland** [davidjbradshaw/iframe-resizer#344]
Is there a method of calling a function onclick that can reset the iframe size based on current content?

I have used the scroll to function which has worked a treat, however the iframe height is then reset to 0px. When i resize the browser it then shows the correct height.

I was hoping to call another function to reset the height. or determine what is causing the iframes height to be reset to 0px

**Comment by coyarzun2013** [comment]
Hi James, same problem for me, but in diferent context, i open a iframe inside a bootstrap modal and this script didn´t work, mabye some conflict with bootstrap css or js. So, looking for internet finally find two lines of code that did the work(but without this script). hope you can solve your problem

`function resizeModalFrame(idFrame) {
    fheight = document.getElementById(idFrame).contentWindow.document.body.scrollHeight;
    $('#'+idFrame).css('height',fheight+'px'); 
}`

then when i open the modal with bootstrap i call this function. Same thing when i change a combo option and get dinamic content throught ajax(after put dinamic content via innerHTML), and works perfect.

**Comment by JamesMyland** [comment]
Hi coyarzun2013 I dont think this will resolve my issue, the iframeresizer script is doing exactly what i need it to however the content within the iframe is changing shape which is why i need to amend the height of the parent iframe from within the iframe on click.

**Comment by davidjbradshaw** [comment]
Just call the parentIFrame.size() method. See docs

**Comment by JamesMyland** [comment]
Hi David, I have called the scrollto method but the iframe height is then
reset to 0 px. Upon physically resizing the browser the iframe height is
updated. I have tried the following:-

window.parentIFrame.scrollTo(0,0);
parentIFrame.size();
return false;
but the iframe height doesn't refresh.

Your script is working perfectly, and has solved a massive issue that we
have had for a number of years.

however due to how well this script is working, when our content changes
people can no longer see shorter content, hense trying to get the parent
window to scroll to top.

Your advice is greatly appreciated.

**Comment by davidjbradshaw** [comment]
It's most likely a CSS issue in you code, but odd that resizing the browser fixes things. Impossible to say what without seeing it. Long shot and a complete ugly hack, but have you tried using setTimeout?

    setTimeout(parentIFrame.size,0);

**Comment by JamesMyland** [comment]
I quite agree, it is an ugly hack, but it seems to work for one part. I will test fully tomorrow. Thank you for your advice so far.

I could pm you across a link but as it is a production server I would prefer not to send publicly.

**Comment by JamesMyland** [comment]
Sadly this doesn't fix the issue. On a mobile the iframe height also disappears once window.parentIFrame.scrollTo(0,0) is called. Once the device is rotated, the iframe resizes to the content height.

**Comment by davidjbradshaw** [comment]
Can you post the entire log output

**Comment by davidjbradshaw** [comment]
Closed due to no response
