### ISSUE TITLE
Resizer not active on iOS Safari, but works fine on other mobile devices

### ISSUE THREAD

**Issue by timpwbaker** [davidjbradshaw/iframe-resizer#346]
Hi, I have the iframe resizer working very well (an awesome tool, thank you) on every browser I can test it on except safari on iOS.

The web page is here: https://www.breastcancercare.org.uk/sign-host-strawberry-tea

I've tested on up to date versions of Firefox/Chrome/Safari (mac), Firefrox/Chrome (windows), Chrome (Android), and Safari (iOS).

Any ideas? Can I do anything else to debug?

**Comment by davidjbradshaw** [comment]
What’s the output from the console log look like?

**Comment by timpwbaker** [comment]
Hi David,

Thank you for the quick reply!

I have this error in the iphone log that I don't get anywhere else:
[Error] Failed to load resource: the server responded with a status of 404
(Not Found) (iframeResizer.contentWindow.map, line 0)

The link is set up correctly. I see the console recording touches on the
phone screen.

Screenshot:

​

Tim

On Fri, Apr 22, 2016 at 9:51 AM, David J. Bradshaw <notifications@github.com
> wrote:

> What’s the output from the console log look like?
>

**Comment by timpwbaker** [comment]
Hi David,

This has fixed by accident. I had 

.row .entry select {
    width: auto;
}

in my CSS, replaced it with

.row .entry select {
	width:100%;
}

and it's fixed. Not strictly sure why.

Thank you again for a great plugin.

TB

**Comment by davidjbradshaw** [comment]
Thanks for the update.
