### ISSUE TITLE
Need testing help - can people check my page?

### ISSUE THREAD

**Issue by wimlibby** [davidjbradshaw/iframe-resizer#348]
Sorry, not an expert programmer, but I am having issues reported by users that the re-sizer is not always working.  My trouble is I cannot duplicate the error to even know where to try and trouble shoot.  It was reported it didn't work in Chrome, but it works fine for me.  

Example page where it works for me, but other have reported an error:
[http://www.vapa.org/exhibitor/exhibitor.php](http://www.acoi.org/education/cme/exhibits-sponsorship-advertising/past-exhibitors.html)

Can anyone duplicate the page not re-sizing? ...even better if you can see why it may not be working.
I have set heightCalculationMethod:"lowestElement" in iframeresizer.min.js file

I do also see this error in the console, but it still works for me.
iframeResizer.js:626 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.esvw.com') does not match the recipient window's origin ('http://www.vapa.org').

**Comment by davidjbradshaw** [comment]
You need to create a simple test case if you want me to look into a bug in this library, if your having trouble with you code take a look at the troubleshooting section, or ask a question on StackOverflow.com

**Comment by davidjbradshaw** [comment]
PS the error message is due to a bug in Chrome, you can safely ignore it.

**Comment by jsers** [comment]
I'm getting the same error message, Where can I see the bug.

**Comment by jeeshenlee** [comment]
Have the same problem, fixed it by making sure i have the right http vs https.

My iFrame source required https, the library shows postMessage error when I try to use http on my iFrame client.
