### ISSUE TITLE
nested iframes  scrollto problem

### ISSUE THREAD

**Issue by elythria** [davidjbradshaw/iframe-resizer#350]
Hi,
first of all: thank you so much for your great iframe-resizer! :)

We try to include a webhelp in an iframe which has already iframes in it.

The resizing is triggered and calculated manually and everything works fine... except:

Within the iframe of our webhelp, we use anchors. 
We decided to trigger the parentIFrame.scrollTo(x, y) after triggering parentIFrame.size(height);

Unfortunately, it seems we can't produce the wished result
what we did so far:
in our webhelp index, we included a function resize(), which calls 
		
```javascript
	if ('parentIFrame' in window) {
			parentIFrame.size(height);
			console.log("scroll!!!!!!!!!!!!!!!!!!!");
			console.log(top);
			parentIFrame.scrollTo(0,top);
		}
```

In our main window, the iFrameResize call is like below. we decided to remove inPageLinks, as the links are in the nested iframe within the index.htm
```javascript
			iFrameResize({
				log:true,
				checkOrigin:false, 
				minHeight:650,
				autoResize:false,
				scrollCallback: function (coords) {
					console.log("[OVERRIDE] overrode scrollCallback x: " + coords.x + " y: " + coords.y);
				}
				//inPageLinks:true
				});
```
The logfile says: 
```
`[iFrameSizer][content] Trigger event: parentIFrame.size(4050)
iframeResizer.contentWindow.js:140 [iFrameSizer][content] Trigger event lock on
iframeResizer.contentWindow.js:140 [iFrameSizer][content] Sending message to host page (content:4050:1904:size)
iframeResizer.contentWindow.js:140 [iFrameSizer][content] Sending message to host page (content:1379.265625:0:scrollTo)
iframeResizer.js:129 [iFrameSizer][Host page: content] Received: [iFrameSizer]content:4050:1904:size
iframeResizer.js:129 [iFrameSizer][Host page: content] Checking height is in range 650-Infinity
iframeResizer.js:129 [iFrameSizer][Host page: content] Checking width is in range 0-Infinity
iframeResizer.js:129 [iFrameSizer][Host page: content] Requesting animation frame
iframeResizer.js:129 [iFrameSizer][Host page: content] Received: [iFrameSizer]content:1379.265625:0:scrollTo
iframeResizer.js:129 [iFrameSizer][Host page: content] Reposition requested from iFrame (offset x:0 y:0) - y:1379.265625
johwe_main.html:115 [OVERRIDE] overrode scrollCallback x: 0 y: 1379.265625
iframeResizer.js:129 [iFrameSizer][Host page: content] --
iframeResizer.js:129 [iFrameSizer][Host page: content] IFrame (content) height set to 4050px
iframeResizer.contentWindow.js:140 [iFrameSizer][content] Trigger event lock off
iframeResizer.contentWindow.js:140 [iFrameSizer][content] --`
```
is there any chance you can help us with this?
Thanks in advance!
Johanna

**Comment by davidjbradshaw** [comment]
scrollCallback needs to return false if you want to stop iFrameResize scrolling the page.

**Comment by elythria** [comment]
Thanks for the fast reply.
We tried this as well, but in this case we scrolled only the first time using the parentiframe.scrollTo () method.

Or does this mean we can't use your scrollTo function and should give postmessage with a custom function a go ?

**Comment by davidjbradshaw** [comment]
It means that if you do `return false` and it still doesn't work the issue is in your code.

If you rip scrollCallback out does it then work?

**Comment by elythria** [comment]
thanks again, I will check that today.
