### ISSUE TITLE
Resizing Issue with Google Chrome, only resizes after mouse click

### ISSUE THREAD

**Issue by Grey007** [davidjbradshaw/iframe-resizer#353]
Hi, 

So I'm having a really weird issue. With Google chrome, my iFrame is resizing, but the height is to large creating lots of white space below the last element. However, if on mouse click, the iFrame resizes perfectly. 

In Firefox and IE, the resizing works perfectly. Any idea what it could be? 

I'm currently resizing the iframe using the following: 
iFrameResize({
log: true, 
autoResize: true
})

Thanks in advance!

**Comment by davidjbradshaw** [comment]
Most likely a CSS problem

**Comment by Grey007** [comment]
If it's a CSS issue, why would IE and Firefox work and not Chrome?

**Comment by davidjbradshaw** [comment]
Because they all have their own implementations of CSS, with their own bugs.

**Comment by Grey007** [comment]
Maybe you could help further. Could this issue be because of loading each iFrame within tabbed content?

**Comment by ggsp** [comment]
I think I might be having a similar issue, on an iFrame with pretty much no CSS whatsoever in it. Basically what happens is that clicking a link inside the iFrame won't trigger a resize. Clicking anywhere else inside the iFrame after having loaded new content then triggers the resize.

**Comment by davidjbradshaw** [comment]
Loading iFrame in tabs has created issues in FireFox in the past. Not seen it in Chrome before.

**Comment by Grey007** [comment]
So I think I know what is happening. Within my iFrames I am loading a HTML Table with many rows of data. The tables data is sorted and paged using https://github.com/Mottie/tablesorter. So what is happening is that when the iFrame loads, the iFrame is resizing before the Pager loads the data. So when an event is triggered such as mouse over or mouse up, the iFrame resizes to the correct height. 

Is there a way you can delay the iFrame from resizing until after the sorter has completed? The sorter code is currently situated in $( document ).ready()

**Comment by pscdodd** [comment]
Add

          if ('parentIFrame' in window) {
            parentIFrame.size();
          }

in the document ready function after your sorting code is finished.

Von: Grey007 [mailto:notifications@github.com]
Gesendet: Mittwoch, 4. Mai 2016 17:02
An: davidjbradshaw/iframe-resizer <iframe-resizer@noreply.github.com>
Betreff: Re: [davidjbradshaw/iframe-resizer] Resizing Issue with Google Chrome, only resizes after mouse click (#353)


So I think I know what is happening. Within my iFrames I am loading a HTML Table with many rows of data. The tables data is sorted and paged using https://github.com/Mottie/tablesorter. So what is happening is that when the iFrame loads, the iFrame is resizing before the Pager loads the data. So when an event is triggered such as mouse over or mouse up, the iFrame resizes to the correct height.

Is there a way you can delay the iFrame from resizing until after the sorter has completed? The sorter code is currently situated in $( document ).ready()
