### ISSUE TITLE
Autoresize not working on Chrome but works on other browsers

### ISSUE THREAD

**Issue by altimea** [davidjbradshaw/iframe-resizer#354]
Hi, I saw several other issues about this, but anyone of them helped me solve this issue.

The thing is that this feature worked in the past and recently I was reported that it stopped working on Chrome.

This is a link to the public website where the iframe is shown: http://www.cyzone.com/pe/maquillador-virtual

The code calling on that public site (from version 0.1.0 from 2013) is:

```
$(window).load(function(){
	$('#contentManicure').iFrameSizer({
		log: true,
		contentWindowBodyMargin:8,
		doHeight:true,
		doWidth:false,
		interval:250
	});
});
```

And the iframe origin has the iframeResizer.contentWindow.min.js script in version 2.8.9

I tried to work with both 2.8.9 but still, and also with latest version (not latest version of contentWIndows as I don't have access right now to that part) with this:

```
$(window).load(function(){
	$('#contentManicure').iFrameResize({
		log: true,
		interval:250,
		autoResize: true
	});
});
```

Also tried every heightCalculationMethod but nothing.

Any idea what could be happening?

Best regards

**Comment by davidjbradshaw** [comment]
Hmm, seems like the latest Chrome version has a bug in it. Have you compared the log output of Chrome and Firefox?

**Comment by altimea** [comment]
Firefox doesn't show the error Chrome shows. I tested the same website with a 44 Chrome version and it works OK.

The error thrown by Chrome now is:

> Uncaught SecurityError: Blocked a frame with origin "http://www.cyzone.com" from accessing a frame with origin "http://makeovr.com". Protocols, domains, and ports must match.

**Comment by davidjbradshaw** [comment]
Does that error show in Chrome 44, you shoul be able to ignore it. Do you see log messages after it?

Chrome 50 seems to have a few bugs in it. I had recreate my user profile after the upgrade.

**Comment by davidjbradshaw** [comment]
Can you please make a simple test of the parent page with the latest version.

**Comment by altimea** [comment]
That error doesn't show on Chrome 44 where it works. Just in the latest Chrome

> I had recreate my user profile after the upgrade
What do you mean here?

> Can you please make a simple test of the parent page with the latest version.
Sorry, I didn't understand. What do you want me to do?

**Comment by davidjbradshaw** [comment]
Can you make a simple page that just has the iFrame on it.

**Comment by altimea** [comment]
Hi

I made a clean iframe for you here: http://cyzone.com/prueba-iframe.html

**Comment by davidjbradshaw** [comment]
Ok thanks, does it still have the issue, I'm away sailing for the next week with just my iPad.

**Comment by travisp** [comment]
Not sure if this is related, but there's someone reporting a problem with postMessage in chrome 50 https://groups.google.com/a/chromium.org/forum/#!searchin/chromium-discuss/postMessage/chromium-discuss/RhgzRx7Dlu0/AtETniGqAgAJ

**Comment by davidjbradshaw** [comment]
You page isn't using iFrame-Resizer! This is what is doing the resize and then falling over.

```js
<script>
            function getDocHeight(doc) {
            doc = doc || document;
            var body = doc.body, html = doc.documentElement;
            var height = Math.max( body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight );
            return height;
            }
            function setIframeHeight(myiframeid) {
            var ifrm = document.getElementById(myiframeid);
            var doc = ifrm.contentDocument? ifrm.contentDocument: ifrm.contentWindow.document;
            ifrm.style.visibility = 'hidden';
            ifrm.style.height = "10px";
            ifrm.style.height = getDocHeight( doc ) + 5+"px";
            ifrm.style.visibility = 'visible';
            }
            </script>
            <script>(function(run){
            for (i=0;i<frames.length; i++) {
            var f1 = document.getElementsByTagName('contentManicure')[i];
            if(!f1 && window.addEventListener && !run){
            document.addEventListener('DOMContentLoaded', arguments.callee, false);
            return;
            }
            if(!f1){setTimeout(arguments.callee, 300); return;}
            f2 = f1.cloneNode(false);
            f1.src = 'about: blank';
            f2.frameBorder = '0';
            f2.allowTransparency = 'yes';
            f2.scrolling = 'no';
            f1.parentNode.replaceChild(f2, f1);
            }
            })();
</script>
```
