### ISSUE TITLE
Iframe resizer not working

### ISSUE THREAD

**Issue by mannverma** [davidjbradshaw/iframe-resizer#355]
I am getting content via ajax into an iframe. But my iframe still not getting the height of content.
My logs are as follows :

[iFrameSizer][Host page: inside_content] [iFrame.onload] Sending msg to iframe[inside_content] (inside_content:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent:scroll) targetOrigin: *

Please help on this

**Comment by clabnet** [comment]
Also for me. My logs are :

```
[iFrameSizer][Host page] IFrame scrolling disabled for dseframe
[iFrameSizer][Host page][init] Sending msg to iframe (dseframe:8:false:true:32:true:true:null:offset:null:null:0:false:parent)
[iFrameSizer][Host page][iFrame.onload] Sending msg to iframe (dseframe:8:false:true:32:true:true:null:offset:null:null:0:false:parent)
```

**Comment by SeanZicari** [comment]
Do you have `iframeResizer.contentWindow[.min].js` being loaded inside the iframe? That is a requirement.

**Comment by mannverma** [comment]
Thanks for reply but i had used message posting instead.

**Comment by davidjbradshaw** [comment]
You need that file inside your iframe.

**Comment by ZacYoutube** [comment]
Hey how do we load the js file inside the iframe?
