### ISSUE TITLE
Why use bottom of taggedElement rather than height?

### ISSUE THREAD

**Issue by arasmussen** [davidjbradshaw/iframe-resizer#357]
I'm using the taggedElement heightCalculationMethod. When my content changes, some of it ends up above the viewport. This results in the following clientBoundingRect.

{bottom: 352, top: -54, height: 406, ...}

This results in a resize to 352px which is incorrect because the height of my content is 406px. So why do we use the bottom of the taggedElement rather than simply using the height?

Any other ideas for workarounds?

**Comment by arasmussen** [comment]
After thinking about this a bit more, I think the algorithm should be:

```javascript
  var rect = el.getBoundingClientRect();
  var maxHeight = Math.max(rect.height, rect.bottom);
```

So for height we'd take `Math.max(rect.height, rect.bottom)` and for width we'd take `Math.max(rect.width, rect.right)`. This will taken into account the case where top is negative.

Thoughts?

**Comment by davidjbradshaw** [comment]
Looks like a good idea. If it works can you make a PR.

**Comment by davidjbradshaw** [comment]
Just read this again. Why not use the min-height option?

https://github.com/davidjbradshaw/iframe-resizer#minheight--minwidth

**Comment by arasmussen** [comment]
Hmm, I don't really see how that would help. My minimum height is 0 which is the default, right?

**Comment by davidjbradshaw** [comment]
Have a look at #373. Has details of test feature to allow you to add custom sizing methods.

**Comment by davidjbradshaw** [comment]
v3.5.5 now has the option to write your own custom method to work out the size.
