### ISSUE TITLE
Autoresizing doesn't work

### ISSUE THREAD

**Issue by Basilews** [davidjbradshaw/iframe-resizer#361]
I did all by instruction: enable 1 file to parent html, 1 for iframed html, turn logs on, but it works only once (on onload). And it doesn't write any logs.

**Comment by Basilews** [comment]
Solved: body has height: 100% in iframed html. Resizing works after deleting this rule.

**Comment by bluesix** [comment]
@Basilews had the same issue - was going completely mad! Thanks!!
