### ISSUE TITLE
Error while adding JQuery public methods

### ISSUE THREAD

**Issue by apu84** [davidjbradshaw/iframe-resizer#362]
If jquery is loaded at page footer and some trick is done make ready function to work before jquery is loaded, like described in here [http://writing.colin-gourlay.com/safely-using-ready-before-including-jquery](http://writing.colin-gourlay.com/safely-using-ready-before-including-jquery) iFrameResizer thorws an exception and stops execution.

Uncaught TypeError: Cannot set property 'iFrameResize' of undefined.

Probably can be fixed if use it like,

if (window.jQuery) {$(document).ready(function () {createJQueryPublicMethod(jQuery);});}

Plunker [link](http://plnkr.co/edit/F5KrLb48BiQeyetTJDXM?p=preview)

**Comment by davidjbradshaw** [comment]
Did you try that? Surely if `$.fn` isn't available, then surely `ready` won't be either.

**Comment by davidjbradshaw** [comment]
Having just read the article, that trick would break just about every jQuery plugin. If you want to do that I'd suggest using requireJS to late load libraries and plugins. Or just load this after jQuery at the foot of your page.

You could also avoid the jQuery 'tax' completely, I've not used it on my last couple of work projects.
http://youmightnotneedjquery.com/

**Comment by davidjbradshaw** [comment]
That said this patch will stop it crashing.
