### ISSUE TITLE
iFrameResize is not defined > When injecting iframe from Chrome Extension after page is loaded 

### ISSUE THREAD

**Issue by lepoulp** [davidjbradshaw/iframe-resizer#363]
A chrome Extension content_script injects on dom1.com (i don't own that page) :

1. The iframe **dom2.com** (i own that one) containing iframeResizer.contentWindow.min.js
2. Then it injects iframeResizer.min.js in **dom1.com**
3. Then it injects a script on **dom1.com** containing 'iFrameResize();'
4. CONSOLE > **Uncaught ReferenceError: iFrameResize is not defined**

Is it an ASYNC issue ? i tried to setinterval iFrameResize or even call it from the console but its always 'not defined'

I have checked and all script load fine.

Because its injected through a browser extension, should i try to place the script elsewhere ?

Here's how my injected code looks (btw i tried without injecting, having all scripts loaded at page load and it worked fine, but beacause i don't own dom1.com i can't do that)

````
<iframe frameborder="0" scrolling="no" src="https://www.dom2.com/script/script.php?blablabla" style="width: 100%;">
<div>SOME DIVE WITH dynamic size</div>
<script type="text/javascript" src="https://www.dom2.com/js/iframeResizer.contentWindow.min.js"></script>
</iframe>
<script src="https://www.dom2.com/js/iframeResizer.min.js"></script>
<script type="text/javascript">iFrameResize();</script>`
```

**Comment by davidjbradshaw** [comment]
I would suggest the problem is that you need to wait for the script to finish loading.

You might get away with changing the last line to.
```js
<script type="text/javascript">setTimeout(iFrameResize,0);</script>
```
Or you might have to poll for it to see when it has finished loading.

**Comment by oneezy** [comment]
the only thing that worked for me was

```
<script type="text/javascript">
	var isOldIE = (navigator.userAgent.indexOf("MSIE") !== -1); // Detect IE10 and below

	iFrameResize( {
	    heightCalculationMethod: isOldIE ? 'max' : 'lowestElement'
	});
</script>
```
