### ISSUE TITLE
Strange error only in IE11

### ISSUE THREAD

**Issue by samithaf** [davidjbradshaw/iframe-resizer#364]
@davidjbradshaw thanks for creating this wonderful library. It simply works in all the use cases except for some reason my application throws really random errors soon after I load the app via an iframe and enable the iframe-resizer. Please see my observations and just wondering these facts and logs gives you any clue what's going on. Thanks for your help!

Tech stack of client app
jQuery 2.0.3, handlebars 1.0 and backbone 1.0.0

Facts
App works fine standalone in all the web browsers
App throws this random error only in IE11 and works fine in IE10 and all the other web browsers.

temp fix:
I have added  `<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10"/>` tag and fixes the issue by running the app in IE10 mode

Logs:

File: test.html
[iFrameSizer][Host page: investor] IFrame scrolling disabled for investor
[iFrameSizer][Host page: investor] [init] Sending msg to iframe[investor] (investor:8:false:true:32:true:true:null:taggedElement:null:null:0:false:parent:scroll) targetOrigin: *
[iFrameSizer][Host page: investor] [iFrame.onload] Sending msg to iframe[investor] (investor:8:false:true:32:true:true:null:taggedElement:null:null:0:false:parent:scroll) targetOrigin: *
[iFrameSizer][Host page: investor] [iFrame requested init] Sending msg to iframe[investor] (investor:8:false:true:32:true:true:null:taggedElement:null:null:0:false:parent:scroll) targetOrigin: *
[iFrameSizer][investor] Initialising iFrame (http://localhost:8000/#app/overview?a=1233)
[iFrameSizer][investor] TargetOrigin for parent set to: *
[iFrameSizer][investor] height calculation method set to "taggedElement"
[iFrameSizer][investor] HTML & body height set to "auto"
[iFrameSizer][investor] Enable public methods
[iFrameSizer][investor] Add event listener: Animation Start
[iFrameSizer][investor] Add event listener: Animation Iteration
[iFrameSizer][investor] Add event listener: Animation End
[iFrameSizer][investor] Add event listener: Input
[iFrameSizer][investor] Add event listener: Mouse Up
[iFrameSizer][investor] Add event listener: Mouse Down
[iFrameSizer][investor] Add event listener: Orientation Change
[iFrameSizer][investor] Add event listener: Print
[iFrameSizer][investor] Add event listener: Ready State Change
[iFrameSizer][investor] Add event listener: Touch Start
[iFrameSizer][investor] Add event listener: Touch End
[iFrameSizer][investor] Add event listener: Touch Cancel
[iFrameSizer][investor] Add event listener: Transition Start
[iFrameSizer][investor] Add event listener: Transition Iteration
[iFrameSizer][investor] Add event listener: Transition End
[iFrameSizer][investor] Create body MutationObserver
[iFrameSizer][investor] In page linking not enabled
[iFrameSizer][investor] Parsed 1 HTML elements
[iFrameSizer][investor] Element position calculated in 1ms
[iFrameSizer][investor] Trigger event lock on
[iFrameSizer][investor] Sending message to host page (investor:0:1584:init)
[iFrameSizer][investor] Trigger event: mutationObserver: [object HTMLBodyElement] childList
[iFrameSizer][Host page: investor] Received: [iFrameSizer]investor:0:1584:init
[iFrameSizer][Host page: investor] Checking height is in range 0-Infinity
[iFrameSizer][Host page: investor] Checking width is in range 0-Infinity
[iFrameSizer][Host page: investor] IFrame (investor) height set to 0px
[iFrameSizer][Host page: investor] Hidden iFrame detected, creating visibility listener
[iFrameSizer][investor] Parsed 1 HTML elements
[iFrameSizer][investor] Element position calculated in 0ms
[iFrameSizer][investor] No change in size detected
[iFrameSizer][investor] Trigger event lock off
[iFrameSizer][investor] --
[iFrameSizer][investor] Trigger event: mutationObserver: [object HTMLBodyElement] childList
[iFrameSizer][investor] Parsed 1 HTML elements
[iFrameSizer][investor] Element position calculated in 0ms
[iFrameSizer][investor] No change in size detected
[iFrameSizer][investor] Trigger event: mutationObserver: [object HTMLDivElement] attributes
[iFrameSizer][investor] Parsed 1 HTML elements
[iFrameSizer][investor] Element position calculated in 0ms
[iFrameSizer][investor] No change in size detected
[iFrameSizer][investor] Trigger event: mutationObserver: [object HTMLDivElement] attributes
[iFrameSizer][investor] Parsed 1 HTML elements
[iFrameSizer][investor] Element position calculated in 0ms
[iFrameSizer][investor] No change in size detected
SCRIPT5022: Parse error on line 1:
<p>{{cms 'Err.IP
---------^
Expecting 'CLOSE', 'CLOSE_UNESCAPED', 'STRING', 'INTEGER', 'BOOLEAN', 'ID', 'DATA', 'SEP', got 'INVALID'
File: handlebars.js, Line: 306, Column: 5
SCRIPT5007: Unable to get property 'show' of undefined or null reference
File: investorController.js, Line: 218, Column: 17
[iFrameSizer][investor] Trigger event: mutationObserver: [object HTMLBodyElement] childList
[iFrameSizer][investor] Parsed 1 HTML elements
[iFrameSizer][investor] Element position calculated in 1ms
[iFrameSizer][investor] No change in size detected

**Comment by davidjbradshaw** [comment]
Looks like a error in your handlebars template to me.

**Comment by samithaf** [comment]
@davidjbradshaw Not really App works fine standalone in all the web browsers including IE11. I am still trying to figure it out what causes rendering engine to act in a strange way soon after I enable the iframe resizer.

**Comment by davidjbradshaw** [comment]
That is your code falling over. I've not seen an issue like this before

**Comment by samithaf** [comment]
@davidjbradshaw finally found the problem and it's actually a bug in IE11 when using Mutation observers. By disable the Mutation observers fixes the problem. https://github.com/talee/mutationobserver-breaks-characterdata
