### ISSUE TITLE
Iframe not shrinking automatically

### ISSUE THREAD

**Issue by qcrtechn** [davidjbradshaw/iframe-resizer#366]
I used "heightCalculationMethod : grow " and Iframe height automatically inrease but it does't shrink when iframe data shrinks.
Here is the [example](http://www.mikesautoglasscharlotte.com/test.html). Please help!

**Comment by davidjbradshaw** [comment]
Clue is in the name 'grow' use 'max' or 'lowestElement' instead.

**Comment by qcrtechn** [comment]
Thanks for getting back. I used all of them still it does't shrink the height. Although it decrease the height when you click on iframe area.

**Comment by qcrtechn** [comment]
my parameters are following 
`log                     : true,                  // Enable console logging
				enablePublicMethods     : true,                  // Enable methods within iframe hosted page
				autoResize : true,
				heightCalculationMethod : "grow",`

**Comment by qcrtechn** [comment]
any suggestion please

**Comment by davidjbradshaw** [comment]
Just had a look at you link and it seems to work in the latest Chrome
