### ISSUE TITLE
Constantly growing in Chrome

### ISSUE THREAD

**Issue by jstevensstein** [davidjbradshaw/iframe-resizer#367]
I am running into an issue where the window is constantly growing in Chrome. Occurs using most of the height calculation methods, and only for some of the height calculation methods will the interval prevent growth (and it usually needs to be relatively large). The window also can never shrink in height in all cases.

Wondering what might be the cause.

**Comment by jstevensstein** [comment]
Pretty sure figured it out... I believe child window kept loading additional content after resizing

**Comment by davidjbradshaw** [comment]
Yep that would do it :)
