### ISSUE TITLE
Meteor support

### ISSUE THREAD

**Issue by Testato** [davidjbradshaw/iframe-resizer#368]
This lib support Meteor ?

**Comment by davidjbradshaw** [comment]
I've never tried it.

**Comment by davidjbradshaw** [comment]
If their is a simple patch I'm open to a PR for it.

**Comment by sahanDissanayake** [comment]
The question i wanted to ask too.. The reason im here isbecause https://github.com/oyvindkinsey/easyXDM/pull/229

Is this plugin the same ? Is this waiting for the document ready event ?

thanks

**Comment by davidjbradshaw** [comment]
It does use document ready as a trigger event, but it's not the only one and it should still work without it firing. I have very little experience of Meteor, I'm open to a PR if you find a simple fix to this problem.

**Comment by rakeshkm2203** [comment]
Hi. I have used your iframe-resizer and it works great. Thank you for sharing it. It works well for cross-platform too. One thing that I noticed is that its not responsive. i.e. I have written separate media query for loading my website on mobiles and tabs, but after using this plugin its just showing a shrunk version  of my desktop view on my mobile. Could you please help me solve this issue.

**Comment by juliomac** [comment]
Dear @davidjbradshaw , I use your wonderful iframe-resizer both ways along with Meteor. Either embedding a Meteor app into static sites or the other way around.  THANK YOU!!!

Embedding Meteor iframes on static sites works the very same way as per your documentation.

To embed iframe on an Meteor app requires no PR from your part either. It just need a trick...

1) Add your ``<iframe src="https://myappORsite"></iframe>``  on your template as you would normally do.
2) Add the iFrameresizer.js on your client folder. No need here to reference it to load on ``<Script>`` tags. This is the standard Meteor way.

3) Add the following onCreate for your template above: 

     Template.yourtemplate.onRendered(function() {
       iFrameResize({log:false,heightCalculationMethod: 'lowestElement'});
    });

**Comment by baberuth22** [comment]
This is not working for me when embedding Meteor iFrames on a static site.  I get a height that grows by about 10px per second.  It seems Meteor reactivity triggers the resize event.

**Comment by juliomac** [comment]
Hi @baberuth22 , the example above is to add an external iFrame on a Meteor site.

To embed a Meteor iFrame on a static site, like in your case, just follow the documentation. That is:
1) Add and load the script:  ``iframeResizer.js`` on static client site.
2) Make sure you add on your Meteor end the file ``iframeResizer.contentWindow.js`` . It will be loaded automatically if you place it on client folder.
3) Initialize the iframe resizer on your static client by placing the following code:

    <script>iFrameResize({log:false,heightCalculationMethod: 'lowestElement'});</script>
IMPORTANT: You must place it at the very bottom of your HTML code. If not working, try change the ``heightCalculationMethod``.

Hope it helps...

**Comment by baberuth22** [comment]
Thanks for the instruction @juliomac.  

I've added this code just before the closing body tag.

`		<script type="text/javascript">
			iFrameResize({
				log                     : true,                  // Enable console logging
				heightCalculationMethod: 'lowestElement',
				enablePublicMethods     : true                  // Enable methods within iframe hosted page
			}, '#booking_frame');
		</script>`

But my iFrame just continually grows.  Any other suggestions?  Here is the console log:

`[iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5249:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5249:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5249px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 2ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5279:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5279:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5279px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 2ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5309:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5309:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5309px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 2ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5339:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5339:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5339px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 1ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5369:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5369:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5369px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 2ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5399:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5399:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5399px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 1ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5429:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5429:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5429px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event: mutationObserver: [object HTMLInputElement] attributes
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Parsed 431 HTML elements
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Element position calculated in 1ms
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock on
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Sending message to host page (booking_frame:5459:1229:mutationObserver)
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Received: [iFrameSizer]booking_frame:5459:1229:mutationObserver
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking connection is from: http://localhost:3000
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking height is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Checking width is in range 0-Infinity
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] Requesting animation frame
iframeResizer.min.js:8 [iFrameSizer][Host page: booking_frame] IFrame (booking_frame) height set to 5459px
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] Trigger event lock off
iframeResizer.contentWindow.min.js?hash=201c85d…:9 [iFrameSizer][booking_frame] --`

**Comment by davidjbradshaw** [comment]
Such issues are almost always related to CSS.

**Comment by baberuth22** [comment]
There was a min-height:80% on one of my divs that was messing up the height.  

But, I ended up using custom code.

On the static page:
`			<script type="text/javascript">

				// Create browser compatible event handler.
				var eventMethod = window.addEventListener ? "addEventListener" : "attachEvent";
				var eventer = window[eventMethod];
				var messageEvent = eventMethod == "attachEvent" ? "onmessage" : "message";

				// Listen for a message from the iframe.
				eventer(messageEvent, function(e) {
					console.log('e: ', e);
					var new_height = e.data.split(':')[1];
					console.log('new_height: ', new_height);
					var set_height = Number(new_height) + 50;
					console.log('set_height: ', set_height);
					document.getElementById('booking_frame').style.height = set_height + 'px';
				}, false);
			</script>`

And I added the chrisbutler:postmessage package to meteor.  Then added an autorun tracker to post the message:

`Template.summary.rendered=function() {

	var instance = this;

	instance.autorun(function () {
		var reservation = Session.get('reservation');
		console.log('Autorun is auto-running!');
		setTimeout( function(){
			var height = $('#homeLayout').height();
		}, 100 );
		
	});
};`

**Comment by juliomac** [comment]
Hi @baberuth22 , so you solved it through a custom solution? Interesting...
