### ISSUE TITLE
iframe grows to infinity in IE

### ISSUE THREAD

**Issue by dukedl** [davidjbradshaw/iframe-resizer#370]
Hi

I have unusual problem...i have in iframe CrushFTP web interface (http://www.crushftp.com/)
when i click on "Advanced upload"(uses java) the height of iframe in IE(tested in v11) grows and it does not stop. This is not the case in Firefox.

i run resizer with:

> 	$('#iframe1').iFrameResize( {
		log:true,
		checkOrigin:false,
		heightCalculationMethod: (navigator.userAgent.indexOf("MSIE") !== -1) ? 'max' : 'lowestElement'
	});

Please find (only part of) console output -> [ifrs.txt](https://github.com/davidjbradshaw/iframe-resizer/files/298410/ifrs.txt) for troubleshooting

Any idea what is wrong?

Thank you for your time and help.

**Comment by davidjbradshaw** [comment]
This is normally a CSS issue. Do you have an element that in IE is alway a few px more than the height of the page?

**Comment by dukedl** [comment]
No. At least i dont think so. Page stays as it is.

Because when i open CrushFTP webinterface without iframe and do the same operation, everything is ok, it does not grow in height. Is there a way to see in console which element(name, id...) is causing this?

```javascript
[iFrameSizer][iframe1] Trigger event: mutationObserver: [object HTMLDivElement] attributes
```
probably HTMLDivElement ?

**Comment by davidjbradshaw** [comment]
But when you open it without an iFrame you don't have some JS constantly checking the size of the page and trying to keep the window the same size. Trust me I'm 99% sure it is a CSS problem.

**Comment by dukedl** [comment]
hmmm, you are probably right. Andy idea how to fix this or steps i should take?

**Comment by davidjbradshaw** [comment]
Have a look at the page outside the iFrame with the browser debug tool and look to see if you can spot the problem element.
