### ISSUE TITLE
height resize doesn't work in IE 11

### ISSUE THREAD

**Issue by Basilews** [davidjbradshaw/iframe-resizer#371]
height resize doesn't work only in IE 11

**Comment by davidjbradshaw** [comment]
Any more details than that?

**Comment by rorygeo** [comment]
First, just to say, David, a great plugin - so thank you for putting this out there.

I was recently struggling a little with IE11 and iframe-resizer and just in case this helps anyone else, you need to ensure that if you are seeking to direct a specific iframe then do ensure that the iframe_name is in quotes and appropriately specified, e.g.

DOESN'T WORK ON IE11/SAFARI: iFrameResize({log:true, inPageLinks:true}, iframe_name);
DOES WORK: iFrameResize({log:true, inPageLinks:true}, '#iframe_name');

This may be obvious, but it may be helpful to anyone suffering issues with IE11 and iframe-resizer, particularly if they are seeing 'exception thrown but not caught' errors in the Developer Console in IE.
