### ISSUE TITLE
Iframe resizes influences XML parsing?!

### ISSUE THREAD

**Issue by amenk** [davidjbradshaw/iframe-resizer#372]
I have the problem, that IE 11 is parsing XML wrong (when there is a hyphen).

See also my stackoverflow post:

http://stackoverflow.com/questions/37655982/internet-explorer-xml-parsing-wrong-at-hypens-and-cant-make-repro-example?noredirect=1#comment62791409_37655982

The XML parsing is happening inside of the iframe.

Now as soon as I disable the iframe resizer, the XML parsing works properly.

Any idea how this strange effect could be caused?

**Comment by davidjbradshaw** [comment]
Wow, that's a new one on me.

IE11 seems to have updated recently and broken a few things. Going to try and take a look later this week hopefully when I have some spare time. Not sure I know where to start with this one though.

Do you have a simple test case?

**Comment by amenk** [comment]
good idea :-)

**Comment by amenk** [comment]
FYI
Somebody reproduced that IE bug
https://github.com/talee/mutationobserver-breaks-characterdata
http://stackoverflow.com/a/39156496/288568
