### ISSUE TITLE
iframeResize.moveToAnchor() not working (@3.5.4)

### ISSUE THREAD

**Issue by sebaplaza** [davidjbradshaw/iframe-resizer#374]
When moveToAnchor() is called from the parent, the iframe is not processing the message.

This method send a messageType : 

> **inPageLink**

Then in iframeResizer.contentWindow.js there is no an event for inPageLink ... so... nothing happen.

```
	function callFromParent(){
			switch (getMessageType()){
			case 'reset':
				resetFromParent();
				break;
			case 'resize':
				resizeFromParent();
				break;
			case 'moveToAnchor':
				moveToAnchor();
				break;
			case 'message':
				messageFromParent();
				break;
			case 'pageInfo':
				pageInfoFromParent();
				break;
			default:
				if (!isMiddleTier() && !isInitMsg()){
					warn('Unexpected message ('+event.data+')');
				}
			}
		}
```

If i call moveToAnchor() in : 
```
			case 'moveToAnchor':
				moveToAnchor();
```

everything works as expected.

**Comment by davidjbradshaw** [comment]
That looks like a very old version. Try upgrading.

On Mon, Jun 13, 2016 at 5:35 PM, Sebastian Plaza <notifications@github.com>
wrote:

> When moveToAnchor() is called from the parent, the iframe is not
> processing the message.
>
> This method send a messageType : inPageLink
>
> Then in iframeResizer.contentWindow.js there is no an event for inPageLink
> ... so... nothing happen.
>
> If i call manually this section moveToAnchor() in :
>
>             case 'moveToAnchor':
>                 moveToAnchor();
>
> everything works as expected.
>
>     function callFromParent(){
>             switch (getMessageType()){
>             case 'reset':
>                 resetFromParent();
>                 break;
>             case 'resize':
>                 resizeFromParent();
>                 break;
>             case 'moveToAnchor':
>                 moveToAnchor();
>                 break;
>             case 'message':
>                 messageFromParent();
>                 break;
>             case 'pageInfo':
>                 pageInfoFromParent();
>                 break;
>             default:
>                 if (!isMiddleTier() && !isInitMsg()){
>                     warn('Unexpected message ('+event.data+')');
>                 }
>             }
>         }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/374>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAkHErdftOpYVpg-j9DnmjjrV8CT_d0Fks5qLYbMgaJpZM4I0guo>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

'The people we think are a little weird are the ones who change the world'
- Simon Sinek

**Comment by davidjbradshaw** [comment]
Seems I misunderstood you, do you have a link you can share with me.

**Comment by davidjbradshaw** [comment]
Hmm, looks like you might be the first person ever to use that :) Yep that's a bug.

**Comment by davidjbradshaw** [comment]
Can you try the dev branch version and let me know if that fixes things for you, before I make a formal release.

**Comment by sebaplaza** [comment]
I confirm, it's working after your commit.
Thanks !

**Comment by sebaplaza** [comment]
Waiting for the release :simple_smile:

**Comment by davidjbradshaw** [comment]
v3.5.5
