### ISSUE TITLE
Twitter/MutationObserver issue

### ISSUE THREAD

**Issue by ile** [davidjbradshaw/iframe-resizer#375]
Hi,

If I embed a tweet in an iframe, there seems to be a resizing issue. I tracked it into here: https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L608-L613

What seems to happen, is that the iframe gets a mutation event. The mutation event is about the removal of this Twitter's `<blockquote>` element. But when the event happens, the blockquote is still in the html structure. So, the size of the iframe ends up larger than it should be.

Another issue is, that the iframe will gradually be resized into the correct size when you click on the wrongly-sized iframe. This is quite distracting/seems wrong. I could make a video if this isn't apparent.

Two test html files attached. [test1.zip](https://github.com/davidjbradshaw/iframe-resizer/files/337458/test1.zip)

**Comment by davidjbradshaw** [comment]
Try putting setTimeout 0 around line 609. 

I'm on holiday for the few weeks, so not likely able to take a look for a bit.

**Comment by ile** [comment]
Yes, I did that. 10 didn't help, but 100 helped.

**Comment by davidjbradshaw** [comment]
Very odd.

**Comment by ile** [comment]
Yes, 10 doesn't seem to work but 100 does, tested again... A bit inconvenient for sure, doesn't feel too robust...

**Comment by davidjbradshaw** [comment]
Is it only one browser?

As a short term hack fire it at 32, 64, 96 and 128 ms. Which is every two frames.

**Comment by ile** [comment]
Seems to be only in Chrome (and maybe Chromium etc.). Firefox seems to work without the workaround.

64 ms seems to work, 32 ms didn't yet work. Thanks.

**Comment by davidjbradshaw** [comment]
This is likely a bug in Chrome then, would be worth raising a bug with them if you can make a simpler test case.

**Comment by ile** [comment]
Yes, I could try to do that. You can too, if you have a test case that is easily doable.

**Comment by ile** [comment]
I was wrong about the cause of this. It's still not working, but MutationObserver wasn't the cause.

It seems that resizing itself causes the problem. Resizing seems to affect body.offsetHeight, which ends up "sticking" to the value set by the parent, even though the size of the content of the iframe has been changed.

Try these files to reproduct the issue: [example.zip](https://github.com/davidjbradshaw/iframe-resizer/files/379828/example.zip)

**Comment by davidjbradshaw** [comment]
Have you tried the difference sizing methods?

**Comment by ile** [comment]
Yes, but I didn't find a one that would work. However, this would work: `getMaxElement('bottom',getAllElements())` but I needed to change the source code to do that only.

Not sure if that would be a good fix overall, but it would work on this case.

**Comment by davidjbradshaw** [comment]
The latest version has the option to pass in your own custom sizing method.

https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod--widthcalculationmethod
