### ISSUE TITLE
Do not touch iframes that don't pass checkOrigin

### ISSUE THREAD

**Issue by arasmussen** [davidjbradshaw/iframe-resizer#376]
I'm having an issue where an unrelated `iframe` gets the following attributes set: `scrolling="no" id="iFrameResize0"`. If this `iframe` doesn't pass `checkOrigin`, why modify it? :/

```javascript
iFrameResize({
  checkOrigin: ['https://productpains.com'],
  heightCalculationMethod: 'taggedElement',
  log: false,
});
```

**Comment by davidjbradshaw** [comment]
Pass in the ID of the iFrame you wish to use, or use the jQuery version for selecting them by class name.
