### ISSUE TITLE
Feature request: ignoring warnings in setupIFrame()

### ISSUE THREAD

**Issue by ile** [davidjbradshaw/iframe-resizer#377]
I'm calling `iFrameResize()` multiple times on the same page - every time a new iframe is added. There seem to be a warning `[iFrameSizer][Host page: iFrameResizer1] Ignored iFrame, already setup.` for the old iframes. 

I couldn't quickly find a way to ignore/suppress these warnings. Also not sure if I should be calling `iFrameResize()` or do something else, but calling that seems to work for resizing the new iframes. It's just the warning that I would like to silence. 

Maybe turn it into `log()`?

**Comment by davidjbradshaw** [comment]
Pass the ID of the new iFrame
