### ISSUE TITLE
Change domain adress via iframe src

### ISSUE THREAD

**Issue by webseocz** [davidjbradshaw/iframe-resizer#378]
Thank you for iframe resizer - I use it with no problems.
But today I have this trouble: 
I have iframe with src affiliate link. All is ok, but if I click on the link in included affil page and the address of domain is changed, the height of iframe with new domain is not calculated. New domain has resizer scripts of course....And I tested new domain in its own iframe - Its ok. But if I use link on new dom via iframe it doesnt calculate height.
Can give me advice how should I solve it please? [I apologize for my English] thx

**Comment by davidjbradshaw** [comment]
Have a look at the checkOrigin option in the docs.

**Comment by webseocz** [comment]
Solved, thank you very much!! :)
