### ISSUE TITLE
Resize before/after printing on webkit browser

### ISSUE THREAD

**Issue by M21B8** [davidjbradshaw/iframe-resizer#379]
the contentWindow.js adds listeners for beforeprint and afterprint, however this is not supported by webkit browsers. It would be useful if this could be built in to the library, possibly with something like the snippet below.

```
if (window.matchMedia) {
  var mediaQueryList = window.matchMedia('print');
  mediaQueryList.addListener(function(mql) {
    if (mql.matches) {
       // before print
    } else {
      // after print
    }
  });
}
```

**Comment by davidjbradshaw** [comment]
Unsupported listeners are just ignored, so no need to test for them.

**Comment by M21B8** [comment]
@davidjbradshaw Not sure I quite understand why this was closed. I wasn't saying the unsupported listeners cause problems, I was asking why can't we have a different listener added to cater for webkit browsers?
