### ISSUE TITLE
Anchor links in iFrame not working

### ISSUE THREAD

**Issue by steezeburger** [davidjbradshaw/iframe-resizer#380]
The app being embedded in an iFrame uses anchor tags to scroll to different menu categories. 

The issue is that these scrollTo's simply don't happen, but only in iOS. Android and Desktop appear to be working completely fine.

For scrollTo I'm using https://github.com/fisshy/react-scroll, a react library to help with some scroll stuff. I believe it uses standard scrollTo under the hood, and I've tried scrolling with `window.scrollTo` manually as well.

 I've tried a few different fixes including calling `parentIFrame.moveToAnchor(category);` in my application instead of using the scrollTo. This scrolls the parent window down to where that category would be, but the iframe container does not scroll with it to show that content in the actual iframe area.

Here is my setup

    iFrameResize({
        scrolling:true,							
        sizeHeight:false,
        log:true,
        initCallback:function(iframe){
        if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) {
            window.scrollTo(0,0);
            }
        },
    });

I've also noticed that a scroll listener I had on the app does not "hear" any scroll events so other UI is not acting properly. 

I'm not sure if these are related, due to bad config or my lack of understanding of the library, but I thought you might be able to point me in the right direction.

**Comment by davidjbradshaw** [comment]
Sounds like an iOS bug to me, sorry not seen the issue before.

**Comment by Bioelite-Vert** [comment]
Any fix on this?
