### ISSUE TITLE
No resizes the height of the frame

### ISSUE THREAD

**Issue by ojedawinder** [davidjbradshaw/iframe-resizer#382]
I have a site A which contains a frame with the content of the site B and is not automatically resizes , and try changing the value of heightCalculationMethod and always gives me the same size , the log always shows me the following :

1.[iFrameSizer][Host page: iFrameResizer0] Added missing iframe ID: iFrameResizer0 ()

2.[iFrameSizer][Host page: iFrameResizer0] IFrame scrolling disabled for iFrameResizer0

3.[iFrameSizer][Host page: iFrameResizer0] [init] Sending msg to iframe[iFrameResizer0] (iFrameResizer0:8:false:true:32:true:true:null:lowestElement:null:null:0:false:parent:scroll) targetOrigin: *
only that.

Resume

**Site A:** **Domain:** a.com **Library:** iframeResizer.js and iframeResizer.contentWindow.js

**js :**

```
iFrameResize ({
    log : true,
    heightCalculationMethod : ' lowestElement ',
    checkOrigin : false
});
```
**html:**

  ` <iframe ng-src="{{url}}" width="100" frameborder="0"     scrolling="yes"></iframe>`
where url is a variable that contains the url of the site B

**Site B:** **Domain:** b.com **Library :** iframeResizer.contentWindow.js

**Comment by davidjbradshaw** [comment]
Put the second JS file in your iFrame.

**Comment by ojedawinder** [comment]
Hi David, the file iframeResizer.contentWindow.js is in both sites, in where is the frame and in the other. for that i do not know which is the problem..
