### ISSUE TITLE
Height not changing when window is resized (stays at shrink state and not expanding)

### ISSUE THREAD

**Issue by rustedsoul** [davidjbradshaw/iframe-resizer#384]
A parent page, let's say, www.maingames.com has an iframe page happywheelsgames.com and loads perfectly using this plugin. The frame page has a modal inside, and changes the body height in every click of the anchor links inside (just doing show and hide here displaying lists and grid of data).

However, the problem occurred when the user loads the site, in minimized window (not full screen), then opens the modal (and also after they closed it), and maximizes the browser window, it stays on its "shrink" state and not expanding the whole iframe like it used to.

Here's my code:

```js
var windowHeight = window.innerHeight || document.documentElement.clientHeight;
var headerHeight = $(".header").outerHeight();
var footerHeight = $(".footer").outerHeight();
var contentHeight = windowHeight - (headerHeight + footerHeight);

$("iframe.gamesData").on("load", function() {
  $(this).iFrameResize({
    heightCalculationMethod: 'max',
    minHeight: contentHeight
  });
});
```

I also tried using **lowestElement** and **taggedElement** but it's not resizing even on the loading of the page. I also tried inserting another iFrameResize function inside a "$(window).on("resize", function ()" but it returns a warning saying something like "iFrame already setup. Ignore [FrameName]", and not actually resizing. I believe there's already a "resize" function inside the plugin, pls correct me if I'm wrong.

Any suggestion or piece of advice is very much appreciated.
![iframeresizer-issue](https://cloud.githubusercontent.com/assets/20450009/16826335/26e0c444-49af-11e6-8d6e-367d6795a00b.jpg)

Thanks!

**Comment by davidjbradshaw** [comment]
You can force the iFrame to resize from the parent page as follows.

    document.getElementById('myIFrame').iFrameResizer.resize();

**Comment by rustedsoul** [comment]
Thanks for the reply! Sadly, the problem still occurs! 

Yes, I did put the code below and forced the frame to resize from its parent but it's not working on my end.

Btw, I put it inside a resize event on my JS.

Please advise and thank you!

**Comment by rustedsoul** [comment]
I edited the code and added the iFrameResize to a separate function with a parameter so it'll dynamically change the minHeight.

What I did so far:

`var windowHeight = window.innerHeight || document.documentElement.clientHeight;
var headerHeight = $(".header").outerHeight();
var footerHeight = $(".footer").outerHeight();
var contentHeight = windowHeight - (headerHeight + footerHeight);

function callFrame (content) {
var newHeight = content;

$("iframe.gamesData").iFrameResize({
heightCalculationMethod: 'lowestElement',
minHeight: newHeight ,
});
}

$(window).bind('resize', function() {
var windowHeight = window.innerHeight || document.documentElement.clientHeight;
var contentHeight2 = windowHeight - (headerHeight + footerHeight);

callFrame (contentHeight2);
});
`

I almost thought it's perfect but yeah, the console warning saying "iFrame already setup. Ignored" something pops out again.

Is there a way I can do this from your perspective/iFrameResize perspective? I tried using the one you mentioned (document.getElementById('myIFrame').iFrameResizer.resize();) but it says undefined function.

Thanks!

**Comment by axew3** [comment]
if i've well understand your problem, to solve you should change the _heightCalculationMethod_ for example to:
heightCalculationMethod:'bodyScroll'
but there are more if it do not fit your needs. This should resolve.

**Comment by davidjbradshaw** [comment]
@rustedsoul you have to change `myIFrame` to the id of **your** iFrame.

**Comment by ltkhuong7** [comment]
I have got same issue as @rustedsoul.

URL change, the resize works well, but when the content height change (using angular to change the UI-Route state) it does not resize.

[iFrameSizer][corepratice-iframe] Trigger event: Mouse Up
VM10328 iframeresizer.contentwindow.js:150 [iFrameSizer][iframe] Parsed 338 HTML elements
VM10328 iframeresizer.contentwindow.js:150 [iFrameSizer][iframe] Element position calculated in 2ms
VM10328 iframeresizer.contentwindow.js:150 [iFrameSizer][iframe] No change in size detected

**Comment by davidjbradshaw** [comment]
If you can create a simple test case I will have a look. Expect their might be some race condition happening.

**Comment by ltkhuong7** [comment]
I am sorry, your IFrameResizer has been fine.
I have found out a problem from my javascript. It conflicts with yours.
