### ISSUE TITLE
Use case where resize doesn't happen

### ISSUE THREAD

**Issue by dsimoes** [davidjbradshaw/iframe-resizer#386]
Hi,

I have a typical setup (crossdomain) where everything works as expected. Illustration:

1) Initialize IFrame to a.html
2) a.html hyperlinks to b.html
3) Resize is triggered uppon loading b.html, test OK

Both a.html and b.html load up iframeResizer.contentWindow js.

But in this particular case it fails:

1) Initialize IFrame to a.html
2) a.html hyperlinks to diagram.svg
3) diagram.svg hyperlinks to b.html
3) Resize for b.html is not triggered, test NOK.

I get no error logs from iFrameSizer after loading b.html. iframeResizer.contentWindow.js is loaded for b.html.

Is there anyway to solve this?

Thanks for the help.

**Comment by davidjbradshaw** [comment]
What version are you using? When b.html loads it should fire the onLoad event on the parent page and the most recent version, as a backup, b.html will also send the parent a message saying it has loaded.

**Comment by dsimoes** [comment]
I'm using v3.5.5.

The target application is quite peculiar.. I did some JS code changes on the target and it seems to be to be triggering correctly. I do get sometimes an issue where the iframe is refreshed and the resize is only triggered some seconds after (but i'ts rare).
Also, i'm loading the contentWindow.js with Javascript and not declarative, which also can have some side effects.
So i guess this is a non issue.

Just a quick question, if i want to "force" a resize from the target site, I should do this? :
parentIFrame.size();

Thanks for the help.

**Comment by davidjbradshaw** [comment]
Yep, but wrap it in a test for parentIFrame, in case the page loads outside the iFrame
