### ISSUE TITLE
Plugin does not work in Microsoft Edge and Internet Exporer 11

### ISSUE THREAD

**Issue by Harrix** [davidjbradshaw/iframe-resizer#387]
Plugin does not work in Microsoft Edge and Internet Exporer 11. For example, does not work  **index.html** from **example**. Windows 10.

![Screenshot](https://habrastorage.org/files/e9a/c36/808/e9ac36808bf94e4b8b707524feeac079.jpg)

**Update**
![Screenshot 2](https://habrastorage.org/files/7b3/f51/107/7b3f51107f9c483ab772f0b46a796ccc.jpg)

**Comment by davidjbradshaw** [comment]
If your running it on your local file system, some browsers require you to set the `checkOrigin` option to false. Should be ok from a remote server without this option.
