### ISSUE TITLE
Works cross-domain, but on same domain I get `Invalid target origin 'about:blank' in a call to 'postMessage'.`

### ISSUE THREAD

**Issue by ryana** [davidjbradshaw/iframe-resizer#388]
Hey there,

When I first started using this library, I had my local app (`my-app.dev`) hosting the content, and I was loading the iframe on another domain (`my-test-app.herokuapp.com`) to make sure it worked cross-domain. To my delight, it worked immediately the first time. Yay!

But then I went to embed the iframe on the same domain, and I started getting this error about the targetOrigin being `about:blank`:

```
[iFrameSizer][Host page: ma8a3c1b436e7cd6fdc36f2a160e3c4e4d440ad87-container] [init] Sending msg to iframe[ma8a3c1b436e7cd6fdc36f2a160e3c4e4d440ad87-container] (ma8a3c1b436e7cd6fdc36f2a160e3c4e4d440ad87-container:8:false:true:32:true:true:null:bodyOffset:null:null:0:false:parent:scroll) targetOrigin: about:blank
iframeResizer.min.js:8 Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'about:blank' in a call to 'postMessage'.
```

Not sure if this matters, but I'm hosting iframeResizer.min.js on S3, and I'm loading everything with `//` (vs. `https://` or `http://`) to ensure protocols match.

Not sure where to go here, but I'll keep hacking and report back what I uncover.

**Comment by ryana** [comment]
* Correction: I'm loading the iframeResizer.min.js off S3 with `https` always.

**Comment by davidjbradshaw** [comment]
It's a bug in the browser and can be ignored.

**Comment by ryana** [comment]
Yeah but it's not actually working. The frame doesn't get resized. Maybes it's just a coincidence and a problem elsewhere on my end. I'll look around and see if I can isolate it. Thanks for the quick reply!

**Comment by ryana** [comment]
Just to follow up here, I ended up rendering this view in a completely blank layout (ie. just `<html><body><%= yield %></body></html>`) and it worked just perfectly. There's not even an error in the console, so there is something is going on with the code in my layout. I will close this for now, but I'll also follow back up and comment on this thread when I figure out what is causing my problem in case someone else runs into it.

**Comment by ryana** [comment]
Ah! I was using HelloBar and it embeds an iframe with `src="about:blank"`. I was calling `window.iframeResize()` and not using the selector option. When I add a class it works: `iFrameResize({}, "iframe._my-special-widget-iframe")`

Hope this helps someone else!

**Comment by davidjbradshaw** [comment]
Thanks for the follow up
