### ISSUE TITLE
ie11 continteously increases the height of the iFrame by 64px

### ISSUE THREAD

**Issue by Jotswana** [davidjbradshaw/iframe-resizer#395]
Hi David,
thanks for creating this wonderful library. I encountered a problem in ie11 and tried a lot to fix it. I currently run out of ideas. I allready checked most of the resolved issues but nothing helped. Everything works fine on all plattforms and Browsers (also in ie10), but in ie11 I get this strange error. 

Whenever I click on the iFrame, the size of the iFrame gets added to the current size. So with each click the size increases by 64px, allthough the size of the iFrame doesn't change. I appreciate any suggestions from anybody.

Kind regards
Jotswana

**Comment by davidjbradshaw** [comment]
This will be an CSS bug in IE11, one element is being sized to be 64px
below the bottom of the page and this greats a loop.

Check your CSS.

**Comment by Jotswana** [comment]
Thank you very much. I found at least a problem on the implemented page. I thought their code was w3 conform, but the HTML is corrupt. An implementation with another test iframe is working properly now. I checked this earlier, but stubmled over my own caching.

You rock, thank you very much
