### ISSUE TITLE
How do you disable the console.logs?

### ISSUE THREAD

**Issue by lizshannon** [davidjbradshaw/iframe-resizer#399]
The 'log' value is already set to false and yet I'm still getting console.log messages. How do I get rid of the following messages from the console log:

`iframeResizer.min.js?ocsamk:8[iFrameSizer][Host page: iFrameResizer0] Added missing iframe ID: iFrameResizer0
iframeResizer.min.js?ocsamk:8[iFrameSizer][Host page: iFrameResizer0] IFrame scrolling disabled for iFrameResizer0
iframeResizer.min.js?ocsamk:8[iFrameSizer][Host page: iFrameResizer0] [init] Sending msg to iframe[iFrameResizer0] 
iframeResizer.min.js?ocsamk:8 [iFrameSizer][Host page: iFrameResizer0] [iFrame.onload] Sending msg to iframe[iFrameResizer0] (iFrameResizer0:8:false:true:32:true:true:null:bodyOffset:null:null:0:false:parent:scroll) targetOrigin: [url]
iframeResizer.min.js?ocsamk:8 [iFrameSizer][Host page: null] Ignored: {"name":"resize","data":{"height":heightvalue}}
3iframeResizer.min.js?ocsamk:8 [iFrameSizer][Host page: window] Trigger event: focus
iframeResizer.min.js?ocsamk:8 [iFrameSizer][Host page: document] Trigger event: Visiblity change
iframeResizer.min.js?ocsamk:8 [iFrameSizer][Host page: window] Trigger event: focus`

**Comment by davidjbradshaw** [comment]
Remove the attribute

**Comment by maksimhodasevich** [comment]
also while rendering package consoles random number of messages like this 
![image](https://user-images.githubusercontent.com/47758224/95427608-7df25800-0950-11eb-8eb7-17711d18359f.png)

**Comment by davidjbradshaw** [comment]
@maksimhodasevich that message is nothing to do with this package
