### ISSUE TITLE
iFrames Not Resizing at all...

### ISSUE THREAD

**Issue by safetypins** [davidjbradshaw/iframe-resizer#40]
Not sure if this is the best place to ask this question, because I don't think this is a problem with your plugin. I'm embedding some HTML forms that I don't have control over inside a web page, and as far as I can tell, I'm doing everything right. However, when I load the page, I see a number of "blocked a frame with origin "..." from accessing a cross-origin frame. Since these messages are from the domain hosting the iframe content, it seems likely this has nothing to do with your code or my code, but the content is trying to do something it shouldn't and I can't help but wonder if this is jacking up the resizing process. Does this make sense? Do you have any advice for working around this? Can I get you any info that might help? I am using jQuery 1.10.2, and this site is not currently live anywhere public.

**Comment by Fairyshi** [comment]
it will work by add the second step of the "Getting started" in the offical doc. That is add the "iframeResizer.contentWindow.min.js" doc into the iframe content page
