### ISSUE TITLE
infinite call

### ISSUE THREAD

**Issue by khalilof** [davidjbradshaw/iframe-resizer#410]
Hello
I have an issue in IE 11, regarding some infinite DOM change, and when I toggle the debug
it shows me an infinite call for the below code

`	setInterval(function(){
				var queuItem = pluginInstance.resizeEventQueue.dequeue();
				if(queuItem != undefined){
		  			try {
		  				queuItem.call();
		  			}
					catch(err){
						_error(err);
					}
				}
			}, settings.dequeueInterval);`
which is in jquery.frameresizer.js

an ideas ?

by the way this happens in all browsers, but only IE gets messy

**Comment by davidjbradshaw** [comment]
Erm that code is't from this project.

**Comment by davidjbradshaw** [comment]
Also the file name isn't from this project either
