### ISSUE TITLE
Iframe resizer does not work when global function AMD "define" exists in other js library called duel.js

### ISSUE THREAD

**Issue by neerajsrivastava** [davidjbradshaw/iframe-resizer#415]
I have created a HTML page and used iframe-resizer library on it with duel.js library, but iframe could not resized on the page and  scroll visible with iframe.
In JS console it return error that "iFrameResize is not defined."

In  "iframeResizer.min.js"  file used below condition.

```
if (typeof define === 'function' && define.amd) {
    define([],factory);
} else if (typeof module === 'object' && typeof module.exports === 'object') { //Node for browserfy
    module.exports = factory();
} else {
    window.iFrameResize = window.iFrameResize || factory();
}
```

while define is already defined in the duel.js file once I comment below mentioned line then frame resizer works fine.
`//"typeof define === 'function' && define.amd"`

Thanks for this great toolkit/component!

**Comment by davidjbradshaw** [comment]
That is a bug in duel then, it would appear that it is creating a function
called define in the global name space. That will break any AMD module.



-- 
Sent from my iPhone.
