### ISSUE TITLE
window.parentIFrame no longer being set?

### ISSUE THREAD

**Issue by ggsp** [davidjbradshaw/iframe-resizer#418]
Hi David, I've been using (and loving!) iframe-resizer for about a year now. Suddenly I've noticed something really weird: it looks like `window.parentIFrame` isn't being set on the parent window at all – not even on your [example page](http://davidjbradshaw.com/iframe-resizer/example/). Only noticed this because an `if('parentIFrame' in window)` type check has begun failing, without there being any code change on my side. This seems to be happening from anywhere I test, so I don't think it's a local issue either. Am I crazy?

**Comment by davidjbradshaw** [comment]
Strange, just tried the example page in Chrome 53 and 54 without problem. Do you just see the issue in one browser?

**Comment by ggsp** [comment]
I'm seeing this issue both across browsers and machines. So far I've tested locally on two different Macs using Chrome 54 and Firefox 49, and via BrowserStack using different versions of Chrome, IE and Firefox on both a Mac and a PC, but to no avail: every time I give the console `window.parentIFrame`, I get `undefined`. Meanwhile, `window.iFrameResize` initialises correctly.  I noticed the issue because a client told me a behaviour was no longer triggering, so they seem to be seeing the same issue.

**Comment by jtlocsei** [comment]
I'm experiencing the same issue

**Comment by jtlocsei** [comment]
My bad, please ignore my previous comment. I was calling window.parentIFrame before it was loaded. It works as expected when calling from inside readyCallback.

**Comment by ggsp** [comment]
@davidjbradshaw I'm sorry to pester you with this, but as a sanity check, could you confirm that only `window.iFrameResize` initializes at https://utopia.de/nachhaltige-stellenangebote/, while `window.parentIFrame` doesn't?

**Comment by shaynasymons** [comment]
I'm not @davidjbradshaw but I'm following this thread as I've had a similar issue.  I can confirm that window.parentIFrame returns as undefined in the console on the link you posted.

**Comment by ggsp** [comment]
@shaynasymons thank you for checking that! Given that there could be any other kind of mistake on my side in the environment I linked to, do you see the same behaviour on [David's example page](http://davidjbradshaw.com/iframe-resizer/example/)?

**Comment by shaynasymons** [comment]
@ggsp Yes, it returns as undefined there, as well.  It also returns as undefined in my project on every page unless I call it in the readyCallback function.

**Comment by davidjbradshaw** [comment]
You need to test it in the iFrame, not on the parent page.

**Comment by jtlocsei** [comment]
Also what I noticed is that you need to wait for the iframe to fully load and resized before window.parentIFrame is available. So, either you need to call it from inside readyCallback or for testing purposes you could call it after a timeout to make sure the iframe has loaded.

**Comment by JohnBergAndersen** [comment]
Had same problem with missing window.parentIFrame. 
Found out, that I needed to set enablePublicMethods: true for iFrameResize in the parent window like this:.

iFrameResize({ 
	log : true, 
	checkOrigin: false,
	enablePublicMethods : true,
	messageCallback : function(messageData){
		if('Reload' === messageData.message){
			location.href = location.href;
		}
	}
});

**Comment by davidjbradshaw** [comment]
Since v3 there is no need to set that option.

You also don't need the messageCallback.

**Comment by harryfear** [comment]
Why does "window.parentIFrame" stop becoming available after navigation within the iFrame itself? After a user clicks on a HREF to change page within the iFrame, "window.parentIFrame" disappears and becomes undefined?

**Comment by davidjbradshaw** [comment]
You have to have the iframe page is file in every page you load into the iframe

**Comment by harryfear** [comment]
You're right. Rookie mistake. The .js wasn't being loaded on requests properly!
