### ISSUE TITLE
Fixed postion inside an iframe?

### ISSUE THREAD

**Issue by cholokla** [davidjbradshaw/iframe-resizer#419]
Hello and thanks for the work you've done on that masterpeace :)

I've a question what can be done with elements inside the iframe which are using fixed positioning?
For example, I have an iframe with height larger than the browser's window height and I scroll it down straight to the bottom. When I open modal dialog (bootstrap) with 'position:fixed; top:0' inside the iframe it will be created outside of the browser's window ;(

**Comment by davidjbradshaw** [comment]
Fixed elements have to be placed in the parent page.
