### ISSUE TITLE
Bootstrap tabs

### ISSUE THREAD

**Issue by svdg** [davidjbradshaw/iframe-resizer#420]
Very nice script! However, I have an issue with Bootstrap tabs.

I have three Bootstrap (3) tabs. In each tab pane is iframe content (same server).

When I initially load the page, the height adjustment to the content in the first tab is OK. But when I click the second or third tab, the iframe is way too high: only after clicking on the tab content, the height adjusts. How to solve this?

**Comment by davidjbradshaw** [comment]
When you change tab call the resize method from JavaScript on the parent
page. See the docs for how to do this.

**Comment by svdg** [comment]
I have read the docs, but not sure how to do this...

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#resize

```js
myIFrame.iFrameResizer.resize()
```
