### ISSUE TITLE
define.amd is present in browser, iFrameResize is undefined

### ISSUE THREAD

**Issue by dfelix86** [davidjbradshaw/iframe-resizer#425]
if (typeof define === 'function' && define.amd) {
		define([],factory);
}

this option is not working some of the websites, i checked in the console as well

Steps to reproduce, 

Go to Facebook.com
open console
paste the iframeResizer.js in the console and hit enter

now check iFrameResize object is still undefined, please let me know what is the issue, i am facing this with some website which having below object
define.amd
Object { vendor: "dojotoolkit.org"__proto__: Object... }

**Comment by davidjbradshaw** [comment]
Looks like a bug with the Dojo toolkit.

**Comment by xijo** [comment]
Same problem here. 

Can you give us some more details about the bug within the Dojo toolkit @davidjbradshaw ? Maybe a link to their issue or some bug tracker? That would make it easier to find out what the problem is and when it might be resolved.

Thanks in advance :+1:

**Comment by aarcro** [comment]
Seriously. I've just spent 2 hours in the debugger to figure out that iframe-resizer isn't quite getting initialized correctly. It would be great to have any idea what's going on here, or that there's a way to fix it.

**Comment by aarcro** [comment]
Anyone who ends up here in the future #468 Has more information.
