### ISSUE TITLE
clearFix related options

### ISSUE THREAD

**Issue by giovdk21** [davidjbradshaw/iframe-resizer#427]
Hello,
from the changelog:

> Inject clearFix into 'body' to work around CSS floats preventing the height being correctly calculated.

As far as I can see now injectClearFixIntoBodyElement is called regardless and there is no option to customise it / not have it.

For example, when using taggedElement, couldn't the clearFix div also have the data-iframe-height attribute?

Or if for some reason I have my own element having data-iframe-height that already have the "clear" style applied to it, then the clearFix would not needed.

Another edge case would be if for some (evil) reason there was a global style setting a margin or min-height to all divs, then the clearFix one may end up creating an extra space at the bottom.

I hope this makes sense. My suggestion would be to have a "injectClearFix" option set to true by default and a "useClearFixAsTaggedElement" set to false by default.

Thanks

**Comment by davidjbradshaw** [comment]
Hi,

I try no to have too many options as it makes things to complicated for people. I've never seen a real world issue where this has created a problem.
