### ISSUE TITLE
iFrame window changes it's size and cause reciever() to run

### ISSUE THREAD

**Issue by naorye** [davidjbradshaw/iframe-resizer#430]
When the iframe change it's size, a post message is thrown (mutation or interval). As a result, reciever() gets that message and performs a warning:
[iFrameSizer][a0849e180478fd0df2e294d6f603ecac-iframe] Unexpected message 

The message was:
[iFrameSizer]a0849e180478fd0df2e294d6f603ecac-iframe:5542:488:interval

**Comment by davidjbradshaw** [comment]
Is the `-` in the ID of your iFrame causing an issue?

**Comment by naorye** [comment]
No, the '-' has no relation to this issue.
The problem is: when postMessage from iframe to parent, the message also captured by the iframe and this situation is not filtered.

**Comment by davidjbradshaw** [comment]
This is something wrong in your setup, but you haven't given me much detail here. Can you make a simple test case.
