### ISSUE TITLE
Content Of Iframe not resize in Iphone 

### ISSUE THREAD

**Issue by TechGuyVN** [davidjbradshaw/iframe-resizer#431]
Hi.

I spend many day researching and find your lib, I have success setup your library too, 
I see message send between iframewindow and iframe too ( with no error)
But nothing happend.

In my case my iframe display this url: https://mcspaplano.millenniumegift.com/GiftCard/BuildGiftCard?templateId=111
If you open it in ios safari browser you will see all web page scale to fix with screen ( user interact by zoom in - out web)
I use iframe to embed that link to Cordova App.
the Website not resize to fix with mobile device 

Please help me solve this case.

I Attach an offline version of that website, you can test with that.
![screen shot 2016-11-21 at 7 20 43 pm](https://cloud.githubusercontent.com/assets/503529/20482518/a16f997a-b01f-11e6-832e-2ff6929aef78.png)
[danny.html.zip](https://github.com/davidjbradshaw/iframe-resizer/files/603489/danny.html.zip)

**Comment by davidjbradshaw** [comment]
Can you make a simple test case?
