### ISSUE TITLE
style height 100% on body breaks resize logic

### ISSUE THREAD

**Issue by poloka** [davidjbradshaw/iframe-resizer#433]
By setting the height attribute on the body to 100%, the resize logic fails to execute.  I may not be fully understanding the logic but if someone could explain to me why this is desired behavior or how to correct this without changing the attribute I would much appreciate it.  My example is located:
https://github.com/poloka/resize-example/tree/master

**Comment by davidjbradshaw** [comment]
It's a limitation of CSS, rather than a desired behaviour. 

See https://github.com/davidjbradshaw/iframe-resizer#iframe-not-downsizing for how to work around.

**Comment by poloka** [comment]
Sorry, didn't get to try your suggestion.  I ended up making the modification to the project I noted above and the taggedElement seems to work.  However, my content will not scroll that is not displayed when I set a maximum height.  Would you know what I did wrong?
