### ISSUE TITLE
callback on iframe resize event

### ISSUE THREAD

**Issue by rgupta2** [davidjbradshaw/iframe-resizer#434]
Is there a way where one can attach a callback function so that whenever iframe gets resized, callback is invoked?

I mainly need it to adjust the parent container in proportion to the iframe it contains.

Currently, I am achieving the above functionality using the following change in iFrameResizer.js. I am sure there must be a neater way.

```
function processDimension(dimension){
            setDimension(dimension);
            iFrameResizeCallback(messageData.id);
            chkZero(dimension);
        }
```

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#resizedcallback
