### ISSUE TITLE
Iframe resize is not working in 

### ISSUE THREAD

**Issue by Shyam-Echidna** [davidjbradshaw/iframe-resizer#435]
Hi,

I implemented iframe-resizer into my app. Its working fine in windows(desktop) chrome. But its not working in ipad, android device.

Its not take automatically height.
This is the url : [http://52.206.111.191:9100/plantLibrary](http://52.206.111.191:9100/plantLibrary)

```js
  function resize(){
            iFrameResize({
                log                     : true,                  // Enable console logging
                enablePublicMethods     : true,                  // Enable methods within iframe hosted page
                checkOrigin:false,
                heightCalculationMethod:'bodyScroll'
            });

       }
 $('iframe').load(function(){

            resize();
            });
 $( window ).resize( function () {
         resize();
        });
ressize();
```
Thanks in advance.

**Comment by davidjbradshaw** [comment]
You only need to call resize once. So you can take out the jQuery stuff.

You no longer need to use `enablePublicMethods`.

Other than that, take a look at the log out put on Mobile and see what it says. Runs ok in Chrome on my Mac.

**Comment by Shyam-Echidna** [comment]
Thanks for your update.

On the load iframe loading fine. But when we click on some events or search of term iframe size is not resetting.

can you please give some idea on this
