### ISSUE TITLE
iframe-resizer is not re setting the height in ipad and ie

### ISSUE THREAD

**Issue by Shyam-Echidna** [davidjbradshaw/iframe-resizer#437]
Hi,
Thanks for you plugin. its working fine in desktop. when i tried in ipad on the load iframe showing perfectly. when i try to click on the any link in the iframe content will be changed  but the height is not automatically not adjusted.
This is the url : [http://52.206.111.191:9100/plantLibrary](http://52.206.111.191:9100/plantLibrary)
Please help me on this  
 function resize()
{
            iFrameResize({
                log                     : true,                  // Enable console logging
                enablePublicMethods     : true,                  // Enable methods within iframe hosted page
                checkOrigin:false,
                heightCalculationMethod:'bodyScroll'
            });

       }
resize()

Thanks

**Comment by davidjbradshaw** [comment]
Please make a simple test case to demonstrate the bug.

**Comment by davidjbradshaw** [comment]
Does this help https://github.com/davidjbradshaw/iframe-resizer/issues/407?
