### ISSUE TITLE
Resizing does not work when the host page uses jQuery and iframeResizer.js included to the host page repeatedly

### ISSUE THREAD

**Issue by dshiryaev-plesk** [davidjbradshaw/iframe-resizer#438]
# Version
3.5.5

# Precondition
- the host page has jQuery loaded	
- the host page have two iframes with content that changes its height dynamically
- every of the iframes do the following:
	- includes iframeResizer.contentWindow.js
	- adds script iframeResizer.js to the host page
	- adds the following call to initialize itself to a script in the host page's body: jQuery('#' + window.frameElement.id).iFrameResize()

# Steps to reproduce
- open host page
- change the height of content of any iframe

# Expected result
The height of the iframe has changed

# Actual result
- The height of the iframe is NOT has changed
- browser's console has messages like the following:
Sending message to host page (iframe-43993:1921:568:mutationObserver)
Ignored: iframe-43993:1921:568:mutationObserver

# Help to fix
iframeResizer.js: 982

**Comment by davidjbradshaw** [comment]
If you want to create a pathc that checks if the jQuery plugin is already loaded, before adding it. Then happy to take the PR.
