### ISSUE TITLE
iframe-resizer doesn't work properly in Chrome

### ISSUE THREAD

**Issue by samirFercios** [davidjbradshaw/iframe-resizer#44]
Hi,

Everything is ok for Firefox and IE but not in Chrome (version 34.0). How I can force/help Chrome to make into account the correct height of my iframe? Actually, the content of my iframe is built dynamically according to the data that I want to show. How I can force your plugin to detect the window resizing in chrome (this is my major problem)?

Thanks in advance for your help.

Regards.

Samir.

**Comment by amol9supe** [comment]
hello sir,
i have same issue.
FF working fine but chrome getting error means iframe id not append.
what i can do sir?
Thanks.
