### ISSUE TITLE
Utilizing taggedElement does not allow content to be scrollable

### ISSUE THREAD

**Issue by poloka** [davidjbradshaw/iframe-resizer#441]
Another issue was discovered from https://github.com/davidjbradshaw/iframe-resizer/issues/433 that upon changing the resize method to taggedElement, scrolling enabled, and a maximum height selected that I was not able to scroll my content.  My intention is to indicate a max and/or minimum height allowed and allow the remaining content to be scrollable but only if the size indicated by the taggedElement calculation exceeds the bounds applied.  See the following commit in my testing: https://github.com/poloka/resize-example/commit/bb708a6672c57c6ff4326125c87d9f62f293f3f1.

**Comment by davidjbradshaw** [comment]
Have you tried putting the iFrame in a `div` with `overflow:auto`?

**Comment by poloka** [comment]
Doh, totally missed I'd removed that css.  Yup, with that it works.  Closing this issue.
