### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin (https://....) provided does not match the recipient window's origin ('https://...')

### ISSUE THREAD

**Issue by sreeeravankara** [davidjbradshaw/iframe-resizer#443]
Hi David, I face an issue when using your scripts in sharepoint sites.
Failed to execute 'postMessage' on 'DOMWindow': The target origin (https://....) provided does not match the recipient window's origin ('https://...')
IFrame is in ADFS ( e.g : https://appdev.com/..) 
Source one is share point site collection. (e.g. https://spde.com/...)

When I tried with two asp.net application it works great but fails in sharepoint site.

Thanks in advance

**Comment by davidjbradshaw** [comment]
You get that error if the iFrame has not loaded, you can ignore it if everything still works, as it makes more than one attempt to communicate

**Comment by raxan** [comment]
I have similar issue, and body of iframe content become empty.

![screen shot 2016-12-31 at 12 19 49](https://cloud.githubusercontent.com/assets/6774210/21577215/8613ae16-cf53-11e6-9dd4-96b554e961b3.png)

![screen shot 2016-12-31 at 12 18 04](https://cloud.githubusercontent.com/assets/6774210/21577216/8615ea50-cf53-11e6-8775-e011f9f31098.png)

First page load everything work fine, then after clicking on some link, body become empty and that error is generated, any idea how to fix?

thanks

**Comment by davidjbradshaw** [comment]
I expect the issue is you need to change the `x-Frame-Options` http header on wordpress.org, as currently it is set to block iframes.

**Comment by Steve-Fenton** [comment]
Just an additional note for anyone else that comes across this... it can also happen if the target site has forgotten to include the content window script file.

**Comment by rafaelbiten** [comment]
I was having the same error logged to the console, but David's message was clear about what was going on.

Before I had:
```
<iframe src="https://..." scrolling="no" frameborder="0" onload="iFrameResize()"></iframe>
<script>iFrameResize()</script>
```

Now I have:
`<iframe src="https://..." scrolling="no" frameborder="0" onload="iFrameResize()"></iframe>`

So I'm running iFrameResize() when the iframe loads and the error is gone.

**Comment by benr77** [comment]
Confirmed - the suggestion by @rafaelbiten is working for me too.

**Comment by romaricdrigon** [comment]
Same, with a slow to load embedded website, I had to use @rafaelbiten solution.

**Comment by MoralesCodefree** [comment]
That error is because  you need to execute into domain configure your Gmail credentials, in my case I executed outside the domain  http://localhost

![image](https://user-images.githubusercontent.com/7216686/36004392-2069c01c-0cf8-11e8-87c0-378b0482a3d7.png)

**Comment by c0bra** [comment]
Using `onload` was not enough for me. I had to add a `setTimeout` wrapper around my resize call and wait a while before attempting the resize.

**Comment by akbarbuneri** [comment]
I was facing the same issue, but my issue was caused by redirect from http to https, I was providing in the target iframe the http address of my website URL by providing the URL in https in the iframe resolved the issue.
