### ISSUE TITLE
Pause  iframe-resizer 

### ISSUE THREAD

**Issue by lilaja** [davidjbradshaw/iframe-resizer#444]
I am trying to implement an animation (css height transform) of an elements inside my iframe content, and i am facing a flickering issues while doing this. It is because iframe-resizer is not  tracking transition iterations(but of course this is fully understandable).  Instead it changes the hight of the iframe twice:
- on adding css class to to the animated element.
- on transitionend
and this is causing the flickering issue

I want to implement my own iframe hight changing animation, but in order to do it I need to be able to pause iframe-resize for a while - so that my custom animation handler wont collide with iframe-resize.
I was thinking of adding a setting for this (I could make a pull request with what i am thinking about).
What do you think ? Perhaps there is simpler way to solve my issue?

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#autoresizebool

**Comment by lilaja** [comment]
I was thinking more like a IFrame Page Method but i will try with this one. Thanks.

**Comment by lilaja** [comment]
Ok, that will do.
worth mentioning autoresize starts working correctly from verison 3.5.6
