### ISSUE TITLE
Embed of WP site new theme

### ISSUE THREAD

**Issue by raxan** [davidjbradshaw/iframe-resizer#445]
When I emabed WP site using the new theme, then on homepage there is an infinite resize of page

![screen shot 2016-12-31 at 12 22 32](https://cloud.githubusercontent.com/assets/6774210/21577233/19cb3408-cf54-11e6-8b7e-06e59616d507.png)

**Comment by raxan** [comment]
It seem an issue with WP, since also without your plugin this issue appear

**Comment by raxan** [comment]
seem this is solution http://stackoverflow.com/questions/8087467/embed-wordpress-admin-in-an-iframe

**Comment by davidjbradshaw** [comment]
Yep this is a Wordpress issue.

**Comment by raxan** [comment]
@davidjbradshaw sorry the issue with x-frame-options is for this https://github.com/davidjbradshaw/iframe-resizer/issues/443

This issues seem something else.
Because the iframe is resized infinitely. Maybe setting max-height could fix, but then if page have more height, the scrolling should be enabled.
You can test by embeding for example this : http://2017.wordpress.net/

**Comment by raxan** [comment]
The log show "Checkiing width is in range 0-Infinity"

**Comment by davidjbradshaw** [comment]
The you have a CSS bug

**Comment by raxan** [comment]
ok, you mean the WP last theme
