### ISSUE TITLE
Activate iframeResizer only if iframe page integrates contentWindow script

### ISSUE THREAD

**Issue by jccazeaux** [davidjbradshaw/iframe-resizer#446]
Hi,

For my website I would like to user `iframeResizer `but the content of iframes can be different partner sites. Some will have the` contentWindow script`, some others won't.
So I would like to activate `iframeResizer `only if the iframe contains a partner who have iframeResizer contentWindow script. If the partner does not have it, I want to let the bar scroll do their job.

I saw that one of the first action of `contentWindow script` was to send a `[iFrameResizerChild]Ready` message to the parent. So i tried to use this message as an activation trigger. The code would be like this
```
<iframe src="http://partner.site" width="100%" scrolling="auto"></iframe>
```
```
function receiveMessage(event)
{
	if (event.data === "[iFrameResizerChild]Ready") {
		window.removeEventListener("message", receiveMessage, false);
		iFrameResize();
	}
}
window.addEventListener("message", receiveMessage, false);
```

My tests are OK, but I'm wondering if doing so can have some side effect I did not see so far?

Thank you

**Comment by davidjbradshaw** [comment]
I would suggest a better approach would be to set `scrolling: true` on all iFrames to start with and then disable it with `initCallback` if you get a message back from the iFrame.

Something like:

```js
iFrameResize({
  scrolling: true,
  initCallback: function(iframe) {
    iframe.style.overflow = 'hidden';
    iframe.scrolling = 'no';
  }
});
```

**Comment by jccazeaux** [comment]
Thanks for the advice. I'll test that and tell you if it's OK.
