### ISSUE TITLE
I can't get it work on my site

### ISSUE THREAD

**Issue by MANOLO3588** [davidjbradshaw/iframe-resizer#447]
Hi David, please check my site:

http://www.misionvida.org/celulas/

I can't get it work. I'm using accordion and google maps there. if you click on Size(1250) it's working but the site does't resize automatically. If there is something wrong please let me know.

Thanks,
Manuel

**Comment by davidjbradshaw** [comment]
If you provide a simple test case of an issue I can take a look, however, I'm afraid I don't have the time to debug more general issues.
