### ISSUE TITLE
iframeresizer getPageInfo

### ISSUE THREAD

**Issue by Jconsult** [davidjbradshaw/iframe-resizer#448]
Hi, David.  IFrameResizer is working fine.  Console logs appear normal.  But I can't get the iframe page method getPageInfo working.  Could you provide an example?  Thanks.

**Comment by davidjbradshaw** [comment]
```js
If (parentIFrame)
  parentIFrame.getPageInfo(
    (pageInfo) => console.log('pageInfo: ', pageInfo)
  );
```
