### ISSUE TITLE
resizer doesn't find new iframes

### ISSUE THREAD

**Issue by JamesGKent** [davidjbradshaw/iframe-resizer#450]
I'm using this library on a project of mine where there is a master device which discovers slave devices, when it finds the slaves an iframe is added to the webpage for each slave devices webpage. however none of the dynamically added iframes are being resized, only the first iframe which is there on page load.

I can't figure out how to get the resizer to find each new iframe?

**Comment by davidjbradshaw** [comment]
You have to call iFrameResizer each time you add a new iFrame and pass it the `ID` of the new iFrame.
