### ISSUE TITLE
Question: What is the purpose of switching height calc mode back to default on resetIFrame

### ISSUE THREAD

**Issue by mdgbayly** [davidjbradshaw/iframe-resizer#453]
We've seen issues with terrible flicker and resize cycles when the height calc mode is set to 'max'.

It seems to be caused by this line in the contentWindow resetIFrame method.

https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L957

It temporarily sets the height calc method back to 'bodyOffset' which seems to cause a different height value to be calculated (understandably) but then this then results in the parent resizing the iframe.

We see this in response to all kinds of events, e.g. 'Mouse Down', 'Transition End' etc when the size of the page has not actually changed.

**Comment by mdgbayly** [comment]
I re-read all your readme again - and I suppose the issue we are seeing is just the flicker issue with the 'max' height calculation method which is intended to enable downsizing.

**Comment by davidjbradshaw** [comment]
Yep

**Comment by concertcoder** [comment]
@davidjbradshaw hey! I was curious what this method is for? Why is it alternating between the default + set calc method?

**Comment by lidermanrony** [comment]
1. Thanks @davidjbradshaw  for this wonderful library. 
2. The alternating calculation method caused wrong sizing in our product. We had to fork and change this behavior in order for the library to work correctly for us.

Any context on the rationale of reseting the calculation method each time will be helpful here.

**Comment by davidjbradshaw** [comment]
The reason for this is that in some browsers, certain height calculation methods only work in an upwards direction, so you end up having to set height to zero, calc the new size, and then size it up again for it to work reliably.

My advice is to use `taggedElement` if the default method doesn't work for you.

@lidermanrony you can use custom sizing methods without having to fork the library.
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md#heightcalculationmethod--widthcalculationmethod

**Comment by concertcoder** [comment]
@davidjbradshaw thanks for the insanely prompt response!

Is there a list of which methods only work in an upwards direction? We were looking to use the "bodyScroll" method as it works best for us - is this prone to the reliability issue?

We used the set height calculation method to set  "bodyScroll" but the alternating of the "bodyOffset" & "bodyScroll" seemed to give us some weird choppy scrolling issues sadly.

**Comment by davidjbradshaw** [comment]
The ones marked with a *, which is then explained in the notes below. ;) 

> Notes:
> 
> If the default option doesn't work then the best solutions is to use either taggedElement, or lowestElement. Alternatively it is possible to add your own custom sizing method directly inside the iFrame, see the [iFrame Page Options](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md) section for more details.
> 
> † The lowestElement option is the most reliable way of determining the page height. However, it does have a performance impact, as it requires checking the position of every element on the page. The taggedElement option provides much greater performance by limiting the number of elements that need their position checked.
> 
> * These methods can cause screen flicker in some browsers.
> 

I wrote this in 2013, memory is a bit hazy on the issues. These methods where for **IE6**, as it's too slow for anything else. It might be that we don't need to back scroll these days, but I don't have access to enough old browsers to test it on.

These days I recommend you use `lowestElement` or `taggedElement`. I expect I should just make a version 5 of this library that removes more of the old IE code.
