### ISSUE TITLE
Question: Anyone any ideas on using this library with Polymer/shadow DOM

### ISSUE THREAD

**Issue by mdgbayly** [davidjbradshaw/iframe-resizer#454]
We're using this library to manage an iframe that is using Polymer to render its page.
We've enabled full shadow DOM in browsers where it is supported (e.g. Chrome) to ensure the web components we create are working in both shady and shadow DOM.

However, this library fails to resize correctly with shadow DOM, presumably due to the fact that DOM mutations are not being propagated outside the shadow DOM boundaries.

Just wondering if anyone had come up with any good workarounds for that.
The only one I can think of at the moment is to add in some kind of behavior to all our Polymer components that tracks mutations internally to the component and fires a regular resize event which we then use to call resizer explicitly on the resizer.

But that would not work with components we don't write.

**Comment by davidjbradshaw** [comment]
I expect you might be the first to try this. If you do come up with a solution please feed it back and PRs are always welcome.

**Comment by Lange** [comment]
With Polymer 2 being due out any day now, I was testing my app (which has a similar iframe setup) against shadow DOM, and encountered this same issue. I also have no idea where to start with looking into this, but I suspect that reports of this issue will become more common once Polymer 2 is out.

**Comment by ottigerb** [comment]
+1

**Comment by ryantmer** [comment]
@mdgbayly A method that appears to work is to set a `min-height` on the outermost Polymer element, e.g. if your iframe loads the file below:

```html
<!doctype html>
<html lang="en">
  <head>
    <link rel="import" href="./my-element.html">
    <style>
      my-element {
        min-height: 400px;
      }
    </style>
  </head>
  <body>
    <my-base-element></my-element>
  </body>
</html>
```

it seems like adding the `min-height` on the Polymer element allows things to size somewhat-correctly initially. Not a great solution, but "works" :man_shrugging:

**Comment by Lange** [comment]
Strange behavior I've just noticed that might be unique to my specific application:
- If I refresh the page normally, none of my iframes get resized to the correct height.
- If I refresh the page and then select a different tab, wait for my application to fully finish loading, then go back to my application's tab, all the iframes will suddenly pop to the correct size. Very strange.

**Comment by Lange** [comment]
Turns out my particular case was not a problem with `iframe-resize`. My issue was that my iframes were within `iron-collapse` elements, which set a `max-height` on themselves. Calling the `updateSize` method on these `iron-collapse` elements in the `resizedCallback` fixed my problem.
