### ISSUE TITLE
Loading both the resizer and the contentwindow script causes an infinite loop

### ISSUE THREAD

**Issue by nmk** [davidjbradshaw/iframe-resizer#456]
Consider this test file:

```html
<html>
  <head>
    <style>body{ background: purple; }</style>
  </head>
  <body>
    <iframe
      id="inner-1"
      src="http://tools.financeads.net/tagesgeldrechner.php?tp=dif&h=1&wf=24106"
      scrolling="no" width="100%"
      style="padding:0px;margin:0px;border-width:0px;"
      frameborder="0"></iframe>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.contentWindow.min.js"></script> -->
    <script>
     iFrameResize({ log: true, checkOrigin: false }, '#inner-1');
    </script>
  </body>
</html>
```

As is, the loading and resizing of the external iframe works as intended. If one uncomments the loading of the iframeResizer.contentWindow.min.js script, loading the page results in an infinite loop of warnings in the console, and the inner iframe grows indefinitely.

I can see the financeads page is using 3.5.5, so this is the version I used on the outer page. The same result can be observed with 3.5.8 in the outer page though.

I tested this in Safari, Chrome and Firefox on macOS, all display the same behaviour.

It seems to be an issue with this particular page, but I am not sure how to debug the problem. Any help would be greatly appreciated.

**Comment by davidjbradshaw** [comment]
That's strange it should work ok. What happens if you change the order to make the call before loading the second script?

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.min.js"></script>
<script>
     iFrameResize({ log: true, checkOrigin: false }, '#inner-1');
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.5/iframeResizer.contentWindow.min.js"></script>
```

**Comment by davidjbradshaw** [comment]
Also can you post the error message here.

**Comment by nmk** [comment]
Changing the order has no effect, the warnings persist. Sorry for having just a screenshot of the warning, but I cannot select anything in the Safari console, while it is in the aforementioned loop.

<img width="1210" alt="screen shot 2017-01-30 at 15 54 41" src="https://cloud.githubusercontent.com/assets/39269/22427777/b3bce7a6-e704-11e6-9b53-cbbc9343e039.png">

**Comment by davidjbradshaw** [comment]
Strange. If you can back a simple test case I will take a look.

Also in the mean time adding `tolerance: 16` as an option should stop the resizing loop.

**Comment by nmk** [comment]
Adding `tolerance: 16` indeed stops the resizing loop. The following warning is displayed:

```
[Warning] [iFrameSizer][inner-1] scroll|1040.34375 is not a valid option for widthCalculationMethod. (iframeResizer.contentWindow.min.js, line 9)
[Warning] [iFrameSizer][inner-1] Unexpected message ([iFrameSizer]inner-1:1028:1105:mutationObserver) (iframeResizer.contentWindow.min.js.gz, line 146, x2)
```

If you paste the code from the first message above in a file and open it in a browser you can observe the behaviour I am talking about.

**Comment by davidjbradshaw** [comment]
Glad that stopped the problem for you. Will take a deeper look next time I some spare time.

**Comment by davidjbradshaw** [comment]
Are you testing this example inside another iFrame or by itself?

**Comment by nmk** [comment]
I am testing by itself. It should ultimately be inside another iFrame
though (thus the loading of the contentWindow script).

If I test it nested (the code above being the "middle" iFrame) it exhibits
the same bahaviour.

**Comment by davidjbradshaw** [comment]
Ok I think their may be two issues here. If the code is in an iFrame the warning should be suppressed. 

The growing loop thing is normally a CSS issue, in your case one bit of content is alway 16px larger than the page. Your option here are to leave the tolerance set, try different height calculation methods, or find what in your CSS is set to be always bigger than the page and fix it.
