### ISSUE TITLE
A question re use in Wordpress

### ISSUE THREAD

**Issue by RAMINCNZ** [davidjbradshaw/iframe-resizer#457]
Not sure how or where I ask a question as opposed to raising an issue, so my apologies for probably doing it in the wrong place..

I would very much like to have this work within my Wordpress Website.

 The iframe is used by our booking engine and they have everything setup on their end.. I'm reasonably confident I have things set up according to instructions here, but resizing does not seem to work.. I have asked our bookings people about this and they say they were not able to get this working in Wordpress.

page currently trying to get working http://dev.bell-lodge.nz/book-motel/

Many Thanks for any help

Rick Malkin

NZ

**Comment by davidjbradshaw** [comment]
I don't the first thing about WordPress I'm affraid. However, this article might be of some help.

http://b-l-i-n-k.com/automatically-adjust-cross-domain-iframe-height-dynamic-content-wordpress/

If not my advise is to ask a question on StackoverFlow and give as much detail as possible.
