### ISSUE TITLE
Unexpected Error: iFrame (resize) does not exist on iframeResizer.js:8

### ISSUE THREAD

**Issue by mrnerdy** [davidjbradshaw/iframe-resizer#459]
I am getting this bug again and again whenever I click on any element on the UI (that has many iframes). iframes are resized correctly though, but this bug sometimes stops execution of other js code which is a problem. I'm attaching the DevTools screenshot.
![DevTools screenshot](https://cloud.githubusercontent.com/assets/17147620/22675089/e9b08386-ed26-11e6-92c3-b58ec1804b5b.png)

**Comment by mrnerdy** [comment]
It seems like iframe-resizer tries to find an iframe with id "resize", but I don't have one in my project.

**Comment by davidjbradshaw** [comment]
Not sure how you have managed to do that. If you can make a simple test case I will have a quick look.

**Comment by mrnerdy** [comment]
My project is based on marionette.js and it has a route where a lot of iframes are used.
In here, I put the following code:
        iFrameResize({
            log: false,
            enablePublicMethods: true
        });

**Comment by davidjbradshaw** [comment]
I think this is going to be a problem somewhere in your code, but I can't say where from just an error message. Turn the logging on, it should give you some clues.

**Comment by mrnerdy** [comment]
Thanks for your tip. Here is what I got by turning on the log.
![After turning on the log](https://cloud.githubusercontent.com/assets/17147620/22702847/6b5ada98-eda5-11e6-9c4e-2862db28fe94.png)
]()

**Comment by davidjbradshaw** [comment]
That is still not very helpful. What is the StackTrace on the error?

**Comment by mrnerdy** [comment]
This is the stack trace - I assume it's not very helpful either..
![Stack Trace](https://cloud.githubusercontent.com/assets/17147620/22703261/e42e5da4-eda6-11e6-851d-1f03e37c73cb.png)

**Comment by davidjbradshaw** [comment]
Nope, not more I can say without seeing a test case

**Comment by davidjbradshaw** [comment]
I'm out of ideas. Need to see a working example of the issue
