### ISSUE TITLE
[iFrameSizer][iFrameResizer0] No change in size detected

### ISSUE THREAD

**Issue by Simobain** [davidjbradshaw/iframe-resizer#460]
Hi !
I made a widget with  iframe-resizer. On my side everything was working just fine and when giving it to one of my partner the widget does not want to resize...

I've activated the log (true) and the checkOrigin (false) : 
It is placed on this website : 
http://www.letouquet.com/accueil/infospratiques/venirautouquet.aspx (at the bottom of the page)
(just inspect the console)

Could you explain me why it says "[iFrameSizer][iFrameResizer0] No change in size detected"

Thanks

**Comment by Simobain** [comment]
I guess there is something going because there is another iframe on the page. Is it possible to attach the iframe resizer to my iframe only ?

**Comment by Simobain** [comment]
Ok, now I'm sure ! The iframe resizer add the iframe ID iFrameResizer0 to the first iframe it found ! However mine already have this id ! It just shouldn't be visible at the beginning...

**Comment by davidjbradshaw** [comment]
You need to give all your iFrames IDs, or at the very least not use `iFrameResizer0` in your html.

**Comment by Simobain** [comment]
That's what I did but i'm not really okay with this solution because the other iframes are ow attached to iFrameResizer.
Those other iframes are not mine at all... So i can't give them a specific id. 
I was thinking of a way to tell to iframeResizer : do not attach ids by yourself ! Is that a possible option ?
