### ISSUE TITLE
Not resizing when frame changes size due to ajax call

### ISSUE THREAD

**Issue by MicWit** [davidjbradshaw/iframe-resizer#465]
I have a project that has interactive content in it, and because it changes via ajax, it seems the resizer is not detecting the change. Can someone test this and see if it works for them?

I just have a list of addresses, and when you select a country from a drop down it updates the list making it shorter and so there is a massive white space under it.

**Comment by davidjbradshaw** [comment]
Have a look at the log out put. I should detect that. Most likely fix is changing the height calculation method.

**Comment by MicWit** [comment]
Thanks for that, helped greatly. The options that seem to work for the heightCalculationMethod (while using an ajax call) are:
- bodyScroll
- documentElementScroll
- max
Any recommendations as to which one of these I should use?

**Comment by davidjbradshaw** [comment]
My preferred option is this code snippet. If that doesn't work, then use `max`.

```
var isOldIE = (navigator.userAgent.indexOf("MSIE") !== -1); // Detect IE10 and below

iFrameResize( {
    heightCalculationMethod: isOldIE ? 'max' : 'lowestElement'
});
```

**Comment by MicWit** [comment]
No worries, that wont work in my case as lowestElement will not resize an ajax request, I might just leave it as bodyScroll as it seems to be more accurate and works on old IE as well as other browsers.

**Comment by davidjbradshaw** [comment]
That is strange never seen `lowestElement` Not work before. The issue will be your CSS, rather than anything to do with Ajax.
