### ISSUE TITLE
No response from iFrame warning

### ISSUE THREAD

**Issue by SnakeME** [davidjbradshaw/iframe-resizer#466]
Hey,

I've got an issue that in the console the following entry is spawning when the iframe is loaded:

[iFrameSizer][Host page: widget-iframe] No response from iFrame. Check iFrameResizer.contentWindow.js has been loaded in iFrame

But iFrameResizer.contentWindow.js is loaded and the iframe is also resizing properly. When I enable logging, no errors are coming up and everything looks fine, except that this message keeps coming up.

Any idea how to debug?

**Comment by pscdodd** [comment]
I also got this in the firefox console. Moved the loading of iFrameResizer.contentWindow.min.js as early as possible, but no difference. Possibly only started seeing this after upgrade from v3.5.5 to v3.5.9.

**Comment by davidjbradshaw** [comment]
You can safely ignore, it just means that your iFrame is taking longer to load than expected.

When the code first runs it sends a message to the iFrame, if the iFrame is not fully loaded at this point it will send the message again once it has loaded. The warning is triggered by the first request timing out.

**Comment by SnakeME** [comment]
Okay, good to know :)

Thanks!

**Comment by davidjbradshaw** [comment]
Forgot to mention you can set the option `warningTimeout` to a higher number to extend the amount of time before the warning. Default is `5000`.

**Comment by pscdodd** [comment]
5 ms as a default seems a little fast, perhaps 100 ms is more reasonable?

**Comment by davidjbradshaw** [comment]
It's 5 seconds, not 5ms!

**Comment by bologer** [comment]
@davidjbradshaw, just crossed that same warning. Wanted to know if it is possible to hide this warning?

**Comment by davidjbradshaw** [comment]
See above.
