### ISSUE TITLE
Iframe Shrink issue.

### ISSUE THREAD

**Issue by sathishavm** [davidjbradshaw/iframe-resizer#467]
I have a extend and collapse menus inside iframe.
The Iframe height is extended well while I extend the menu inside  iframe, but when I collapse the menu inside iframe, I get an empty space.(i.e the iframe height is not reduced)

This work good in Firefox, but not in chrome, IE..etc

Did anyone faced this issue?.. please suggest.

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#iframe-not-downsizing
