### ISSUE TITLE
Not working with Require.js

### ISSUE THREAD

**Issue by b-yond** [davidjbradshaw/iframe-resizer#468]
I have an iframe "product showcase" module that's injected into clients' pages with a single JS script tag.

I've noticed that clients with require.js see the error "ReferenceError: iFrameResize is not defined". 
Since I don't have access to their servers, I'm not able to place the iframeResizer scripts into their web-reachable folders -- they're all served remotely from our server.

Is there a fix for this? 
Thanks!

**Comment by mcat** [comment]
A similar issue occurs when including via npm

`import iFrameResize from 'iframe-resizer';`

**Comment by davidjbradshaw** [comment]
It should work ok when using es6 import. @mcat what error do you get?

**Comment by davidjbradshaw** [comment]
@b-yond Think I have the solution.
```
var iFrameResizerPath = '/myPath/iframeResizer.min.js'

if (require) {
  require([iFrameResizerPath], function (iFrameResize) {
    iFrameResize()
  })
} else {
  var script = document.createElement('script')
  script.onload = function () {
    iFrameResize()
  }
  script.src = iFrameResizerPath
}
```

**Comment by b-yond** [comment]
Thanks much, David. I managed to get this somewhat solved after I RTFM'd, but your solution is a little more elegant.

**Comment by b-yond** [comment]
It's not too different from yours, except that in my haste I put a condition in for the one client using require.js. The PHP that spits out my JS sees his API key, and deviates a little.

**Comment by davidjbradshaw** [comment]
Well if you have the time to try mine, as a guard against any more clients using `require`, then I'd love to know if it works.

**Comment by b-yond** [comment]
Will do. I'll report back when I have a chance to implement it.

**Comment by basnijholt** [comment]
I am running into the same problem I think.

I am trying to use `iframe-resizer` in an [edX.org course](https://test.topocondmat.org) and tried your suggestion.

[This](https://test.topocondmat.org/test1.htm) is the page with:
```
<script>
var isOldIE = (navigator.userAgent.indexOf("MSIE") !== -1); // Detect IE10 and below

iFrameResize({{
    heightCalculationMethod: isOldIE ? 'max' : 'lowestElement',
    minSize:100,
    log:true,
    checkOrigin:false
}});
</script>
```

and [this](https://test.topocondmat.org/test2.htm) is the page with:
```
const iFrameResizerPath = 'https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.14/iframeResizer.js'

if (require) {
  require([iFrameResizerPath], (iFrameResize) => iFrameResize())
} else {
  const script = document.createElement('script')
  script.onload = () => iFrameResize()
  script.src = iFrameResizerPath
}
```

I would really appreciate some help, I have been stuck on this issue for weeks.

**Comment by davidjbradshaw** [comment]
Looking at you errors in the console, it seems your having errors with other libraries. If you can make a simple test case with just require and iframe-resizer, I'd be interested to take a look.

In the meantime for iFrame-Resizer you could take the JS file and change these lines

	if (typeof define === 'function' && define.amd) {
		define([],factory);
	} else if (typeof module === 'object' && typeof module.exports === 'object') { //Node for browserfy
		module.exports = factory();
	} else {
		window.iFrameResize = window.iFrameResize || factory();
	}

to just

    window.iFrameResize = window.iFrameResize || factory();

**Comment by basnijholt** [comment]
It's hard to copy the webpage and put it somewhere else because it indeed generates many new errors.

However, this is the error that I get on the original page:
<img width="677" alt="screen shot 2017-04-21 at 16 59 33" src="https://cloud.githubusercontent.com/assets/6897215/25284897/c7dbbf66-26b8-11e7-89f4-4953cda561e1.png">

**Comment by basnijholt** [comment]
Actually, it seems like [these](https://github.com/jazkarta/obsolete-edx-sga/issues/1) people were having a very similar issue, where [this](https://github.com/jazkarta/obsolete-edx-sga/commit/4d23f2b22a294ac6dd3b227d1212d4b3217080fa) fixed the issue.

Unfortunatly I am almost illiterate in javascript, so I am not able to judge if the cause was really `require.js` here.

**Comment by davidjbradshaw** [comment]
That is basically the same thing as I outlined above.

**Comment by lonroth** [comment]
@davidjbradshaw Actually your code above causes an error if require is not defined:
`Uncaught ReferenceError: require is not defined`

But by changing
```
if (require) {
  require([iFrameResizerPath], function (iFrameResize) {
    iFrameResize()
  })
```
to
```
if( typeof require !== 'undefined' ) {
  require([iFrameResizerPath], function (iFrameResize) {
    iFrameResize()
  })
```
your code works perfectly! 😊

**Comment by davidjbradshaw** [comment]
@lonroth thanks for this. I have updated my answer above. Just wondering if it is worth going a bit further and making it `typeof require === 'function'`.
