### ISSUE TITLE
Iframe Resizer and Bootstrap

### ISSUE THREAD

**Issue by f-aubert** [davidjbradshaw/iframe-resizer#469]
Hello,
I found your promising little library and attempted to use it with a responsive Boostrap Layout.  At default size the embedded iframe works perfectly allowing it to be scrolled from the host (instead of directly), but when making the browser window smaller I would expect the content of my iframe to switch to a vertical layout (because of Bootstrap responsiveness) and still allows it to be scrolled from the host. Unfortunately at this point, the content of the iframe is simply cut.
I attach you two files, in order to demonstrate what I did so far. I understand perfectly it could be because of my little understanding of your library and that a solution might already exist if I configure the library properly.
Thank you very much, for your time, and for your piece of software,
Best regards from Switzerland,
Frederic Aubert

[embedded.zip](https://github.com/davidjbradshaw/iframe-resizer/files/819329/embedded.zip)

**Comment by davidjbradshaw** [comment]
The issue will most likely be something in your CSS. I'm afraid I don't have the time to debug everyone's code. I would suggest posting a question on StackOverflow.
