### ISSUE TITLE
the iframe height makes the parent not scrolling

### ISSUE THREAD

**Issue by SebastiaanKloos** [davidjbradshaw/iframe-resizer#472]
Only on Windows, the parent document is not scrolling when the cursor is on the iframe. This problem does not occur on a Mac. It effects all browsers on Windows.

Does anyone know what is causing this problem? You can try it yourself here:

http://www.burtonfrance.com/2cv-pieces-en-ligne/

Thank you in advance!

**Comment by SebastiaanKloos** [comment]
I think it is because the iframe is getting the mousewheel event. But I think the parent should handle this if the iframe has a scrolling attribute with value "no".

**Comment by davidjbradshaw** [comment]
I expect this is a bug with Windows, rather than anything we can control with code.
