### ISSUE TITLE
Incorrect height with documentElement margin

### ISSUE THREAD

**Issue by Rycochet** [davidjbradshaw/iframe-resizer#474]
When the iFrame content html element has a margin on it then that is not taken into account with the `lowestElement` method - it seems to ignore that extra little chunk outside of it (and cause bottom-right overflow).

**Comment by davidjbradshaw** [comment]
Have you tried using `padding` instead?

**Comment by Rycochet** [comment]
@davidjbradshaw We've already been "fixing" it with padding (supplied source that didn't use our template etc) - but still something that needs to be taken into account to give the correct value for `lowestElement` :-/

**Comment by davidjbradshaw** [comment]
It did used to do this, but then people complained that it wasn't sizing to the `lowestElement`.

**Comment by Rycochet** [comment]
That's weird - if it's not sizing to fit the contents then they'd have to be adding a specific `overflow:hidden` to the css to prevent scrollbars, which could cause it's own problems etc. Another option to include documentElement margin maybe?
