### ISSUE TITLE
Cut down version?

### ISSUE THREAD

**Issue by alexmcmillan** [davidjbradshaw/iframe-resizer#475]
I'd love to use this tool, but I can't justify 12k minified for it - especially when a lot of that appears to be flexible configuration (I just want an iFrame that doesnt collapse) and extending jQuery (which we don't use).

Is there any possibility of a "no-frills" version?

**Comment by davidjbradshaw** [comment]
Have been thinking about it. Along with and es6 version. 

In the means time How about trying version 2.0?

**Comment by alexmcmillan** [comment]
v2.8.10 looks like it's 4k minified - that's a bit better.

Do you think it would it be more efficient to look over the changes since then and incorporate anything important, or to work backwards from the latest version removing all the cruft?

**Comment by davidjbradshaw** [comment]
I would try v2 and if that works for you then just stick with it. 

The jQuery wrapper is only five lines of code, and most of the options don't add much weight. The majority of the code is dealing with either working out the size of the page, or detecting that the content has changed.

At some point I plan to rip out all the support for IE8-11. Waiting on global usage to fall below 1%. 

Thing
