### ISSUE TITLE
Uncaught TypeError: Cannot read property 'loaded' of undefined

### ISSUE THREAD

**Issue by qkevinto** [davidjbradshaw/iframe-resizer#477]
If `iframe.iframeResizer.close()` is called shortly after the iframe has been loaded, the particular iframe will be removed from the `settings` object, but it appears that the `trigger()` function still gets called 2 or 3 times, and it throws `Uncaught TypeError: Cannot read property 'loaded' of undefined` as `settings[id]` (https://github.com/davidjbradshaw/iframe-resizer/commit/18df6815880bd922b3e5f9704f05e890248621a0#diff-dc9292a3e8d7708966ee5ec5ba1b00beR652) is undefined at this point.

Great library by the way! 😃

**Comment by davidjbradshaw** [comment]
I knew a x.x.13 release was going to be unlucky. Will take a look later today. Thanks.
