### ISSUE TITLE
Problems with multiple origins

### ISSUE THREAD

**Issue by Mhbuur** [davidjbradshaw/iframe-resizer#479]
I keep getting origin mismatch errors despite of having tried both _checkOrigin:false_ and _checkOrigin:['https://payment.someotherdomain.com', 'http://www.domain.com']_

Here is how I defined the iframe:

`<iframe src="http://www.domain.com/index.php?option=com&Itemid=15" width="100%" frameborder="0" scrolling="auto" onload="iFrameResize({log:true, checkOrigin:['https://payment.someotherdomain.com', 'http://www.domain.com']});" ></iframe>`

Is the functionality broken or am I doing something wrong?

The error message reads:

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://www.domain.com') does not match the recipient window's origin ('payment.someotherdomain.com').

**Comment by Mhbuur** [comment]
Figured out the cause - I have multiple iframes on the page which uses iframe-resizer. It seems subsequent setup is ignored when you don't provide unique IDs ;-)

> **Multiple IFrames on one page**
> 
> When the resizer does not work using multiple IFrames on one page, make sure that each frame has an unique id.

**Comment by yahyaouiy538-ops** [comment]
أحب كرة القدم
