### ISSUE TITLE
Resize external content

### ISSUE THREAD

**Issue by AndresGilabert** [davidjbradshaw/iframe-resizer#480]
Hi,

I was using the Iframe-resizer and this works fine, congratulations!!

In my Iframe, I redirect to an external URL (domaIninsideIFrame.com/one.html -> otherDomain.com/two.html) and this cause that the step 2, in the other domain, the Iframe not resize.

Exists any mode to resize the Iframe with external domains or show the scrollbars in "OtherDomain.com"

This ocurrs because my page need go to an page of the payment gateway.

Thanks in advance

**Comment by davidjbradshaw** [comment]
You need to ensure the second JS file is included in the page served by the other domain.

**Comment by AndresGilabert** [comment]
I can't include in the other domine because not is mine, is the payment gateway of PayPal.

Exists any other option?
