### ISSUE TITLE
Error with liferay 7

### ISSUE THREAD

**Issue by ovanderzee** [davidjbradshaw/iframe-resizer#481]
When i add iFrameResizer to Liferay 7 (with jquery 2.1.4), i get the following error: 

Mismatched anonymous define() module: function N(){function a(f,e){if(e){if(!e.tagName)throw new TypeError("Object is not a valid DOM element");if("IFRAME"!==e.tagName.toUpperCase())throw new TypeError("Expected \x3cIFRAME\x3e tag, found \x3c"+
e.tagName+"\x3e");$(e,f);c.push(e)}}var c;ea();ma();return function(f,e){c=[];f&&f.enablePublicMethods&&y("enablePublicMethods option has been removed, public methods are now always available in the iFrame");switch(typeof e){case "undefined":case "string":Array.prototype.forEach.call(document.querySelectorAll(e||"iframe"),a.bind(void 0,f));break;case "object":a(f,e);break;default:throw new TypeError("Unexpected data type ("+typeof e+")");}return c}}  

everything.jsp:295:44

Is there anything to do about this?

**Comment by davidjbradshaw** [comment]
See: http://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module
