### ISSUE TITLE
Page is not properly resized if open iframe within iframe.

### ISSUE THREAD

**Issue by manojwtb** [davidjbradshaw/iframe-resizer#482]
I have a forum and created an embed code for it which creates iframe and used library to resize it. It's working fine and iframe resized properly if used on a normal page. But resized didn't working if I used our embed code inside an iframe page.

![test](https://cloud.githubusercontent.com/assets/4255156/24997275/ad732df0-2053-11e7-8d3d-94359f788418.jpg)

Please suggest us, is there any way to resolve this issue.

**Comment by davidjbradshaw** [comment]
Need to see the log output.
