### ISSUE TITLE
Resizer doesn't work with Google Analytics Experiment

### ISSUE THREAD

**Issue by silv3r007** [davidjbradshaw/iframe-resizer#483]
Hello, first of all a very useful piece of kit.

Unfortunately though, it doesn't work with Google Analytics Experiments.

The original page resizes, but none of the experiment variants work although they have the code in there.

The page is hosted in a wordpress system.

**Comment by davidjbradshaw** [comment]
That is more of a question for StackOverflow.

If you want to raise a bug please see https://github.com/davidjbradshaw/iframe-resizer/blob/master/CONTRIBUTING.md
