### ISSUE TITLE
angular ifram resizer

### ISSUE THREAD

**Issue by NahidaHK** [davidjbradshaw/iframe-resizer#488]
Hello .

i need to use angular variable within src attribute  like this :

`<ifram src="{{ url }}" ></ifram>`

resizer dosn't work in such case , do u have any idea ?

**Comment by pscdodd** [comment]
Prehaps "iframe" instead of "ifram"?

**Comment by NahidaHK** [comment]
i'm sorry it is just typing error  

` <iframe src="{{url}}" width="100%" scrolling="no" frameborder="0"></iframe>`

it doesn't resize  , if the url was static it works very well

**Comment by pscdodd** [comment]
You are missing the "id" attribute for the iframe which you pass to iFrameResize().

**Comment by davidjbradshaw** [comment]
The code will add an id if one is missing.

**Comment by davidjbradshaw** [comment]
Normally people inject the whole iFrame tag into the page and then call iFrameResizer.

I think here you are likely calling iFrame Resizer too early. Wait until angular has injected {{url}} into the page.

**Comment by NahidaHK** [comment]
I solved the problem by adding this 

`  <script type="text/javascript">
        iFrameResize({  checkOrigin: false  });
 </script>`

it works now :)

**Comment by davidjbradshaw** [comment]
OK now I understand the issue.
