### ISSUE TITLE
Question: resizing iframe to occupy entire screen?

### ISSUE THREAD

**Issue by alexanderkustov** [davidjbradshaw/iframe-resizer#489]
Hey @davidjbradshaw 

I could not figure out the best way to resize this to fit the whole iframeParent size

This is how I tried, and the cross-origin error happens right at the first line

`Blocked a frame with origin "https://demoiframeapp.herokuapp.com" from accessing a cross-origin frame.`

``` 
  var h = $(window.parent.document).height(); // <-- this is the error line
  var w = $(window.parent.document).width();
  if ('parentIFrame' in window) {
    parentIFrame.size([h],[w]);
    $('#bgOverlay, #myModal').show();
}
```
Basically, any way of getting the height width of parent? without causing a mess?

**Comment by davidjbradshaw** [comment]
You have to do that from the parent. Not in the iFrame.

**Comment by alexanderkustov** [comment]
I managed to do this all in parent having this:
```
setTimeout(function(){
  iFrameResize({
    // log: true,
    autoResize : false,
    sizeWidth: true,
    minHeight: 400,
    minWidth: 200
  });
}, 100);

```
and in the respective iframe:
```

if ('parentIFrame' in window ) { 
  parentIFrame.getPageInfo(showIntroNotice);
}

  function showIntroNotice(e){
    console.log('showing intro notice intro');
    parentIFrame.size([e.clientHeight],[e.clientWidth]);
    $('#bgOverlay, #notice-intro').show();
  }

```

Works like a charm in resizing iFrame to the whole document, but still cant figure out the best way to make this happen only once and not every time on scroll, since apparently everytime i scrolls this runs again `('parentIFrame' in window )` any tips?

**Comment by davidjbradshaw** [comment]
You don't need the `setTimeout`, just call once after the iFrame tag is rendered to the page.

Also why are you passing two one element arrays to `parentIFrame.size`? I'm amazed that even works.

No idea about the scroll thing.

**Comment by alexanderkustov** [comment]
I understand about the setTimeout is not needed, but apparently sometimes being all async, I am not getting in time to first resize, then display. I am also trying to do this with promises, but not yet there.

**Comment by alexanderkustov** [comment]
I have discovered having other issues with my implementation, I do not think my issue is valid anymore
