### ISSUE TITLE
Parent pages scroll position problem

### ISSUE THREAD

**Issue by Renkas** [davidjbradshaw/iframe-resizer#491]
I have a problem with iframe resizing changing parent pages scroll position.

I have:
* n+1 iframes on page (admin page).
* I close one Iframe and scroll page to the next one by JS (after everything is done in the last iframe)
* now something triggers in plugin and browser window jumps back to the position it was before my scroll.

I think the problem is because `pagePosition` variable holds the coordinates and will not be updated or invalidated by the scroll I trigger myself.

I would like an option to either
a) disable this scrolling alltogether (I can't see currently why it is an function at all).
b) unset `pagePosition` so it would not use old cached value.

Right now I don't seem to be able to do neither.

And no the `scrollCallback` is not an option here because this call is not using this callback. It originates from: https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.js#L140

**Comment by davidjbradshaw** [comment]
Can you create a simple test case?

**Comment by Renkas** [comment]
I'll add it to my todo list - but I probably can't allocate time for that in near future.

**Comment by AndreFabris** [comment]
I have the same problem. Opening new page in the iframe remembers the vertical position of the last page. So if the user scrolls down and opens a new page that page will be shown scrolled to that same position even if the page does not have that much content - in this case it just displays white screen.
It makes perfect sense that every time page is loaded, vertical position is reset to 0.
Any ideas of the quick fix?

**Comment by davidjbradshaw** [comment]
You could use `onInit` To trigger scrolling the page to the top
