### ISSUE TITLE
I can't get scrollTo() to work

### ISSUE THREAD

**Issue by produktive** [davidjbradshaw/iframe-resizer#492]
I have read the docs and it seems like I just need to insert this in the page loaded in the iframe:

```
<script type="text/javascript">if ('parentIFrame' in window) { parentIFrame.scrollTo(0,0); }</script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.14/iframeResizer.contentWindow.min.js"></script>
```
Unfortunately it has no effect. Am I using it incorrectly? My page is http://healthfitchiro.com/alternate-login/

**Comment by davidjbradshaw** [comment]
You have to wait for the iFrame to resize before making that call.

https://github.com/davidjbradshaw/iframe-resizer#readycallback
