### ISSUE TITLE
Iframe resizing problem.

### ISSUE THREAD

**Issue by BlackTones** [davidjbradshaw/iframe-resizer#493]
Hello :) I'm fightin with iframes on my site. 
All looks like this:
https://sklepdruku.pl/project/wizytowki-skladane/
And iframed site is from this domain:
https://zakupy.sklepdruku.pl/product/wizytowki-klasyczne
So google chrome is giving me this error
"[iFrameSizer][iFrameResizer0] No tagged elements (data-iframe-height) found on page"
iframeResizer.contentWindow.min.js is implemented in head of zakupy.sklepdruku.pl.
Ah and there is something strange, mayby you can help me with that. My iframe is seting up to height:0px; so i need to force min height in css.

All should work like this http://www.comers-drukarnia.pl/archiwa/produkty/biuro/pocztowki

**Comment by davidjbradshaw** [comment]
Use a different high calculation method.

https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod
