### ISSUE TITLE
prevent double scroll

### ISSUE THREAD

**Issue by Coeos** [davidjbradshaw/iframe-resizer#495]
Hi, i'm using your library on a iframe on which I've no hand (cross domain).
I would like to avoid the scroll on this iframe ( avoid double scrollbar body / iframe), 
a click on a button in the frame  scroll inside it  thus I can't scroll back to the top, is there a way to set a scrollTo (0,0) or refresh the size calculation? 

there is a jsfiddle https://jsfiddle.net/jz2sctcd/
if you click on one of the social button, the scroll gets wrong, any idea? 
thanks!

**Comment by davidjbradshaw** [comment]
You have to get the other domain to include the `iframeresizer.contentWindow.js` file.

**Comment by Coeos** [comment]
HI, actually it does
https://broadbean.socialreferral.com/iframeResizer.contentWindow.min.js

**Comment by davidjbradshaw** [comment]
I'm not seeing a double scroll bar

**Comment by Coeos** [comment]
oh the ending point is an integration inside a wordpress page thats  why I have a double srollbar, nevrmind, it's more a web problem with no link with your library  

last question 
is it possible to change css elements inside the frame with your lib the same way we have bodyBackground ?

**Comment by davidjbradshaw** [comment]
The only CSS you can change from outside the iFrame is the `bodyMargin` and `bodyBackground`.

Beyond that you would have to write something that passes a URL of a stylesheet via PostMessage
