### ISSUE TITLE
iframe with excessive height after resizing

### ISSUE THREAD

**Issue by victornpb** [davidjbradshaw/iframe-resizer#504]
I cannot find why this is happening nor a way to solve this issue.

https://jsfiddle.net/Victornpb/nb0mewwv/show

if you resize your window from wide => narrow (like 400px) => wide and leave 1150px, there's a almost screen tall excess margin at the end of the page.

I've tried all heightCalculationMethod settings.

It would be great if I could fix this without changing the frame content.

Gif: https://gfycat.com/IllinformedLonelyAnkole

**Comment by davidjbradshaw** [comment]
This is almost certainly a CSS issue.

You might get around it by using `taggedElement` height calculation method.

**Comment by victornpb** [comment]
I do not control the iframe content, so I can't use any element in specific. Is there any workaround?

**Comment by davidjbradshaw** [comment]
Nope, not possible without access to the other page.

**Comment by victornpb** [comment]
I mean, I have a script injected there so I can initiate the frame.js but the actual content is dynamic, it is user uploaded, I can do whatever I want via js, like traverse the DOM, modify it, but I have no way of manually fixing it without a algorithm to detect this and fixing this behavior.

First I have to isolate what style make this happen.
Then I can write a test to detect it on the page l.
Then decide if I should like modify the style/element in question or modify the height calculation algorithm for that page.

Any thoughts?
