### ISSUE TITLE
[off/2] [discussion] Using library without access to site with iframe hosting

### ISSUE THREAD

**Issue by hellboy81** [davidjbradshaw/iframe-resizer#505]
Info from manual:

> The first (iframeResizer.min.js) is for the page hosting the iFrames. It can be called with native JavaScript;
> 
> The second file (iframeResizer.contentWindow.min.js) is a native JavaScript file that needs placing in the page contained within your iFrame. This file is designed to be a guest on someone else's system, so has no dependencies and won't do anything until it's activated by a message from the containing page

Is there possible to use library in this case:

```html
<!-- COP iframe should be inside a form -->
<form enctype="application/x-www-form-urlencoded" method="post" action="..">
    <!--Hier wird mittels Script div durch iframe ersetzt -->
    <div id="@containerName"></div>
</div>

<!-- Script from 3rd party server we dont own and cannot modify -->
<script type="text/javascript" src="@embedScriptUrl"></script>
<script type="text/javascript">
   // Code to initialize IFRAME
   
  // IFrame can be accessed here
  var copIFrame = document.getElementById(@containerName);
  copIFrame.sandbox.add("allow-same-origin");

    // Important! To allow 3rd party IFrame to add token hidden field to form
    copIFrame.sandbox.add("allow-scripts");
</script>
```

**Comment by davidjbradshaw** [comment]
You would have to detect that the iFrame contents have loaded, inject the script into the iFramed page. Detect when it has finished loading and then call `iFrameResize` on the parent page.

**Comment by davidjbradshaw** [comment]
Also you would need to be able to access `copIFrame.contentWindow`

**Comment by hellboy81** [comment]
>Also you would need to be able to access copIFrame.contentWindow

Here I am getting problems with 


```js
var getIFrameDocument = function getIFrameDocument(iframe) {
    // SecurityError: Permission denied to access property "document" on cross-origin object
    var doc = iframe.contentDocument ? iframe.contentDocument : (iframe.contentWindow ?  iframe.contentWindow.document : iframe.document);

     return doc;
}

var x = getIFrameDocument(copIFrame);
```

**Comment by davidjbradshaw** [comment]
You have to get the other site to give you permission using CORS.
