### ISSUE TITLE
query-string-append feature question/request

### ISSUE THREAD

**Issue by GoOcto** [davidjbradshaw/iframe-resizer#506]
I'd like to see a feature in iframeResizer that allows me to provide a string to append to the query string for all framed pages. That is, when the user clicks a nav link within the frame the QSA value provided will persistently be appended to all query strings. 

So, for example, if I call `iFrameResizer({qsa:"framed=1"})` then all URLs within the iframe will contain whatever URL was in the link plus the "framed=1" parameter. This allows me to omit some content or style it differently when I know that I or some other authorized web developer is containing it within an iframe.

Does a feature like this already exist?

**Comment by davidjbradshaw** [comment]
You could add something like this to your pages, so that they update their links once the iFrame has resized.
```
<script>
  window.iFrameResizer = {
     readyCallback: () =>
         document.getElementsByTagName('a').forEach(a => a.src = a.src + '?framed=1')
  }
</script>
```
