### ISSUE TITLE
Expose getHeight / getWidth in the content frame

### ISSUE THREAD

**Issue by Rycochet** [davidjbradshaw/iframe-resizer#509]
I've just run into an issue at work where an external client is loading content into an iframe, and using a custom bit of code for resizing the frame. We have no control over the outer window itself, but can change the contents - so can't use iframeResizer properly.

It got me thinking that it would be useful if there were `getHeight` and `getWidth` methods exposed within the content frame, so I can effectively get the numbers that are normally reported back, and then send them back through their own method, rather than having to use custom code to do the same job that we normally leave up to this ;-)

Just to be annoying, the client is adding 20px to the iframe size, so we'd need to manipulate the numbers reported anyway to account for that...

**Comment by davidjbradshaw** [comment]
You can supply your own custom methods to work out the page size.

https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod--widthcalculationmethod

**Comment by Rycochet** [comment]
The issue is that I can't put iframeResizer on the outside page to do the actual resizing, so want to use the content window script on it, but manually pass those numbers on (and in this case take 20px off the height).

In addition, if using a custom method it would probably be useful to be able to get hold of the normal methods used to manipulate them (ie, wanting the width to be a multiple of 20px etc) - rather than having to work it all out manually, just changing it slightly afterwards.

**Comment by davidjbradshaw** [comment]
It would be more complex than that, as the script doesn't start till it gets a call from the outside window, so won't work without it.

**Comment by Rycochet** [comment]
Ah, I see - although the methods there are perfectly usable, there's nothing to attach them to so they can be exposed (I've only had a quick look through, so missed that) - would it be possible to send a local message to initialise it first?

The second part (ie, for everyone who might want to get access the internal methods) could still be useful even if not.

**Comment by davidjbradshaw** [comment]
I think at this point we are beyond the scope of the project.

You best bet is to create a fork and make a version with your own hooks. Look at lines 983 and 1101.

**Comment by n0rthk1n9** [comment]
Hi @davidjbradshaw is this feature still out of the scope of this project? I think you did an awesome work with this project and I want to use it to work with the amp Project of Google. So I have the exact same problem, that I am not able to place the iFrameResizer.contentWindow,js into the amp iFrame and therefore can not use iFrame Resizer.

**Comment by davidjbradshaw** [comment]
Not sure this would work on AMP, as the pages are hosted by Google you would run into cross-domain issues

**Comment by n0rthk1n9** [comment]
We would want to use the resize/change detection from the contentWindow script and instead or addionally fire the postMessage implemented in the AMP runtime. That way the resizing would work with the library on the "normal" site but use the same logic for AMP.

**Comment by davidjbradshaw** [comment]
I still think that is way beyond the scope of this project. What you could do is post a message from the child to the same window mocking the message that normally gets sent from the parent and then catch the response. Which might be simple enough, or otherwise just lift the hieght calculation method that you need from this code base
