### ISSUE TITLE
IFRAME not resized on Google reCAPTCHA challenge popup 

### ISSUE THREAD

**Issue by benallfree** [davidjbradshaw/iframe-resizer#512]
Has anyone else run into this issue? The iframe height will not adjust to accommodate a recaptcha challenge popup.

**Comment by davidjbradshaw** [comment]
Can you put a simple test case up somewhere?

**Comment by davidjbradshaw** [comment]
Will re open if someone sends me a simple test case

**Comment by timnolte** [comment]
This is a very old issue, but it seems like it still exists, and I'm surprised there has not been a more recent report on it. I'm am having the very issue when attempting to embed a Pardot form that includes a reCaptcha.

**Comment by chris-vas** [comment]
Has anyone found a solution to that one?

**Comment by davidjbradshaw** [comment]
Still waiting on someone to create a simple test case

**Comment by timnolte** [comment]
I was able to find a working custom setting combination that worked. I will supply my fix once I get a chance to go look at the code again.

**Comment by miglehu** [comment]
Can anyone point me in a direction where I can learn more about how fix this issue? It looks like it's still an ongoing problem:
![image](https://user-images.githubusercontent.com/88154251/127544483-6091a0b7-ad39-4d2f-bc96-297cd2320c0a.png)

![image](https://user-images.githubusercontent.com/88154251/127543227-f2b4fe2e-f8f7-410d-8018-365a3c3a136c.png)

iframe-resizer works to accommodate the initial reCAPTCHA box, but the challenge box does not trigger a resize. I think it only happens on short forms where the initial form is shorter than the reCAPTCHA challenge box.

It looks like @timnolte was able to tweak the iframe resizer to work on https://bettergivingstudio.com, but I lack the detective skills to figure out how. If anyone could point me in the right direction I would greatly appreciate it. I'm happy to put in the work, but unfortunately I don't know where to start. 

@davidjbradshaw I can send you a link to a site where you can test it if you email me: michaelghuggard@gmail.com

Any help anyone can offer would be greatly appreciated!

**Comment by davidjbradshaw** [comment]
Given the nature of this, why not just set a min size for the iframe that is tall enough for this box?

**Comment by timnolte** [comment]
> @timnolte were you able to find a fix for this?

@kahlan88 sorry, I'll try to post and update with the settings I ended up using sometime this week.

**Comment by timnolte** [comment]
> Given the nature of this, why not just set a min size for the iframe that is tall enough for this box?

@davidjbradshaw setting a minimum height sort of defeats the purpose of the plugin as you end up with an initial display of a bunch of blank space.

**Comment by timnolte** [comment]
@kahlan88 the key for me was to set the `heightCalculationMethod` to use `documentElementScroll` using the following code on the page:
```
<script type="text/javascript">
	iFrameResize({log:true,heightCalculationMethod:'documentElementScroll'});
</script>
```

**Comment by miglehu** [comment]
@davidjbradshaw thank you for supporting this library and responding to this topic. I appreciate the simple solution you offered. I will probably go with the more responsive solution mentioned above to minimize initial blank space. I am sincerely grateful for your work though; I'm stuck with iframes and this library has really helped improve our website.

**Comment by miglehu** [comment]
@timnolte thank you so much for responding to this old thread and sharing your insights / solution. I'll be using your method.
I really appreciate your help!
