### ISSUE TITLE
Do not work with Doxigen HTML file in an iframe

### ISSUE THREAD

**Issue by grrseguin** [davidjbradshaw/iframe-resizer#514]
Hello,

After having implemented "iframe-resizer", it doesn't work with a "Doxygen" documentation.

I reproduce your demo page in a [JSFiddle](http://jsfiddle.net/tc5yj5wz/) and as you can see [in my example](http://jsfiddle.net/grrseguin/tc5yj5wz/3/), the `iframe` is not resized.

Have you got an idea why ?

**Comment by davidjbradshaw** [comment]
Your fiddle works fine for me

**Comment by grrseguin** [comment]
On Chrome Version 60.0.3112.101 (Build officiel) (64 bits) MAS OS X:
<img width="659" alt="capture d ecran 2017-08-23 a 15 46 10" src="https://user-images.githubusercontent.com/5268254/29619752-294f6a1c-881c-11e7-8712-d456f3206e20.png">

The menu is truncated!

**Comment by davidjbradshaw** [comment]
That is not the fiddle that you linked

**Comment by grrseguin** [comment]
Yet the same

**Comment by grrseguin** [comment]
In your demo page, when you click on "Toggle content", the height of the iframe tag change, but not with my Doxygen documentation, right ?

> Click on PLDuino the first link in the content section
