### ISSUE TITLE
Option to suppress all console warnings

### ISSUE THREAD

**Issue by shofman10** [davidjbradshaw/iframe-resizer#515]
Hi,

Thanks for this plugin, it works great! The problem though that I'm running into is the console warning messages are quickly filling up my console.

I'm implementing this for an iframe that is inside of a modal, but the modal disappears from the dom when it's closed so a lot of warning messages get thrown "IFrame(iFrameResizer0) not found" and such.

It would be great if there was an option to suppress all of these warnings :)

**Comment by shofman10** [comment]
Or even just a way to uninitialize the plugin on modal close

**Comment by davidjbradshaw** [comment]
You can call the close() method from both the iframe and the parent page. See the docs.
