### ISSUE TITLE
Can the iframe script be omitted if CORS available

### ISSUE THREAD

**Issue by aleemb** [davidjbradshaw/iframe-resizer#516]
Is it possible to skip embedding the script in the iframe if CORS policy is used?

**Comment by davidjbradshaw** [comment]
Nope, although you could maybe get the parent page to load it into the child.

**Comment by aleemb** [comment]
@davidjbradshaw my thinking was that if the iframe is on the same domain, the solution is very trivial, so the same solution would apply with CORS by explicitly trusting the other domain.

Not sure how the parent would load it into the child. Any pointers or links?

**Comment by davidjbradshaw** [comment]
To use this script in same or cross domain requires a script to be placed in the iFrame. Have a look at the following for how to load it

https://stackoverflow.com/questions/14521108/dynamically-load-js-inside-js
