### ISSUE TITLE
Use readyState to know if document is ready

### ISSUE THREAD

**Issue by lostincomputer** [davidjbradshaw/iframe-resizer#517]
iframeResizer.contentWindow thinks that my HTML page is ready even though it isn't. I unfortunately can't pinpoint which part of my HTML page is causing the problem so I can't tell you how to reproduce the problem. The problem is extremely easy to fix though. 

In iframeResizer.contentWindow, replace `document.body` with `document.readyState === "interactive" || document.readyState === "complete"`

so that this:

```
if (document.body){
	fireInit();
} else {
	log('Waiting for page ready');
	addEventListener(window,'readystatechange',processRequestFromParent.initFromParent);
}
```

becomes

```
if (document.readyState === "interactive" || document.readyState === "complete"){
	fireInit();
} else {
	log('Waiting for page ready');
	addEventListener(window,'readystatechange',processRequestFromParent.initFromParent);
}
```

**Comment by davidjbradshaw** [comment]
Nice do you want to make a PR?

**Comment by davidjbradshaw** [comment]
Fixed in r3.5.15
