### ISSUE TITLE
Ignored iFrame, already setup.

### ISSUE THREAD

**Issue by jzhanglsw** [davidjbradshaw/iframe-resizer#519]
Here's a very simple JSFiddle example:
http://jsfiddle.net/2sLfzvua/

For whatever reason, calling iFrameResizer spits out the following error:
iframeResizer.js:132 [iFrameSizer][Nested host page: IframeId] Ignored iFrame, already setup.

What am I missing here?

**Comment by davidjbradshaw** [comment]
You only need to call iFrameResize once
