### ISSUE TITLE
iFrameResizer doesn't work in Firefox Extension environment

### ISSUE THREAD

**Issue by mdnsk** [davidjbradshaw/iframe-resizer#522]
iFrameResizer doesn't work in firefox extension enviroment. (Firefox 55).
In browser console I see the error: "TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window.", it looks like Semantic-Org/Semantic-UI#3855
So now I use the following hack to make it working in firefox extension:

In the file iframeResizer.js:
line 12: ;(function(window) {
and
line 1040: })(Function('return this')());

**Comment by davidjbradshaw** [comment]
Will take a look when I next have some free time. Thanks for the link.

**Comment by davidjbradshaw** [comment]
Having read up on this, happy to take a PR.
