### ISSUE TITLE
How to use it in vue.js

### ISSUE THREAD

**Issue by mysteryHJJ** [davidjbradshaw/iframe-resizer#523]
Can you give me some advice

**Comment by davidjbradshaw** [comment]
I'm afraid I have never used Vue.js. Maybe worth asking on stackoverflow. I will leave this open in the hope some in the future can add some suggestions here.

**Comment by mysteryHJJ** [comment]
I have already sloved this problem. Thank you all the same.

**Comment by davidjbradshaw** [comment]
Can you share the fix here, in case anyone else has the same issue.

**Comment by alexpvieira** [comment]
Just sharing for anyone looking to use this library in a Vue project (the Vue part in this case will be the page contained in the iFrame).

You need to put the [iframeResizer.contentWindow.min.js](https://raw.github.com/davidjbradshaw/iframe-resizer/master/js/iframeResizer.contentWindow.min.js) into your src folder then include it into your main.js file as bellow:

```
import * as Resize from './path/to/iframeResizer.contentWindow.min.js'
Vue.use(Resize)
```

Got it woking doing this way.
