### ISSUE TITLE
Native js call iFrameResize not working, but jQuery $('iframe').iFrameResize(); call does.

### ISSUE THREAD

**Issue by emiellohr** [davidjbradshaw/iframe-resizer#525]
I'm having a problem with a particular html/site. The offline version is attached here. My script that calls iFrameResize didn't work here. Repeating the call from the console returns an empty array. Calling the jQuery version works and resizes the iframe correctly, but I can't alway depend on jQuery. What can be the problem here? Looks like the script isn't detecting the iframe elements correct, since it returns an empty array.

[Entreetickets Kasteeldag.html.zip](https://github.com/davidjbradshaw/iframe-resizer/files/1333145/Entreetickets.Kasteeldag.html.zip)

**Comment by davidjbradshaw** [comment]
Hi,

I don't have time to debug your code, but I expect that you are calling iFrameResize too early. You need to place the code that make the call after the iFrame in the HTML. Loading the script at the bottom of the page is the best way of doing this.

If you think you have found a bug, then please make a simple test case.

Dave.
