### ISSUE TITLE
Calls to resize don't work after iframe contents are reloaded

### ISSUE THREAD

**Issue by ianluddy** [davidjbradshaw/iframe-resizer#533]
Hi David,

I have an issue when trying to resize the iframe after the page within it gets reloaded.
The child page contains a form which will be submitted and the page will be reloaded but the height will have increased.

**In the parent page I do the following, which sets the height correctly initially:**
```
$(document).ready( function(){ 
  jQuery("#targetIframe").iFrameResize({log:true, checkOrigin: false}); 
}); 
jQuery("#targetIframe").on("load", function(){ 
  targetIframe.iFrameResizer.resize(); 
});
```
**Typically I will get the following response when resize is called:**
```
targetIframe.iFrameResizer.resize()
iframeResizer.js:129 targetIframe[Host page: targetIframe] [Window resize] Sending msg to iframe[targetIframe] (resize) targetOrigin: *
undefined
```
**Or else I get an actual error:**
```
iframeResizer.contentWindow.js:1025 Uncaught TypeError: Cannot read property 'split' of undefined
    at getMessageType (iframeResizer.contentWindow.js:1025)
    at callFromParent (iframeResizer.contentWindow.js:1058)
    at processMessage (iframeResizer.contentWindow.js:1093)
    at receiver (iframeResizer.contentWindow.js:1102)
```
Any assistance would be greatly appreciated.

Thanks,
Ian

**Comment by ianluddy** [comment]
Thanks for the quick response David, I removed that call but still having issues.
When page loads initially the size is set correctly but when the form in the iframe is submitted the container doesn't get resized.

**I'm still seeing this happen in the console:**
parcelTracker[Host page: parcelTracker] [Tab Visable] Sending msg to iframe[parcelTracker] (resize) targetOrigin: *
VM5184 iframeResizer.contentWindow.js:1025 Uncaught TypeError: Cannot read property 'split' of undefined
    at getMessageType (VM5184 iframeResizer.contentWindow.js:1025)
    at callFromParent (VM5184 iframeResizer.contentWindow.js:1058)
    at processMessage (VM5184 iframeResizer.contentWindow.js:1093)
    at receiver (VM5184 iframeResizer.contentWindow.js:1102)

**Comment by davidjbradshaw** [comment]
Are you using the latest `3.5.15` version?

**Comment by ianluddy** [comment]
Updated to latest version and it's all good, thanks David
