### ISSUE TITLE
Destructor needed

### ISSUE THREAD

**Issue by f-w** [davidjbradshaw/iframe-resizer#534]
When the parent is a SPA and user navigates away from the view that contains the iframe, the <iframe> dom is removed but iframe-resizer still listens to windows resize event and complains something like `[Window resize] IFrame(#element) not found`.

To correct, I think iframe-resizer should automatically destroy itself when the binding iframe dom is removed, or at least offering an API to do so. The destructor should at least remove all the event listeners it registered.

**Comment by davidjbradshaw** [comment]
```
const iframe = documentGetElementById('myIFrame');
iframe.iframeResizer.close();
```

**Comment by f-w** [comment]
Thanks @davidjbradshaw , that works. I have noticed method .close() but couldn't figure out how to obtain the iFrameResizer object. I have tried `let obj = $('iframe').iFrameResize( [{options}] )` but I found obj doesn't have .close().

**Comment by davidjbradshaw** [comment]
You have to use the non-jQuery version to do that.
