### ISSUE TITLE
Bootstrap Modal position to the ifram content center but it should center of client desktop

### ISSUE THREAD

**Issue by thehiddennepali** [davidjbradshaw/iframe-resizer#540]
Everything works fine with this, but the bootstrap modal took the center position of the iframe content, but in this the requirement is that it should take center of the main document.

I have list of long menu item, and when click on the item add it gives me boostrap modal to select option but, the popup open on the center of the iframe menu list which very long, so if the bootstrap modal take center of the main body than iframe content, it will very useful.

Let me if there already any turnaround for this, i checked all the closed issue but didn't find any of this kind.

Thank you waiting for your kind response.

**Comment by davidjbradshaw** [comment]
It requires a little work on your part, but this call will give you all the data that you need.

https://github.com/davidjbradshaw/iframe-resizer#getpageinfocallback--false

**Comment by nunopeixoto** [comment]
> It requires a little work on your part, but this call will give you all the data that you need.
> 
> https://github.com/davidjbradshaw/iframe-resizer#getpageinfocallback--false

URL does not work. Can you replace it?
