### ISSUE TITLE
Resizer not working with multiple iFrame instances

### ISSUE THREAD

**Issue by bmcpeakserenova** [davidjbradshaw/iframe-resizer#541]
Hi,

I'm implementing iFrame Resizer on several iFramed forms within light boxes on this page:

https://succeed.serenova.com/lp-cloud-contact-center/

The only instance where iFrame Resizer works is on the first lightbox, which is instantiated through the "Get My Free Live Demo" button and a few others. 

The lightboxed iFrames connected to the "Questions?" and "Download the Gartner Report" buttons are not working, despite being implemented in exactly the same way. 

Here is the first light box before resize:
![lightbox-1-before-resize](https://user-images.githubusercontent.com/23015601/33567246-2e615796-d8e8-11e7-81fe-0a0ba46e3799.png)

And after successful resize: 
![lightbox-1-after-successful-resize](https://user-images.githubusercontent.com/23015601/33567245-2e53aa6a-d8e8-11e7-854d-bc959c3a9535.png)

And the second before:
![lightbox-2-before-resize](https://user-images.githubusercontent.com/23015601/33567250-2e7dd470-d8e8-11e7-899f-897998efa31b.png)

And after failed resize:

![lightbox-2-after-failed-resize](https://user-images.githubusercontent.com/23015601/33567248-2e6f1d9a-d8e8-11e7-83f3-900e51e74fbb.png)

Note that the form at the very bottom of the page is the exact same iFrame as the one that's working, but even it is not working on the second instance.

Can you help me understand why it is working on the first instance but not the following ones?

Thanks!

**Comment by davidjbradshaw** [comment]
If you think this is a bug in iFrameResizer please create a simple test case. If you just need help using it then ask a question on StackOverflow and add the `iFrame-iframeresize` tag.

**Comment by bmcpeakserenova** [comment]
Thanks for your response, David. I'm not 100% sure that this isn't user error, so I have gone ahead and asked a question on StackOverflow with that tag.
