### ISSUE TITLE
jquery animate now working 

### ISSUE THREAD

**Issue by thehiddennepali** [davidjbradshaw/iframe-resizer#546]
Jquery animate is not working.
This is the http://www.littlesicily.com.au/order-now/ where iframe is included. When on clicking on the left category animate is not working.

**Comment by davidjbradshaw** [comment]
Sounds like a bug with jquery animate then.

**Comment by thehiddennepali** [comment]
when i remove the iframe resizer jquery animate works.

**Comment by thehiddennepali** [comment]
i have used parentIFrame.scrollTo() method to scroll. But after that it is repositioned automatically. I cannot scroll to up or down. Its sending message to the host page.
