### ISSUE TITLE
Doesn't Seem To Be Working

### ISSUE THREAD

**Issue by robertallenbaker** [davidjbradshaw/iframe-resizer#549]
Hi,

I tried to implement this, but I'm getting an error:

iframeResizer.js:643 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://dealers.feedlease.com') does not match the recipient window's origin ('http://fl2017.wpengine.com').
f @ iframeResizer.js:643
i @ iframeResizer.js:652
u @ iframeResizer.js:676
o @ iframeResizer.js:813
w @ iframeResizer.js:861
b @ iframeResizer.js:988
(anonymous) @ iframeResizer.js:1012
(anonymous) @ custom.js?ver=1.0.0:21
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
iframeResizer.js:132 [iFrameSizer][Host page: dealers-frame] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ingored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.
k @ iframeResizer.js:132
j @ iframeResizer.js:127
a @ iframeResizer.js:662
setTimeout (async)
k @ iframeResizer.js:667
u @ iframeResizer.js:677
o @ iframeResizer.js:813
w @ iframeResizer.js:861
b @ iframeResizer.js:988
(anonymous) @ iframeResizer.js:1012
(anonymous) @ custom.js?ver=1.0.0:21
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
iframeResizer.js:132 [iFrameSizer][Host page: dealers-frame] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ingored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.

The source is http://fl2017.wpengine.com/dealer

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer#checkorigin

**Comment by cdalexndr** [comment]
bad link in solution
