### ISSUE TITLE
Height not changing when advancing to sub pages (stays at shrink state and not expanding)

### ISSUE THREAD

**Issue by spacejunkie774** [davidjbradshaw/iframe-resizer#550]
Hello David, 
similar to issue https://github.com/davidjbradshaw/iframe-resizer/issues/384 

iframe is not resizing (shrinking footer) when navigating away from parent page. It is retaining the height and is left with a big gap between footer of iframe and footer of host page.
The gap disappears when shrinking window size for mobile device view.

I have heightCalculationMethod: 'lowestElement'. taggedElement does not work at all, and i'm not quite sure where I should insert data-iframe-height attribute as am just not that saavy.

Please see https://futureprimitive.org/community
Username: test
Password: fptest

You'll notice after logging in the 'Board Index' page is ok, but once you click on a board, say 'Episodes', you will see the gap. 

js log is enabled.

**Comment by spacejunkie774** [comment]
Hello,
Willing to send some funds via PayPal to help with this. :) We appreciate your work!

**Comment by davidjbradshaw** [comment]
The attribute should be added to the HTML element you want to use to measure the height of the page. 

My rate for consulting services is USD1,000 per day. Email if interested
