### ISSUE TITLE
Duplicate iframe instance created (cascading iframes)

### ISSUE THREAD

**Issue by spacejunkie774** [davidjbradshaw/iframe-resizer#551]
Hello David,
I have another issue with iframe resizer and perhaps it is not the issue but thought I would check and see if there is a simple solution.

The iframe is creating another instance of iframe when clicking on certain links such as the 'home' button (home button for forum) or the middle logo that should take you back to the main page, in this case the forum home page and not the host site home. You can do this repeatedly until your left with a vertical cascade of iframes that is encompassing wordpress.

The home button or large center graphic at the top should take you back to the forum home.

Please see https://futureprimitive.org/community
Username: test
Password: fptest

See if you can replicate this issue by logging into the forum and then clicking the center graphic  (Zia symbol or Sun symbol), or also in right hand corner "Home" link. 

Thanks,
Justin

**Comment by spacejunkie774** [comment]
Solved.

**Comment by deva-gali** [comment]
Hi ,

I have the same issue as above. Kindly let me know the fix for cascading issue.

Thanks,
Deva.
