### ISSUE TITLE
Uncaught syntax error 

### ISSUE THREAD

**Issue by chaitanya1248** [davidjbradshaw/iframe-resizer#553]
<img width="636" alt="screen shot 2018-01-10 at 4 55 39 pm" src="https://user-images.githubusercontent.com/20464756/34799911-45705ade-f627-11e7-9d6a-543baa8c1b99.png">

I get 'Uncaught syntaxError: Unexpected token <' on iframeResizer.contentWindow.min.js. Is there any formatting issue when saving the min file from git?

**Comment by schwamic** [comment]
@chaitanya1248 how did you solve the problem?

**Comment by davidjbradshaw** [comment]
Don't try and run it directly from GitHub would be my guess looking at the @chaitanya1248 post above. If you don't want to host the file yourself, use jsdeliver or cdnjs.

**Comment by Venubalan-T** [comment]
@chaitanya1248 How did you solve this issue ? i am facing the same
