### ISSUE TITLE
Example not working correctly on "fast" resize

### ISSUE THREAD

**Issue by thomasmattheussen** [davidjbradshaw/iframe-resizer#558]
http://davidjbradshaw.com/iframe-resizer/example/

When resizing very slowly, the resizing keeps on working. But when resizing a little faster, it's not resizing properly (iframe height ends to be too small or too high). When you click inside the iframe, it's then resized to the correct height.

I'm guessing it's related to https://github.com/davidjbradshaw/iframe-resizer/issues/405 (but that's just wild guesswork)

**Comment by davidjbradshaw** [comment]
This should be fixed now
