### ISSUE TITLE
Event emitter option

### ISSUE THREAD

**Issue by chaitanya1248** [davidjbradshaw/iframe-resizer#559]
I've implemented `iframe-resizer` library in angular 4 environment. It works well doing the resize part and updating the height whenever the iframe DOM height changes.

Now we have a requirement to reset the parent window session clock while the user is interacting within the iframe. I see the events getting trigged and logging on console. 

I updated `iframeResizer.contentWindow.js` to send back parent a string message with event type for various DOM events like mouse, input, scroll. 

Would this be a valid use case for others? 
If yes, can I add an option and make a pull request with the changes?

**Comment by davidjbradshaw** [comment]
It would be cool to have an Angular wrapper as a separate project, like current exists for React. 

This project will remand library agnostic
