### ISSUE TITLE
IE Constant Refreshing

### ISSUE THREAD

**Issue by michaelflip7** [davidjbradshaw/iframe-resizer#56]
In IE11 (or any other version of IE), my initial frame loads in properly, though sometimes subsequent page loads cause the frame to constantly reset, grabbing a different height value every time.

Link: 
Settings:

```
enablePublicMethods     : false,                  
                heightCalculationMethod : 'max',
                interval                : -33,
                autoResize              : true, 
                checkOrigin             : false,
```

To replicate: In IE, initial page loads in fine, on left hand side, click 'Search', next page loads in, and infinitely refreshes.

I tried changing the interval to 0, -X, and X and it didn't seem to fix the problem. 

Any ideas?

EDIT: Also, as a side/unrelated question, how would I go about positioning the parent frame to the top of the page after each resize? (sometimes on a long page, if you click a link, you stay at the bottom of the page on the parent frame, leaving some people lost!

**Comment by andreyvolokitin** [comment]
Dealing with the same issue here. IE9+ working fine with ```autoResize: true```. But in IE8 iframe height is constantly increasing. ```autoResize: false``` solves this, but what if we actually need ```autoResize: true```? As far as I understand when we set ```autoResize: true``` iframe is resizing automatically when we make changes to the iframe DOM. This seems like very common need, so I am wondering if this can be solved without needing to set ```autoResize: false```.

I also found that this CSS inside iframe can cause this issue:

```css
html,
body {
    height: 100%;
    }
```

But I think this is valid CSS and in the perfect world it should not cause issues like this...
