### ISSUE TITLE
Closing Iframes

### ISSUE THREAD

**Issue by bindrid** [davidjbradshaw/iframe-resizer#565]
I am stumped on how to close individual iframe resizers.

My Iframes are dynamically added and removed. My code looks something like

```
  var newFrame = $("<div class='frame-wrapper'><iframe seamless /></div>");
          var resizer = newFrame.data("iframeresizer", iFrameResize({
            log: false,
            heightCalculationMethod: 'taggedElement'
        }, newFrame.find("iframe")[0]));
```

These iframes are added by the user when they click on a particular node in a tree.
When they are done, they can individually close the iframes they have opened.

It all works except I cannot figure out how to unbind and remove the instance of the resizer that was created with the iframe so I end up with a bunch of warnings  like:
```
gentpsplanner.js:6054 [iFrameSizer][Host page: iFrameResizer0] [Window resize] IFrame(iFrameResizer0) not found.
```
I get that warning for each time the user adds then remove an iframe.

**Comment by davidjbradshaw** [comment]
From the `iFrame`
https://github.com/davidjbradshaw/iframe-resizer#close

From the parent page
https://github.com/davidjbradshaw/iframe-resizer#close-1

**Comment by bindrid** [comment]
Sorry to have wasted your time. I did not understand that the instance of the resizer was being added to the instance of the iframe element.
Scott

**Comment by davidjbradshaw** [comment]
Np
