### ISSUE TITLE
Events keep listening even when the iframe element is gone

### ISSUE THREAD

**Issue by bmxmaga** [davidjbradshaw/iframe-resizer#566]
Hi,
I'm using the iframe-resizer in a React project (don't ask why).

**The problem is**, once I initialize the iframe-resizer on an iframe element, some window event handlers are listening forever, even if the iframe element is removed from the DOM (which is pretty common for a React app when you navigate to a different route).

I'm getting warnings in the console, like:

`[iFrameSizer][Host page: iFrameResizer0] [Window focus] IFrame(iFrameResizer0) not found`
or
`[iFrameSizer][Host page: iFrameResizer0] [Window resize] IFrame(iFrameResizer0) not found`

**The questions is**, how can I unbind all the window event handlers that are failing to find the removed iframe?

**Comment by davidjbradshaw** [comment]
Have you tried

https://github.com/brudil/react-iframe-resizerY

**Comment by bmxmaga** [comment]
Yes, I have tried it but it doesn't support React v15.5 which uses prop-types package instead of built-in React.PropTypes object. But that's a separate story...

The package that you pointed, basically uses the same approach that I managed to prepare by myself. This approach doesn't work because of a bug in iframe-resizer in the first place.

This bug is:

```
import iframeResizer from 'iframe-resizer/js/iframeResizer';

// (...) later in the code
this.resizerInstance = iframeResizer(this.iframe);

// (...) when the component is detached
this.resizerInstance.close();
```

This gives me an error in the console:
```
this.resizerInstance.close is not a function
```

Is it really a bug or I am doing something wrong?

**Comment by davidjbradshaw** [comment]
That should work. What does `this.resizerInstance` contain at that point

**Comment by bmxmaga** [comment]
When I `console.log` it, it tells me that it's an array with one element being the iframe itself:

```
console.log(Array.isArray(this.resizerInstance),
  this.resizerInstance[0] instanceof HTMLIFrameElement,
   this.resizerInstance.close);
```

gives:

```
true, true, undefined
```

**Comment by davidjbradshaw** [comment]
Ah
```
this.resizerInstance[0].close();
```

**Comment by bmxmaga** [comment]
I don't think so :(

```
this.resizerInstance[0].close is not a function
```

**Comment by bmxmaga** [comment]
The latter works! Thank you :)

```
this.resizerInstance[0].iframeResizer.close();
```
