### ISSUE TITLE
Iphone X Issue

### ISSUE THREAD

**Issue by dozel** [davidjbradshaw/iframe-resizer#569]
Has anyone noticed weirdness on iPhone X when resizing an iframe? I don't think it gets the right dimensions for it. It seems to make it wider than it should be.

**Comment by davidjbradshaw** [comment]
Just tested the example and it seemed to work.

Does this help: https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by dozel** [comment]
![image](https://user-images.githubusercontent.com/1053530/38395545-5c0c9e16-38e8-11e8-9bbd-ae207b112f18.png)

See how it is pushed to the right? Also, the iframe's height is about 40px bigger than what it should be.

**Comment by dozel** [comment]
I will try your suggestion and re-open the ticket if it doesn't work.
