### ISSUE TITLE
inPageLinks not working

### ISSUE THREAD

**Issue by availit** [davidjbradshaw/iframe-resizer#571]
Hello,
I am testing this library for a production feature. I'm needing the inPageLinks option to work as it's [mentioned here](https://stackoverflow.com/questions/34196137/iframe-resizer-js-library-child-anchor-link-not-working-w-iframe-parent/34196888#34196888).

However whenever I set it `true` I still receive this in the console:
`[iFrameSizer][iFrameID] In page linking not enabled`

Any ideas on why it's still false even when I set it with `$('iframe').iFrameResize({inPageLinks:true,log:true});`

Thank you for your time!

**Comment by davidjbradshaw** [comment]
You can see it work in the demo here:

http://davidjbradshaw.com/iframe-resizer/example/

I expect something else in your page is cause the issue, but you have not given me any info to go on.

If you create a simple test case and it is still an issue than please add a link to it here.

**Comment by availit** [comment]
Hey @davidjbradshaw Thanks for responding so quickly.

I've setup a test case located at [https://hungry-hippo.netlify.com/](https://hungry-hippo.netlify.com/)

As you can see the option is set to `true` although the console states otherwise.

**Comment by davidjbradshaw** [comment]
You need to use a more upto date version of the script in the parent. Currently you are using this, which predates the inPageLinks options.

```
iFrame Resizer (iframeSizer.min.js ) - v2.8.3 - 2015-01-29
```
