### ISSUE TITLE
autoResize(false) does not remove parent event listeners

### ISSUE THREAD

**Issue by caillou** [davidjbradshaw/iframe-resizer#573]
I have implemented the following code from the idea outlined in #572:

1. Parent page sends message to iframe
2. Iframe calls `window.parentIFrame.autoResize(false);`

While the event listeners within the iframe are removed in [iframeResizer.contentWindow.js#L487-L495](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L487-L495), the event listeners of the parent are still active and set the hight attribute of the iframe, e.g. `resize` and `scroll` event listeners that are registered in [`startPageInfoMonitor()`](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.js#L287).

Shouldn't these event listeners be removed when calling `window.parentIFrame.autoResize(false);`

If no, how would I have to go about to temporarily remove these event listeners?

**Comment by davidjbradshaw** [comment]
You can force the resize events to come from the child.

https://github.com/davidjbradshaw/iframe-resizer#resizefrom

Beyond that and I think you have found a bug.
