### ISSUE TITLE
Wrong msgID

### ISSUE THREAD

**Issue by auchri** [davidjbradshaw/iframe-resizer#575]
Hi, the message id is different in the two js files, 

https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.js#L23 => iFrameResizer

https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L39 => iFrameSizer

`//Must match host page msg ID`

**Comment by auchri** [comment]
Also, in https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L1101 the message ID is hardcoded..shouldn't it use the msgID variable?

**Comment by davidjbradshaw** [comment]
I agree that it's a little old that it is `msgId` in one and `msgID` in the other, but it is their contents that needs to match. Feel free to make a PR is you want to change it to be `msgId` everywhere.

The second one is a different message, so have a different msgId.

**Comment by auchri** [comment]
I meant that the content of the two differ, not the name of the variables

**Comment by davidjbradshaw** [comment]
They are both `[iFrameSizer]`.

**Comment by davidjbradshaw** [comment]
```
    msgId                 = '[iFrameSizer]', //Must match iframe msg ID
    msgID                 = '[iFrameSizer]',  //Must match host page msg ID
```
