### ISSUE TITLE
IE 11 : IFrame flickers due to ajax call

### ISSUE THREAD

**Issue by anktsrkr** [davidjbradshaw/iframe-resizer#577]
Hi, 
First of all thanks for the great library! 

I'm facing parent website flickering issues in IE 11 only , due to ajax call of child website. 

**Scenario:** In my scenario, Multiple ajax call of child website increases the height of iframe.  and hence for some moment two scrollbars are coming, one is for iframe and another is for browser. (Please see the attached screenshot ) and when everything is completed, parent website takes the actual height! In my child window, i have 4 ajax calls and hence it flickers 4 times before it  takes the final height.  

![image](https://user-images.githubusercontent.com/5505886/39362755-2e2e54bc-4a45-11e8-94ac-0191510cdb4f.png)

As per recommendation, I have tried all types of _heightCalculationMethod_ but none of those worked, and seems the default settings fits best in my scenario : 
   ```
     $('iframe').iFrameResize({
            log: false
        });
```

Any help will be appreciated.  Thanks in advance.

**Comment by davidjbradshaw** [comment]
I'm afraid that is a limitation of IE, the library has to fall back to methods to work out the hieght that can cause flicker.

It might help to set the hieghtCalculationMethod to `grow` while the ajax calls are loading it in, and then change it to `max` once it is complete. The only other option is to play around with `taggedElement` which often has the best results, but requires you to tag the bottem element of the child page.

**Comment by davidjbradshaw** [comment]
It might also just be caused be how slow other scripts on your page are running, blocking the JS execution stack.

**Comment by anktsrkr** [comment]
Hi @davidjbradshaw , indeed _taggedElement_ is working! 
I need to put   `<div style="clear:both"  data-iframe-height></div>` at the bottom of the child window body.

Thank You!
- Ankit
