### ISSUE TITLE
Feature request: Flag to suppress the "scrolling" attribute entirely

### ISSUE THREAD

**Issue by mryand** [davidjbradshaw/iframe-resizer#581]
I have a case where I'd like to use iframe-resizer but I don't need the `scrolling` attribute on the iframe.

In fact, I'd like it to have the option to omit it. That's because I use an accessibility checker (Siteimprove) that flags the `scrolling` attribute as an error because it is presentational.

I don't need to support older versions of IE so the issue explained in the docs should not be a problem.

**Comment by rafaelbiten** [comment]
I also have a use case where I'd like to 'jump' to specific positions of the page instead of scrolling. Any idea on how we could achieve this? Thank you!
