### ISSUE TITLE
Content is not being fit properly in the iframe. I am facing an issue of height.

### ISSUE THREAD

**Issue by tanmay-kadam** [davidjbradshaw/iframe-resizer#585]
I have embedded iframe in page and I want that content to be fit in the iframe. I have fetched the form in the iframe which is from different domain. But the height of the iframe is not being adjusted according to the content.
I want to make iframe resizable height should be adjusted according to the content.

**Comment by hs-tanmay** [comment]
@davidjbradshaw 
That form is coming from third party tool which is pardot sales force tool and I don't see any option to upload js file.

**Comment by davidjbradshaw** [comment]
Then you will need to talk with them

**Comment by hs-tanmay** [comment]
@davidjbradshaw 
Thanks for the support. 
Issue has been resolved.

**Comment by hs-tanmay** [comment]
We have added iframeResizer.contentWindow.js on the third party tool and each and every configuration started working properly.
Thanks for the support.
