### ISSUE TITLE
Scroll top using iframeResizer

### ISSUE THREAD

**Issue by jorgerey89** [davidjbradshaw/iframe-resizer#587]
Hello, I currently have an iframe, and I use your javascript:

Example:
```
<iframe id = "myIframe" src = "https://www.compras.icambio.es/compradivisas.aspx" scrolling = "no"> </ iframe>
```
On the page that is the URL of the src, I have included the javascript `iframeResizer.contentWindow.js`

The problem is the following, when I am browsing:

I have a form on the first page, when I sent it the scroll stays in half because the second screen is higher than the first and I want it to go back to the top of the second page.

I have tried to use a jquery to return top of the page when loading:
```
window.parent. $ ("body"). animate ({scrollTop: 0}, 'slow');
```

But it's not working.

I would like that when you load the second page into the iframe, return to position 0 of the top of that page.

I do not know if you can help me, regards.

**Comment by davidjbradshaw** [comment]
Please see the docs:

https://github.com/davidjbradshaw/iframe-resizer#scrolltoxy

**Comment by acclaimuser** [comment]
These links are broken !!

**Comment by davidjbradshaw** [comment]
Updated links

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/methods.md#scrolltooffsetxy

And

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/events.md#onscroll

**Comment by umutesen** [comment]
is it possible to animate scrollToOffset?

**Comment by davidjbradshaw** [comment]
If you return `false` to the `onScroll()`  event, you are then free to implement your own scrolling code to the new position

**Comment by floripaoliver** [comment]
Hi guys, can someone help me out here. I read this documentation but I still don't get it to scroll to the top if the user clicked a link inside the iframe. I do not have access to the content inside the iframe. I try to scroll to the top always when the user clicks something. I would be happy if somebody can help me with this code. thx

**Comment by romi-getbowtied** [comment]
$('iframe').iFrameResize({
	onInit: function() {
		$(window).scrollTop(0);
	}
});

**Comment by msuthars** [comment]
```
$("#my_iframe").on("load", function () {
  $('#my_iframe').iFrameResize({
    'log': true
     resizedCallback : function(info){
        scrollTo(0, 0);
      }
    });
  });
```
