### ISSUE TITLE
"Unexpected message ([iFrameSizer]resize)" warnings printed by iframeresizer.contentwindow

### ISSUE THREAD

**Issue by s-brooks** [davidjbradshaw/iframe-resizer#588]
Warning messages about unexpected messages, are written to the console in the situation where a web page is within an iframe and has a nested iframe within it - what the iframeresize.contentwindow calls a middle tier, however it fails to detect that it is a middle tier in the case I am about to describe. The iframe in the "middle tier" scenario can receive iframeresizer messages from it's parent window, but also from the child iframe which it is trying to resize.
The contentwindow script in this middle tier will try to filter out the messages from the child iframe and calls a function isMiddleTier() to determine if the iframeresizer script could also be running in the iframe, thereby indicating that it is a "middle tier" situation. In my case, isMiddleTier() is returning false when it should be returning true. That is then leading to the callFromParent() function to print the warning message.
The reason isMiddleTier() is returning false in my case is that the web page uses AMD (requirejs) to load iframeresizer, and so the contentwindow code:
```
function isMiddleTier() {
  return !(typeof module !== 'undefined' && module.exports) && ('iFrameResize' in window);
}
```
won't see module or module.export, nor will it see 'iFrameResize' in window.

Perhaps a solution could be to change the check in isMiddleTier such that it returns true
if iFrameResize is a global (in window) OR (an AMD/define/require environment is detected) OR (a node-type/commonJS module environment is detected).
Specifically:
```
function isMiddleTier() {
  return window.iFrameResize || (typeof define === 'function' && define.amd) || (typeof module !== 'undefined' && module.exports);
}
```
It's not a great test to see if the iframeresizer script is also loaded, but when loaders are used, the global variable iFrameResize isn't set.

Or would it be better just to ignore these messages altogether except for maybe printing a message if logging is enabled.
What do you think?

**Comment by davidjbradshaw** [comment]
We now have a `removeListerners` method to get around this problem.

https://github.com/davidjbradshaw/iframe-resizer#removelisteners

**Comment by angelinekwan** [comment]
Thanks for the awesome plugin. Do you have an example on how to apply the IFrame Object Methods? Thanks in advance.

For example:-
iFrameResize({
..options
});

if ('parentIFrame' in window) {
     parentIFrame.removeListeners(); // would this work?
}

**Comment by davidjbradshaw** [comment]
```
document.getElementById('myiframe').iframeResizer.removeListeners()
```
or 
```
const iframes = iframeResizer()

iframes[].iframeResizer.removerListeners()
```

**Comment by s-brooks** [comment]
Thank you David for working on this problem.
I'm trying the latest version (3.6.2), but in my setup I'm seeing an error on the console:
TypeError: window.jQuery is undefined[Learn More] iframeresizer.contentwindow.js:1067:1

I think what is happening, is that in the midde tier iframe, jQuery is being used, and a call is made during initialization to jQuery.noConflict(true). That results, as far as I can tell, in window.$ and window.jQuery being set to the values of window.$ and window.jQuery before the jQuery script was run, which is the undefined value.
So, inside the isMiddleTier function, at line 1067:
  ('jQuery' in window) && ('iFrameResize' in window.jQuery.prototype);
The expression 'jQuery' in window is true, however, window.jQuery has the value undefined.
Hence, the evaluation of window.jQuery.prototype triggers a TypeError exception.
Could you perhaps change that line to:
  (window.jQuery) && ('iFrameResize' in window.jQuery.prototype);

Anyhow, assuming that was working, I'm unsure about on which iframe to invoke the removeListeners() method? Is it the middle tier iframe or the inner iframe? Could you explain, in this context, how calling removeListeners would achieve the objective of preventing the logging of "unexpected message". From looking at the code, removeListeners removes the iframeId from the settings object. If that is done on the middle tier iframe, would that stop it handing resized messages from the inner iframe?

Thanks,
Stephen
