### ISSUE TITLE
contentDocument cross origin 

### ISSUE THREAD

**Issue by falconmick** [davidjbradshaw/iframe-resizer#592]
```
Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.
```

I understand that the above error occurs in chrome because of the cross domain policies that it has, however when this fails it looks like my iframe falls back to polling for getting the iframe height and it still works... Is there any way to disable this exception or at least catch it so it doesn't show?

I'm using the React wrapper https://github.com/zeroasterisk/react-iframe-resizer-super if that throws any spanners into the mix.

**Comment by davidjbradshaw** [comment]
I consider this a bug in Chrome, you get this because the first attempt to contact the iFrame happens before it has started loading. Their is no way to workout from JS if this is the case, so we just have to ignore it and try again in a bit.
