### ISSUE TITLE
Responsive iFrame - force resize after display

### ISSUE THREAD

**Issue by gillescharge** [davidjbradshaw/iframe-resizer#593]
Hi,

I am displaying a responsive iFrame in my parent page: the max height of my iFrame content is 900px, and therefore the iFrame initialises at this height.
Once it is displayed it resizes perfectly well after an event (a click for example).
>> I would like to force this resize, to make sure the proper iFrame height is displayed from the beginning

Thank you in advance for your help!

**Comment by gillescharge** [comment]
Oh and here are the logs -
`[Log] JQMIGRATE: Migrate is installed, version 1.4.1 (jquery-migrate.min.js, line 2)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Added missing iframe ID: iFrameResizer0 (https://chargeguru.com/outils/)" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "IFrame scrolling disabled for iFrameResizer0" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "[init] Sending msg to iframe[iFrameResizer0] (iFrameResizer0:8:false:true:32:true:true:null:bodyOffset:null:null:0:false:parent:scroll…" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "[iFrame.onload] Sending msg to iframe[iFrameResizer0] (iFrameResizer0:8:false:true:32:true:true:null:bodyOffset:null:null:0:false:parent:scr…" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "[iFrame requested init] Sending msg to iframe[iFrameResizer0] (iFrameResizer0:8:false:true:32:true:true:null:bodyOffset:null:null:0:false:pa…" (iframeResizer.min.js, line 8, x2)
[Log] [iFrameSizer][iFrameResizer0] Initialising iFrame (https://chargeguru.com/outils/) (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] TargetOrigin for parent set to: * (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] HTML & body height set to "auto" (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Enable public methods (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Animation Start (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Animation Iteration (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Animation End (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Input (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Mouse Up (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Mouse Down (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Orientation Change (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Print (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Ready State Change (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Touch Start (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Touch End (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Touch Cancel (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Transition Start (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Transition Iteration (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Add event listener: Transition End (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Create body MutationObserver (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] In page linking not enabled (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Trigger event lock on (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Sending message to host page (iFrameResizer0:900:175:init) (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Trigger event: mutationObserver: [object SVGRectElement] attributes (iframeResizer.contentWindow.min.js, line 9, x2)
[Log] [iFrameSizer][iFrameResizer0] No change in size detected (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Received: [iFrameSizer]iFrameResizer0:900:175:init" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Checking connection is from: https://chargeguru.com" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Checking height is in range 0-Infinity" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Checking width is in range 0-Infinity" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "IFrame (iFrameResizer0) height set to 900px" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][iFrameResizer0] Trigger event: mutationObserver: [object SVGRectElement] attributes (iframeResizer.contentWindow.min.js, line 9, x2)
[Log] [iFrameSizer][iFrameResizer0] No change in size detected (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][iFrameResizer0] Sending message to host page (iFrameResizer0:613:819:mousedown) (iframeResizer.contentWindow.min.js, line 9)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Received: [iFrameSizer]iFrameResizer0:613:819:mousedown" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Checking connection is from: https://chargeguru.com" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Checking height is in range 0-Infinity" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Checking width is in range 0-Infinity" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "Requesting animation frame" (iframeResizer.min.js, line 8)
[Log] [iFrameSizer][Host page: iFrameResizer0] – "IFrame (iFrameResizer0) height set to 613px" (iframeResizer.min.js, line 8)`

**Comment by davidjbradshaw** [comment]
Try a different highCalculationMethod

**Comment by gillescharge** [comment]
Hi David,

I tried them all, the calculations are all correct, my full height iFrame content is about 900px. Elements change disposition and therefore the height changes depending on the width.
Everything works perfectly well when I resize the window.

The iFrame is initially hidden - it shows up through a click.
The only issue is the initial opening of the iframe, which starts at 900px - then a simple click and your script detects that the height of the iFrame now displayed is actually something else.

**Comment by davidjbradshaw** [comment]
When you unhide the iFrame, you most likely need to force it to resize due to it not being able to detect that you unhid it.

https://github.com/davidjbradshaw/iframe-resizer#resize

**Comment by gillescharge** [comment]
Great, thank you David - Could you share a simple line example to call the iFrameResizer object with the resize() method?

Thanks again!

**Comment by davidjbradshaw** [comment]
```
myIframe.iframeResizer.resize()
```
