### ISSUE TITLE
IE11: get 'Object expected' error after removed iframe from DOM

### ISSUE THREAD

**Issue by Arc311** [davidjbradshaw/iframe-resizer#598]
Hi,
I get infinitely spamming error 'Object expected' in iframeResizer.contentWindow.js after removed iframe from the DOM.
IE doesn't remove the iframe's scripts from itself and they still running.
Stack trace:
```
        getComputedStyle [Line: 713, column: 5], iframeResizer.contentWindow.js
        getBodyOffsetHeight [Line: 778, column: 9], iframeResizer.contentWindow.js
        isSizeChangeDetected [Line: 880, column: 7], iframeResizer.contentWindow.js
        sizeIFrame [Line: 908, column: 5], iframeResizer.contentWindow.js
        Anonymous function [Line: 128, column: 9], iframeResizer.contentWindow.js
        sendSize [Line: 934, column: 9], iframeResizer.contentWindow.js
        handleEvent [Line: 275, column: 11], iframeResizer.contentWindow.js
```
As I can see, it occurs after calling parseInt function, because after removing iframe window.parseInt becomes undefined.

**Comment by davidjbradshaw** [comment]
You need to use IFrame-Resizer’s own close methods to remove the iFrame. See the docs on how to do this in either the parent or iFrame

**Comment by Arc311** [comment]
thanks
