### ISSUE TITLE
Do you have error handler?

### ISSUE THREAD

**Issue by VOsipenkov** [davidjbradshaw/iframe-resizer#599]
I use iframe-resizer with react+redux. So, how to detects, that content loaded with error(f.e. 404 not found)?
Do you have some error handlers or callbacks?

**Comment by VOsipenkov** [comment]
const iframeResizerOptions = {
    log: true,
    checkOrigin: true,
    initCallback: (iframe) => {
      if (iframe.contentDocument.getElementsByClassName("error-title").length > 0) {
        onError();
      } else {
        onLoad();
      }
    },
  };

**Comment by davidjbradshaw** [comment]
Nice trick for same domain iFrames
