### ISSUE TITLE
works in IE and EDGE from example link on github but not from downloaded local files

### ISSUE THREAD

**Issue by rudolfdw** [davidjbradshaw/iframe-resizer#602]
Accessed from the example link on 'http://davidjbradshaw.github.io/iframe-resizer/' full functionality in IE11 and EDGE. From the local files downloaded using the zipped version all other browsers still succeed except the MS ones. The same with the code retrieved from the linked page on 'http://davidjbradshaw.com/iframe-resizer/example/'. There was an issue reported on Oct 18. 2006, but I see no CSS used here.

**Comment by davidjbradshaw** [comment]
The example is a slightly older version. Would be very helpful if you could workout which version this broke in

**Comment by rudolfdw** [comment]
Dear Mr Bradshaw 

I feel very pleased to have received this quick answer form you. The
unzipped content is dated 09.06 15:00 on my PC. The zipped files date
form June 18th sized 410.956 / 413.696 and 18th / 21st sized 428.257 /
430.080 (Bytes). If this doesn't help you should tell me, how to get the
requested information. Could you confirm the issue with a downloaded
local installation of the example files or is this a 'unique' phenomenon
here with my attempt? 

Thanks a lot and kind regards from Basel, Switzerland     Rudolf
Duerrwang 

Am 22.06.2018 21:34, schrieb David J. Bradshaw:

> The example is a slightly older version. Would be very helpful if you could workout which version this broke in 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/davidjbradshaw/iframe-resizer/issues/602#issuecomment-399558530
[2]

**Comment by davidjbradshaw** [comment]
The version number is at the top of the JS file
