### ISSUE TITLE
Height issue on Mozilla Firefox and safari.

### ISSUE THREAD

**Issue by hs-tanmay** [davidjbradshaw/iframe-resizer#603]
When I refresh the page sometimes it is unable to calculate the height of the iframe on Mozilla firefox and safari. It loads properly but this issue is found randomly if I refresh 2-3 times. Maybe it fires before iframe content load.

**Comment by Stuuel** [comment]
Hi there have the same problem. Did you find a solution?

**Comment by bmcpeakserenova** [comment]
Same issue. @davidjbradshaw, do you have any insight on this issue?

Thank you!

**Comment by hs-tanmay** [comment]
@Stuuel 
Could you please try adding 
<iframe id="sizetracker" src="" width="100%" type="text/html" frameborder="0" allowTransparency="true" style="border: 0"  scrolling="no" ></iframe>

sizetracker id in your iframe.
Please remove your custom id and add sizetracker.
It works for me.

**Comment by Stuuel** [comment]
Hey @hs-tanmay Thanks for your reply and sorry for my late answer.

Just tried it like you said but the initial height is still not calculated right.

**Comment by hs-tanmay** [comment]
@Stuuel 
Above configuration works for me properly. Please check whether library is being called properly.
https://github.com/davidjbradshaw/iframe-resizer
