### ISSUE TITLE
Parent pages scroll position problem

### ISSUE THREAD

**Issue by reubenrd** [davidjbradshaw/iframe-resizer#604]
Hello David

Thank you for creating the iframe resizer script.

I seem to be having the occasional issue with a few of our websites. Once the iframe source has changed to a new source the page position keeps being thrown to the bottom of the page.

Just wondering if anyone else has had an issue like this? Please see example here: https://goo.gl/icHEBF

Please follow through to the last page which requires users details. Any thoughts would be appreciated.

**Comment by AndreFabris** [comment]
Hello I have the same problem. It seems it remembers the vertical position of the last loaded page, and new loaded page is displayed in the same position - usually if the new page has no content there it just looks like a white screen.

It makes perfect sense that every time new page loads, vertical position is set to 0. No idea how to do this.

**Comment by AlexMeh** [comment]
Same problem here. Anyone figured out how to solve this problem?

@davidjbradshaw  Wouldn't it be a great solution to set y-scroll on every new iframe page load to 0?

**Comment by davidjbradshaw** [comment]
You could call scrollTo(0,0) in the onReady event in the page you are loading

**Comment by AlexMeh** [comment]
@davidjbradshaw 
We already call parentIFrame.scrollTo(0,0), but it passes a negative y-value:
`[iFrameSizer][Host page: iFrameResizer0] Reposition requested from iFrame (offset x:8 y:-544)`

So the parent site doesn't scroll to top when the iframe page loads a new page.

**Comment by davidjbradshaw** [comment]
That looks like you are calling `scrollToOffset()`, rather than
`scrollTo()`.

**Comment by AlexMeh** [comment]
@davidjbradshaw No, we simply call:
```
if ('parentIFrame' in window) {
  parentIFrame.scrollTo(0,160)
}
```
Can I reach you for private (paid) support? It would be great to have this problem solved.

**Comment by davidjbradshaw** [comment]
The first step would be to put a simple example of the issue online somewhere that I can look at it.

**Comment by AndreFabris** [comment]
I used 
$(document).ready(function () {
$("iframe").load(function () {
                $("html, body").animate({scrollTop: 0}, "slow");
            });

**Comment by sandrab** [comment]
Try using `parentIFrame.scrollTo()` within the `onReady` event, in the page that is loaded in the iframe. Something like this:

    window.iFrameResizer = {
      onReady: function () {
        if( 'parentIFrame' in window ) {
          window.parentIFrame.scrollTo(0, 0);
        }
      }
    };

This seems to work in my situation. Hope it helps someone!

**Comment by davidjbradshaw** [comment]
@sandrab you can reduce you example to this: 
 ```
window.iFrameResizer = {
  onReady: function () {
     window.parentIFrame.scrollTo(0, 0);
  }
};
```
