### ISSUE TITLE
Possible breaking changes with Site Isolation on Chrome 67

### ISSUE THREAD

**Issue by victornpb** [davidjbradshaw/iframe-resizer#607]
Chrome 67 on desktop has a new feature called Site Isolation enabled by default.

For the most part, Site Isolation is a behind-the-scenes browser feature that is not directly exposed to web developers. There is no new web-exposed API to learn, for example. In general, web pages shouldn’t be able to tell the difference when running with or without Site Isolation.

However, there are some exceptions to this rule. Enabling Site Isolation comes with a few subtle side-effects that might affect your website. We maintain a list of known Site Isolation issues, and we elaborate on the most important ones below.

Full-page layout is no longer synchronous, since the frames of a page may be spread across multiple processes.  This may affect pages that change the size of a frame and then send a postMessage to it, since the receiving frame may not yet know its new size when receiving the message.  One workaround is to send the new size in the postMessage itself if the receiving frame needs it.  In Chrome 68, pages can also work around this by forcing a layout in the sending frame before sending the postMessage.  See Site Isolation for web developers for more details.

Beforeunload handlers are not working in cross-site subframes, and unload handlers may have issues with postMessage.  We are working on fixes for these.

https://developers.google.com/web/updates/2018/07/site-isolation
https://www.chromium.org/Home/chromium-security/site-isolation#TOC-Known-Issues

Can you anticipate with any of this may cause issues in the near future?

**Comment by davidjbradshaw** [comment]
I think we should be ok, but if you get the chance would be great if you could check the Chromium release for this
