### ISSUE TITLE
Embedding R Shiny Application and Responsive iFrame

### ISSUE THREAD

**Issue by PSB-Turtle** [davidjbradshaw/iframe-resizer#610]
I would like to embed an R Shiny application within a website that I am developing, which can be done by use of an iframe element.  However, I'd like the iframe height to adjust in a responsive manner to the application's content.  So as the user toggles hidden elements within the R Shiny application the iframe resizes itself accordingly.  I'm not sure if iframe-resizer can handle that, but at least it should be able to resize an iframe's height upon loading the initial R Shiny application.  I followed the instructions and modified the R Shiny application from [here](https://github.com/rstudio/shiny-examples/tree/master/087-crandash), so that the original iframeResizer.contentWindow.min.js was included within the source page within the iframe (I uploaded that app to shinyapps.io so that I could include it within an iframe).  I also put together an example website ([example.zip](https://github.com/davidjbradshaw/iframe-resizer/files/2206026/example.zip)) to illustrate the issue (simply unzip the folder and open the index.html in Firefox and click on the App tab in the navbar).  The iframe does not get resized, with a decent amount of the application still hidden.  Am I doing something wrong or is it a bug or perhaps an unexpected behavior because of AngularJS?

**Comment by PSB-Turtle** [comment]
I was able to find a workaround thanks to dlukes and his post [here](https://dlukes.github.io/responsive-iframe.html).  I think the issue lies with Angular not manipulating the DOM for a route within a single-page application until you navigate to that route.  So if iframe-resizer is doing some stuff on page load then the workflow will get messed up.  At least that is my hunch...

**Comment by 765303440** [comment]
I encountered a similar problem with you. using angular JS to hide the DOM element (Responsive Website),.but the height of the iframe does not shrink automatically.i need help
