### ISSUE TITLE
Height not decreasing on increasing the window width

### ISSUE THREAD

**Issue by bhawin-boom** [davidjbradshaw/iframe-resizer#612]
I have implemented this , but i have a problem .

When i am resizing the window screen to the minimize , the height of the iframe increases, but when i try to maximize , the height of iframe doesn't get decreased .

What can i do to achieve that ? 

When i reduce the window width  , the height of iframe gets increased , 
When i again put it at full width , you can see empty space below the iframe area. 

https://www.profiledata.co.za/BrokerSites/NedbankPrivateWealth/SDOv3/components/companydetails.aspx?c=NED

Try this link as iframe 

I have float content in it .

**Comment by bhawin-boom** [comment]
@davidjbradshaw

**Comment by bhawin-boom** [comment]
@ggtr1138  @outoftime @pomartel @vitoss @jbruni

**Comment by jbruni** [comment]
There are a few troubleshooting sections in the README. Maybe one of them may help:

https://github.com/davidjbradshaw/iframe-resizer#iframe-not-sizing-correctly

**Comment by bhawin-boom** [comment]
@jbruni  , I have seen the Trouble shoot docs  . Still getting the problem .

**Comment by bhawin-boom** [comment]
@jbruni   , Anything you can share on this

**Comment by bhawin-boom** [comment]
@davidjbradshaw @jbruni  , Forgive me if i am asking stupid questions here  , When i put the content of https://www.profiledata.co.za/BrokerSites/NedbankPrivateWealth/SDOv3/components/companydetails.aspx?c=NED in a localhost file and then add it as an iframe  , It works perfect.

Why SO ?

**Comment by bhawin-boom** [comment]
I also found one more issue  , 
Lets say initial height of iframe is 300px and the screen is full width.
Now i resize the screen to the min . The height of iframe becomes 1100px
Now i resize the screen to full width fast , the the height i get is 600px instead of 300px .

How about that ?

@davidjbradshaw  @jbruni

**Comment by Badestrand** [comment]
I had the same issue (the iframe not getting smaller in height again) and just got it resolved. For some reason putting the doctype <!DOCTYPE html> as the first line in the iframe fixed it.

**Comment by kshkrao3** [comment]
@Badestrand Could you please let me know if it is in the src page we need to include `<!doctype html>`

**Comment by davidjbradshaw** [comment]
Yep
-- 
Sent from my iPhone.

**Comment by kshkrao3** [comment]
I too have a similar issue @davidjbradshaw. But in my case, I have autocomplete available in the src page. Autocomplete will have some 200-300 options. When the options are shown, the list actually extends the body height to some 5000px, but when the option is selected and list of options are hidden, the height of iframe never reduces back to actual height, whereas in source page it works fine and the body scrollbar will be hidden. 

I tried using `bodyScroll`, `max`, `lowestElement` options for `heightCalculationMethod`. But none of them resolves the issue. Should I be opening a new issue for this or you can suggest something here. :) Appreciate any help.

**Comment by davidjbradshaw** [comment]
Check your CSS, and that you have a valid DocType

**Comment by kshkrao3** [comment]
@davidjbradshaw Thank you so much.. It is working fine with <!doctype html> added. I am using bodyScroll now. But I am just facing one more issue. We are using this with AEM, sightly where the html is something like below:


```
<sly data-sly-test.author="${wcmmode.edit || wcmmode.design}">
    iframe component
</sly>

<sly data-sly-test="${properties.frameurl}">
        <sly data-sly-use.constructedUrl="${'converturl.js' @ link=properties.frameurl}"></sly>
</sly>
<iframe src="${properties.frameurl}" scrolling="${properties.scrolling}" width="${properties.framewidth}" height="${properties.frameheight}" frameborder="0">
</iframe>

```

If I include <sly> sightly tags then the html will be screwed up and it will render the whole section somthing like below:

```
<sly&nbsp;data-sly-test.author=>
    iframe component


<sly&nbsp;data-sly-test=>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<sly&nbsp;data-sly-use.constructedurl=>

<iframe src="falsehttps://bestellung.unitymediabusiness.de/iframe?upc=2PLAY200Bconverturl.jshttps://bestellung.unitymediabusiness.de/iframe?upc=2PLAY200B" &nbsp;scrolling="no" &nbsp;width="300px" &nbsp;height="200px" &nbsp;frameborder="0" id="iFrameResizer0" scrolling="no" style="overflow: hidden;">
</iframe>
</sly&nbsp;data-sly-use.constructedurl=></sly&nbsp;data-sly-test=></sly&nbsp;data-sly-test.author=>
```
Could you please let me know if it doesn't support this type of set ups or it will not work with sightly templates?

**Comment by davidjbradshaw** [comment]
Sorry no idea about slightly templates
