### ISSUE TITLE
Default height (size)

### ISSUE THREAD

**Issue by firojm57** [davidjbradshaw/iframe-resizer#616]
I am using iframeResizer it is working fine as mentioned in document. While using this I came to a situation where some of the iframe pages does not include iframeResizer.contentWindow.min.js. And such pages are in between those pages which include iframeResizer.contentWindow.min.js.

Let me explain the scenario..
A page hosts iframe-x and it includes iframeResizer.min.js
In iframe-x there are three pages, page-A (height: 800px), page-B (height: 300px), and page-C (height: 600px)
page-A and page-C includes iframeResizer.contentWindow.min.js and page-B doesn't.

When iframe got resized it changes height of page-A to 800px
Now I am browsing to page-B, its actual height is 300px but previously it was set to 800 and it remains same for page-B, and when I browse to page-C now it changes to 600px which is correct.

Here page-B's height is 800px and I am not able to change it to 300px. I think there should be an option like default height or something, which will resize to that height if anything goes wrong..
In my case I will set default height to 300px, so page which does not includes iframeResizer.contentWindow.min.js will resize to 300px.

**Comment by davidjbradshaw** [comment]
Why not just include the file on all three pages in the iFrame?

**Comment by firojm57** [comment]
I am rendering third party pages in my iframe. And those pages have such scenario which no one can change.
