### ISSUE TITLE
Height Auto Resize Does Not Work With Firefox Quantum

### ISSUE THREAD

**Issue by BrainScanMedia** [davidjbradshaw/iframe-resizer#617]
Height Auto Resize Does Not Work With Firefox Quantum

Example: https://www.carcoverusa.com/covercraft-readyfit-200-series-car-covers.php

See screen Shots... Any Help would be great...

**Vivaldi Screen Shot:**
![vivaldi](https://user-images.githubusercontent.com/41655428/44061158-6e0e8ccc-9f14-11e8-9ed7-8f12e9d0a49d.png)

**FireFox Screen Shot:**
![firefox](https://user-images.githubusercontent.com/41655428/44061160-70a3297a-9f14-11e8-80e9-babd65695a19.png)

**Comment by bhawin-boom** [comment]
I had the same issue man , @davidjbradshaw  says  , " check your css " .

**Comment by jcm9000** [comment]
@bhawin-boom Can you be more specific on the CSS that is causing the issue described above? Thanks

**Comment by davidjbradshaw** [comment]
Normally it something in the CSS that makes something just a little bit bigger than the page height and that then creates an infinite loop

**Comment by BrainScanMedia** [comment]
> Normally it something in the CSS that makes something just a little bit bigger than the page height and that then creates an infinite loop

We are linking to a Car Cover dealer's website. this is the iframe they sent us to use. Your resizer works well with all browsers except FireFox.

<iframe src="https://www.covercraft.net/cartlink/index.php?cust_id=8cept_dev&prod_id=rfb2" style="width: 100%; border: 1px solid #337AB7; border-radius: 5px; padding: 10px"></iframe>

There is no special CSS to increase the height.
