### ISSUE TITLE
mutationObserver event firing repeatedly

### ISSUE THREAD

**Issue by bmcpeakserenova** [davidjbradshaw/iframe-resizer#618]
Hi,

If you load this page and look at the console you will see that the mutationObserver event fires continuously and the plugin logs "No change in size detected":

https://succeed.serenova.com/lp-t-cb-omnichannel-uk-2018/

While the plugin seems to be functioning correctly on the front-end, I'm concerned whether this might have performance implications or cause issues in any OS/browser combos I haven't view it in.

Thank you!

**Comment by bmcpeakserenova** [comment]
Hi @davidjbradshaw, any idea what might be happening here?

Thanks!

**Comment by davidjbradshaw** [comment]
I expect you have something on your page that is constantly updating, you could try setting the `interval` option to `-9999` to switch of the mutationObserver
