### ISSUE TITLE
Uncaught ReferenceError: iFrameResize is not defined when imported after MailChimp js (with examples)

### ISSUE THREAD

**Issue by jfeust** [davidjbradshaw/iframe-resizer#619]
I've seen other issues referencing the "iFrameResize is not defined", but this is a very clear example with JSFiddles to show.

If we import the iFrameResize AFTER the mailchimp signup form js, then we get an `Uncaught ReferenceError: iFrameResize is not defined`

If we import iFrameResize BEFORE the mailchimp signup form js, then everything works.

iFrameResize before MailChimp (working): https://jsfiddle.net/zvs305h9/
iFrameResize after MailChimp (not working): https://jsfiddle.net/b8qLvw1j/

**Comment by davidjbradshaw** [comment]
I expect MailChimp is using some strange none standard version of `require`. I expect they have the same impact on a lot of projects. This is really their bug I am afraid.
