### ISSUE TITLE
[iFrameSizer][Host page: iFrameResizer5] [Window resize] IFrame(iFrameResizer5) not found

### ISSUE THREAD

**Issue by bhawin-boom** [davidjbradshaw/iframe-resizer#622]
[iFrameSizer][Host page: iFrameResizer5] [Window resize] IFrame(iFrameResizer5) not found

I am getting this warning  for all the 50 iframes 

I have around 50 iframes which loading on a single page .

Some of those iframes height gets extra height when window gets resized from lower width to heigher width .

Thanks

**Comment by davidjbradshaw** [comment]
I am not sure what your question is, if you just need help using this library, please ask on StackOverflow, this is for tracking bugs
