### ISSUE TITLE
Set taggedElement using selector instead of HTML attribute

### ISSUE THREAD

**Issue by ericmorand** [davidjbradshaw/iframe-resizer#624]
I recently had to use iframe-resizer with iframes rendered by a CMS that doesn't allow custom attributes on HTML elements - i.e. it is impossible to add a `<div data-iframe-height></div>` element to the iframe markup because `data-iframe-height` is not a standard HTML attribute.

Is there a way to set iframe-resizer to use a selector instead of an HTML attribute - something like `#iframe-height`?

If not, would you accept a PR?

**Comment by davidjbradshaw** [comment]
Any attribute starting with data- is a vaild html5 attribute. You might like to talk to your CMS vendor about that. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

I am not keen on adding new options unless their is a wide demand for them. However, you can place your own custom height calculate method in the iFrame. 

https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod--widthcalculationmethod
