### ISSUE TITLE
Presence of x-scrollbar cause y-scrollbar to appear

### ISSUE THREAD

**Issue by carlo-nz** [davidjbradshaw/iframe-resizer#625]
Hi,

I have 2 iframes placed side-by-side, each taking up half the horizontally space. The content of the iframes may contain elements with a minimum or fixed width.

I would like each iframe to:

- automatically resize vertically
- not resize horizontally but when overflow occurs, the iframe can be scrolled horizontally

I am seeing an issue where overflow occurs and the x-scrollbar is correctly being displayed, but for some reason the y-scrollbar also appears. Shouldn't the iframe's height be automatically resized so the y-scrollbar is not needed?

I've reproduced this on Windows 10 in the browsers I tested with (Chrome, Edge and IE11). This can also be reproduced on Mac OS when the system configuration "Show scroll bars" is set to "Always".

**Screenshot of issue**
![windows-edge](https://user-images.githubusercontent.com/43197010/45408089-73a4f780-b6bf-11e8-89a1-f1065b219aad.PNG)

I've tested all the different `heightCalculationMethod` values set on the host page with no luck. I would also like to avoid implementing my own custom `heightCalculationMethod` function.

Souce code is below:

**index.htm**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>iframe-resizer</title>
    <style>
      iframe {
        width: 48%;
      }
    </style>
  </head>
  <body>
    <iframe src="iframe.htm"></iframe>
    <iframe src="iframe.htm"></iframe>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.6.1/iframeResizer.min.js"></script>
    <script>
      iFrameResize({
        scrolling: 'auto' // set to auto as we want x-scrollbars to appear
      });
    </script>
  </body>
</html>
```

**iframe.htm**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <style>
      .fixed {
        background-color: teal;
        height: 200px;
        width: 1000px;
      }
    </style>
  </head>
  <body>
    <div class="fixed"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.6.1/iframeResizer.contentWindow.min.js"></script>
  </body>
</html>
```

**Comment by davidjbradshaw** [comment]
The issue is the x scrollbar effects the height and we can not calculate that. The best solution for you is to write your own custom height calculation method that adds an extra 10px to the height.

**Comment by carlo-nz** [comment]
Hi @davidjbradshaw,
Thanks for your response. It looks like the custom height calculation method can only be passed in from the iframe page. Is there a way to set this once by the host page rather than for every iframe page? 

If not, would it make sense to introduce a new `heightCalculationMethod` value to the library that can be set by the host page and behind the scenes it adds the extra 10px? Another option may be to introduce a new iFrameResize option which allows the host page to specify an additional height that gets added to the calculated height. What are your thoughts on this?

**Comment by davidjbradshaw** [comment]
It's done that way as it would be insecure to allow code to be passed into the iframe from the parent page. You can just add a JS file for your resize method and add it to every page.

I don't want to add more options unless their is strong demand for them, as their is already enough complexity in this library.

**Comment by canerozdemircgi** [comment]
> The issue is the x scrollbar effects the height and we can not calculate that. The best solution for you is to write your own custom height calculation method that adds an extra 10px to the height.
> 
> https://github.com/davidjbradshaw/iframe-resizer#heightcalculationmethod--widthcalculationmethod

Is it possible in 2022 ?
