### ISSUE TITLE
Iframe not resizing first page when another page with iframe is embedded

### ISSUE THREAD

**Issue by char2** [davidjbradshaw/iframe-resizer#627]
Hello - I have searched and tested solutions through here and stackoverflow for this but have been unable to find anything that has worked so far. I am thinking this could be a bug or perhaps not be possible at all. If you could have a look that would be great.

Here we have Page 1 with an iframe embedded on it: 
http://work.ronpiper.com.au/page1.html
Resizing works fine

Now type something in any of the fields and click Submit. On submission the form will redirect to another page (http://work.ronpiper.com.au/page2.html) which also has an iframe on it.
If you access page2 directly, you will see iframe resizing is also working great on this page.

However since the redirect happened inside the first iframe, we now have the second page embedded inside the first page.
The first page is not resizing to fit the new height of the second page.

**Comment by davidjbradshaw** [comment]
Have you looked at the nested iFrame example? The page in the middle needs
both js files

> --
Sent from my iPhone.
