### ISSUE TITLE
my life saver! .  .  .

### ISSUE THREAD

**Issue by KnIfER** [davidjbradshaw/iframe-resizer#631]
Thank you.u are my life saver!

And a little strange thing is that iframe page needs `<!DOCTYPE html>` at start, or the down resizing will be very slow and unsuccessful.

**Comment by davidjbradshaw** [comment]
Yeah, I guess forcing the page into standards mode make the browser run a lot quicker

**Comment by MQuigg** [comment]
This is huge. Adding DOCTYPE makes all the difference. Great library BTW!
