### ISSUE TITLE
Please add example for readyCallback

### ISSUE THREAD

**Issue by lubosdz** [davidjbradshaw/iframe-resizer#632]
Hello guys,

could please somebody provide example of how to setup `readyCallback()` ?
There is no example available anywhere on the internet.
Though it looks like elementary setup, I cannot make it working ..

I understand, that `readyCallback` should be configured as following:

```
iFrameResize({
	//log : true,
	checkOrigin: false,
	minHeight : 800,
	maxHeight : 4000,
	readyCallback: function(){
		console.log('ready parent callback .. '); // (!) never called
	},
	messageCallback: function(data){
		console.log('message callback .. '); // works OK
		console.log(data);
	},
	//initCallback: function(){window.scrollTo(0,0); alert("OK initiated");}, // works OK
	resizedCallback : function(info){ // works OK
		console.log(info);
		scrollTo(0, info.iframe.offsetTop);
	},
	heightCalculationMethod : 'taggedElement'
}, '#iframe123');
```
But it seems it never gets called.
Am I doing something wrong here?
Thank you.

**Comment by davidjbradshaw** [comment]
You should place it in the iFrame, not the parent page
```
<script>
  window.iFrameResizer = {
    readyCallback: () => console.log('ready callback .. ')
  }
</script>
```
If you need know when the iFrame is ready in the parent page, use `initCallback`

**Comment by lubosdz** [comment]
Thank you. 
I thought I tested such a setup inside contentWindow, but apparently I did something wrong ...
