### ISSUE TITLE
Possible to use with Google Docs/Sheets?

### ISSUE THREAD

**Issue by devuxer** [davidjbradshaw/iframe-resizer#634]
Reading the documentation, it appears I need to somehow get the `iFrameResize.contentWindow.js` script to be included in the web page embedded within the iframe. I'm not quite clear on how I'd do this since the web page gets is automatically generated by Google when the document is edited. I do have full access to the document, though, so maybe there's a way?

**Comment by davidjbradshaw** [comment]
You will have to ask Google to include that file.

**Comment by devuxer** [comment]
OK, that's what I figured.

**Comment by abidhassantokee** [comment]
Are there any solutions to this problem? Is there any way now to include iFrameResize.contentWindow.js in google docs?
