### ISSUE TITLE
add scrollBy to IFrame Page

### ISSUE THREAD

**Issue by lubosdz** [davidjbradshaw/iframe-resizer#639]
Hello, 

please would it be possible to add also `scrollBy(x,y)` method to IFrame parent ?
Just like the existing `scrollTo(x,y)` and `scrollToOffset(x,y,)`.

We use quite a lot of show/hide sections inside iframe for which we can easily calculate height and it would be handy to tell parent iframe **scroll by such a relative height** and thus ensure centered view.
Currently it's also possible to calculate, but it's kinda clumsy and we'd also prefer to minimize code on outside page (outer page containing iframe).

Thank you very much.
Lubos

**Comment by davidjbradshaw** [comment]
I’m not keen to add endless more options. However, this would be easy for you to implement on your own page by getting the current page position using the getPageInfo call and then using scrollTo to more the page to where you want
