### ISSUE TITLE
Resize only goes bigger not smaller

### ISSUE THREAD

**Issue by Fanvaron** [davidjbradshaw/iframe-resizer#641]
Hello, 
I just tried implementing this into my webpage, though it only seems to be working in upscalling not downscalling.

The website is https://www.pz-online.de/zielgruppen/ with the options `{log:true, heightCalculationMethod: 'max'}`

the way to reproduce this is simple:
just press `Start`with everything selected and then click one of the list entries.
The first Start will increase the frame size, the second click will decrease the content but not the frame size.
The log seems to show everything running in both parent and child, but the calculated height is always min the old.

The double size increase works:
This is done by first delesecting everything but the first entry before clicking `Start`
this increases the size once, then clicking `Analyseauswahl` in the top right and selecting everything and clicking `wählen` increases the size once again, which also resizes properly.

Doing it the other way around, first the bigger than the smaller does not resize properly.

Every click is a new pageload, so I don't think that there is any scripts in the child that could mess with the size calculations.

I have a strong feeling that I missed some option but I read through the readme and could not find anything.

Sincerely

**Comment by mikebranderhorst** [comment]
```
Replace:
<script>iFrameResize({log:true, heightCalculationMethod: 'max'}, '#zgIframe')</script>
With:
<script>(function(){$('#zgIframe').iFrameResize({log: true, checkOrigin: false});})();</script>
```

**Comment by Fanvaron** [comment]
I did that, but it does not seem to change anything, still the same behaviour of going bigger but not smaller

**Comment by davidjbradshaw** [comment]
Check your css, that is where the issue will be
-- 
Sent from my iPhone.

**Comment by Badestrand** [comment]
I had the same issue and just got it resolved. For some reason putting the doctype `<!DOCTYPE html>` as the first line in the iframe fixed it.
