### ISSUE TITLE
Uncaught ReferenceError: iFrameResize is not defined

### ISSUE THREAD

**Issue by dahmian** [davidjbradshaw/iframe-resizer#642]
It looks like including require.js before loading iFrameResizer causing an error: Uncaught ReferenceError: iFrameResize is not defined. I'm currently seeing this issue on Chrome, Firefox and Edge while using Windows.

In this example the code runs without error and the iFrame resizes: https://codepen.io/anon/pen/XyqMJO

But when I include require.js, then I get an error, and the iFrame doesn't resize: https://codepen.io/anon/pen/pQVevK

Unfortunately I can't remove require.js, because we give code snippets to our customers who run it on their own websites. So we don't have control over their environment.

**Comment by davidjbradshaw** [comment]
Does this help

https://github.com/davidjbradshaw/iframe-resizer/issues/468

**Comment by dahmian** [comment]
Yes, thank you! Changing

```
if (typeof define === 'function' && define.amd) {
	define([],factory);
} else if (typeof module === 'object' && typeof module.exports === 'object') { //Node for browserfy
	module.exports = factory();
} else {
	window.iFrameResize = window.iFrameResize || factory();
}
```

to

`window.iFrameResize = window.iFrameResize || factory();`

worked. Is there a way I can help with a solution that could be merged in?

**Comment by davidjbradshaw** [comment]
I guess we could just take the last `else` out and make the function always available one the window object. Does that work for all your use cases?

**Comment by dahmian** [comment]
Yup! That would work wonderfully.

**Comment by davidjbradshaw** [comment]
If you want to make a PR and give it a try, I’ll be happy to merge

**Comment by dahmian** [comment]
Verified that it works, thanks!
