### ISSUE TITLE
IE 11 filter issue

### ISSUE THREAD

**Issue by kshkrao3** [davidjbradshaw/iframe-resizer#645]
Hi David,

I am getting **Object doesn't support property or method 'filter'** error in IE11. I have included **ie8.polyfill.js** file in the page before **iframeResizer.min.js** but I am still seeing this issue. Could you please let me know if I am missing anything?

**Comment by davidjbradshaw** [comment]
You should only need the polyfil for IE8. Beyond that I am not sure what is causing your issue
