### ISSUE TITLE
Question: Page loading indicator

### ISSUE THREAD

**Issue by AndreFabris** [davidjbradshaw/iframe-resizer#646]
Hello, some times pages in the frame take long time to open and user has no feedback that page is loading. It would be great to have some sort of spinner while page loads.
Any ideas how can we add this?
Thanks,
ANdre

**Comment by davidjbradshaw** [comment]
This is more a question for StackOverflow, to get you started you can use `initCallback()` to be notified once the content of the iFrame has loaded. 

https://github.com/davidjbradshaw/iframe-resizer#initcallback

**Comment by AndreFabris** [comment]
@davidjbradshaw That is cool, my problem is what callback to use when user clicks on the link in the iframe?
initcallback is called when page is finished loading so i can hide spinner, however how do i know when to display it again?
