### ISSUE TITLE
Triggering resize when showing a div with iframe in

### ISSUE THREAD

**Issue by youradds** [davidjbradshaw/iframe-resizer#647]
I love this plugin - thanks for sharing :)

I've got a bit of a problem with hidden divs though. I'm using: 

`var iframes = iFrameResize( [{ log: true, autoResize: true, heightCalculationMethod: 'documentElementOffset' }], 'iframe' );`

When the div is shown with the IFRAME in, it doesn't seem to trigger. If I click on something inside the iframe it seems to force it.

If I don't hide the div with the IFRAME to start with, it works fine (but I need them hidden).

I see there is a resize() option but I'm unsure of how to invoke it?

Thanks

Andy

**Comment by davidjbradshaw** [comment]
If you just have one iFrame you can do `iframes[0].iframeResizer.resize()`

**Comment by youradds** [comment]
@davidjbradshaw  thank you :) That got me onto the right track:

                 iframes.forEach(function(item, i) {
			item.iFrameResizer.resize();
		    });
