### ISSUE TITLE
Nested iFrames not found

### ISSUE THREAD

**Issue by wasabii** [davidjbradshaw/iframe-resizer#648]
I am actually using the iframe-resizer-super-react package (by somebody else), and trying to nest iframe instances.

```
<ReactIframeResizer iframeResizerOptions={hOption}>
    <ReactIframeResizer id="DataFrame" iframeResizerOptions={sOption} src={this.state.url} />
</ReactIframeResizer>
```

The React library I'm using basically just emits two `iframe` elements, and calls into your library. However, it's not working. But, I don't think it's the React libraries fault.

Over in `sendTriggerMsg`, you are looping over the settings object, and then calling `trigger` for each frame in it. However, you are going back to the document to get the `iframe` element: `document.GetElementById(iframeId)`. This is returning `null`, for the nested iframe, because the document object it's working with is the parent document object: not the document object of the middle -iframe, which would be able to find the element.

```
    for (var iframeId in settings) {
      if(isIFrameResizeEnabled(iframeId)) {
        trigger(eventName, event, document.GetElementById(iframeId), iframeId);
      }
    }
```

I'm wondering why you need to call `document.GetElementById` here? It looks like `settings` has a reference to the `iframe` element. Why not just use that?

**Comment by davidjbradshaw** [comment]
Good question, I can not remember why it is done that way, if you change it does it fixes things for you?

**Comment by wasabii** [comment]
Yes. Along with one other instance of the same thing.

Would you like a PR?
