### ISSUE TITLE
test "'jQuery' in window" could lead to a ReferenceError exception

### ISSUE THREAD

**Issue by s-brooks** [davidjbradshaw/iframe-resizer#649]
The contentWindow.js file contains the code at line 1261:
```
function isMiddleTier() {
        return (
        (!(typeof module !== 'undefined' && module.exports) &&
          'iFrameResize' in window) ||
        ('jQuery' in window && 'iFrameResize' in window.jQuery.prototype)
      );
}
```

The right hand side of the logical OR test is, as far as I can see, trying to determine if the iframeResizer has been loaded into jQuery as a plugin. However, this test does not take into account the fact that 'jQuery' in window can be true, and yet window.jQuery is undefined. That can arise if jQuery's noConflict's method is called, which is a common enough use case. Thus, evaluating ('jQuery' in window && 'iFrameResize' in window.jQuery.prototype) leads to undefined.protype being evaluated thus throwing a ReferenceError exception.

My suggestion is to change the expression to:
    `(window.jQuery && window.jQuery.prototype.iFrameResize)`

**Comment by davidjbradshaw** [comment]
Happy to take a PR for that
