### ISSUE TITLE
Memory leak in case of programmatically removed IFrames

### ISSUE THREAD

**Issue by seckardt** [davidjbradshaw/iframe-resizer#650]
I'm heavily using IFrames inside popovers and modals of several enterprise apps. These dialogs are created dynamically on the fly and provide entry points for sandboxed customizations (of our customers). During development I found that there are warnings in the console like `[iFrameSizer][Host page: iFrameResizer0][Window focus] IFrame(iFrameResize[0) not found`. These warnings referred to IFrames that actually got removed after closing their dialog container.

Looking at the code I saw that the removed IFrame instances never get removed from the `settings` array. So every call to `sendTriggerMsg` still lists these zombies (`settings[iframeId]`).

**Comment by davidjbradshaw** [comment]
You can avoid that problem with this call
https://github.com/davidjbradshaw/iframe-resizer#removelisteners

That said your PR does make things simpler

**Comment by seckardt** [comment]
Right, without the PR every implementor will be forced to take care of unsubscriptions himself. If that's the proposed solution, I'm absolutely fine with that and simply move the code to our project. Yet if you think it makes sense to merge the PR, that might help others that run into similar issues.

**Comment by davidjbradshaw** [comment]
When I get a moment to test it out I will merge your PR.

**Comment by davidjbradshaw** [comment]
fix merged
