### ISSUE TITLE
Why attach so many listener to svg file?

### ISSUE THREAD

**Issue by Cuiyansong** [davidjbradshaw/iframe-resizer#652]
Hi, 

Recently I receive a lot of event logs when use iframe-resizer. This library is very good, but I am a beginner with this library. Could some one help me to explain why it attach to many linteners to svg files.

Message like:

```[iFrameSizer][iFrameResizer0] Attach listeners to https://xxxxx.com/fonts/xxxx.svg```

Thanks,

**Comment by davidjbradshaw** [comment]
It's so it can detect if the size of the image changes, which would require the page size to be recalculated.

**Comment by Cuiyansong** [comment]
Thanks David,

Is there a way to set some config on this to filter some special elements? As I have a lot of Dom elements, I don't what to be attached on them if possible. (I send size event when iframe inner component size changed manually)

**Comment by davidjbradshaw** [comment]
You could give this setting a very large negative number

https://github.com/davidjbradshaw/iframe-resizer#removelisteners
