### ISSUE TITLE
iFrame Resizer Not Working When iFrame Automatically Downloads a File From a Different Root Domain

### ISSUE THREAD

**Issue by danpayne88** [davidjbradshaw/iframe-resizer#654]
Hi David,

First and foremost, this is a great script and has been a huge help to me. Thank you so much for putting this together!

I came across an issue that I was hoping you or someone in the community could help with. Here are the steps to recreate:

1. I have an iframe on this page: https://www.exterro.com/resources/search-collection-workflow-checklist/

2. On page load, the iframe resizer works fine and the form in the blue box is resized as expected

3. Upon form submission, the form does not resize properly. It should look like this:

![image](https://user-images.githubusercontent.com/24421677/51198017-ef01fa00-18a7-11e9-8784-bf93679862f3.png)

but instead looks like this and does not resize correctly: 

![image](https://user-images.githubusercontent.com/24421677/51198129-3be5d080-18a8-11e9-85dc-61ae4c15095d.png)

4. What is going on here is that after a form is submitted, our marketing automation tool (Pardot), which hosts the form), deploys some "thank you code." Within that thank you code is a piece of script that automatically downloads the resource for the user. It looks like this:

```
<script type="text/javascript"> 
var link = document.createElement('a'); link.href = 'https://go.pardot.com/l/43312/2017-10-19/7d1ljr/43312/142702/In_House_Legal_Workflow_Checklist_Part_3_FINAL.pdf'; 
link.download = 'Exterro PDF'; 
link.dispatchEvent(new MouseEvent('click')); 
</script>
```

What I've found is that when the link.href from the above script begins with https://go.exterro.com, the iframe resizer works correctly. When it's https://go.pardot.com, the download works correctly (as it does with https://go.exterro.com), but the iframe resizer does not resize the iframe. The iframe resizer also does not work if I change protocol to http and the download gets blocked due to a mixed content warning. 

I set checkOrigin to false while I was debugging locally and that didn't seem to address the issue. I believe the iframe has an older version of the code but it was tested with v3.6.1, which is the code used on the site, and it still did not work.

Any idea what's going on here and how to fix it? 

Thanks!

**Comment by davidjbradshaw** [comment]
You have the logging turned off, so it had to see what is happening
