### ISSUE TITLE
Release includes test code

### ISSUE THREAD

**Issue by smulesoft** [davidjbradshaw/iframe-resizer#656]
Hello @davidjbradshaw I wanted to ask you if it's possible to remove the test sources from your releases? Honestly it looks like an unnecessary clog that could easily be removed.

**Comment by davidjbradshaw** [comment]
Good point, feel free to make a PR and I'll include it in the next release

**Comment by smulesoft** [comment]
Thanks @davidjbradshaw , here it is: https://github.com/davidjbradshaw/iframe-resizer/pull/658/files

**Comment by smulesoft** [comment]
Could you release it as 3.6.5 ?

**Comment by smulesoft** [comment]
Thanks to you @davidjbradshaw , we now solved our issue (our dependency scanner which was reporting vulnerability threats in jQuery and quintjs located in test/resources).
Good to collaborate with you!

**Comment by davidjbradshaw** [comment]
That is good to hear, and I should also mention that I added you to the version history notes as well.
