### ISSUE TITLE
iframe not resizing after opening+closing DevTools in IE +Edge

### ISSUE THREAD

**Issue by mogyoro** [davidjbradshaw/iframe-resizer#660]
Steps to reproduce:
1. Open your working example in IE or Edge (http://davidjbradshaw.com/iframe-resizer/example/)
2. Open, then close the Developer Tools window
3. Try resizing your browser window

iframe won't resize anymore as you resize the window.
Error in console:` SCRIPT5: Access is denied.`

**Comment by mogyoro** [comment]
Related problems:
https://github.com/ckeditor/ckeditor5/issues/829
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14146025/

**Comment by davidjbradshaw** [comment]
That is a bug in IE, not this project, please discuss with Microsoft
