### ISSUE TITLE
Iframe Resizer not working in wordpress

### ISSUE THREAD

**Issue by simbarao** [davidjbradshaw/iframe-resizer#661]
Hi, i have implemented the Js scripts as directed- iframeresizer.min.js in the host page http://tdc.webmoksha.com/track-your-shipment and iframeResizer.contentWindow.min.js in the page hosted in the iframe (view-source:http://106.51.129.171/m/getrec_m.php?T1=) and placed the respective js files in the Js directory too but it does not seem to work !

**Comment by davidjbradshaw** [comment]
I've never used wordpress, try this link

https://stackoverflow.com/questions/24613836/using-david-j-bradshaws-iframe-resizer

A couple of years ago, someone wrote a wp plugin to use this, so try searching for that as well

**Comment by davidjbradshaw** [comment]
Also search the issues on this project, this question has come up before

**Comment by simbarao** [comment]
Thank you very much :) i will try it out 👍
