### ISSUE TITLE
iFrame Cross-Domain Tracking and iframe-resizer

### ISSUE THREAD

**Issue by Dave-Lindberg** [davidjbradshaw/iframe-resizer#662]
My client's site contains a donation form (https://www.resurge.org/donate/) which is an embedded iframe from a 3rd-party provider using iframe-resizer. I have separate Google Tag Manager containers installed on the main domain and in the iframe page, and want to pass the clientId from the original ga object to the iFrame. 

On the parent page, I have the following code:

```
<script>
setTimeout(function(){ 
  ga(function(tracker) {
    var clientId = tracker.get('clientId');
    var frameWindow = document.getElementById('my_iframe').contentWindow;
    // change https://xyz.shoppingcart.com to match your iFrame domain
    frameWindow.postMessage(clientId, 'https://app.etapestry.com'); 
  });
}, 2000); 
</script>

```
and in the iFrame:

```
<script>
  window.addEventListener('message', function(event) {
    // Ignores messages from untrusted domains.
    if (event.origin != 'https://www.resurge.org') return;
    // Creates the tracker with the data from the parent page.
    ga('create', 'UA-19540393-1', 'auto', {clientId: event.data});
    ga('send', 'pageview');
  });
</script>

```

in the GA Debugger console, I'd expect to see a new ga object including clientId. Instead, I get the following results:

```
Running command: ga("create", "UA-19540393-1", "auto", {clientId: "[iFrameSizer]my_iframe:8:false:true:32:false:true:null:offset:null:null:0:false:parent"})
analytics_debug.js:24 Creating new tracker: t0
analytics_debug.js:24 Used client Id from constructor.
analytics_debug.js:24 Auto cookieDomain found: "etapestry.com"
```

Appears that iframe-resizer is inserting "[iFrameSizer]my_iframe:8:false:true:32:false:true:null:offset:null:null:0:false:parent" into the clientId.

**Comment by davidjbradshaw** [comment]
Iframe-resizer also uses postMessage, you code the receive you message needs to filter out messages not intended for it.

**Comment by Dave-Lindberg** [comment]
I've been trying to figure out the filtering approach, but keep coming up short. 

Posted a recap at https://stackoverflow.com/questions/54738116/how-to-filter-postmessages. Any advice/help would be really appreciated. Thanks!
