### ISSUE TITLE
default export broken

### ISSUE THREAD

**Issue by objectfoo** [davidjbradshaw/iframe-resizer#669]
index.js in root of project folder is trying to require ./js/index.js
```
module.exports = require('./js')
```

but ./js no longer contains an index.js file.

both 4.x ~~and 3.~~

(edit) Whoops, sorry you are correct, 3.x does a `./js/index.js` file

**Comment by davidjbradshaw** [comment]
Looks like it is in the v3 version still, not sure how got remove from 4. I’ve added it back and will release with a fix for auto resize soon.

**Comment by davidjbradshaw** [comment]
Fixed in v4.0.2, thanks for raising the issue.
