### ISSUE TITLE
iframe doesnt resize on window.resize, but on click inside iframe

### ISSUE THREAD

**Issue by interactivevalues** [davidjbradshaw/iframe-resizer#677]
HI,
my iframe resizes correct on page-load. but when you resize the window the iframe height stays the same. when I click inside the iframe the iframe heights is set to the correct height.

any idea why this doesn't happen on window.resize?

cheers,
ToM

**Comment by davidjbradshaw** [comment]
Try version 4.0.4. Their was a bug that has been fixed.


-- 
Sent from my iPhone.
