### ISSUE TITLE
Iframe not shrinking as content shrinks

### ISSUE THREAD

**Issue by billstennett** [davidjbradshaw/iframe-resizer#679]
Hi there,

I am using a cross domain page in the iframe so I am setting checkorigin to false. I am also using the latest version of the library. 

My iframe resizes correctly on page load and also expands if I choose an option from my drop down which expands thee content. The frame does not however shrink down if I make a selection that causes the iframe content to reduce.

Example page is here: https://www.edenproject.com/node/256099

Iframe code is at the bottom of the page.

Choose an option from the bottom drop-down and the page will expand. Choose "select requirements" from the drop-down and the page content will be reduced but the iframe will not shrink back.

Any advice appreciate.

Bill

**Comment by davidjbradshaw** [comment]
Try different height calculation methods and check your css


-- 
Sent from my iPhone.

**Comment by billstennett** [comment]
Hi - thanks for the reply. 

I have retried the different height calculation methods and summarised the results below. In summary the 'bodyoffset' and the 'min' loaded correctly but did not increase with the iframe contents. All the others loaded correctly and increased correctly but none of the shrank when the contents reduced in size. 

bodyOffset – initial size OK; no increase
bodyScroll – initial size OK; increase OK; no reduction
documentElementOffset – initial size OK; no increase
documentElementScroll – initial size OK; increase OK; no reduction
max - initial size OK; increase OK; no reduction
min - initial size OK; no increase
grow - initial size OK; increase OK; no reduction
lowestElement - initial size OK; increase OK; no reduction

I haven't tried the tagged element method as I do not have immediate access to the iframe contents. 

I'm not sure what else to try really - I am not aware of any issues with the CSS but if there are specific things I should be including I'd appreciate any suggests

Best,

Bill

**Comment by tkelling** [comment]
I seem to be having the same problem. I'm embedding a Qualtrics form using iframeResizer. I've tried all the height calculation methods and other options suggested. I don't seem to be able to get the iframe to ever shrink. It will grow, but it doesn't ever shrink when the contents change. Thanks for any thoughts or ideas you might have.

**Comment by tkelling** [comment]
I solved the related problem I was having. The problems was the child page CSS as noted in other threads about this issue. I found an element with height:100% and changed it to height:auto. Works great now. (@davidjbradshaw, thanks for the excellent plugin.)

**Comment by mmihalev** [comment]
I have exactly the same problem. Using Bootstrap 4. I can't find elements with height:100%, however height doesn't shrinks

**Comment by davidjbradshaw** [comment]
When the default `bodyOffset` does not work, it is always a CSS issue, the other methods calculate the height in different ways to try and work around what you have in your CSS. In most cases one of them normally works.

If you still have an issue, you have to options, the first is to inspect your CSS and look for which ever element on the page is not shrinking and causing the problem. The other option is to write you own custom method to calculate the height of your page. 

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md#heightcalculationmethod--widthcalculationmethod

**Comment by douglassdavis** [comment]
Hi @davidjbradshaw,
The iframe does shrink when in Firefox, however, it does not shrink in Chrome. 
Example here:
https://devonline.northcarolina.edu/iframeresize.htm

**Comment by davidjbradshaw** [comment]
Did the newer version fix it for you?

**Comment by douglassdavis** [comment]
I'll try it Monday.

Thanks,
Doug
________________________________
