### ISSUE TITLE
anchor links in page

### ISSUE THREAD

**Issue by beardedgeek** [davidjbradshaw/iframe-resizer#68]
Thanks for such a great script. It's working great apart from one tiny issue that I'm hoping is my config rather than it not working.

I'm embedding a mediawiki application within a page which creates a table of contents at the top. The TOC has a load of in page anchor links to content lower down the page, however when I click on one of the links it doesn't scroll down to focus it.

**Comment by davidjbradshaw** [comment]
Just released version v2.8.0 with support for  In Page Anchor links. The code now intercepts these in the iFrame and reposition the parent page. Both html links and JS calls to the location object are intercepted.

It will first look for an anchor in the iframe and if it is not found it will bubble up through nested parent pages until it finds the correct link.

I've also added a new [scrollCallback](https://github.com/davidjbradshaw/iframe-resizer#scrollcallback) function that allows you to hook in your own code for animated scrolling.

This works with in page links and also the parentIFrame.scrollTo() and parentIFrame.scrollToOffset() methods.

**Comment by lucaswxp** [comment]
Hey guys.

Anchor scrolling is not working for me, is this still valid today?

I'm using angular and the html anchors are created dynamically, could this be it?

**Comment by davidjbradshaw** [comment]
Yep take a look at the example. If it is an Angular issue you would be better asking on StackOverflow.

**Comment by davidjbradshaw** [comment]
@LukeLeber that is a fair point. Would you like to raise a PR? Or create an accessibility issue
