### ISSUE TITLE
calculating size of iframe with borders

### ISSUE THREAD

**Issue by ivangermes** [davidjbradshaw/iframe-resizer#683]
If iframe have a borders, size calculation is incorrect.
So iframe has a scroll, in case `scrolling="auto"`.
How can i add an iframe borders sizes to size calculation?

**Comment by ivangermes** [comment]
Quick fix is set `box-sizing: content-box;` for iframe

**Comment by davidjbradshaw** [comment]
PLease feel free to submit a PR for this
