### ISSUE TITLE
Iframe not resizing to contents on iOS safari

### ISSUE THREAD

**Issue by mpmart20** [davidjbradshaw/iframe-resizer#684]
![Screen Shot 2019-03-21 at 2 48 50 PM](https://user-images.githubusercontent.com/9059135/54787282-88bb8f80-4be8-11e9-991d-e3b48fb09399.png)

The Iframe is unable to detect the height difference between page changes in my application. As you can see here, the whitespace is what the iframe is resizing too, however, the highlighted blue portion is where my content cuts off. I'm currently using the lowestElement calculation method.

**Comment by davidjbradshaw** [comment]
I would need a simple test case to look at this

**Comment by mdkamrulcse** [comment]
i am facing same problem, what is solution for this
