### ISSUE TITLE
Make window.innerHeight available in getPageInfo()

### ISSUE THREAD

**Issue by nuschk** [davidjbradshaw/iframe-resizer#685]
**Use case**

My iframe contains an Infinite loader (using 'react-visibility-sensor'), which loads list items whenever the user scrolls to the bottom of a list. The iframe adjusts its height according to the number of items already in the list. The iframe doesn't scroll at all, only the parent document does.

**Problem**

I can't determine the parent's viewport from within the iframe. Using `getPageInfo()` I can get close, but unfortunately, `clientHeight` doesn't work, because it's the document's size and the document will be taller than the actual viewport and parts of it may be off-screen. I only want to trigger reload when bottom of the list is visible in the window.

**Proposed Solution**

Make `window.innerHeight` and `window.innerWidth` available in `getPageInfo()`.

**Comment by davidjbradshaw** [comment]
Happy to take a PR if you want to add that.

**Comment by nuschk** [comment]
Here's one: #686. Seems simple enough.

I somehow couldn't get the tests to work though. If you could take a look?

Also, documentation is a bit misleading now. `window.inner*` is essentially the HTML viewport size. Now `clientWidth` and `clientHeight` already claim that. Maybe we should describe those more clearly and say what it really is (i.e., the maximum of document and viewport size).

Thanks!

**Comment by davidjbradshaw** [comment]
Maybe the best solution is to also add `documentClientHeight` and `documentClientWidth` as well.

Then the current options we can either explain in the docs what it actually does, or just leave it in undocumented for backwards compatibility.

**Comment by nuschk** [comment]
Ok, I've done that. I renamed them to `documentWidth`/`Height` and `windowWidth`/`Height` which is less verbose and still very clear. I've also added a deprecation note to the `clientWidth`/`Height`. 

Tests are now working.
