### ISSUE TITLE
Anchor issue (using 4.0.4)

### ISSUE THREAD

**Issue by AndreFabris** [davidjbradshaw/iframe-resizer#687]
It seems similar issue was fixed in the past, however it is back. I am using latest 4.0.4 code.
Basically this is a standard FAQ page in the iframe, and the anchor links get an iframeresizer event attached. This prevents anchor links from working as expected.

I have: inPageLinks: true, as setting, as I want non anchor links to open inside the frame. However when i set it to false, non anchor links still work, and anchor links dont. In this case Event is not attached, and when clicked the page scrolls just a few pixels.

Opening the page outside the frame makes all anchor links work as expected

![image](https://user-images.githubusercontent.com/2181773/55065559-57294500-507c-11e9-8501-183318c29355.png)

**Comment by davidjbradshaw** [comment]
Do you have a link to an example?

**Comment by AndreFabris** [comment]
http://demo.appsforce.org
use provided login, go to myForums on the left and select FAQ from the top

**Comment by davidjbradshaw** [comment]
Can you turn the logging on please

**Comment by AndreFabris** [comment]
turned on :) thanks for looking into it btw

**Comment by ketokun** [comment]
Is there any update for this, please?

**Comment by davidjbradshaw** [comment]
Finally have time to look at this, but I need an example to see the issue

**Comment by davidjbradshaw** [comment]
Closing due to no response
