### ISSUE TITLE
Resizer not working with iframe having multiple iframes inside it .

### ISSUE THREAD

**Issue by bhawin-boom** [davidjbradshaw/iframe-resizer#690]
I have a url which i am trying to put it in an iframe 

https://www.profiledata.co.za/brokersites/NedbankPrivateWealth/sharedata/scripts/Overviewind.asp

This url has a lot of iframes inside it . 

Iframe resixzer does not works on this one . 

any Idea ?

**Comment by davidjbradshaw** [comment]
You most likely need to add iframe resizer to the inner iframes
