### ISSUE TITLE
'documentElementOffset' is better default value for heightCalculationMethod

### ISSUE THREAD

**Issue by mainTao** [davidjbradshaw/iframe-resizer#696]
In some cases, the `html` height is larger than `body` height, if use `bodyOffset` as default it will hide some part of the page. So I recommend use `documentElementOffset` as default value?

Take an example:
iframe.html：
```html
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/iframe-resizer@4.1.1/js/iframeResizer.contentWindow.min.js"></script>
  </head>
<body>
  <div style="margin-top: 200px; height: 100px;">not show</div>
</body>
</html>
```

index.html：
```html
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/iframe-resizer@4.1.1/js/iframeResizer.min.js"></script>
  </head>
<body>
  <iframe src="iframe.html" frameborder="0"></iframe>
  <script>
  iFrameResize() // invisible
  // iFrameResize({heightCalculationMethod: 'documentElementOffset'}) // visible
  </script>
</body>
</html>
```

The `not show` element is out of the view.

**Comment by davidjbradshaw** [comment]
`documentElementOffset` is not perfect either and can sometime over report the height. For pages where the CSS is not causing the content to overflow the `<body>` of the document, `bodyOffset` is the better value.
