### ISSUE TITLE
Width does not shrink when heightCalculationMethod is 'bodyOffset'

### ISSUE THREAD

**Issue by WebVeteran** [davidjbradshaw/iframe-resizer#70]
The only way I was able to get the frame width to shrink reliably was to set heightCalculationMethod: 'max'. That causes a bad flicker when the iframe disappears and the container's footer jumps up. To get around that I set the iframe's CSS min-height to 500px;
I suggest defaulting heightCalculationMethod to 'max'. And on init set the min-height css of the iframe to 500px. Make that a setting of course.
Also 'heightCalculationMethod' should probably be renamed as 'sizeCalculationMethod' as it also effects the width.

**Comment by jakehilton** [comment]
I can only get the width to adjust adjust wider but it does not shrink. I'm using the heightCalculationMethod set to max. If it does affect the width as well then the rename might make sense as mentioned above.

**Comment by jakehilton** [comment]
In looking at the code.. the width is calculated off of a fixed type.. so we cannot change it. It uses
Math.max(document.documentElement.scrollWidth, document.body.scrollWidth); .. I'm going to run a few use cases to see if I get better results using a different option.

**Comment by WebVeteran** [comment]
Jake - something else might be going on. In my case the width does shrink when appropriate.

**Comment by MartijnKooij** [comment]
+1
We are seeing a similar "flicker" when setting the calculation method to 'max'. Not sure if it is the exact same issue though.
When clicking form fields inside the resized frame, the frame will grow a bit and then shrink again. In IE it's a bit different as it no longer shrinks after growing?

**Comment by davidjbradshaw** [comment]
Fixed in v3.0.0. Beta version currently in the dev branch.

https://github.com/davidjbradshaw/iframe-resizer/tree/dev
