### ISSUE TITLE
Docs don’t match current code base/API

### ISSUE THREAD

**Issue by nicholashead** [davidjbradshaw/iframe-resizer#700]
Thanks for the awesome library however trying to implement it over the past few days I believe I’ve found cases where the docs don’t match the actual code/API. I would like to take a crack at a pull request to help here, but wanted to confirm this is the case — or am I just bonkers?

**Comment by davidjbradshaw** [comment]
What did you find?

-- 
Sent from my iPhone.

**Comment by nicholashead** [comment]
@davidjbradshaw sorry I didn't put more detail in my original issue - I was on mobile/on the go.

For example, the docs at https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/events.md speak of having `onReady` and `onMessage` events for the iframed/child page, however I could not get these to work, and looking at the source code I see `readyCallback` and `messageCallback` - which I assume are newer names for those events. Example code that works:

```js
window.iFrameResizer = {
        readyCallback: function () {
            window.parentIFrame.sendMessage('IFRAME_LOADED');
        },
        messageCallback: function (message) {
            alert('messageCallback: ' + message);
        }
    };
```

**Comment by davidjbradshaw** [comment]
Oh yes please make a PR for anything like that

**Comment by davidjbradshaw** [comment]
Sorry just ready that again, what version of the code are you using?

**Comment by davidjbradshaw** [comment]
Just checked the code and it should be `onReady` and `onMessage`

https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L247

This was changed in version 4, in version 3 it was what you have

**Comment by nicholashead** [comment]
Oh wow, apologies. You're correct. I thought I had installed latest via npm, but apparently not.
