### ISSUE TITLE
Cross domain not working without access to frame

### ISSUE THREAD

**Issue by psp-anon** [davidjbradshaw/iframe-resizer#702]
I get this error:
`IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.`

I use:
`<iframe id="calc_frame" allowtransparency="true" src="https://domain1.com/?url=https%3A%2F%2Fadomain2.com" frameborder="0"></iframe>
<script src="/template/js/iframe_size.js"></script>
<script> $('#calc_frame').iFrameResize({log: true}); </script>`

I have no access to domain1.com and domain2.com
Does it possible to resize iframe in this situation?

**Comment by davidjbradshaw** [comment]
No you need to ask the other domain to host the iframe je file
-- 
Sent from my iPhone.

**Comment by psp-anon** [comment]
No more questions
