### ISSUE TITLE
Smooth scrolling with moveToAnchor

### ISSUE THREAD

**Issue by mashedkeyboard** [davidjbradshaw/iframe-resizer#704]
It'd be great to have the ability to smooth scroll in `moveToAnchor` rather than having to have a jumping scroll there.

This already works in a modern browser if the parent page has the `scroll-behaviour: smooth` CSS on the body, but it can't be scoped, making it a less than ideal solution if you don't own the parent page.

One option for this could be to use something like [Zenscroll](https://github.com/zengabor/zenscroll) - it's public domain licensed and only a smidge over a single kilobyte big.

**Comment by davidjbradshaw** [comment]
You can return false from the onScroll event and then call want ever lib you like to reposition the page in a more animated way.
