### ISSUE TITLE
Can't iframe on different domain and use anchor # tags

### ISSUE THREAD

**Issue by codermjb** [davidjbradshaw/iframe-resizer#705]
I can iframe using the same domain and when clicking anchor tags that have #, they work. But, when I iframe in a different domain, iframe resize does work, but the links with # do not work. I tried various things, but I am getting the error message below and I think it might be related.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://admin.domain.com') does not match the recipient window's origin ('https://dev.domain.com').

**Comment by codermjb** [comment]
Nevermind, I looked over the source code and I found inPageLinks:

```
$( document ).ready(function() {
        iFrameResize({
            checkOrigin: false,
            inPageLinks: true
        });
    });
```

I might also work on getting some scroll animations if you haven't implemented that already.

**Comment by davidjbradshaw** [comment]
Have a look at this for scrolling
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/events.md#onscroll

It pass the new page position and if you return false, it leaves up to you to scroll however you like to the new position.
