### ISSUE TITLE
Memory leak in contentWindow addImageListeners

### ISSUE THREAD

**Issue by OleksiiKukuruza** [davidjbradshaw/iframe-resizer#708]
function [addImageListeners](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L744) can be called multiple times for same image, so image element can be [pushed](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L749) multiple times, but calling [element.addEventListener](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L747) load/error with same handler multiple times adds handler only once, so that [element removal](https://github.com/davidjbradshaw/iframe-resizer/blob/master/src/iframeResizer.contentWindow.js#L764) happens only once

**Comment by davidjbradshaw** [comment]
Do you want to make a PR to fix that?

**Comment by davidjbradshaw** [comment]
Looking at this a bit more and I don't think it is an issue, as the browser will only add
