### ISSUE TITLE
base64 encoded iframe resize support

### ISSUE THREAD

**Issue by ParkSeungwon** [davidjbradshaw/iframe-resizer#709]
Does this resizer work when the iframe is base64 encoded text?
<iframe onload=resize(this) id='if' src='data:text/html;charset=utf-8;base64,CjwhLS08P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJ1dGYtOCI/Pi0tPgo8IURPQ1RZUEUgaHRtbCBQVU....>
like this...
I tried many ways, but all failed.
Please add support for this kind of situation.

**Comment by davidjbradshaw** [comment]
I have no idea why that does not work, are you encoding the iframe js file into it?
