### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by bilmaijer** [davidjbradshaw/iframe-resizer#721]
Hi!
Can you try helping me understand why some users are getting this error? I was not able to reproduce it, but from time to time some user gets it. I'm using latest versions, although this happened in version 3 also. I was hoping upgrade would help, but it didn't. Maybe you have an idea why this could be happening. Logs also show that iframe existed and was passed to the resizer.

It happens here:
```javascript
function processOptions(options) {
      options = options || {}
      settings[iframeId] = {
        firstRun: true,
        iframe: iframe,
        remoteHost: iframe.src
          .split('/')
          .slice(0, 3)
          .join('/')
      }

...
    }
```

**Comment by davidjbradshaw** [comment]
Sounds like some sort of race conditions, is it dependent on browser type?

**Comment by SiddMajum1993** [comment]
In case you guys are still facing this issue. I was facing this issue in chrome and tried in a different browser  and it work. The problem with chrome was a popup blocker extension, which I suspect was stoping the iframe rendering. Just by disabling  it I was able to make it work.

**Comment by bilmaijer** [comment]
Hi! Thanks for the response. I see it in different browsers. (I myself have not encountered it, but I see from logs it happens). I implemented a workaround by catching the errors and just applying min-height to the container so it's at least usable. If it's adblocker then nothing we can do, can't force the user to turn it off.
@SiddMajum1993 Which ad blocker did you use to see this error?

**Comment by SiddMajum1993** [comment]
@bilmaijer its this one 
https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche

**Comment by davidjbradshaw** [comment]
Is the us file in the iframe being loaded from the same domain as the page in the iframe? Just wondering if that could cause ad blocker problems if they are on different domains.

**Comment by bilmaijer** [comment]
@davidjbradshaw It's the same domain

**Comment by bilmaijer** [comment]
I can indeed reproduce the error with the popup blocker. Could there be a workaround?

**Comment by davidjbradshaw** [comment]
Not sure what it is doing, can you raise a bug with the pop-blocker?
