### ISSUE TITLE
iFrame-resizer flickering on IOS 12 on apple devices

### ISSUE THREAD

**Issue by ConAllen** [davidjbradshaw/iframe-resizer#732]
Hi @davidjbradshaw,

I've been having a lot of trouble with the iFrame resizer with IOS 12 devices for the past while, I have seen there is an Apple bug related to this, but I'm wondering is there a work-around? or is there any available updates I can make to the code? 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.6.1/iframeResizer.min.js"></script>
<iframe id="iFrame_id" src="URL" width="100%" height="0" scrolling="no" frameborder="0"></iframe>
<script>iFrameResize({ log: false, checkOrigin: false, tolerance: 10, sizeHeight: true, heightCalculationMethod: 'lowestElement', minHeight: 300, scrolling: 'auto' }, '#iFrame_id') </script>
```

Any help would be GREATLY appreciated.

Thanks a mill

C

**Comment by davidjbradshaw** [comment]
Looking at that code, why do you need to set tolerance to 10. I would start by looking at the code in the iframe that is causing you to need to do that.
