### ISSUE TITLE
Iframe not resizing when html and body has a 100% height

### ISSUE THREAD

**Issue by xBau** [davidjbradshaw/iframe-resizer#733]
The iframe will not resize properly if the url has the following styles:

```
html,
body {
	height: 100%;
}
```

In my tests the iframe always resize to 150px, no matter which height has the content.
Without that style everything works properly.

Maybe an improve would be the library auto resetting the height of the html and body to auto. Or at least throw an error so the user can be aware.

**Comment by davidjbradshaw** [comment]
Have you tried the different height calculation methods. Their are too many odd things you can do in CSS to cause issues, but normally their a built in way to calc the height with what ever CSS you have in your iFrame
