### ISSUE TITLE
Child page not answering when iFrameResizer is called too early

### ISSUE THREAD

**Issue by gablaflamme** [davidjbradshaw/iframe-resizer#736]
Parent page is on wordpress. Here is the snippet I use to initialize iFrameResizer.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.1.1/iframeResizer.min.js" integrity="sha256-cEc8isF4TnMrb5OarPG3xyR5aOlECPt9Dbup+rFaEcw=" crossorigin="anonymous"></script>
<iframe style="width: 100%; max-width: 1080px;" id="my-id" src="******"></iframe>
<script>
  iFrameResize({ log: true, checkOrigin: false }, '#my-id');
</script>
```

I've included the right script in my child project. Now the weird thing is this sometimes work and sometimes does not. I have noticed it does not work whenever iFrameResize is called **too early**. For example, when I call iFrameResize({ log: true, checkOrigin: false }, '#my-id'); in a setTimeout with a 2 seconds delay, **it always works**, but this solution is fragile and I hate it. I have also tried waiting for iframe to be loaded with no success. Now I am pretty lost with this.

When it does not work, the iframed page just does not respond, so I get this:
[iFrameSizer][Host page: my-id] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.

Am I doing something wrong? How can I make sure iFrameResize is called when the script in the iframe is loaded?

Thanks!

**Comment by davidjbradshaw** [comment]
That should work, in some cases people have made the call from the onLoad event of the iframe. Which seems to solve the old case like this where their is an issue
