### ISSUE TITLE
IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame.

### ISSUE THREAD

**Issue by BrunildaDosti** [davidjbradshaw/iframe-resizer#739]
Hi there,

Is there any way how to change heightCalculationMethod value in iframeResizer.min.js file

Thanks in advance!

**Comment by davidjbradshaw** [comment]
You mean like this?

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/options.md#targetorigin
