### ISSUE TITLE
Bootstrap  modal pop up issue on Iphone

### ISSUE THREAD

**Issue by gauravsarwal** [davidjbradshaw/iframe-resizer#742]
I am using iframe-resizer for a cross domain application, The Iframe loads fine in desktop and andriod devices but on my Iphone, I am facing below issue:

1) The bootstrap modal pop ups on Iframe app is hiding and flickering behind when I scroll on page.

I tried -webkit-overflow-scrolling: touch; on container of Iframe but that does not work.

Any help/suggestion will be highly appreciated.

**Comment by davidjbradshaw** [comment]
Not sure, think that is more a question for StackOverflow
