### ISSUE TITLE
Cross domain origin with Shopify

### ISSUE THREAD

**Issue by yrk2yrk** [davidjbradshaw/iframe-resizer#743]
I am getting cross-domain origin error when I try to load iframe in Shopify frontend. It works fine on normal html website. 

I tried loading the example frame as well. It didn't show cross domain origin error but doesn't resize the iframe. What am I missing here? Below is my code:

iFrameResize({        
log: true, // Enable console logging        
inPageLinks: true,        
checkOrigin:false,		
sizeHeight:true,		
scrolling:true,		
enablePublicMethods:true      })

**Comment by davidjbradshaw** [comment]
I would check HTTP headers and also is Shopify setting any sandbox options on the iframe?
