### ISSUE TITLE
slippry slider auto slide display increments iframe height

### ISSUE THREAD

**Issue by goingsmart** [davidjbradshaw/iframe-resizer#745]
iframe-resizer works great for my other needs but iframe displaying slippry slider increments the height every time a slide is auto displayed. Have tried to set heightCalculationMethod but not helping. I suspect the problem is the control Arrows display in Slippry Slider. 

My code for iframe-resizer  works OK other than Slippry Slider.

Any suggestions are appreciated

**Comment by davidjbradshaw** [comment]
Have you tried setting the tolerance option?
-- 
Sent from my iPhone.

**Comment by goingsmart** [comment]
Do you mean setting the jQuery Tolerance? I only see Droppable Tolerance:
// Getter
var tolerance = $( ".selector" ).droppable( "option", "tolerance" );
 
// Setter
$( ".selector" ).droppable( "option", "tolerance", "fit" );

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#tolerance

**Comment by goingsmart** [comment]
Works Great...THX
