### ISSUE TITLE
Setup on Wordpress Multisite

### ISSUE THREAD

**Issue by Fotic** [davidjbradshaw/iframe-resizer#752]
Hello, Im trying to setup on my wordpress multisite without any luck. 
I wanna resize the iframe according to nested content of iframe from Subsite to Main Site.

### On **Main Site** using **ListingPro**

On ```listingpro/page.php```

```
<style>
iframe {
    width: 1px;
    min-width: 100%;
}
</style>

<iframe id="barber" src="/barber-shop/products/" width="100%" scrolling="no" onload="iFrameResize()"></iframe>

<script type="text/javascript" src="assets/iframeResizer.js"></script>
<script>
iFrameResize({
    log: false,
    checkOrigin: false,
    heightCalculationMethod: 'taggedElement'
}, '#barber')
</script>

```

On ```listingpro/functions.php```

```
function load_js_iframe_resizer() {
    wp_enqueue_script( 'iframe-resizer', get_template_directory_uri() . '/assets/iframeResizer.js', array(), '1.0.0', true );
    wp_enqueue_script( 'iframe', get_template_directory_uri() . '/assets/iframe.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'load_js_iframe_resizer' );
```

On ```listingpro/assets/iframe.js```

```
iFrameResize({
    log                     : true,                  // Enable console logging
    enablePublicMethods     : true,                  // Enable methods within iframe hosted page
});
```
And on ```listingpro/assets/iframeResizer.js``` the downloaded code (v.4.2)

### On **Subsites** using **OnePagePro**

On ```onepagepro/page.php```
```<script type="text/javascript" src="js/iframeResizer.contentWindow.js"></script>```

On ```onepagepro/functions.php```
```
function load_js_iframe_resizer_content_window() {
    wp_enqueue_script( 'iframe-resizer-content-window', get_template_directory_uri() . '/js/iframeResizer.contentWindow.js', array(), '1.0.0', true );
    wp_enqueue_script( 'iframe', get_template_directory_uri() . '/js/iframe.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'load_js_iframe_resizer_content_window' );
```
On ```onepagepro/js/iframe.js```
```
iFrameResize({
    log                     : true,                  // Enable console logging
    enablePublicMethods     : true,                  // Enable methods within iframe hosted page
});
```
And on ```onepagepro/js/iframeResizer.contentWindow.js``` the downloaded code (v.4.2)

### Output (of MainSite)
![Καταγραφή](https://user-images.githubusercontent.com/28195589/65282736-51e61800-db3e-11e9-9794-005dc79a6dac.PNG)

Is not working is taking the default wordpress height. What am i doing wrong?

**Comment by tou-larki** [comment]
Hey @Fotic did you get to making this work?

**Comment by davidjbradshaw** [comment]
I would love to create a proper Wordpress plugin, but have never used WordPress.

**Comment by davidjbradshaw** [comment]
https://iframe-resizer.com/frameworks/wordpress/
