### ISSUE TITLE
How to pass HTMLElement to iFrameResize?

### ISSUE THREAD

**Issue by dharmaturtle** [davidjbradshaw/iframe-resizer#756]
Hi!

Is it possible to pass an HTMLElement to iFrameResize? The CSS selector doesn't work with Blazor, unfortunately. However, it is possible to pass an HTMLElement to a javascript function in Blazor, so that would be a great workaround.

Thanks!

**Comment by davidjbradshaw** [comment]
Yeah just send as the second parameter instead of the selector
