### ISSUE TITLE
Height not reducing after decreasing\increasing browser window

### ISSUE THREAD

**Issue by Peppe87** [davidjbradshaw/iframe-resizer#757]
Hi I'm using your library to embed an iframe from a website we have into another site. 
It works quite good, except for one problem. 

When reducing the browser window the iframe correctly resize (increase) its height.
However if after that the browser window is enlarged, the iframe doesn't resize (it should decrease) its height anymore. 
In other words, it keeps the highest height reached and doesn't lower it. 

The code I'm using to launch it it's very minimal: 

`
      iFrameResize({
        checkOrigin: false,
        heightCalculationMethod: 'bodyScroll',
      });
` 

I've read other issues where it's pointed out css could be the culprit with things like "position:absolute" etc. However, I couldn't find in my iframe any style that could refer to that.

What's more, I've tested that even the example in your page suffers of the same problem, albeit only "temporarily": in your example, this problem only happens sometimes and after it has happened it disappears if resizing again the browser window. 
On my website, on the other hand, the iframe won't change the height anymore unless the page is reloaded. 

Any clue of what could cause it? 
I've attached some vids and an image showing this problem with your example. I'm on chrome on MacOs.

https://streamable.com/1761u
https://streamable.com/w46c4
https://streamable.com/77rop

![Schermata 2019-09-27 alle 10 16 12](https://user-images.githubusercontent.com/4638858/65754822-26e95e80-e112-11e9-94b8-9bb07348f081.png)

**Comment by davidjbradshaw** [comment]
I would suggest switching away from `bodyScroll` as the resize method. It's about the least reliable out of all the options. If the default option does not work then `lowestElement`, or `taggedElement` if your able to tag the code in the iframe, is a much better option

**Comment by Peppe87** [comment]
Thank you for your fast answer. 
I tried with `taggedElement` and the iframe is resized correctly in any scenario I've tested.
Kudos for your work!
