### ISSUE TITLE
Suppport for dynamically created iframe

### ISSUE THREAD

**Issue by giannoudak** [davidjbradshaw/iframe-resizer#758]
Hello and thanks for the great work here.
Does this work for dynamically created iframes that are being appended to DOM on some event (e.g scroll to a specific div)?

Can you please share a sample code if its possible?

**Comment by davidjbradshaw** [comment]
You would need to inject the iframe script into your dynamic iframe. 

Have a look at this for an example
https://github.com/zeroasterisk/react-iframe-resizer-super/blob/master/src/index.js#L62
