### ISSUE TITLE
Child page with scalable content

### ISSUE THREAD

**Issue by CousinOfDeath** [davidjbradshaw/iframe-resizer#759]
We have a case where the initial content of the child page contains static table and height of the frame is adjusted properly. User can then select to view the data as an _SVG_ resulting quite small graph, since it is scaled into the height of the frame (that contained rather small table) and there is no size change. In a case of an _SVG_ we would like to reset the frame height so that the frame uses as much of the view port height as possible.

We have solved this by sending a message (_window.parentIFrame.sendMessage_) from the child page telling if the content is scalable. On the parent side we have a _css_ rule for iframe `height: 100vh` and _onMessage_-event we clear the iframe style attribute so that the height will be '_100vh_'.

Is there a better way to handle this kind of scenario with scalable content?

**Initial page:**
![Näyttökuva (3)](https://user-images.githubusercontent.com/39416191/66108769-f0a55680-e5cb-11e9-96dc-b696a198f9c4.png)

**SVG after the initial page:**
![Näyttökuva (4)](https://user-images.githubusercontent.com/39416191/66108817-0fa3e880-e5cc-11e9-938c-28825acf4753.png)

**How we would like to have the SVG:**
![Näyttökuva (1)](https://user-images.githubusercontent.com/39416191/66108838-17fc2380-e5cc-11e9-8eab-c4955b3e62d2.png)

**Comment by davidjbradshaw** [comment]
Yeah you can just request the height for the iframe with this call

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/methods.md#size-customheight-customwidth
