### ISSUE TITLE
BUG: IE10-IE11 Syntax error due to const expression

### ISSUE THREAD

**Issue by realb0t** [davidjbradshaw/iframe-resizer#760]
I'm including iframe-resizer as a dependency in my project without babel transformation and get an exception in IE11-IE10.

`Unhandled promise rejection SyntaxError: Syntax error`

After debugging, I found out that the problem was in the `js/index.js` File, namely in using the expression.

```
const iframeResize = require('./iframeResizer')
...
```

I want to suggest replacing this expression with the following

```
var iframeResize = require('./iframeResizer')
...
```

In addition, a similar expression is used throughout the code.

Pull request will be soon...

**Comment by davidjbradshaw** [comment]
Have you tried using V3 of iframe-resizer? That should correctly support IE10

**Comment by realb0t** [comment]
I'll try. Thanks you!

**Comment by realb0t** [comment]
Unfortunately, V3 does not work resize in my case. But there is no error in the IE10.

**Comment by davidjbradshaw** [comment]
Is it just IE10 that it does not work in?

**Comment by realb0t** [comment]
I solved the problem this way:

```
import resizer from 'iframe-resizer/js/iframeResizer';
```

But I want to create a pull request. Ok?

**Comment by realb0t** [comment]
> Is it just IE10 that it does not work in?

No IE10 loaded code without errors. But my resize logic does not work with V3.

**Comment by davidjbradshaw** [comment]
Happy to look at a PR, still confused why V3 does not work for you
