### ISSUE TITLE
Not working with following

### ISSUE THREAD

**Issue by lwx-jaswant** [davidjbradshaw/iframe-resizer#762]
<iframe id="frmae" width="100%"   style="overflow:hidden;background-color:transparent;"  src="http://vco.sax.softvoyage.com/cgi-bin/querypackage.cgi?code_ag=vco&alias=TKS&language=EN&mode=wide"  frameborder="0"  allowTransparency="true"></iframe>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="iframeResizer.min.js"></script>
<script>
        
        iFrameResize({ log: true }, '#frmae');
        autoResize(true);
        
    </script>

**Comment by davidjbradshaw** [comment]
Delete `autoResize(true);`

**Comment by lwx-jaswant** [comment]
I have delete but not working

**Comment by davidjbradshaw** [comment]
No sure then
