### ISSUE TITLE
checkIFrames argument error ?

### ISSUE THREAD

**Issue by tonyliving** [davidjbradshaw/iframe-resizer#766]
in checkIFrames function 
[checkIFrames](https://github.com/davidjbradshaw/iframe-resizer/blob/1ea778e7e605fe865d7db23ea51097cc5731ed7e/src/iframeResizer.js#L1188)
`  checkIFrame(settings[key])`
The  argument is settings[key].May be key is right?

**Comment by davidjbradshaw** [comment]
I don’t understand your question

**Comment by tonyliving** [comment]
I think settings[key] need change to key

**Comment by davidjbradshaw** [comment]
Good spot, do you want to male a PR?

**Comment by davidjbradshaw** [comment]
Thanks will merge when I get some free time
