### ISSUE TITLE
Iframe height not resizing when it contains a positioned child element

### ISSUE THREAD

**Issue by Ifedi** [davidjbradshaw/iframe-resizer#770]
It seems that when the iframe contains an absolutely positioned element, it is NOT able to resize when it contains a child of `position: absolute` or `position: fixed`. In these situations, the positioned child element gets clipped off at the bottom of the iframe (as in `overflow: hidden`).

If this is a known limitation, can we have a workaround, please?

**Comment by davidjbradshaw** [comment]
You need to use one of the different hightncalcmethods. Check the docs for
the options, to see what works best for you
-- 
Sent from my iPhone.

**Comment by Ifedi** [comment]
Wow, thanks @davidjbradshaw for the prompt reply.
I'm afraid I've cycled through all the options for `heightCalculationMethod` , and I've actually been confused, since there was NO noticeable difference with any option change. 

Just in case I did something wrong, here's my setup:

	$(iframe).iFrameResize([
		{ 
			log: true, 
			heightCalculationMethod: 'bodyOffset' //TRIED ALL THESE: 'bodyOffset' | 'bodyScroll' | 'documentElementOffset' | 'documentElementScroll' | 'max' | 'min' | 'grow' | 'lowestElement' | 'taggedElement'
		}
	]);

**Comment by Ifedi** [comment]
Just in case this helps, the iframe in question is actually loaded inside of a `jQuery` dialog.
Thank you.

**Comment by davidjbradshaw** [comment]
Pass the options as an object, not an array of one object
