### ISSUE TITLE
Iframe not resized when using shadowDom on ResizeWindow Event

### ISSUE THREAD

**Issue by martinbelanger** [davidjbradshaw/iframe-resizer#772]
I have an iframe in a shadow dom. (using stencil-js)

I create iFrameResize with the DOM object instead of "css selector" and everything works as expected, except when resizing the main window.

The problem is the use of document.getElementById instead of using the "iframe" object in the iFrameResize settings (iFrameReadyMsgReceived, sendTriggerMsg functions).

    function iFrameReadyMsgReceived() {
      // eslint-disable-next-line no-restricted-syntax, guard-for-in
      for (var iframeId in settings) {
        trigger(
          'iFrame requested init',
          createOutgoingMsg(iframeId),
          document.getElementById(iframeId),
          iframeId
        )
      }
    }

    function sendTriggerMsg(eventName, event) {
        function isIFrameResizeEnabled(iframeId) {
          return (
            settings[iframeId] &&
            'parent' === settings[iframeId].resizeFrom &&
            settings[iframeId].autoResize &&
            !settings[iframeId].firstRun
          )
       }
        Object.keys(settings).forEach(function(iframeId) {
          if (isIFrameResizeEnabled(iframeId)) {
            trigger(eventName, event, document.getElementById(iframeId), iframeId)
          }
        })
    }
    

My fix is to get the "iframe" object in the settings object instead of trying to get the DOM from the document.

    var iframeObj = settings[iframeId].iframe;
    if(iframeObj == null){
      iframeObj = document.getElementById(iframeId);
    }

I'm going to create a pull request to fix it, but would there be any reasons to use getElementById?
If not we can always get it directly from settings[iframeId].iframe

**Comment by davidjbradshaw** [comment]
That sounds good to me, happy to have a look at a PR, could you add a shadow Dom example as part of the PR please

**Comment by martinbelanger** [comment]
I create the pull request
https://github.com/davidjbradshaw/iframe-resizer/pull/773

But like I wrote in the pull request comment... I spend the last day to try to test it with your automated tests. I don't push the compiled version (only the src modification)

**Comment by davidjbradshaw** [comment]
Released as v4.2.4 - Thanks for the PR
