### ISSUE TITLE
Issue with resizing

### ISSUE THREAD

**Issue by k0mrad** [davidjbradshaw/iframe-resizer#778]
Resize event seems to fire only once when clicking into a sub page, on clicking back or a link that takes the user to the previous page, the iframe does not resize. 

1. https://sproutwholesale.webflow.io/reference-library
2. click on article
3. click back or on breadcrumb link "reference library" 
4. notice that the iframe is still the same heigth it was. 

**Expected behavior**
iframe should resize back to smaller proportions. 

**Screenshots**
https://www.dropbox.com/s/7wt6uv7pff9x28i/Screenshot%202019-11-16%2013.23.50.png?dl=0

**Desktop (please complete the following information):**
MacOS Catalina - Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by k0mrad** [comment]
Fixed using 

html, body, .body{ min-height:0; } inside the iframed window

**Comment by davidjbradshaw** [comment]
Interesting fix, not sure why that would work. Where did the idea for this come from?
