### ISSUE TITLE
Possible issue with host server

### ISSUE THREAD

**Issue by CoryDobsonTraina** [davidjbradshaw/iframe-resizer#786]
I have an issue where the iframeresizer works on both a local install, as well as on a mediatemple server, but the same code/database doesn't work at wpengine.

Media Temple: http://brooklynbrew.trainadesign.com/where-to-find-our-beer/
wpengine: https://brooklynbrews.wpengine.com/where-to-find-our-beer/

If you visit the media temple link, and use the zip code 92103, you'll see the iframe resize, and the content of the iframe is scrollable. You will see in the console that the iframeresizer is working correctly. 

If you visit the wpengine link, you'll see it doesn't resize, and the console log shows "[iFrameSizer][beer-finder-frame] No change in size detected"

I've been in contact with wpengine support, but they were not able to figure out what the issue might be. They asked if it might require a specific nginx rule to be set up for iframeresizer to work.

Any idea what the issue might be?

**Comment by davidjbradshaw** [comment]
Sorry no idea, you just need the JS files to download, it's not an nginx issue
