### ISSUE TITLE
iFrames always expand, does not always shrink.

### ISSUE THREAD

**Issue by nickBumgarner** [davidjbradshaw/iframe-resizer#79]
One issue I have run into is I've found that the iFrame Resizer doesn't always work when transitioning from a super long page to a short page. I get left with super long iFrames where 80% of it is blank or doesn't have any content.

I cannot share the URL currently, but has anybody else ran into this problem?

**Comment by ladjzero** [comment]
I'm very interested in how the iframe content height change is detected. Use a timer loop to check sroll height? Or some magic event that can be triggered from the element resizing.

I found that it overrides the iframe element height by attaching an inline style {height: `someHeight`}. 
If the iframe hosts a single page webapp, its content might be shortened, however the iframe is silent on `load` event. The `resize` event can be detected?

If `resize` is detected, how to read the new shorter height? If read `body.scrollHeight`, we will get the `someHeight` set before.

**Comment by davidjbradshaw** [comment]
The height change is detected via mutationObserver and also detecting a
range of events that can cause the frame content to resize.

I'm interested in simple test examples where this fails.

Also have a try with the beta for version 3 which is in the dev branch.

D.

On Friday, July 3, 2015, ladjzero <notifications@github.com> wrote:

> I'm very interested in how the iframe content height change is detected.
> Use a timer loop to check sroll height? Or some magic event that can be
> triggered from the element resizing.
>
> I found that it overrides the iframe element height by attaching an inline
> style {height: someHeight}.
> If the iframe hosts a single page webapp, its content might be shortened,
> however the iframe is silent on load event. The resize event can be
> detected?
>
> If resize is detected, how to read the new shorter height? If read
> body.scrollHeight, we will get the someHeight set before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/iframe-resizer/issues/79#issuecomment-118270593>
> .
>


-- 
Sent from my iPhone.
