### ISSUE TITLE
Can't get height to be responsive... Is there a workaround that actually works?

### ISSUE THREAD

**Issue by exzizt** [davidjbradshaw/iframe-resizer#790]
From "Iframe not downsizing" at http://davidjbradshaw.github.io/iframe-resizer/:
"The most likely cause of this problem is having set the height of an element to be 100% of the page somewhere in your CSS. This is normally on the html or body elements, but it could be on any element in the page." -- And this is exactly the case. But the workarounds like trying to use "taggedElement" don't work.

I've tried all of the workarounds and none work. Please see issue here for more details: https://github.com/metabase/metabase/issues/11873

Any help is greatly appreciated.

**Comment by davidjbradshaw** [comment]
I'm not sure I understand the issue

**Comment by exzizt** [comment]
> I'm not sure I understand the issue

I updated my comment. Your help is greatly appreciated. 😃

**Comment by davidjbradshaw** [comment]
I think the issue is either in MetaBase or your code. Other than suggest you look at your CSS, then I am out of ideas

**Comment by exzizt** [comment]
The issue is that the height of the html element is being set to 100% somewhere in the iframe's styling (which I can't remove!). I need a way to override/ignore it somehow.
