### ISSUE TITLE
Change scroll option depending on parent height

### ISSUE THREAD

**Issue by erralb** [davidjbradshaw/iframe-resizer#798]
**Describe the bug**
This is not a bug I guess, it's more that I can't achieve something. I've read the docs and searched the issues but couldn't find a solution on my own.

I've got this Pardot form that does not fit in the frame when there's filling errors. This happens on mobile (small height) screens.

The screenshots explain it all:

Working fine by default:
![screenshot-localhost_3000-2020 03 10-09_36_11](https://user-images.githubusercontent.com/790992/76294484-3836b980-62b3-11ea-984d-0ae3615b2708.png)

After submitting, with the error messages, the form is too big:
![screenshot-localhost_3000-2020 03 10-09_36_58](https://user-images.githubusercontent.com/790992/76294485-3967e680-62b3-11ea-8915-dca95369a758.png)

I would like to set the scroll option when this happens, but couldn't figure it out how to do it.

**Expected behavior**
If the content of the iframe is bigger than its parent container, then activate scrolling.

Cheers

**Comment by davidjbradshaw** [comment]
Have you tried doing `scrolling: 'omit'`?

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/options.md#scrolling

**Comment by erralb** [comment]
Thanks, that worked.
