### ISSUE TITLE
Iframe source is in a different origin

### ISSUE THREAD

**Issue by bradyclifford** [davidjbradshaw/iframe-resizer#801]
In my specific scenario, we need to include an `iframe` in our React application of which its source cannot utilize the `iframe-resizer`.

Can I still use this library?  Can I still utilize at the parent level the messaging, if the same contract is utilized by the `iframe` source?

**Comment by davidjbradshaw** [comment]
Have you seen

https://github.com/davidjbradshaw/iframe-resizer-react
