### ISSUE TITLE
Iframe not responding even though iframeResizer.contentWindow.min.js is included

### ISSUE THREAD

**Issue by keithpickering** [davidjbradshaw/iframe-resizer#808]
**Describe the bug**
I'm trying to make a certain page of our Next.JS app embeddable on any website. The required file (iframeResizer.contentWindow.min.js) is being loaded in said embeddable page, but I'm still getting this error on the parent page:
```
"[iFrameSizer][Nested host page: portfolio-0c708dd2-d973-5ce8-8b44-8cf4629e2bf7]" "IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning."
```
Basically, there's just no response to the height of the embedded site. I initially thought this was because the site has a div that extends past the body element, but I've tried the different `heightCalculationMethod`s and those aren't working either. Right now I have an element with the `data-iframe-height` attribute (set to 'true', does it explicitly need to be blank?) but the iframe simply isn't responding to its height.

What's annoying is that if I change a single character of JS in the codepen (i.e. just add a random space somewhere), for a split second before the view refreshes, it looks like the iframe height actually IS updating. So maybe I just need to listen to the right event, yeah? Except when I check for `parentIFrame` in the `window` object of the embedded site, it doesn't exist, so I can't call the `.size()` method.

**To Reproduce**
1. Go to https://codepen.io/keithpickering/pen/gOaryqG?editors=1111
2. The iframe does not respond automatically to its content's height

**Expected behavior**
It should respond as each new gallery page is loaded. Is this kind of infinite scrolling functionality, which loads a new page when you're scrolled to the bottom, even possible for an iframe without scrollbars? If so, please let me know and I'll give up the pipe dream lol.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: whatever the latest one is

**Comment by davidjbradshaw** [comment]
For what ever reason the script would appear to not be loading in the iframe, or you have something blocking the postMessage API.
