### ISSUE TITLE
Same-Domain Scenario?

### ISSUE THREAD

**Issue by johnaweiss** [davidjbradshaw/iframe-resizer#810]
Hi

You are the iFrame height master. 

If you were re-designing this component for same-domain operation only, that would radically simplify your code, correct? And eliminate all the cross-domain communication, correct? All code could reside in a single JS file, correct? And may provide a variety of performance improvements? May eliminate some bugs or persistent problems? 

thx!

**Comment by davidjbradshaw** [comment]
It would remove the need to use postMessage API, but that is only a small part of the code. You could get it to run in one JS file, but that would add complication, not reduce it. Perf wise wouldn't make much difference. Bug wise, no difference, most issues are to do with detecting page size, not comms between parent and child
