### ISSUE TITLE
Automatic adjust height is not working properly

### ISSUE THREAD

**Issue by ncatallo** [davidjbradshaw/iframe-resizer#814]
When we use iFrameResize we get our page but the height continue to increase infinitely.
We added iframeResizer on the iframe page and iframeResizer.contentWindow on the iframed page. We can then see the scroll bar on the right going smaller and smaller.

Even if I use your examples to import the right files it doesn't work. I think the size return by the iframed page is going up but I don't know why.

We check on cross domain and on local pages it's still making the same thing.

Thanks

**Comment by davidjbradshaw** [comment]
Check you're CSS, you will have something set to be more than 100% of the current document size, so every time the page resizes, it grows to bigger than the new size and round you go again.

Other options are the `tolerance` option and the `taggedElement` height calculation method.
