### ISSUE TITLE
window.iFrameResize causing performance issues

### ISSUE THREAD

**Issue by oma0256** [davidjbradshaw/iframe-resizer#816]
I have been using `iframe-resizer` to resize my iframes, everything has been working perfectly however I wanted to update how the height was calculated such that my iframes are resized to the height of the content since initially the iframes had a lot of blank space at the bottom which was coming from the body of the iframe. However when I include the `heightCalculationMethod` using the `window.iFrameResize` on the iframed page my parent page performance takes a hit, whenever I try to scroll sometimes the content on the iframes disappear then reappear after sometime, sometimes the page freezes yet this wasn't the case before when I hadn't modified the `heightCalculationMethod`. When I remove the `window.iFrameResize` from the iframed page everything starts working normally again, any idea why this would happen. Any help will be much appreciated thanks. Below are the setup on both pages.

**Parent page**
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.2.10/iframeResizer.min.js" integrity="sha256-0FsDr6k3iiIaao/F1olkJHUfEU/eGSYClQ7ZhVc2md8=" crossorigin="anonymous"></script>
<script>
  iFrameResize({
      log: false,
      onResized: function(messageData) {
        var iframe = messageData.iframe;
        $(iframe).LoadingOverlay("hide");
        var nextElement = $(iframe).next('iframe');
        if (!nextElement.is('iframe')) {
          nextElement = $($(iframe).parent('section').next('section').find('iframe')[0]);
          $($(iframe).parent('section').next('section').find('header')[0]).show();
        }
        nextElement.show();
      },
      checkOrigin: [domain_of_iframed_page] }, iframeId));
</script>
```

**Iframed page**
```
<srcipt>
  window.iFrameResizer = {
    heightCalculationMethod: function () {
      var body = document.body;
      var html = document.documentElement;
      const contentWrapper = document.querySelector('#main');
      return Math.max(contentWrapper.clientHeight, contentWrapper.offsetHeight);
    }
  }
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.2.10/iframeResizer.contentWindow.min.js" integrity="sha256-1KGRbLQC4fuk7tM1+xnGjCOig1VPdJwj513JDKebuA8=" crossorigin="anonymous"></script>
```

**Comment by davidjbradshaw** [comment]
I expect this call `const contentWrapper = document.querySelector('#main');` is expensive and you really only need to do it once, so can it be moved out of the function?

You also don't need those two `var`s

**Comment by davidjbradshaw** [comment]
I'm also not sure what your `onResized` function is for, but that Ain't going to run faster either

**Comment by oma0256** [comment]
> I'm also not sure what your `onResized` function is for, but that Ain't going to run faster either

There's an overlay with a loader I display while the iframe is resizing and removing it once the the iframe has finished to resize. I'm using it also to display the next iframe once the current iframe has finished resizing. Any ideas on how I can improve that.

**Comment by oma0256** [comment]
> I expect this call `const contentWrapper = document.querySelector('#main');` is expensive and you really only need to do it once, so can it be moved out of the function?
> 
> You also don't need those two `var`s
> 
> ```js
> <srcipt>
>   const contentWrapper = document.querySelector('#main');
>   window.iFrameResizer = {
>     heightCalculationMethod: function () {
>       return Math.max(contentWrapper.clientHeight, contentWrapper.offsetHeight);
>     }
>   }
> </script>
> <script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.2.10/iframeResizer.contentWindow.min.js" integrity="sha256-1KGRbLQC4fuk7tM1+xnGjCOig1VPdJwj513JDKebuA8=" crossorigin="anonymous"></script>
> ```

I have implemented this, however still facing the issues of freezing screen as well as content on the iframes disappearing then reappearing after sometime.

**Comment by oma0256** [comment]
Hey @davidjbradshaw I'm trying to detach `iFrameResize` from the iframe however it doesn't seem to work. When I click on the iframe I still logs related to `iFrameResize`, below is the code I'm executing. Thanks for the help.
```
const Iframe = document.querySelector(iframeId);
iframe.iFrameResizer.removeListeners();
```

**Comment by davidjbradshaw** [comment]
You might need to `debounce` your `onResize` event. Beyond that I am not sure.

Use `close()` rather than `removeListeners()`, the later is only for wrapper libraries like iframe-resizer-react

**Comment by oma0256** [comment]
Hmmm... tried using `close()` but that just deletes the iframe, how do I `debounce` the `onResize` event.

**Comment by davidjbradshaw** [comment]
https://lodash.com/docs/4.17.15#debounce
