### ISSUE TITLE
Toggle listeners/observers

### ISSUE THREAD

**Issue by aguycalledpete** [davidjbradshaw/iframe-resizer#817]
Hi,

I have been looking into the possibility to toggle the listeners/observers which trigger the resizing.

I am trying to do this because i wan to add routing animations to my angular project but during the animations, the content disappears from the dom for a brief moment and the iframe is resized down to a smaller size and then is resized again when the new content comes in after the animations finish. It looked like the 'removeListeners()' would be helpful but i still want the iframe to resize after the routing animations complete.

Would there be a way to have toggle-able listeners? 
For example, i would intend to disconnect the listeners at the start of any routing within the iframe and then reconnect the listeners after the routing is complete.

**Comment by davidjbradshaw** [comment]
You can turn resizing on and off in the iframe
```js
if ('parentIFrame' in window) {
  parentIFrame.autoResize(false);
}
```
