### ISSUE TITLE
WordPress example

### ISSUE THREAD

**Issue by davidjbradshaw** [davidjbradshaw/iframe-resizer#821]
Would be great if someone could submit an example to the docs for WordPress, as the question keeps coming up an I have never used WordPress

**Comment by cliffordp** [comment]
@davidjbradshaw I'm using this with WordPress (but quite a bit of custom code site-wide). Any use cases/scenarios you keep getting asked about?

**Comment by davidjbradshaw** [comment]
@cliffordp just after a simple example, like we have for Vue

https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/use_with/vue.md

**Comment by zgieske** [comment]
I just used this plugin to create a dynamic iframe in WordPress and wrote up a quick set of instructions in markdown that should cover the vast majority of use cases. Feel free to include it in the docs so other WordPress users have a simple example to follow.

[wpinstructions.md](https://github.com/davidjbradshaw/iframe-resizer/files/7564751/wpinstructions.md)

**Comment by cliffordp** [comment]
Thanks for sharing, @zgieske

Personally, I wouldn't agree with your exact approach, but for those that would like to reference yours, it would be great as a [Gist](https://gist.github.com/) instead of a download file

**Comment by zgieske** [comment]
I'm definitely open to other methods, this just seemed like the best way to get it working with the setup I had and documentation for WordPress was slim. How would you do it differently?

https://gist.github.com/zgieske/d715adc6dd768072dc4cedba28f392d8

**Comment by davidjbradshaw** [comment]
Added info to new version 5 website.

https://iframe-resizer.com/frameworks/wordpress/

Feedback welcome.
