### ISSUE TITLE
parseInt isn't supported in IE

### ISSUE THREAD

**Issue by DrRoach** [davidjbradshaw/iframe-resizer#822]
**Describe the bug**
Number.parseInt() is used throughout the script however it is not supported in any version of IE

**To Reproduce**
1. Add the script to page
2. Call script
3. Visit page in IE

**Expected behavior**
The iframe is resized

**Screenshots**
<img width="1270" alt="Screenshot 2020-06-02 at 12 15 14" src="https://user-images.githubusercontent.com/5173524/83514024-baa5d280-a4ca-11ea-8d38-577397aa1ee4.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE
 - Version: Any

**Comment by davidjbradshaw** [comment]
Good spot, it seems the unicorn ESLint rules updated and 'fixed' that.

Removed rule `unicorn/prefer-number-properties` and reverted code.

Published as v4.2.11

**Comment by DrRoach** [comment]
Thanks a lot for the quick resolution for this.
