### ISSUE TITLE
Ad-Served Iframe

### ISSUE THREAD

**Issue by nebulousecho** [davidjbradshaw/iframe-resizer#823]
I have a second article in an infinite scroll situation that is loaded via a native ad call served via Google DFP. This one specific page has an embedded iframe that loads content from a remote server and uses this script. The script doesn't appear to run in this situation, and the iframe remains loaded on the page but with `display: none;` and unsized if I remove that style.

Any help on how to get the frame to display would be much appreciated.

**Comment by davidjbradshaw** [comment]
After you remove `display:none` you might need to focus the iFrame or manually call `iFrameResizer.resize()` on it. Beyond that and this is more a question for StackOverflow
