### ISSUE TITLE
Clicking links inside the iframe doesn't go to that URL

### ISSUE THREAD

**Issue by JoshuaCrewe** [davidjbradshaw/iframe-resizer#825]
**Describe the bug**
We have a property booking site which has an iframed instances on the booking form. Date pickers and number inputs, that sort of thing. The book now button is an `<a>` with an href to a subdomain. With the iframe-resizer script running the anchor doesn't work.

**To Reproduce**
The host is on domain.co.uk while the iframe url is booking.domain.co.uk. We have the following configuration : 
```
var iframes = iFrameResize({
        checkOrigin: false, // While in development I want to get it working
        inPageLinks: true,
        log: true,
        scrolling: true,
        heightCalculationMethod: 'documentElementScroll',
}, '#booking-widget');
```
```
<iframe id="booking-widget" style="width: 100%; overflow: hidden;" borderframe="0" src="https://booking.domain.co.uk"></iframe>
```
1. Go to the page with the iframe on it
2. Configure the form by selecting a date and number of guests
3. Book now button appears
4. Click the button
5. The iframe flickers as it resizes and back again but doesn't navigate to the href

**Expected behavior**
I would have expected to navigate to the href when clicking the anchor.

**Desktop (please complete the following information):**
 - macOS 10.14.6
 - Firefox 77.0.1
- Brave 1.9.76
- Chromium Version 83.0.4101.0 (Developer Build) (64-bit)

**Additional context**
This might be an exercise in configuration. I have tried different height calculation methods and toggled inPageLinks to see if that would make a difference but it didn't. Do we need to set up the Origin Domain on the iframe side for this to work properly?

**Comment by davidjbradshaw** [comment]
That’s a new one on me I am afraid. From what is in this ticket I have no idea. Have you tried to make a simple test case for this?

**Comment by JoshuaCrewe** [comment]
I will continue to follow this debugging route. I wanted to get an issue up while it was all fresh in my mind. It could be something on the booking side of things which is throwing things. 

I will see if I can boil it down to a simple scenario seperate from the project and see what I can find out.

Thanks for taking a look.

**Comment by JoshuaCrewe** [comment]
I created two new pages on their own URLs. One on a subdomain and loaded in the iframe for the other. Links work in this scenario.

When using the URL of the booking page I get the same error. So it seems like something is going on with the booking page.

I didn't think much of it but the default behaviour of links in an iFrame is to change the content of the iframe with that URL. The booking widget changes the URL of the host. This means they are specifically making communication with the host to do this right? It seems like this is what is failing and not the iframe resizer script.

I have reached out to them for more information. Should hear back today I reckon.

**Comment by JoshuaCrewe** [comment]
So I eventually heard back from the booking people and they did change something to fix the issue. I wasn't 100% clear on what the problem was but they were using postmessage() for their URL changes. This is what they said : 

> There was a snippet with postmessage(), but live site still have been working. Probably the conversation between http and https can prevent the windows from that and block it completely.

So thats that.
