### ISSUE TITLE
Cross domain issue

### ISSUE THREAD

**Issue by somenathghosh** [davidjbradshaw/iframe-resizer#826]
I am trying to use this lib for cross domain iframe. Has anyone encountered this and solved? 

This on latest Chrome v 81.

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:4200') does not match the recipient window's origin ('http://localhost:8080').

```

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md#failed-to-execute-postmessage-on-domwindow
