### ISSUE TITLE
angular 8 implementation (help require)

### ISSUE THREAD

**Issue by rppgoud** [davidjbradshaw/iframe-resizer#828]
Hi we are trying to implement iframe-resizer in angular 8, but i followed mentioned methods in github,
it is not working as it is, can you please latest documentation for implementing the iframe resizer in angular 8, this.component = components && components.length > 0 ? components[0] : null; i am getting issue line many methods defined. can you help me

**Comment by davidjbradshaw** [comment]
I am not an Angular developer, so no idea.

If you get it working please update the discussion on here

**Comment by balazsmaria** [comment]
Using Angular 9. 
I was following the documentation without 100% success. I'll try to come back here if I make it work.

**Comment by Eve-Sama** [comment]
@balazsmaria So still fail?
