### ISSUE TITLE
Differences from iFramely?

### ISSUE THREAD

**Issue by denvergeeks** [davidjbradshaw/iframe-resizer#832]
(Not a buggy.) I would really appreciate an article contrasting this iframe resizer with [iFramely](https://iframely.com/) (https://github.com/itteco/iframely).

I am writing a blog post about iFrames for use in the [Ghost Platform](https://github.com/TryGhost/Ghost) and [Discourse Forum Platform](https://www.discourse.org/).

I would like to display such an article within an iFrame, using this code, and further, offer an iFrame Insert Plugin for these editors!

Thank you so much, David!

**Comment by davidjbradshaw** [comment]
I have never seen that before, looks like it is just for media embeds, rather than pages.
