### ISSUE TITLE
dom element inside iframe that has viewport height set to 100vh will prevent resizer working

### ISSUE THREAD

**Issue by crapthings** [davidjbradshaw/iframe-resizer#835]
https://streamable.com/0s1keq

in this video, if you can see i changed height to 100vh

the resizer acting weird

edit

it looks use 'vh' is not support

**Comment by cesar-blog** [comment]
I hava the same problem.
when I change "vh" to "px" , it solved！
But is there a elegant way ?

**Comment by aaronlutze** [comment]
I have noticed the same problem. Either we need to create a feature request, to dynamically convert the viewport height to pixels, or, we need to find ways to avoid use of the viewport height (vh) measurement in our development.

**Comment by davidjbradshaw** [comment]
That is very strange, would welcome a PR if anyone works out a fix

**Comment by icreateweb** [comment]
I am having this problem, I think. Have you come up with a solution?

**Comment by davidjbradshaw** [comment]
This is fixed in v5, by forcing `height: auto !important` on to the `<html>` and `<body>` elements. 

Alpha version is on PR #1212 if you would like to give it a go.
