### ISSUE TITLE
How to adjust the stacking order between specific elements in the iframe and the main page.

### ISSUE THREAD

**Issue by yoyomule** [davidjbradshaw/iframe-resizer#837]
I encountered the following problem, I hope iframesizer can help.
The embedded iframe page is named iframeA, element A1 in iframeA, iframe element A2 (dialog box).
Main page, named B. This is the dialog B1 of the main page.
A2 is blocked by B1. I want A2 to be placed in front of B1, but A1 is still at the bottom.
I encountered the following problem, I hope iframesizer can help.
The embedded iframe page is named iframeA, element A1 in iframeA, iframe element A2 (dialog box).
Main page, named B. This is the dialog B1 of the main page.
A2 is blocked by B1. I want A2 to be placed in front of B1, but A1 is still at the bottom.
That is to say, when adjusting the order of the iframe and the main page, I don’t want the entire iframeA to be adjusted, but some elements in iframeA are adjusted (such as a certain part of the dialog box). I don’t know if it can be done.
![pic](https://user-images.githubusercontent.com/10000818/86531457-00075680-bef4-11ea-8ab5-b30d7cdae00c.png)
Thanks.

**Comment by davidjbradshaw** [comment]
I really don’t follow you
