### ISSUE TITLE
iframe with Flash Content does not work properly

### ISSUE THREAD

**Issue by unique33** [davidjbradshaw/iframe-resizer#838]
In The Name Of GOD
Hello,

If the iframe resizer content contain Flash ( Micromedia Flash , swf ) Content ,the iframe resizer does not work properly ( the auto height does not function properly ) .

Please Help Us.

Thanks

**Comment by davidjbradshaw** [comment]
Flash is not supported
-- 
Sent from my iPhone.

**Comment by unique33** [comment]
In The Name Of GOD
Hello,

I tested the iframe resizable with just the swf content and it works fine , the problem was from the javascript content on the same page .
any suggestion on javascript problems ?

our working environment :
Joomla : version 1.5

Extension : 
http://www.mintjoomla.com/download/mighty-extensions/item/3655-mighty-analytics.html

when I want to produce a graph and report table from the content and when I press the view the results button on the making report page , the iframe does not resize properly .
the report table is hided to some extend .

Any suggestion on this problem ?

Thanks

**Comment by davidjbradshaw** [comment]
I would suggest not using Flash, it is not longer support or distributed.
