### ISSUE TITLE
Inaccurate height until interaction

### ISSUE THREAD

**Issue by smth** [davidjbradshaw/iframe-resizer#841]
**Describe the bug**
I tried iframe-resizer on a few iframes, and for one of them (the one with the most complex content) the height calculation is a little off when the page loads. Clicking in the iframe presumably causes a recalculation, this time it is correct. I have tried different `heightCalculationMethod`s but they all either produce the same result, or no resizing at all.

Edit: It seems `min-height: 100%` on the page in the iframe is what's causing the problem.

**To Reproduce**
1. Create a page with `html { min-height: 100% }`
2. Use this page as the src of your iframe

**Expected behavior**
I expect the initial result to be the same as you get after clicking in the iframe.

**Screenshots**
![image](https://user-images.githubusercontent.com/1375708/87218768-b6809680-c34d-11ea-93f5-a4a48b1c3700.png)

![image](https://user-images.githubusercontent.com/1375708/87218865-943b4880-c34e-11ea-852d-6c1b9ccbd8a5.png)

**Desktop**
 - OS: macOS & Windows 10
 - Browser: Firefox, Chrome, Safari
 - Latest versions

**Comment by davidjbradshaw** [comment]
Yeah CSS can cause all sorts of problems, the only solution is to fix the CSS I’m afraid
