### ISSUE TITLE
Height does not get calculated with Mat-accordion. 

### ISSUE THREAD

**Issue by somenathghosh** [davidjbradshaw/iframe-resizer#855]
**Describe the bug**
Using Mat-accordion. Height does not seem to be get evaluated when expansion and collapse happen. Tried using all calculation methodologies, none of them seems to be working. 

It left lot of blank space after Accordion ( almost the space it took  during expansion )

**Expected behavior**
Should get the height calculated correctly.

**Desktop (please complete the following information):**
- all

**Smartphone (please complete the following information):**
-all

**Comment by davidjbradshaw** [comment]
You might need to manual force the iFrame to resize after the accordion runs, so events are hard to detect

```js 
if ('parentIFrame' in window) {
  parentIFrame.size()
}
```

If that doesn’t work then it will be a CSS bug in the accordion control

**Comment by somenathghosh** [comment]
Looks to be an issue with CSS on page. Used 100vh that does not seems to work with it.
