### ISSUE TITLE
Error onMessage function not defined

### ISSUE THREAD

**Issue by sozakir** [davidjbradshaw/iframe-resizer#861]
**Describe the bug**
I am using iframe-resizer library for adjusting the size of my Iframe. I have **angular component** consisting of **Iframe**. 

Iframe contains a form for validation. When I load the component , I also load the iframe in it and everything works fine including the validation. I have added validation function on the onMessage handler of window.iFrameResizer 

I have a uses case when I need to show a different component on changing the radio button. So I have used **ngIf** check for that. If user click on second check box first check box (iFrame component) **deleted from the DOM**

When user again click on the first checkbox I am **reinitializing the iframe.** 

My problem is that when I **switch frequently** from one component to another and reinitializing the iframe many times. When I try to click the submit button which call iframe for validation give me this error

`onMessage function not defined`. 

My question is `why I am getting this error`. If I load iframe first time everything works fine but removing the component from dom which is done by  angular **ngIf directive** and then again initializing iframe **many times** causes trouble.

I have also enabled logging and check what steps are missing but I am not able to rectify the issue.

My speculation is this piece of code runs first time 

```javascript

 function readData() {
      var data = window.iFrameResizer

      log('Reading data from page: ' + JSON.stringify(data))
      Object.keys(data).forEach(depricate, data)

      onMessage = 'onMessage' in data ? data.onMessage : onMessage
      onReady = 'onReady' in data ? data.onReady : onReady
      targetOriginDefault =
        'targetOrigin' in data ? data.targetOrigin : targetOriginDefault
      heightCalcMode =
        'heightCalculationMethod' in data
          ? data.heightCalculationMethod
          : heightCalcMode
      widthCalcMode =
        'widthCalculationMethod' in data
          ? data.widthCalculationMethod
          : widthCalcMode
    }
```

but on the subsequent time it **does not run** because of this check `(firstRun = false)` it does not take onMessage value from window.iFrameResizer

```javascript
 function processMessage() {
      if (false === firstRun) {
        callFromParent()
      } else if (isInitMsg()) {
        processRequestFromParent.init()
      } else {
        log(
          'Ignored message of type "' +
            getMessageType() +
            '". Received before initialization.'
        )
      }
    }
```

**Expected behavior**
Click on submit button should run validation function instead of giving onMessage function not defined error

**Screenshots**
Code is proprietary

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version:  85.0.4183.102 (Official Build) (64-bit)

**Comment by davidjbradshaw** [comment]
I would suggest hiding and reshowing the iframe, rather than reloading if
you need to switch that much

**Comment by sozakir** [comment]
@davidjbradshaw I was also thinking of the same. I would try hiding and showing the component instead of recreating them and initializing the iframe
