### ISSUE TITLE
On Worpdress, some iframed post content does not get correct height

### ISSUE THREAD

**Issue by galoxia** [davidjbradshaw/iframe-resizer#863]
On my Wordpress website i have an archive page with many iframes, each showing the post content associated with it. It works nicely with almost every post but i have found some cases where the iframe height is not calculated correctly and the iframe shows shorter than it should be. The CSS is the same for every post and no problematic CSS (like vh units or % heights) is used as far as i know

For example, this one is calculated nicely:

![image](https://user-images.githubusercontent.com/24755697/94362567-8f1fa700-00bc-11eb-83a0-5ae3e42beee5.png)

But for this one, iframe is cut down:

![image](https://user-images.githubusercontent.com/24755697/94362749-d0fd1d00-00bd-11eb-81be-ecb0773cf4d2.png)

If i try to force an extra resize 100ms after the initial resize then it works nicely **(with 0ms it does not work)**:

```
window.iFrameResizer = {
    onReady: function() {
        window.setTimeout(() => {
            window.parentIFrame.size();
        }, 100);
    }            
}
```

and the result is the expected:

![image](https://user-images.githubusercontent.com/24755697/94362881-8def7980-00be-11eb-856f-869724cc0350.png)

Why could this be happening? Is there a way so i don't need to force that extra resize?

Thanks in advance.

**Comment by davidjbradshaw** [comment]
>
> That is strange, does the fix still work if you set the timeout to 1 or
even 0?

I expect their is sometimes a race condition in the browser, where the
browser is telling JavaScript that an update has finished, before CSS has
fully reflowed.

If that is the case, not sure what other fix to suggest, other than to
really look into the CSS.

I am assuming you have tried different height calculation methods. Do you
see the same issue in all browsers?

>
> --
Sent from my iPhone.

**Comment by galoxia** [comment]
If i set the timeout to 0 or 1 and it does not work. It "needs" some more time (the minimum time i've tried (that works) being 100ms). I have tried all height calculation methods also and the results are the same. I have tested with Chrome, Firefox and Edge and results are the same on each browser.

**Comment by davidjbradshaw** [comment]
It’s a long time since I last saw an issue anything like this. It must be something on your page in the iframe, but I have no idea what it might be. Over the last 8 years I’ve had PRs for all sorts of weird edge cases and if you work out what’s going on then I’d be happy to consider a PR that fixes it.

**Comment by davidjbradshaw** [comment]
A long shot, but post the log output here and I see if I spot anything odd in it.
