### ISSUE TITLE
iframe-resizer chrome print

### ISSUE THREAD

**Issue by somenathghosh** [davidjbradshaw/iframe-resizer#874]
**Describe the bug**
Does NOT resize correctly on CHROME when someone clicks on print. On Click or print, it add some white space/margin at the bottom of the page. Iframe Resizer keeps calculating height with that white space/margin.  

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: WIndows , OS X
 - Browser CHORME 
 - Version : 84.x.x

**Additional context**
Used all methods of height calculation. None seems to work here.

**Comment by davidjbradshaw** [comment]
Sadly this is a problem with the latest browsers. Iframe-Resizer detects the `beforePrint` and `afterPrint` events. However, modern browsers don't allow the JS to run and update the pages after it is reformatted for your printer.

This is a bug in Chrome and you need to raise it with the team at Google. The latest version of Safari also has the same issue.
