### ISSUE TITLE
Using iframe-resizer with a Google Web App

### ISSUE THREAD

**Issue by nuanda744** [davidjbradshaw/iframe-resizer#886]
Hi David,
I'm trying to put a Google Web App realized with Google Apps Script into an iFrame.
The main page is a simple web page realized with Wordpress. 
I put the iFrameResizer.contentWindow.min.js into the script <head> tag of the page created by Google Apps Script who must be contained within my iFrame.

I get the error "IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame.".

So I realized my page is nested into three iframes.

![Schermata 2020-11-15 alle 18 55 55](https://user-images.githubusercontent.com/74505814/99192799-2b893000-2775-11eb-9816-20f4060b9ff6.png)

As you can see in the image the Google script result is inside an iFrame with id "userHtmlFrame". This iFrame has the call to contentWindow.js.
This iFrame is inside another iFrame with id "sandboxFrame" which is inside another iFrame with id "my-id" (the one I created into Wordpress). 

I suppose the script doesn't work because iFrameResizer.contentWindow.min.js is loaded into the head of "userHtmlFrame" only. 

Do you think my guess is correct?
If so, do you have any idea of how to inject the script into the head of the other two iframes?

**Comment by davidjbradshaw** [comment]
Yep your guess is correct, you will need to get Google to put the script in the higher iFrame for this to work
