### ISSUE TITLE
Scroll to specific on PARENT page, when button is clicked within iframe?

### ISSUE THREAD

**Issue by cheestudio** [davidjbradshaw/iframe-resizer#893]
This script works beautifully and is a huge life saver for our particular needs. We have a situation where the iframe content, which is a quiz, has a NEXT button. When this button is clicked, we'd like to scroll the parent page to the top of the quiz within the iframe. Does this script have anything that would help us get there?

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/iframed_page/methods.md#scrolltoxy

**Comment by cheestudio** [comment]
Awesome! I was looking for this in the Parent Page API...I see why now that doesn't make sense. THANK YOU!

**Comment by cheestudio** [comment]
Last quick question...how does one go about animating this scroll? I saw this from some docs:

http://davidjbradshaw.github.io/iframe-resizer/

_"If this callback function returns false, it will stop the library from repositioning the page, so that you can implement your own animated page scrolling instead."_

But not entirely sure if these docs are still relevant, nor how I do what is being described here.

**Comment by davidjbradshaw** [comment]
You can just call any scrolling library you like

**Comment by cheestudio** [comment]
Do you perchance happen to have an example? I'm just trying to animate it with jQuery and ScrollTop, but I am not understanding how you would use that in conjunction with this callback, when also happening onClick with the button within the iframe...
