### ISSUE TITLE
Mouse events in parent page?

### ISSUE THREAD

**Issue by lewiswolf** [davidjbradshaw/iframe-resizer#896]
Hi, thanks for this package its super useful. I have it installed in react.

Is there anyway to use the mouse events captured from the iframed page? I can see them coming through on the logs, but can't work out how to access them. When I click on the iframe I want to focus() it, so that I can blur() the rest of the UI on my page.

Thanks,
Lewis

**Comment by davidjbradshaw** [comment]
Interesting question, you can pass and iframe attribute and it will drop through to the iframe

**Comment by lewiswolf** [comment]
I've tried 

```
<iFrameResizer
        ...
	onMouseDown={() => alert('hi')}
	onClick={() => alert('hi')}
/>
```

and neither work 😬

**Comment by davidjbradshaw** [comment]
Oh I understand what your trying to do now, you need to that in the iFrame

**Comment by davidjbradshaw** [comment]
Having thought about it over the Christmas break, I've just added `onMouseEnter` and `onMouseLeave`
