### ISSUE TITLE
The target origin provided does not match the recipient window’s origin.

### ISSUE THREAD

**Issue by AmtechInnovarch** [davidjbradshaw/iframe-resizer#925]
Isn't the whole point of this script to work cross origin?

Well, it doesn't seem to.

After installing the `iframeResizer.contentWindow.min.js` file in the page that I am accessing via the iframe (the iframe's content page - in the body), and installing `iframeResizer.min.js` before the `<iframe id="myIframe">` and the `iFrameResize({ log: true }, '#myIframe')` after the `</iframe>` I am the lucky owner of a brand new error message in console:
```
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://iframe.content.source’) does not match the recipient window’s origin (‘https://page.with.iframe’).
```
My guess is I'm a complete idiot and there is a setting I need to discover by reading for countless hours.

Ain't nobody got time fo dat.

**Comment by AmtechInnovarch** [comment]
After moving the mouse around many times in the iframe and clicking on things I finally got this message:
```
[iFrameSizer][Host page: frame-one] IFrame (frame-one) height set to 150px
```
The funny part is that page loading in the iframe is a minimum of 525px...so...I guess the origin side script actually doesn't know the height of the content so it just guesses 150px? Or maybe it's still a CORS problem but the error only appears once at first load?

I wrote a script like this a very long time ago, like 7+ years ago that actually worked well back then, but it seems that with the CORS standards of today's browsers that old script of mine won't send the height data, but it does at least output the correct content height to console.

So why isn't your script calculating the correct content height?

How can I assure the content is completely loaded on the origin side before your script calculates the content height?

**Comment by akdarrah** [comment]
@AmtechInnovarch I ran into this same problem and think I found the solution in the troubleshooting documentation https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md#failed-to-execute-postmessage-on-domwindow

**Comment by akdarrah** [comment]
To add to my previous response, I was able to remove this error by making sure my iframe content was loaded before attempting to use this library. Here is a code snippet where `this.iframe` is the HTML iframe element:

```
this.iframe.addEventListener("load", () => {
  window['iFrameResize'](this.iframe);
});
```
