### ISSUE TITLE
Opening iframe popups in parent window

### ISSUE THREAD

**Issue by binaryfire** [davidjbradshaw/iframe-resizer#933]
Hi David,

Just discovered iframe resizer and loving it. Just wondering if there's a way to make all iframe modals open in the parent window?

Cheers

**Comment by janklubus** [comment]
Hi, 

still no way to open modals outside of an iframe? I need to position the modal to the center of the viewport, not the size of the iframe.

J

**Comment by davidjbradshaw** [comment]
You need to send a message to the parent page and have that open it.
