### ISSUE TITLE
Issue with website navigation header that is position: fixed and uses z-index property which places it above the normal rendering of the page

### ISSUE THREAD

**Issue by PaulGDev** [davidjbradshaw/iframe-resizer#945]
**Describe the bug**
Ticket Tailor iframe is scrolling to top and due to Scrollex theme navigation bar being fixed and using z-index (layers)  eg using the Layers WP theme

**To Reproduce**
- Go to website makeitcommunications.com/#Book
- Click any one of the Buy Tickets buttons. 
- Then scroll wheel forward on mouse you will see the Title of the event in large bold white letters. eg. UNDERSTAND COMPLEX TRAUMA – Bunbury at Bunbury Football Club etc (eg the scrolling behaviour has resulting in training event header being not shown to customer)
- When I click contact on menu then book it works as expected, it is only the behaviour of the Buy Tickets button or Next Button and dynamic loading of the html in the iFrame. 

**Expected behavior**
[Actual vs Expected Behaviour Screenshot](https://imgur.com/a/97EU9Lk)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Windows 10
 - Edge (also in most browsers)
 - Version 90.0.818.56 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by davidjbradshaw** [comment]
Unable to repro, v5 when it comes out will have some extra options that might help
