### ISSUE TITLE
Extra space after resizing the browser

### ISSUE THREAD

**Issue by VarLad** [davidjbradshaw/iframe-resizer#956]
**Describe the bug**
Its good after resizing down, but when resized up, there's a lot of extra space

**To Reproduce**
1. Go to https://varlad.github.io/tutorials/getting-started/8-deutsch/
2. Click on Resize the browser down, then resize it back to full 
3. Scroll down to the end
4. See the extra space

**Expected behavior**
No extra space

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser Firefox
 - Version 88

**Additional context**
A temporary solution is to make the height = 0px, then equal to Bodyoffset, the resize fixes the issue.

**Comment by davidjbradshaw** [comment]
I just had a very quick look at your page. Something in your code is causing height to be set on the `<main/>` element. You either need to stop that happening, or perhaps look at the `tagElement` resize method to get the height of your `<pluto-notebook/>` element instead of `document.body`.

**Comment by VarLad** [comment]
> or perhaps look at the tagElement resize method to get the height of your <pluto-notebook/> element instead of document.body

Any idea on how would I do that? :sweat_smile:

**Comment by VarLad** [comment]
As in, do I set an empty attribute named data-iframe-resize?

**Comment by davidjbradshaw** [comment]
yep

**Comment by VarLad** [comment]
@davidjbradshaw Thanks！Works like a charm！🙂
