### ISSUE TITLE
Calling close event using ForwardRef of IFrame

### ISSUE THREAD

**Issue by VikasITG** [davidjbradshaw/iframe-resizer#962]
Hello,

I would like to call Close event of IFrame using forwardref, I have tried with following example which is given in documentation.
```js
const WrappedComponent = React.forwardRef(function myFunction(props, ref) {
        return (
            <IframeResizer
                forwardRef={ref}
                heightCalculationMethod="lowestElement"
                log={true}
                src={theURL as string}
                checkOrigin={false}
            />
        );
    });
 ```
When I am calling ref.current.close() it showing error ref.current.close is not a function.
    
 How to call close event of IFrame.

**Comment by davidjbradshaw** [comment]
In React you just need to remove the element from the page and it will sort this for you.

**Comment by VikasITG** [comment]
When I remove IFrame from page it does not call close event of IFrame
