### ISSUE TITLE
Position: sticky is not working for div in iframe.

### ISSUE THREAD

**Issue by zeeshanpk92** [davidjbradshaw/iframe-resizer#963]
My website is loaded in another application using iframe. Parent site is using iframeresizer.js to calculate iframe content height. 
Sticky position div is working locally but when it is loaded in parent iframe then div's  doesnot stay sticky.
Any ideas? 
I have limitation that i cannot load html in parent application.

**Comment by zeeshanpk92** [comment]
@davidjbradshaw plz suggests.

**Comment by davidjbradshaw** [comment]
No idea sorry
