### ISSUE TITLE
taggedElement not resizing

### ISSUE THREAD

**Issue by benwallis** [davidjbradshaw/iframe-resizer#969]
I am setting data-iframe-height="" on an element using Javascript.

On the first page the iframe is resized correctly but after following a link in the iframe, it resizes to 0.

Is there a specific way/time that the attribute needs to be added?

```
jQuery(document).ready(function(){
  const gformBody = document.querySelector('.gform_body');
  if (gformBody !== null) {
    gformBody.dataset.iframeHeight = '';
  } else {
    document.documentElement.dataset.iframeHeight = '';
  }
});
```

**Comment by davidjbradshaw** [comment]
I normally just set it in the HTML, rather than JS
