### ISSUE TITLE
Height calculation when resizing up the browser

### ISSUE THREAD

**Issue by MohamadElfar** [davidjbradshaw/iframe-resizer#972]
**Bug Description**

On load, it works perfectly, but when resizing the browser up, the iframe body takes extra white space underneath.
In addition, on mouse click inside the iframe body, the height decreases by 16px per click.
@davidjbradshaw 
Iframe styles are:

iframe {
    width: 1px;
    min-width: 100%;
}
Script:
  iFrameResize({ log: true }, '#myiframe')
This behavior is present on all browsers except for Firefox.

**Comment by jbejam** [comment]
@MohamadElfar Were you able to fix the issue? I am experiencing this too.

**Comment by davidjbradshaw** [comment]
Check the CSS in your iframe. That is always the issue when this happens.
