### ISSUE TITLE
postMessage failed to execute

### ISSUE THREAD

**Issue by resimovic** [davidjbradshaw/iframe-resizer#975]
hello,
i have simple html for testing:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>iFrame message passing test</title>
    <meta name="description" content="iFrame message passing test" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  </head>

  <body>
    <iframe id="myIframe" src="https://www.deubner-online.de/taxplain/videopages/iframe_inhalt.php?kdnr=XXXXXXXX" width="100%" ></iframe>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script type="text/javascript" src="../js/iframeResizer.min.js"></script>
    <script>
     iFrameResize({ log: true }, '#myIframe')
</script>
  </body>
</html>
```
XXXXXX kdnr i have but it's not for public

in dev tools I have message like this:
 
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.deubner-online.de') does not match the recipient window's origin ('null').

how to correct this and make it work

thx

**Comment by adamduncan** [comment]
Just to follow on from @davidjbradshaw's advice on this in the [Troubleshooting guide](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md#failed-to-execute-postmessage-on-domwindow), one approach to avoiding the error is to not invoke the `iFrameResizer()` call until the frame has loaded. To build on your example:

```js
<script type="text/javascript" src="../js/iframeResizer.min.js"></script>
<script>
var frame = document.getElementById('myIframe');
frame.addEventListener('load', function () {
  iFrameResize({ log: true }, '#myIframe');
});
</script>
```
