### ISSUE TITLE
How to import in NodeJS?

### ISSUE THREAD

**Issue by el-pol** [davidjbradshaw/iframe-resizer#976]
I can't seem to manage to import it in NodeJS using `import x from 'y'`. There's nothing in the docs.

If I do: `import { iframeResizer } from 'iframe-resizer'` I get the error that the element is not exported.

And if I just `import x` I get the error that there is no `default export`.

**Comment by mutluhanuzmez** [comment]
I tried to import the js files inside of the module directly in the parent page this way and it worked.
`import 'iframe-resizer/js/iframeResizer';`

also in the iframed page this way
`import 'iframe-resizer/js/iframeResizer.contentWindow';`

ps: There was also another problem for me while using iFrameResize method. I was using LitElement and it was rendering in the shadow DOM. Therefore sending the target as the iframe id didn't work for me. I took the iframe ref and send it to the method.
```
const iframe = this.shadowRoot.querySelector('#myIframe');
iFrameResize({log: true}, iframe);
```
Works perfect now, but I still don't like the import this way.

**Comment by mattvb91** [comment]
For anyone else coming here from react side of things this worked for me. Probably not idea but for now its a workaround

```tsx
import 'iframe-resizer/js/iframeResizer';
import 'iframe-resizer/js/iframeResizer.contentWindow';

const Page = () => {

    const iframe = useRef()

    useEffect(() => {
        //@ts-ignore
        iFrameResize({}, iframe.current);
    }, [])

    return <>
        <iframe
            ref={iframe}
            src="bla.com" >
        </iframe>
    </>
}
```

**Comment by davidjbradshaw** [comment]
This will be address in v5
