### ISSUE TITLE
default Iframe height before first resize ? 

### ISSUE THREAD

**Issue by jbonlinea** [davidjbradshaw/iframe-resizer#983]
Hi there

I'm using IframeResizer and like it a lot ! 

I'm just bumping into an "issue" user experience wise.

The Iframe can take some time to load, which is something we can do nothing about (not every internet access is lightning fast).

I embeded the iframe as recomended. 
On load the Iframe is 0px in height, untill IframeResizer do it's job.

If there a way to set the iframe size, a default size, witch is maintained untill IframeResizer  runs for the first time ? 
If I set the iframe size in the inframe tag, then iframe resizer won't resize it anymore.

I wish I could set my iframe to be 640*480px untill IframeResizer fires, then the iframe size it up to / set by iframe resiser (which do a great job)

Thank's in advance

**Comment by davidjbradshaw** [comment]
You can set it with css, I recommend `100vh` in cases like this.
