### ISSUE TITLE
Error when using 2021 update with vue

### ISSUE THREAD

**Issue by kaa-serpent** [davidjbradshaw/iframe-resizer#987]
https://github.com/davidjbradshaw/iframe-resizer/blob/d0a7c843cf1eaef09050b5f0886c1c6ee561ed2c/js/iframeResizer.contentWindow.min.js#L9

My code work fine with this version : `v3.5.14 - 2017-03-30`

```     

error in ./src/iframeResizer.contentWindow.min.js

Module Error (from ./node_modules/thread-loader/dist/cjs.js):

/root/project/src/iframeResizer.contentWindow.min.js
10:820 error Empty block statement no-empty
10:6343 error 'e' is already defined no-redeclare
10:6632 error 'e' is already defined no-redeclare
10:8091 error 'e' is assigned to itself no-self-assign
10:8095 error 'n' is assigned to itself no-self-assign
10:10503 error 'e' is assigned to itself no-self-assign
10:11786 error 'a' is assigned to itself no-self-assign
```

**Comment by davidjbradshaw** [comment]
What happens if you try the non-minified version? Hopefully it gives a more useful error message than that

**Comment by kaa-serpent** [comment]
I have no errors with the non-minified version, this is pretty strange.

**Comment by decademoon** [comment]
That looks like eslint errors; you shouldn't be linting vendor files.
