### ISSUE TITLE
Ignored iFrame, already setup: is there way to destroy(no remove iframe) iFrame-resizer once click the button. 

### ISSUE THREAD

**Issue by SungmiKStuff** [davidjbradshaw/iframe-resizer#988]
Hi,

My iframe original height is more than 25,000px (it has lots of lists), so had added a button in parent div `show more`.
`iframeresizer` is really working well when I click `show more` button for the first time and iframe height is also back to `1000px` once I click `show less` button. 

Here is my code snippet: 

```
$(document).ready(function(){
$('.loi-btn').click(function(){
  $(this).text() === 'Show more  ? $(this).text('Show less') : $(this).text('Show more');
  if($(this).text() === 'Show less'){
   iFrameResize({ log: true}, '#loi')
  }
  if($(this).text() === 'Show more){
    $('#loi').css('height','1000px');
  }
})
});
```
I am not able to run `iFrameResize({ log: true}, '#loi')` again, maybe we only need to run once. 
So I wonder is there anyway we could remove `iFrameResize({ log: true}, '#loi')`? then run again?

**Comment by davidjbradshaw** [comment]
Once setup you can tell the iframe to resize

```js
window.getElementById(‘loi’).iFrameResizer.resize()
```


https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/parent_page/methods.md
