### ISSUE TITLE
it doesn't work with Chrome & Safari

### ISSUE THREAD

**Issue by Schili-Moritz** [davidjbradshaw/iframe-resizer#989]
**Describe the bug**
if i open another page in the iframe, only Firefox will resize the iframe, not Safari, Chrome

See: https://www.moritz.de/Tickets

Any help?

**Comment by markvantilburg** [comment]
Are you talking about the mac versions? On windows your page works fine in firefox,chrome and edge

**Comment by Schili-Moritz** [comment]
Yes, mac version

**Comment by Schili-Moritz** [comment]
I checked it. I have the same issue on windows...

**Comment by markvantilburg** [comment]
remove defer from the page you are loading
<script type="text/javascript" src="https://tickets.moritz.de/iframeResizer.contentWindow.min.js" defer></script>
or load the script earlier in the process..

my console logs "[iFrameSizer][Host page: ade6f87b] IFrame has not responded within 5 seconds. Check iFrameResizer.contentWindow.js has been loaded in iFrame. This message can be ignored if everything is working, or you can set the warningTimeout option to a higher value or zero to suppress this warning.
s @ iframeResizer.js:144
"

**Comment by Schili-Moritz** [comment]
nothing helped... :-(

**Comment by markvantilburg** [comment]
on your mainpage you should only load iframeResizer and not the contentWindow version

![image](https://user-images.githubusercontent.com/4510245/131350926-0e32b656-d16b-4c37-af5b-337bf551a04b.png)

**Comment by markvantilburg** [comment]
The page that contains the iframe:
iframeResizer

Inside the iframe content:
contentWindow

**Comment by pimhakkertgc** [comment]
Your issue seems to be resolved. What's the fix? @Schili-Moritz
