### ISSUE TITLE
"$ is not defined" in official example

### ISSUE THREAD

**Issue by jameshfisher** [davidjbradshaw/iframe-resizer#995]
**To Reproduce**
1. Go to the official example at https://davidjbradshaw.com/iframe-resizer/example/
2. Open console
4. See error `$ is not defined`

**Expected behavior**
No errors in official example

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome, Firefox

**Comment by markvantilburg** [comment]
jquery is loaded over http on that page, it should be done over https..

**Comment by davidjbradshaw** [comment]
Fix in V4.4 and V5 will remove jQuery from the examples
